import type { Course } from "@/curriculum/types";

// German course content. Hand-authored, beginner-friendly (A1–A2).
// Vocabulary is introduced per unit and reused across that unit's lessons.

export const germanCourse: Course = {
  code: "de",
  name: "German",
  endonym: "Deutsch",
  flag: "🇩🇪",
  fromLanguage: "English",
  speechLocale: "de-DE",
  sections: [
    {
      id: "de-s1",
      title: "Rookie",
      subtitle: "First words & phrases",
      units: [
        // ---------------------------------------------------------------
        // UNIT 1 — Greetings & basics
        // ---------------------------------------------------------------
        {
          id: "de-u1",
          title: "Greetings",
          subtitle: "Say hello and introduce yourself",
          cefr: "A1",
          color: "#58CC02",
          icon: "👋",
          lessons: [
            {
              id: "de-u1-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the greetings",
                  pairs: [
                    { target: "Hallo", source: "Hello", speak: "Hallo" },
                    { target: "Tschüss", source: "Bye", speak: "Tschüss" },
                    { target: "Ja", source: "Yes", speak: "Ja" },
                    { target: "Nein", source: "No", speak: "Nein" },
                    { target: "Danke", source: "Thanks", speak: "Danke" },
                  ],
                },
                {
                  type: "select",
                  prompt: "How do you say “Hello”?",
                  question: "Hello",
                  options: ["Hallo", "Tschüss", "Danke"],
                  answer: 0,
                  speak: "Hallo",
                },
                {
                  type: "select",
                  prompt: "What does “Tschüss” mean?",
                  question: "Tschüss",
                  speak: "Tschüss",
                  options: ["Hello", "Bye", "Please"],
                  answer: 1,
                },
                {
                  type: "fill",
                  prompt: "Complete the greeting",
                  before: "Guten",
                  after: "!",
                  answer: "Morgen",
                  options: ["Morgen", "Nacht", "Hallo"],
                  translation: "Good morning!",
                  speak: "Guten Morgen!",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "Good day!",
                  answer: "Guten Tag!",
                  bank: ["Guten", "Tag!", "Nacht", "Hallo"],
                  speak: "Guten Tag!",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Hallo, danke!",
                  answer: "Hallo, danke!",
                  bank: ["Hallo,", "danke!", "Tschüss", "bitte"],
                  translation: "Hello, thanks!",
                },
              ],
            },
            {
              id: "de-u1-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "bitte", source: "please", speak: "bitte" },
                    { target: "ich", source: "I", speak: "ich" },
                    { target: "du", source: "you", speak: "du" },
                    { target: "bin", source: "am", speak: "bin" },
                  ],
                },
                {
                  type: "select",
                  prompt: "Choose the correct word",
                  question: "I am Anna.",
                  options: ["Ich bin Anna.", "Du bist Anna.", "Ich ist Anna."],
                  answer: 0,
                  speak: "Ich bin Anna.",
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "Ich",
                  after: "Tom.",
                  answer: "bin",
                  options: ["bin", "bist", "ist"],
                  translation: "I am Tom.",
                  speak: "Ich bin Tom.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I am Lena.",
                  answer: "Ich bin Lena.",
                  bank: ["Ich", "bin", "Lena.", "bist", "du"],
                  speak: "Ich bin Lena.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct verb",
                  question: "Du ___ Max.",
                  options: ["bist", "bin", "ist"],
                  answer: 0,
                  speak: "Du bist Max.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Ich bin Anna.",
                  answer: "Ich bin Anna.",
                  bank: ["Ich", "bin", "Anna.", "du", "bist"],
                  translation: "I am Anna.",
                },
              ],
            },
            {
              id: "de-u1-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the phrases",
                  pairs: [
                    { target: "Wie geht es dir?", source: "How are you?", speak: "Wie geht es dir?" },
                    { target: "Gut", source: "Good", speak: "Gut" },
                    { target: "und", source: "and", speak: "und" },
                    { target: "heiße", source: "am called", speak: "heiße" },
                  ],
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "My name is Tom.",
                  answer: "Ich heiße Tom.",
                  bank: ["Ich", "heiße", "Tom.", "bin", "du"],
                  speak: "Ich heiße Tom.",
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "Wie geht es",
                  after: "?",
                  answer: "dir",
                  options: ["dir", "du", "ich"],
                  translation: "How are you?",
                  speak: "Wie geht es dir?",
                },
                {
                  type: "select",
                  prompt: "Choose the best reply",
                  question: "Wie geht es dir?",
                  speak: "Wie geht es dir?",
                  options: ["Gut, danke!", "Guten Morgen!", "Tschüss!"],
                  answer: 0,
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "Good, and you?",
                  answer: "Gut, und du?",
                  bank: ["Gut,", "und", "du?", "ich", "Tag"],
                  speak: "Gut, und du?",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Ich heiße Lena.",
                  answer: "Ich heiße Lena.",
                  bank: ["Ich", "heiße", "Lena.", "bin", "Tom."],
                  translation: "My name is Lena.",
                },
              ],
            },
          ],
        },
        // ---------------------------------------------------------------
        // UNIT 2 — People & family
        // ---------------------------------------------------------------
        {
          id: "de-u2",
          title: "Family",
          subtitle: "Talk about people and family",
          cefr: "A1",
          color: "#1CB0F6",
          icon: "👨‍👩‍👧",
          lessons: [
            {
              id: "de-u2-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the family words",
                  pairs: [
                    { target: "die Mutter", source: "the mother", speak: "die Mutter" },
                    { target: "der Vater", source: "the father", speak: "der Vater" },
                    { target: "der Bruder", source: "the brother", speak: "der Bruder" },
                    { target: "die Schwester", source: "the sister", speak: "die Schwester" },
                    { target: "das Kind", source: "the child", speak: "das Kind" },
                  ],
                },
                {
                  type: "select",
                  prompt: "Which article fits?",
                  question: "___ Mutter",
                  options: ["die", "der", "das"],
                  answer: 0,
                  speak: "die Mutter",
                },
                {
                  type: "select",
                  prompt: "Which article fits?",
                  question: "___ Vater",
                  options: ["der", "die", "das"],
                  answer: 0,
                  speak: "der Vater",
                },
                {
                  type: "fill",
                  prompt: "Fill in the article",
                  before: "Das ist",
                  after: "Bruder.",
                  answer: "der",
                  options: ["der", "die", "das"],
                  translation: "This is the brother.",
                  speak: "Das ist der Bruder.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "This is the sister.",
                  answer: "Das ist die Schwester.",
                  bank: ["Das", "ist", "die", "Schwester.", "der", "Vater"],
                  speak: "Das ist die Schwester.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Das ist das Kind.",
                  answer: "Das ist das Kind.",
                  bank: ["Das", "ist", "das", "Kind.", "die", "Mutter"],
                  translation: "This is the child.",
                },
              ],
            },
            {
              id: "de-u2-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "mein", source: "my (masc.)", speak: "mein" },
                    { target: "meine", source: "my (fem.)", speak: "meine" },
                    { target: "die Familie", source: "the family", speak: "die Familie" },
                    { target: "die Frau", source: "the woman", speak: "die Frau" },
                    { target: "der Mann", source: "the man", speak: "der Mann" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "Das ist",
                  after: "Mutter.",
                  answer: "meine",
                  options: ["meine", "mein", "der"],
                  translation: "This is my mother.",
                  speak: "Das ist meine Mutter.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct form",
                  question: "This is my father.",
                  options: ["Das ist mein Vater.", "Das ist meine Vater.", "Das ist der Vater."],
                  answer: 0,
                  speak: "Das ist mein Vater.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "My family is big.",
                  answer: "Meine Familie ist groß.",
                  bank: ["Meine", "Familie", "ist", "groß.", "mein", "klein"],
                  speak: "Meine Familie ist groß.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct word",
                  question: "the man",
                  options: ["der Mann", "die Frau", "das Kind"],
                  answer: 0,
                  speak: "der Mann",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Das ist meine Familie.",
                  answer: "Das ist meine Familie.",
                  bank: ["Das", "ist", "meine", "Familie.", "mein", "Vater"],
                  translation: "This is my family.",
                },
              ],
            },
            {
              id: "de-u2-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "haben", source: "to have", speak: "haben" },
                    { target: "habe", source: "have (I)", speak: "habe" },
                    { target: "groß", source: "big", speak: "groß" },
                    { target: "klein", source: "small", speak: "klein" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "Ich",
                  after: "einen Bruder.",
                  answer: "habe",
                  options: ["habe", "hast", "ist"],
                  translation: "I have a brother.",
                  speak: "Ich habe einen Bruder.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I have a sister.",
                  answer: "Ich habe eine Schwester.",
                  bank: ["Ich", "habe", "eine", "Schwester.", "einen", "Bruder"],
                  speak: "Ich habe eine Schwester.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "My brother is small.",
                  options: ["Mein Bruder ist klein.", "Meine Bruder ist klein.", "Mein Bruder ist groß."],
                  answer: 0,
                  speak: "Mein Bruder ist klein.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "My mother is nice.",
                  answer: "Meine Mutter ist nett.",
                  bank: ["Meine", "Mutter", "ist", "nett.", "mein", "groß"],
                  speak: "Meine Mutter ist nett.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Ich habe einen Bruder.",
                  answer: "Ich habe einen Bruder.",
                  bank: ["Ich", "habe", "einen", "Bruder.", "eine", "Schwester"],
                  translation: "I have a brother.",
                },
              ],
            },
          ],
        },
        // ---------------------------------------------------------------
        // UNIT 3 — Food & drink
        // ---------------------------------------------------------------
        {
          id: "de-u3",
          title: "Food",
          subtitle: "Order food and drinks",
          cefr: "A1",
          color: "#FF9600",
          icon: "🍞",
          lessons: [
            {
              id: "de-u3-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the food words",
                  pairs: [
                    { target: "das Brot", source: "the bread", speak: "das Brot" },
                    { target: "der Apfel", source: "the apple", speak: "der Apfel" },
                    { target: "das Wasser", source: "the water", speak: "das Wasser" },
                    { target: "der Kaffee", source: "the coffee", speak: "der Kaffee" },
                    { target: "die Milch", source: "the milk", speak: "die Milch" },
                  ],
                },
                {
                  type: "select",
                  prompt: "Which article fits?",
                  question: "___ Apfel",
                  options: ["der", "die", "das"],
                  answer: 0,
                  speak: "der Apfel",
                },
                {
                  type: "select",
                  prompt: "What does “das Wasser” mean?",
                  question: "das Wasser",
                  speak: "das Wasser",
                  options: ["the water", "the milk", "the bread"],
                  answer: 0,
                },
                {
                  type: "fill",
                  prompt: "Fill in the article",
                  before: "Ich trinke",
                  after: "Milch.",
                  answer: "die",
                  options: ["die", "der", "das"],
                  translation: "I drink the milk.",
                  speak: "Ich trinke die Milch.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "The bread is good.",
                  answer: "Das Brot ist gut.",
                  bank: ["Das", "Brot", "ist", "gut.", "der", "Apfel"],
                  speak: "Das Brot ist gut.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Der Kaffee ist heiß.",
                  answer: "Der Kaffee ist heiß.",
                  bank: ["Der", "Kaffee", "ist", "heiß.", "das", "Wasser"],
                  translation: "The coffee is hot.",
                },
              ],
            },
            {
              id: "de-u3-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the verbs",
                  pairs: [
                    { target: "essen", source: "to eat", speak: "essen" },
                    { target: "ich esse", source: "I eat", speak: "ich esse" },
                    { target: "du isst", source: "you eat", speak: "du isst" },
                    { target: "trinken", source: "to drink", speak: "trinken" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "Ich",
                  after: "Brot.",
                  answer: "esse",
                  options: ["esse", "isst", "trinke"],
                  translation: "I eat bread.",
                  speak: "Ich esse Brot.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct verb",
                  question: "Du ___ einen Apfel.",
                  options: ["isst", "esse", "trinkst"],
                  answer: 0,
                  speak: "Du isst einen Apfel.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I drink water.",
                  answer: "Ich trinke Wasser.",
                  bank: ["Ich", "trinke", "Wasser.", "esse", "Brot"],
                  speak: "Ich trinke Wasser.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I eat an apple.",
                  options: ["Ich esse einen Apfel.", "Ich isst einen Apfel.", "Ich trinke einen Apfel."],
                  answer: 0,
                  speak: "Ich esse einen Apfel.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Ich esse Brot.",
                  answer: "Ich esse Brot.",
                  bank: ["Ich", "esse", "Brot.", "trinke", "Wasser"],
                  translation: "I eat bread.",
                },
              ],
            },
            {
              id: "de-u3-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "möchte", source: "would like", speak: "möchte" },
                    { target: "ein Glas", source: "a glass", speak: "ein Glas" },
                    { target: "lecker", source: "delicious", speak: "lecker" },
                    { target: "und", source: "and", speak: "und" },
                  ],
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I would like coffee.",
                  answer: "Ich möchte Kaffee.",
                  bank: ["Ich", "möchte", "Kaffee.", "trinke", "Wasser"],
                  speak: "Ich möchte Kaffee.",
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "Ich möchte ein Glas",
                  after: ".",
                  answer: "Wasser",
                  options: ["Wasser", "Brot", "Apfel"],
                  translation: "I would like a glass of water.",
                  speak: "Ich möchte ein Glas Wasser.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "The apple is delicious.",
                  options: ["Der Apfel ist lecker.", "Das Apfel ist lecker.", "Der Apfel ist gut Milch."],
                  answer: 0,
                  speak: "Der Apfel ist lecker.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "Bread and water.",
                  answer: "Brot und Wasser.",
                  bank: ["Brot", "und", "Wasser.", "Milch", "Kaffee"],
                  speak: "Brot und Wasser.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Ich möchte einen Kaffee.",
                  answer: "Ich möchte einen Kaffee.",
                  bank: ["Ich", "möchte", "einen", "Kaffee.", "ein", "Wasser"],
                  translation: "I would like a coffee.",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "de-s2",
      title: "Explorer",
      subtitle: "Everyday situations",
      units: [
        // ---------------------------------------------------------------
        // UNIT 4 — Around town
        // ---------------------------------------------------------------
        {
          id: "de-u4",
          title: "Town",
          subtitle: "Find your way around town",
          cefr: "A2",
          color: "#CE82FF",
          icon: "🏙️",
          lessons: [
            {
              id: "de-u4-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the places",
                  pairs: [
                    { target: "der Bahnhof", source: "the train station", speak: "der Bahnhof" },
                    { target: "die Straße", source: "the street", speak: "die Straße" },
                    { target: "das Hotel", source: "the hotel", speak: "das Hotel" },
                    { target: "die Stadt", source: "the city", speak: "die Stadt" },
                    { target: "der Markt", source: "the market", speak: "der Markt" },
                  ],
                },
                {
                  type: "select",
                  prompt: "Which article fits?",
                  question: "___ Bahnhof",
                  options: ["der", "die", "das"],
                  answer: 0,
                  speak: "der Bahnhof",
                },
                {
                  type: "select",
                  prompt: "What does “die Stadt” mean?",
                  question: "die Stadt",
                  speak: "die Stadt",
                  options: ["the city", "the street", "the hotel"],
                  answer: 0,
                },
                {
                  type: "fill",
                  prompt: "Fill in the article",
                  before: "Wo ist",
                  after: "Bahnhof?",
                  answer: "der",
                  options: ["der", "die", "das"],
                  translation: "Where is the train station?",
                  speak: "Wo ist der Bahnhof?",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "Where is the hotel?",
                  answer: "Wo ist das Hotel?",
                  bank: ["Wo", "ist", "das", "Hotel?", "der", "Bahnhof"],
                  speak: "Wo ist das Hotel?",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Die Stadt ist schön.",
                  answer: "Die Stadt ist schön.",
                  bank: ["Die", "Stadt", "ist", "schön.", "der", "Markt"],
                  translation: "The city is beautiful.",
                },
              ],
            },
            {
              id: "de-u4-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "links", source: "left", speak: "links" },
                    { target: "rechts", source: "right", speak: "rechts" },
                    { target: "geradeaus", source: "straight ahead", speak: "geradeaus" },
                    { target: "hier", source: "here", speak: "hier" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "Der Bahnhof ist",
                  after: ".",
                  answer: "links",
                  options: ["links", "rechts", "hier"],
                  translation: "The train station is on the left.",
                  speak: "Der Bahnhof ist links.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "The hotel is on the right.",
                  answer: "Das Hotel ist rechts.",
                  bank: ["Das", "Hotel", "ist", "rechts.", "links", "hier"],
                  speak: "Das Hotel ist rechts.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct word",
                  question: "straight ahead",
                  options: ["geradeaus", "links", "rechts"],
                  answer: 0,
                  speak: "geradeaus",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "The market is here.",
                  answer: "Der Markt ist hier.",
                  bank: ["Der", "Markt", "ist", "hier.", "Stadt", "links"],
                  speak: "Der Markt ist hier.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Gehen Sie geradeaus.",
                  answer: "Gehen Sie geradeaus.",
                  bank: ["Gehen", "Sie", "geradeaus.", "links", "rechts"],
                  translation: "Go straight ahead.",
                },
              ],
            },
            {
              id: "de-u4-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "der Zug", source: "the train", speak: "der Zug" },
                    { target: "der Bus", source: "the bus", speak: "der Bus" },
                    { target: "fahren", source: "to go (by vehicle)", speak: "fahren" },
                    { target: "die Karte", source: "the ticket", speak: "die Karte" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "Ich",
                  after: "mit dem Bus.",
                  answer: "fahre",
                  options: ["fahre", "fährst", "gehe"],
                  translation: "I go by bus.",
                  speak: "Ich fahre mit dem Bus.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "The train is here.",
                  answer: "Der Zug ist hier.",
                  bank: ["Der", "Zug", "ist", "hier.", "Bus", "links"],
                  speak: "Der Zug ist hier.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I take the train.",
                  options: ["Ich fahre mit dem Zug.", "Ich esse mit dem Zug.", "Ich fahre mit der Zug."],
                  answer: 0,
                  speak: "Ich fahre mit dem Zug.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "Where is the bus?",
                  answer: "Wo ist der Bus?",
                  bank: ["Wo", "ist", "der", "Bus?", "Zug", "das"],
                  speak: "Wo ist der Bus?",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Ich fahre mit dem Zug.",
                  answer: "Ich fahre mit dem Zug.",
                  bank: ["Ich", "fahre", "mit", "dem", "Zug.", "Bus."],
                  translation: "I go by train.",
                },
              ],
            },
          ],
        },
        // ---------------------------------------------------------------
        // UNIT 5 — Daily life
        // ---------------------------------------------------------------
        {
          id: "de-u5",
          title: "Daily life",
          subtitle: "Describe your daily routine",
          cefr: "A2",
          color: "#FF4B4B",
          icon: "⏰",
          lessons: [
            {
              id: "de-u5-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the verbs",
                  pairs: [
                    { target: "arbeiten", source: "to work", speak: "arbeiten" },
                    { target: "wohnen", source: "to live", speak: "wohnen" },
                    { target: "schlafen", source: "to sleep", speak: "schlafen" },
                    { target: "lesen", source: "to read", speak: "lesen" },
                    { target: "spielen", source: "to play", speak: "spielen" },
                  ],
                },
                {
                  type: "select",
                  prompt: "What does “wohnen” mean?",
                  question: "wohnen",
                  speak: "wohnen",
                  options: ["to live", "to work", "to read"],
                  answer: 0,
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "Ich",
                  after: "in Berlin.",
                  answer: "wohne",
                  options: ["wohne", "wohnst", "arbeite"],
                  translation: "I live in Berlin.",
                  speak: "Ich wohne in Berlin.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I work in the city.",
                  answer: "Ich arbeite in der Stadt.",
                  bank: ["Ich", "arbeite", "in", "der", "Stadt.", "wohne"],
                  speak: "Ich arbeite in der Stadt.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct verb",
                  question: "Du ___ ein Buch.",
                  options: ["liest", "lese", "spielst"],
                  answer: 0,
                  speak: "Du liest ein Buch.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Ich wohne in Berlin.",
                  answer: "Ich wohne in Berlin.",
                  bank: ["Ich", "wohne", "in", "Berlin.", "arbeite", "Stadt."],
                  translation: "I live in Berlin.",
                },
              ],
            },
            {
              id: "de-u5-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the time words",
                  pairs: [
                    { target: "heute", source: "today", speak: "heute" },
                    { target: "morgen", source: "tomorrow", speak: "morgen" },
                    { target: "jetzt", source: "now", speak: "jetzt" },
                    { target: "immer", source: "always", speak: "immer" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "Ich arbeite",
                  after: ".",
                  answer: "heute",
                  options: ["heute", "morgen", "jetzt"],
                  translation: "I work today.",
                  speak: "Ich arbeite heute.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I read now.",
                  answer: "Ich lese jetzt.",
                  bank: ["Ich", "lese", "jetzt.", "heute", "arbeite"],
                  speak: "Ich lese jetzt.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I sleep now.",
                  options: ["Ich schlafe jetzt.", "Ich schlafe heute Buch.", "Ich schlafst jetzt."],
                  answer: 0,
                  speak: "Ich schlafe jetzt.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "Today I work.",
                  answer: "Heute arbeite ich.",
                  bank: ["Heute", "arbeite", "ich.", "morgen", "lese"],
                  speak: "Heute arbeite ich.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Ich spiele heute.",
                  answer: "Ich spiele heute.",
                  bank: ["Ich", "spiele", "heute.", "lese", "jetzt."],
                  translation: "I play today.",
                },
              ],
            },
            {
              id: "de-u5-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "das Buch", source: "the book", speak: "das Buch" },
                    { target: "die Arbeit", source: "the work", speak: "die Arbeit" },
                    { target: "gern", source: "gladly", speak: "gern" },
                    { target: "müde", source: "tired", speak: "müde" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "Ich lese",
                  after: "ein Buch.",
                  answer: "gern",
                  options: ["gern", "müde", "jetzt"],
                  translation: "I like to read a book.",
                  speak: "Ich lese gern ein Buch.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I am tired today.",
                  answer: "Ich bin heute müde.",
                  bank: ["Ich", "bin", "heute", "müde.", "gern", "Buch"],
                  speak: "Ich bin heute müde.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I like to play.",
                  options: ["Ich spiele gern.", "Ich spiele müde.", "Ich spielst gern."],
                  answer: 0,
                  speak: "Ich spiele gern.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "The work is good.",
                  answer: "Die Arbeit ist gut.",
                  bank: ["Die", "Arbeit", "ist", "gut.", "Buch", "müde"],
                  speak: "Die Arbeit ist gut.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Ich lese gern.",
                  answer: "Ich lese gern.",
                  bank: ["Ich", "lese", "gern.", "spiele", "müde."],
                  translation: "I like to read.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
