import type { Section } from "@/curriculum/types";

// Advanced German course content (B1–C2). Hand-authored, continuing the
// beginner course (de.ts, sections de-s1/de-s2). Difficulty scales with CEFR:
// B1 = Perfekt, modal verbs, weil/dass clauses; B2 = passive, Konjunktiv II,
// comparatives, opinions; C1 = nominalization, Genitiv, abstract connectors;
// C2 = idioms, register, literary/debate phrasing.
//
// Each lesson has exactly 8 exercises and includes at least one each of
// match, wordbank, fill, listen, select, and speak.

export const advancedGermanSections: Section[] = [
  // =================================================================
  // SECTION de-s3 — Independent (B1)
  // =================================================================
  {
    id: "de-s3",
    title: "Independent",
    subtitle: "Connected, everyday German (B1)",
    units: [
      // ---------------------------------------------------------------
      // UNIT 6 — Work & study
      // ---------------------------------------------------------------
      {
        id: "de-u6",
        title: "Work & study",
        subtitle: "Talk about jobs, studies and plans",
        cefr: "B1",
        color: "#2EC4B6",
        icon: "💼",
        lessons: [
          {
            id: "de-u6-l1",
            title: "Lesson 1",
            exercises: [
              {
                type: "match",
                prompt: "Match the work words",
                pairs: [
                  { target: "die Stelle", source: "the job/position", speak: "die Stelle" },
                  { target: "der Kollege", source: "the colleague", speak: "der Kollege" },
                  { target: "die Besprechung", source: "the meeting", speak: "die Besprechung" },
                  { target: "der Vertrag", source: "the contract", speak: "der Vertrag" },
                  { target: "verdienen", source: "to earn", speak: "verdienen" },
                ],
              },
              {
                type: "select",
                prompt: "Choose the correct past tense (Perfekt)",
                question: "Yesterday I worked a lot.",
                options: [
                  "Gestern habe ich viel gearbeitet.",
                  "Gestern ich habe viel gearbeitet.",
                  "Gestern habe ich viel arbeiten.",
                ],
                answer: 0,
                speak: "Gestern habe ich viel gearbeitet.",
              },
              {
                type: "fill",
                prompt: "Fill in the modal verb",
                before: "Ich",
                after: "heute länger arbeiten.",
                answer: "muss",
                options: ["muss", "musst", "müssen"],
                translation: "I have to work longer today.",
                speak: "Ich muss heute länger arbeiten.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "I have found a new job.",
                answer: "Ich habe eine neue Stelle gefunden",
                bank: ["Ich", "habe", "eine", "neue", "Stelle", "gefunden", "gemacht", "der"],
                speak: "Ich habe eine neue Stelle gefunden",
              },
              {
                type: "select",
                prompt: "What does “verdienen” mean?",
                question: "verdienen",
                speak: "verdienen",
                options: ["to earn", "to spend", "to lose"],
                answer: 0,
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Ich arbeite gern mit meinen Kollegen",
                translation: "I like working with my colleagues.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Wir haben eine lange Besprechung gehabt",
                answer: "Wir haben eine lange Besprechung gehabt",
                bank: ["Wir", "haben", "eine", "lange", "Besprechung", "gehabt", "Stelle", "gemacht"],
                translation: "We had a long meeting.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "I have to sign the contract.",
                answer: "Ich muss den Vertrag unterschreiben",
                bank: ["Ich", "muss", "den", "Vertrag", "unterschreiben", "die", "lesen"],
                speak: "Ich muss den Vertrag unterschreiben",
              },
            ],
          },
          {
            id: "de-u6-l2",
            title: "Lesson 2",
            exercises: [
              {
                type: "match",
                prompt: "Match the study words",
                pairs: [
                  { target: "die Universität", source: "the university", speak: "die Universität" },
                  { target: "studieren", source: "to study (at uni)", speak: "studieren" },
                  { target: "die Prüfung", source: "the exam", speak: "die Prüfung" },
                  { target: "das Fach", source: "the subject", speak: "das Fach" },
                  { target: "bestehen", source: "to pass", speak: "bestehen" },
                ],
              },
              {
                type: "fill",
                prompt: "Fill in the conjunction",
                before: "Ich lerne viel,",
                after: "ich die Prüfung bestehen will.",
                answer: "weil",
                options: ["weil", "dass", "und"],
                translation: "I study a lot because I want to pass the exam.",
                speak: "Ich lerne viel, weil ich die Prüfung bestehen will.",
              },
              {
                type: "select",
                prompt: "Choose the correct subordinate clause",
                question: "I think that the exam was difficult.",
                options: [
                  "Ich glaube, dass die Prüfung schwer war.",
                  "Ich glaube, dass die Prüfung war schwer.",
                  "Ich glaube, die Prüfung dass schwer war.",
                ],
                answer: 0,
                speak: "Ich glaube, dass die Prüfung schwer war.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "I study medicine in Munich.",
                answer: "Ich studiere Medizin in München",
                bank: ["Ich", "studiere", "Medizin", "in", "München", "lerne", "Fach"],
                speak: "Ich studiere Medizin in München",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Ich habe die Prüfung bestanden",
                translation: "I passed the exam.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Mein Lieblingsfach ist Geschichte",
                answer: "Mein Lieblingsfach ist Geschichte",
                bank: ["Mein", "Lieblingsfach", "ist", "Geschichte", "Fach", "war"],
                translation: "My favourite subject is history.",
              },
              {
                type: "fill",
                prompt: "Fill in the verb (Perfekt)",
                before: "Ich habe drei Stunden",
                after: ".",
                answer: "gelernt",
                options: ["gelernt", "lernen", "lerne"],
                translation: "I studied for three hours.",
                speak: "Ich habe drei Stunden gelernt.",
              },
              {
                type: "select",
                prompt: "What does “bestehen” mean here?",
                question: "die Prüfung bestehen",
                speak: "die Prüfung bestehen",
                options: ["to pass the exam", "to fail the exam", "to take the exam"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u6-l3",
            title: "Lesson 3",
            exercises: [
              {
                type: "match",
                prompt: "Match the phrases",
                pairs: [
                  { target: "sich bewerben", source: "to apply", speak: "sich bewerben" },
                  { target: "das Gehalt", source: "the salary", speak: "das Gehalt" },
                  { target: "die Erfahrung", source: "the experience", speak: "die Erfahrung" },
                  { target: "selbstständig", source: "self-employed", speak: "selbstständig" },
                ],
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "I have applied for a new job.",
                answer: "Ich habe mich um eine Stelle beworben",
                bank: ["Ich", "habe", "mich", "um", "eine", "Stelle", "beworben", "gemacht"],
                speak: "Ich habe mich um eine Stelle beworben",
              },
              {
                type: "fill",
                prompt: "Fill in the modal verb",
                before: "Ich",
                after: "mehr Geld verdienen.",
                answer: "möchte",
                options: ["möchte", "muss", "kann"],
                translation: "I would like to earn more money.",
                speak: "Ich möchte mehr Geld verdienen.",
              },
              {
                type: "select",
                prompt: "Choose the correct sentence",
                question: "I have a lot of experience because I have worked for ten years.",
                options: [
                  "Ich habe viel Erfahrung, weil ich zehn Jahre gearbeitet habe.",
                  "Ich habe viel Erfahrung, weil ich habe zehn Jahre gearbeitet.",
                  "Ich habe viel Erfahrung, weil zehn Jahre ich gearbeitet habe.",
                ],
                answer: 0,
                speak: "Ich habe viel Erfahrung, weil ich zehn Jahre gearbeitet habe.",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Ich möchte mich selbstständig machen",
                translation: "I would like to become self-employed.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Das Gehalt ist leider zu niedrig",
                answer: "Das Gehalt ist leider zu niedrig",
                bank: ["Das", "Gehalt", "ist", "leider", "zu", "niedrig", "hoch"],
                translation: "The salary is unfortunately too low.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "I want to work abroad.",
                answer: "Ich will im Ausland arbeiten",
                bank: ["Ich", "will", "im", "Ausland", "arbeiten", "wohnen", "Stelle"],
                speak: "Ich will im Ausland arbeiten",
              },
              {
                type: "select",
                prompt: "What does “sich bewerben” mean?",
                question: "sich bewerben",
                speak: "sich bewerben",
                options: ["to apply", "to resign", "to promote"],
                answer: 0,
              },
            ],
          },
        ],
      },
      // ---------------------------------------------------------------
      // UNIT 7 — Travel & plans
      // ---------------------------------------------------------------
      {
        id: "de-u7",
        title: "Travel & plans",
        subtitle: "Make plans and talk about trips",
        cefr: "B1",
        color: "#FFB703",
        icon: "✈️",
        lessons: [
          {
            id: "de-u7-l1",
            title: "Lesson 1",
            exercises: [
              {
                type: "match",
                prompt: "Match the travel words",
                pairs: [
                  { target: "die Reise", source: "the trip", speak: "die Reise" },
                  { target: "der Flug", source: "the flight", speak: "der Flug" },
                  { target: "das Gepäck", source: "the luggage", speak: "das Gepäck" },
                  { target: "die Unterkunft", source: "the accommodation", speak: "die Unterkunft" },
                  { target: "buchen", source: "to book", speak: "buchen" },
                ],
              },
              {
                type: "select",
                prompt: "Choose the correct Perfekt",
                question: "We travelled to Italy last summer.",
                options: [
                  "Wir sind letzten Sommer nach Italien gereist.",
                  "Wir haben letzten Sommer nach Italien gereist.",
                  "Wir sind letzten Sommer nach Italien reisen.",
                ],
                answer: 0,
                speak: "Wir sind letzten Sommer nach Italien gereist.",
              },
              {
                type: "fill",
                prompt: "Fill in the modal verb",
                before: "Wir",
                after: "den Flug heute buchen.",
                answer: "wollen",
                options: ["wollen", "will", "wollt"],
                translation: "We want to book the flight today.",
                speak: "Wir wollen den Flug heute buchen.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "I have booked a hotel in Berlin.",
                answer: "Ich habe ein Hotel in Berlin gebucht",
                bank: ["Ich", "habe", "ein", "Hotel", "in", "Berlin", "gebucht", "gereist"],
                speak: "Ich habe ein Hotel in Berlin gebucht",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Ich möchte eine lange Reise machen",
                translation: "I would like to take a long trip.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Mein Gepäck ist leider verloren gegangen",
                answer: "Mein Gepäck ist leider verloren gegangen",
                bank: ["Mein", "Gepäck", "ist", "leider", "verloren", "gegangen", "gebucht"],
                translation: "My luggage was unfortunately lost.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "The flight has been cancelled.",
                answer: "Der Flug ist gestrichen worden",
                bank: ["Der", "Flug", "ist", "gestrichen", "worden", "gebucht", "Reise"],
                speak: "Der Flug ist gestrichen worden",
              },
              {
                type: "select",
                prompt: "What does “die Unterkunft” mean?",
                question: "die Unterkunft",
                speak: "die Unterkunft",
                options: ["the accommodation", "the flight", "the luggage"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u7-l2",
            title: "Lesson 2",
            exercises: [
              {
                type: "match",
                prompt: "Match the planning words",
                pairs: [
                  { target: "der Plan", source: "the plan", speak: "der Plan" },
                  { target: "vorhaben", source: "to plan/intend", speak: "vorhaben" },
                  { target: "sich freuen auf", source: "to look forward to", speak: "sich freuen auf" },
                  { target: "der Urlaub", source: "the holiday", speak: "der Urlaub" },
                ],
              },
              {
                type: "fill",
                prompt: "Fill in the conjunction",
                before: "Ich bleibe zu Hause,",
                after: "es draußen regnet.",
                answer: "weil",
                options: ["weil", "dass", "oder"],
                translation: "I am staying home because it is raining outside.",
                speak: "Ich bleibe zu Hause, weil es draußen regnet.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "I am looking forward to the holiday.",
                answer: "Ich freue mich auf den Urlaub",
                bank: ["Ich", "freue", "mich", "auf", "den", "Urlaub", "Plan", "uns"],
                speak: "Ich freue mich auf den Urlaub",
              },
              {
                type: "select",
                prompt: "Choose the correct sentence",
                question: "What do you plan to do tomorrow?",
                options: [
                  "Was hast du morgen vor?",
                  "Was du morgen vorhast?",
                  "Was hast du vor morgen?",
                ],
                answer: 0,
                speak: "Was hast du morgen vor?",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Wir haben am Wochenende viel vor",
                translation: "We have a lot planned for the weekend.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Nächstes Jahr fahren wir nach Spanien",
                answer: "Nächstes Jahr fahren wir nach Spanien",
                bank: ["Nächstes", "Jahr", "fahren", "wir", "nach", "Spanien", "Urlaub"],
                translation: "Next year we are going to Spain.",
              },
              {
                type: "fill",
                prompt: "Fill in the verb",
                before: "Ich",
                after: "vor, am Samstag zu wandern.",
                answer: "habe",
                options: ["habe", "hat", "bin"],
                translation: "I plan to go hiking on Saturday.",
                speak: "Ich habe vor, am Samstag zu wandern.",
              },
              {
                type: "select",
                prompt: "What does “sich freuen auf” mean?",
                question: "sich freuen auf",
                speak: "sich freuen auf",
                options: ["to look forward to", "to be afraid of", "to forget about"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u7-l3",
            title: "Lesson 3",
            exercises: [
              {
                type: "match",
                prompt: "Match the words",
                pairs: [
                  { target: "die Grenze", source: "the border", speak: "die Grenze" },
                  { target: "der Ausweis", source: "the ID card", speak: "der Ausweis" },
                  { target: "ankommen", source: "to arrive", speak: "ankommen" },
                  { target: "die Verspätung", source: "the delay", speak: "die Verspätung" },
                ],
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "The train arrived late.",
                answer: "Der Zug ist spät angekommen",
                bank: ["Der", "Zug", "ist", "spät", "angekommen", "gefahren", "Grenze"],
                speak: "Der Zug ist spät angekommen",
              },
              {
                type: "fill",
                prompt: "Fill in the conjunction",
                before: "Ich weiß,",
                after: "der Bus eine Verspätung hat.",
                answer: "dass",
                options: ["dass", "weil", "ob"],
                translation: "I know that the bus is delayed.",
                speak: "Ich weiß, dass der Bus eine Verspätung hat.",
              },
              {
                type: "select",
                prompt: "Choose the correct sentence",
                question: "We missed the train because we arrived too late.",
                options: [
                  "Wir haben den Zug verpasst, weil wir zu spät gekommen sind.",
                  "Wir haben den Zug verpasst, weil wir sind zu spät gekommen.",
                  "Wir haben den Zug verpasst, weil zu spät wir gekommen sind.",
                ],
                answer: 0,
                speak: "Wir haben den Zug verpasst, weil wir zu spät gekommen sind.",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Wann kommen wir am Bahnhof an?",
                translation: "When do we arrive at the station?",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Bitte zeigen Sie mir Ihren Ausweis",
                answer: "Bitte zeigen Sie mir Ihren Ausweis",
                bank: ["Bitte", "zeigen", "Sie", "mir", "Ihren", "Ausweis", "Grenze"],
                translation: "Please show me your ID card.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "We have crossed the border.",
                answer: "Wir haben die Grenze überquert",
                bank: ["Wir", "haben", "die", "Grenze", "überquert", "angekommen", "der"],
                speak: "Wir haben die Grenze überquert",
              },
              {
                type: "select",
                prompt: "What does “die Verspätung” mean?",
                question: "die Verspätung",
                speak: "die Verspätung",
                options: ["the delay", "the arrival", "the departure"],
                answer: 0,
              },
            ],
          },
        ],
      },
    ],
  },
  // =================================================================
  // SECTION de-s4 — Upper Intermediate (B2)
  // =================================================================
  {
    id: "de-s4",
    title: "Upper Intermediate",
    subtitle: "Opinions, media and society (B2)",
    units: [
      // ---------------------------------------------------------------
      // UNIT 8 — Opinions & media
      // ---------------------------------------------------------------
      {
        id: "de-u8",
        title: "Opinions & media",
        subtitle: "Express opinions and discuss media",
        cefr: "B2",
        color: "#8338EC",
        icon: "📰",
        lessons: [
          {
            id: "de-u8-l1",
            title: "Lesson 1",
            exercises: [
              {
                type: "match",
                prompt: "Match the opinion phrases",
                pairs: [
                  { target: "meiner Meinung nach", source: "in my opinion", speak: "meiner Meinung nach" },
                  { target: "ich bin überzeugt", source: "I am convinced", speak: "ich bin überzeugt" },
                  { target: "es kommt darauf an", source: "it depends", speak: "es kommt darauf an" },
                  { target: "ich bezweifle", source: "I doubt", speak: "ich bezweifle" },
                  { target: "einerseits", source: "on the one hand", speak: "einerseits" },
                ],
              },
              {
                type: "select",
                prompt: "Choose the correct Konjunktiv II",
                question: "I would say that the film was boring.",
                options: [
                  "Ich würde sagen, dass der Film langweilig war.",
                  "Ich werde sagen, dass der Film langweilig war.",
                  "Ich würde sagen, dass der Film war langweilig.",
                ],
                answer: 0,
                speak: "Ich würde sagen, dass der Film langweilig war.",
              },
              {
                type: "fill",
                prompt: "Fill in the Konjunktiv II",
                before: "An deiner Stelle",
                after: "ich das anders machen.",
                answer: "würde",
                options: ["würde", "werde", "wäre"],
                translation: "In your place I would do that differently.",
                speak: "An deiner Stelle würde ich das anders machen.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "In my opinion the news is often exaggerated.",
                answer: "Meiner Meinung nach sind die Nachrichten oft übertrieben",
                bank: ["Meiner", "Meinung", "nach", "sind", "die", "Nachrichten", "oft", "übertrieben", "ist"],
                speak: "Meiner Meinung nach sind die Nachrichten oft übertrieben",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Ich bin der Ansicht, dass soziale Medien gefährlich sind",
                translation: "I am of the view that social media is dangerous.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Dieser Artikel wurde stark kritisiert",
                answer: "Dieser Artikel wurde stark kritisiert",
                bank: ["Dieser", "Artikel", "wurde", "stark", "kritisiert", "gelobt", "ist"],
                translation: "This article was strongly criticised.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "The report was written by a journalist.",
                answer: "Der Bericht wurde von einem Journalisten geschrieben",
                bank: ["Der", "Bericht", "wurde", "von", "einem", "Journalisten", "geschrieben", "hat"],
                speak: "Der Bericht wurde von einem Journalisten geschrieben",
              },
              {
                type: "select",
                prompt: "What does “es kommt darauf an” mean?",
                question: "es kommt darauf an",
                speak: "es kommt darauf an",
                options: ["it depends", "it is certain", "it is wrong"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u8-l2",
            title: "Lesson 2",
            exercises: [
              {
                type: "match",
                prompt: "Match the media words",
                pairs: [
                  { target: "die Werbung", source: "the advertising", speak: "die Werbung" },
                  { target: "die Sendung", source: "the (TV) programme", speak: "die Sendung" },
                  { target: "der Sender", source: "the channel/station", speak: "der Sender" },
                  { target: "die Quelle", source: "the source", speak: "die Quelle" },
                  { target: "glaubwürdig", source: "credible", speak: "glaubwürdig" },
                ],
              },
              {
                type: "fill",
                prompt: "Fill in the passive auxiliary",
                before: "Die Sendung",
                after: "jeden Abend ausgestrahlt.",
                answer: "wird",
                options: ["wird", "hat", "ist"],
                translation: "The programme is broadcast every evening.",
                speak: "Die Sendung wird jeden Abend ausgestrahlt.",
              },
              {
                type: "select",
                prompt: "Choose the comparative sentence",
                question: "Television is less reliable than newspapers.",
                options: [
                  "Das Fernsehen ist weniger zuverlässig als Zeitungen.",
                  "Das Fernsehen ist wenig zuverlässig wie Zeitungen.",
                  "Das Fernsehen ist weniger zuverlässiger als Zeitungen.",
                ],
                answer: 0,
                speak: "Das Fernsehen ist weniger zuverlässig als Zeitungen.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "One should always check the source.",
                answer: "Man sollte immer die Quelle überprüfen",
                bank: ["Man", "sollte", "immer", "die", "Quelle", "überprüfen", "Werbung", "ist"],
                speak: "Man sollte immer die Quelle überprüfen",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Diese Quelle scheint mir nicht glaubwürdig",
                translation: "This source does not seem credible to me.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Werbung beeinflusst unser Verhalten stärker als gedacht",
                answer: "Werbung beeinflusst unser Verhalten stärker als gedacht",
                bank: ["Werbung", "beeinflusst", "unser", "Verhalten", "stärker", "als", "gedacht", "schwächer"],
                translation: "Advertising influences our behaviour more than thought.",
              },
              {
                type: "fill",
                prompt: "Fill in the comparative",
                before: "Diese Zeitung ist",
                after: "als die andere.",
                answer: "objektiver",
                options: ["objektiver", "objektiv", "am objektivsten"],
                translation: "This newspaper is more objective than the other.",
                speak: "Diese Zeitung ist objektiver als die andere.",
              },
              {
                type: "select",
                prompt: "What does “glaubwürdig” mean?",
                question: "glaubwürdig",
                speak: "glaubwürdig",
                options: ["credible", "boring", "expensive"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u8-l3",
            title: "Lesson 3",
            exercises: [
              {
                type: "match",
                prompt: "Match the debate words",
                pairs: [
                  { target: "der Vorteil", source: "the advantage", speak: "der Vorteil" },
                  { target: "der Nachteil", source: "the disadvantage", speak: "der Nachteil" },
                  { target: "behaupten", source: "to claim", speak: "behaupten" },
                  { target: "zustimmen", source: "to agree", speak: "zustimmen" },
                  { target: "ablehnen", source: "to reject", speak: "ablehnen" },
                ],
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "I would agree with you if I had more time.",
                answer: "Ich würde dir zustimmen, wenn ich mehr Zeit hätte",
                bank: ["Ich", "würde", "dir", "zustimmen,", "wenn", "ich", "mehr", "Zeit", "hätte", "habe"],
                speak: "Ich würde dir zustimmen, wenn ich mehr Zeit hätte",
              },
              {
                type: "fill",
                prompt: "Fill in the Konjunktiv II of sein",
                before: "Es",
                after: "besser, wenn alle mitmachen würden.",
                answer: "wäre",
                options: ["wäre", "war", "würde"],
                translation: "It would be better if everyone joined in.",
                speak: "Es wäre besser, wenn alle mitmachen würden.",
              },
              {
                type: "select",
                prompt: "Choose the correct sentence",
                question: "Everyone has the right to express their opinion.",
                options: [
                  "Jeder hat das Recht, seine Meinung zu äußern.",
                  "Jeder hat das Recht, seine Meinung äußern.",
                  "Jeder hat das Recht, zu äußern seine Meinung.",
                ],
                answer: 0,
                speak: "Jeder hat das Recht, seine Meinung zu äußern.",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Da muss ich dir leider widersprechen",
                translation: "I unfortunately have to disagree with you there.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Dieser Vorschlag wurde von vielen abgelehnt",
                answer: "Dieser Vorschlag wurde von vielen abgelehnt",
                bank: ["Dieser", "Vorschlag", "wurde", "von", "vielen", "abgelehnt", "angenommen", "ist"],
                translation: "This proposal was rejected by many.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "He claims that he is always right.",
                answer: "Er behauptet, dass er immer recht hat",
                bank: ["Er", "behauptet,", "dass", "er", "immer", "recht", "hat", "ist"],
                speak: "Er behauptet, dass er immer recht hat",
              },
              {
                type: "select",
                prompt: "What does “ablehnen” mean?",
                question: "ablehnen",
                speak: "ablehnen",
                options: ["to reject", "to accept", "to suggest"],
                answer: 0,
              },
            ],
          },
        ],
      },
      // ---------------------------------------------------------------
      // UNIT 9 — Health & society
      // ---------------------------------------------------------------
      {
        id: "de-u9",
        title: "Health & society",
        subtitle: "Discuss health, society and change",
        cefr: "B2",
        color: "#06D6A0",
        icon: "🩺",
        lessons: [
          {
            id: "de-u9-l1",
            title: "Lesson 1",
            exercises: [
              {
                type: "match",
                prompt: "Match the health words",
                pairs: [
                  { target: "die Gesundheit", source: "the health", speak: "die Gesundheit" },
                  { target: "die Behandlung", source: "the treatment", speak: "die Behandlung" },
                  { target: "sich erholen", source: "to recover", speak: "sich erholen" },
                  { target: "vorbeugen", source: "to prevent", speak: "vorbeugen" },
                  { target: "die Ernährung", source: "the nutrition", speak: "die Ernährung" },
                ],
              },
              {
                type: "fill",
                prompt: "Fill in the passive auxiliary",
                before: "Der Patient",
                after: "sofort behandelt.",
                answer: "wurde",
                options: ["wurde", "hatte", "war"],
                translation: "The patient was treated immediately.",
                speak: "Der Patient wurde sofort behandelt.",
              },
              {
                type: "select",
                prompt: "Choose the Konjunktiv II",
                question: "If I had more time, I would exercise more.",
                options: [
                  "Wenn ich mehr Zeit hätte, würde ich mehr Sport machen.",
                  "Wenn ich mehr Zeit habe, würde ich mehr Sport machen.",
                  "Wenn ich mehr Zeit hätte, werde ich mehr Sport machen.",
                ],
                answer: 0,
                speak: "Wenn ich mehr Zeit hätte, würde ich mehr Sport machen.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "A healthy diet prevents many illnesses.",
                answer: "Eine gesunde Ernährung beugt vielen Krankheiten vor",
                bank: ["Eine", "gesunde", "Ernährung", "beugt", "vielen", "Krankheiten", "vor", "ist"],
                speak: "Eine gesunde Ernährung beugt vielen Krankheiten vor",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Ich sollte mich mehr um meine Gesundheit kümmern",
                translation: "I should take better care of my health.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Nach der Operation muss er sich lange erholen",
                answer: "Nach der Operation muss er sich lange erholen",
                bank: ["Nach", "der", "Operation", "muss", "er", "sich", "lange", "erholen", "kurz"],
                translation: "After the operation he has to recover for a long time.",
              },
              {
                type: "fill",
                prompt: "Fill in the comparative",
                before: "Vorbeugen ist",
                after: "als heilen.",
                answer: "besser",
                options: ["besser", "gut", "am besten"],
                translation: "Prevention is better than cure.",
                speak: "Vorbeugen ist besser als heilen.",
              },
              {
                type: "select",
                prompt: "What does “sich erholen” mean?",
                question: "sich erholen",
                speak: "sich erholen",
                options: ["to recover", "to get sick", "to worry"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u9-l2",
            title: "Lesson 2",
            exercises: [
              {
                type: "match",
                prompt: "Match the society words",
                pairs: [
                  { target: "die Gesellschaft", source: "the society", speak: "die Gesellschaft" },
                  { target: "die Veränderung", source: "the change", speak: "die Veränderung" },
                  { target: "die Gerechtigkeit", source: "the justice", speak: "die Gerechtigkeit" },
                  { target: "fördern", source: "to promote", speak: "fördern" },
                  { target: "die Bildung", source: "the education", speak: "die Bildung" },
                ],
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "Education should be promoted by the state.",
                answer: "Bildung sollte vom Staat gefördert werden",
                bank: ["Bildung", "sollte", "vom", "Staat", "gefördert", "werden", "wird", "der"],
                speak: "Bildung sollte vom Staat gefördert werden",
              },
              {
                type: "fill",
                prompt: "Fill in the Konjunktiv II",
                before: "Ohne Bildung",
                after: "die Gesellschaft ärmer.",
                answer: "wäre",
                options: ["wäre", "war", "würde"],
                translation: "Without education society would be poorer.",
                speak: "Ohne Bildung wäre die Gesellschaft ärmer.",
              },
              {
                type: "select",
                prompt: "Choose the correct sentence",
                question: "Many people demand more justice.",
                options: [
                  "Viele Menschen fordern mehr Gerechtigkeit.",
                  "Viele Menschen fordern mehr Gerechtigkeit fordern.",
                  "Viele Menschen mehr Gerechtigkeit fordern.",
                ],
                answer: 0,
                speak: "Viele Menschen fordern mehr Gerechtigkeit.",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Die Gesellschaft verändert sich immer schneller",
                translation: "Society is changing ever faster.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Diese Reform wurde lange diskutiert",
                answer: "Diese Reform wurde lange diskutiert",
                bank: ["Diese", "Reform", "wurde", "lange", "diskutiert", "kurz", "ist"],
                translation: "This reform was discussed for a long time.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "Change is more important than tradition.",
                answer: "Veränderung ist wichtiger als Tradition",
                bank: ["Veränderung", "ist", "wichtiger", "als", "Tradition", "wichtig", "die"],
                speak: "Veränderung ist wichtiger als Tradition",
              },
              {
                type: "select",
                prompt: "What does “fördern” mean?",
                question: "fördern",
                speak: "fördern",
                options: ["to promote", "to forbid", "to ignore"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u9-l3",
            title: "Lesson 3",
            exercises: [
              {
                type: "match",
                prompt: "Match the environment words",
                pairs: [
                  { target: "die Umwelt", source: "the environment", speak: "die Umwelt" },
                  { target: "der Klimawandel", source: "the climate change", speak: "der Klimawandel" },
                  { target: "vermeiden", source: "to avoid", speak: "vermeiden" },
                  { target: "nachhaltig", source: "sustainable", speak: "nachhaltig" },
                  { target: "die Verantwortung", source: "the responsibility", speak: "die Verantwortung" },
                ],
              },
              {
                type: "fill",
                prompt: "Fill in the passive",
                before: "Plastik sollte unbedingt",
                after: "werden.",
                answer: "vermieden",
                options: ["vermieden", "vermeiden", "vermeidet"],
                translation: "Plastic should definitely be avoided.",
                speak: "Plastik sollte unbedingt vermieden werden.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "We would have to live more sustainably.",
                answer: "Wir müssten nachhaltiger leben",
                bank: ["Wir", "müssten", "nachhaltiger", "leben", "müssen", "nachhaltig", "wäre"],
                speak: "Wir müssten nachhaltiger leben",
              },
              {
                type: "select",
                prompt: "Choose the correct Konjunktiv II",
                question: "If everyone helped, the climate would improve.",
                options: [
                  "Wenn alle helfen würden, würde sich das Klima verbessern.",
                  "Wenn alle helfen werden, würde sich das Klima verbessern.",
                  "Wenn alle würden helfen, das Klima verbessern würde.",
                ],
                answer: 0,
                speak: "Wenn alle helfen würden, würde sich das Klima verbessern.",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Jeder trägt Verantwortung für die Umwelt",
                translation: "Everyone bears responsibility for the environment.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Der Klimawandel bedroht unsere Zukunft",
                answer: "Der Klimawandel bedroht unsere Zukunft",
                bank: ["Der", "Klimawandel", "bedroht", "unsere", "Zukunft", "schützt", "die"],
                translation: "Climate change threatens our future.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "More needs to be done for the environment.",
                answer: "Für die Umwelt muss mehr getan werden",
                bank: ["Für", "die", "Umwelt", "muss", "mehr", "getan", "werden", "wird"],
                speak: "Für die Umwelt muss mehr getan werden",
              },
              {
                type: "select",
                prompt: "What does “nachhaltig” mean?",
                question: "nachhaltig",
                speak: "nachhaltig",
                options: ["sustainable", "wasteful", "temporary"],
                answer: 0,
              },
            ],
          },
        ],
      },
    ],
  },
  // =================================================================
  // SECTION de-s5 — Advanced (C1)
  // =================================================================
  {
    id: "de-s5",
    title: "Advanced",
    subtitle: "Abstract and academic German (C1)",
    units: [
      // ---------------------------------------------------------------
      // UNIT 10 — Abstract ideas
      // ---------------------------------------------------------------
      {
        id: "de-u10",
        title: "Abstract ideas",
        subtitle: "Discuss abstract and complex ideas",
        cefr: "C1",
        color: "#3A0CA3",
        icon: "💡",
        lessons: [
          {
            id: "de-u10-l1",
            title: "Lesson 1",
            exercises: [
              {
                type: "match",
                prompt: "Match the abstract nouns",
                pairs: [
                  { target: "die Entwicklung", source: "the development", speak: "die Entwicklung" },
                  { target: "die Erkenntnis", source: "the insight", speak: "die Erkenntnis" },
                  { target: "die Wahrnehmung", source: "the perception", speak: "die Wahrnehmung" },
                  { target: "das Bewusstsein", source: "the consciousness", speak: "das Bewusstsein" },
                  { target: "der Zusammenhang", source: "the context/connection", speak: "der Zusammenhang" },
                ],
              },
              {
                type: "select",
                prompt: "Choose the sentence with a Genitiv",
                question: "the consequences of this development",
                options: [
                  "die Folgen dieser Entwicklung",
                  "die Folgen diese Entwicklung",
                  "die Folgen dieser Entwicklungen den",
                ],
                answer: 0,
                speak: "die Folgen dieser Entwicklung",
              },
              {
                type: "fill",
                prompt: "Fill in the connector",
                before: "Es ist schwierig,",
                after: "wir geben nicht auf.",
                answer: "dennoch",
                options: ["dennoch", "weil", "damit"],
                translation: "It is difficult, nevertheless we do not give up.",
                speak: "Es ist schwierig, dennoch geben wir nicht auf.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "Despite the criticism the idea remained convincing.",
                answer: "Trotz der Kritik blieb die Idee überzeugend",
                bank: ["Trotz", "der", "Kritik", "blieb", "die", "Idee", "überzeugend", "wegen"],
                speak: "Trotz der Kritik blieb die Idee überzeugend",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Die Bedeutung dieser Erkenntnis lässt sich kaum überschätzen",
                translation: "The significance of this insight can hardly be overstated.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Obwohl die Theorie umstritten ist, überzeugt sie viele",
                answer: "Obwohl die Theorie umstritten ist, überzeugt sie viele",
                bank: ["Obwohl", "die", "Theorie", "umstritten", "ist,", "überzeugt", "sie", "viele", "weil"],
                translation: "Although the theory is controversial, it convinces many.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "The development of language is a fascinating phenomenon.",
                answer: "Die Entwicklung der Sprache ist ein faszinierendes Phänomen",
                bank: ["Die", "Entwicklung", "der", "Sprache", "ist", "ein", "faszinierendes", "Phänomen", "den"],
                speak: "Die Entwicklung der Sprache ist ein faszinierendes Phänomen",
              },
              {
                type: "select",
                prompt: "What does “der Zusammenhang” mean?",
                question: "der Zusammenhang",
                speak: "der Zusammenhang",
                options: ["the connection/context", "the contradiction", "the coincidence"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u10-l2",
            title: "Lesson 2",
            exercises: [
              {
                type: "match",
                prompt: "Match the connectors",
                pairs: [
                  { target: "trotzdem", source: "nevertheless", speak: "trotzdem" },
                  { target: "obwohl", source: "although", speak: "obwohl" },
                  { target: "infolgedessen", source: "consequently", speak: "infolgedessen" },
                  { target: "im Gegensatz dazu", source: "in contrast", speak: "im Gegensatz dazu" },
                  { target: "demzufolge", source: "accordingly", speak: "demzufolge" },
                ],
              },
              {
                type: "fill",
                prompt: "Fill in the connector",
                before: "Er war müde,",
                after: "arbeitete er weiter.",
                answer: "trotzdem",
                options: ["trotzdem", "weil", "dass"],
                translation: "He was tired, nevertheless he kept working.",
                speak: "Er war müde, trotzdem arbeitete er weiter.",
              },
              {
                type: "select",
                prompt: "Choose the correct nominalization",
                question: "Reading promotes thinking.",
                options: [
                  "Das Lesen fördert das Denken.",
                  "Lesen fördert das denken.",
                  "Das Lesen fördert dem Denken.",
                ],
                answer: 0,
                speak: "Das Lesen fördert das Denken.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "Although he was right, no one listened to him.",
                answer: "Obwohl er recht hatte, hörte ihm niemand zu",
                bank: ["Obwohl", "er", "recht", "hatte,", "hörte", "ihm", "niemand", "zu", "weil"],
                speak: "Obwohl er recht hatte, hörte ihm niemand zu",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Im Gegensatz dazu vertritt sie eine völlig andere Auffassung",
                translation: "In contrast, she holds a completely different view.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Die Argumente waren überzeugend, dennoch blieb er skeptisch",
                answer: "Die Argumente waren überzeugend, dennoch blieb er skeptisch",
                bank: ["Die", "Argumente", "waren", "überzeugend,", "dennoch", "blieb", "er", "skeptisch", "weil"],
                translation: "The arguments were convincing, nevertheless he stayed sceptical.",
              },
              {
                type: "fill",
                prompt: "Fill in the Genitiv article",
                before: "Wegen",
                after: "schlechten Wetters blieben wir zu Hause.",
                answer: "des",
                options: ["des", "dem", "der"],
                translation: "Because of the bad weather we stayed home.",
                speak: "Wegen des schlechten Wetters blieben wir zu Hause.",
              },
              {
                type: "select",
                prompt: "What does “infolgedessen” mean?",
                question: "infolgedessen",
                speak: "infolgedessen",
                options: ["consequently", "beforehand", "by chance"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u10-l3",
            title: "Lesson 3",
            exercises: [
              {
                type: "match",
                prompt: "Match the nuanced words",
                pairs: [
                  { target: "die Voraussetzung", source: "the prerequisite", speak: "die Voraussetzung" },
                  { target: "die Auswirkung", source: "the impact", speak: "die Auswirkung" },
                  { target: "der Anspruch", source: "the claim/demand", speak: "der Anspruch" },
                  { target: "die Annahme", source: "the assumption", speak: "die Annahme" },
                  { target: "abwägen", source: "to weigh up", speak: "abwägen" },
                ],
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "The success of the project depends on many factors.",
                answer: "Der Erfolg des Projekts hängt von vielen Faktoren ab",
                bank: ["Der", "Erfolg", "des", "Projekts", "hängt", "von", "vielen", "Faktoren", "ab", "dem"],
                speak: "Der Erfolg des Projekts hängt von vielen Faktoren ab",
              },
              {
                type: "fill",
                prompt: "Fill in the connector",
                before: "Man muss die Vor- und Nachteile sorgfältig",
                after: ".",
                answer: "abwägen",
                options: ["abwägen", "abwägt", "abgewogen"],
                translation: "One must carefully weigh up the pros and cons.",
                speak: "Man muss die Vor- und Nachteile sorgfältig abwägen.",
              },
              {
                type: "select",
                prompt: "Choose the sentence with correct Genitiv",
                question: "the impact of the decision on society",
                options: [
                  "die Auswirkung der Entscheidung auf die Gesellschaft",
                  "die Auswirkung die Entscheidung auf die Gesellschaft",
                  "die Auswirkung der Entscheidung auf der Gesellschaft",
                ],
                answer: 0,
                speak: "die Auswirkung der Entscheidung auf die Gesellschaft",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Diese Annahme erweist sich bei näherer Betrachtung als falsch",
                translation: "This assumption proves false on closer examination.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Eine gründliche Vorbereitung ist die Voraussetzung des Erfolgs",
                answer: "Eine gründliche Vorbereitung ist die Voraussetzung des Erfolgs",
                bank: ["Eine", "gründliche", "Vorbereitung", "ist", "die", "Voraussetzung", "des", "Erfolgs", "dem"],
                translation: "Thorough preparation is the prerequisite of success.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "Despite all doubts the plan was implemented.",
                answer: "Trotz aller Zweifel wurde der Plan umgesetzt",
                bank: ["Trotz", "aller", "Zweifel", "wurde", "der", "Plan", "umgesetzt", "wegen"],
                speak: "Trotz aller Zweifel wurde der Plan umgesetzt",
              },
              {
                type: "select",
                prompt: "What does “abwägen” mean?",
                question: "abwägen",
                speak: "abwägen",
                options: ["to weigh up", "to reject", "to exaggerate"],
                answer: 0,
              },
            ],
          },
        ],
      },
      // ---------------------------------------------------------------
      // UNIT 11 — Work & academia
      // ---------------------------------------------------------------
      {
        id: "de-u11",
        title: "Work & academia",
        subtitle: "Professional and academic language",
        cefr: "C1",
        color: "#7209B7",
        icon: "🎓",
        lessons: [
          {
            id: "de-u11-l1",
            title: "Lesson 1",
            exercises: [
              {
                type: "match",
                prompt: "Match the academic words",
                pairs: [
                  { target: "die Forschung", source: "the research", speak: "die Forschung" },
                  { target: "die These", source: "the thesis", speak: "die These" },
                  { target: "der Beleg", source: "the evidence", speak: "der Beleg" },
                  { target: "die Schlussfolgerung", source: "the conclusion", speak: "die Schlussfolgerung" },
                  { target: "untersuchen", source: "to investigate", speak: "untersuchen" },
                ],
              },
              {
                type: "fill",
                prompt: "Fill in the Genitiv article",
                before: "Die Ergebnisse",
                after: "Studie waren eindeutig.",
                answer: "der",
                options: ["der", "die", "dem"],
                translation: "The results of the study were clear.",
                speak: "Die Ergebnisse der Studie waren eindeutig.",
              },
              {
                type: "select",
                prompt: "Choose the academic phrasing",
                question: "This study examines the influence of stress on sleep.",
                options: [
                  "Diese Studie untersucht den Einfluss von Stress auf den Schlaf.",
                  "Diese Studie untersucht der Einfluss von Stress auf den Schlaf.",
                  "Diese Studie untersucht den Einfluss von Stress auf dem Schlaf.",
                ],
                answer: 0,
                speak: "Diese Studie untersucht den Einfluss von Stress auf den Schlaf.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "The conclusion is based on solid evidence.",
                answer: "Die Schlussfolgerung beruht auf soliden Belegen",
                bank: ["Die", "Schlussfolgerung", "beruht", "auf", "soliden", "Belegen", "These", "dem"],
                speak: "Die Schlussfolgerung beruht auf soliden Belegen",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Die Forschung liefert dafür bislang keine eindeutigen Belege",
                translation: "Research so far provides no clear evidence for this.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Diese These wird durch zahlreiche Studien gestützt",
                answer: "Diese These wird durch zahlreiche Studien gestützt",
                bank: ["Diese", "These", "wird", "durch", "zahlreiche", "Studien", "gestützt", "wenige", "ist"],
                translation: "This thesis is supported by numerous studies.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "Despite the evidence the hypothesis remains disputed.",
                answer: "Trotz der Belege bleibt die Hypothese umstritten",
                bank: ["Trotz", "der", "Belege", "bleibt", "die", "Hypothese", "umstritten", "wegen"],
                speak: "Trotz der Belege bleibt die Hypothese umstritten",
              },
              {
                type: "select",
                prompt: "What does “untersuchen” mean?",
                question: "untersuchen",
                speak: "untersuchen",
                options: ["to investigate", "to ignore", "to publish"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u11-l2",
            title: "Lesson 2",
            exercises: [
              {
                type: "match",
                prompt: "Match the workplace words",
                pairs: [
                  { target: "die Zuständigkeit", source: "the responsibility/remit", speak: "die Zuständigkeit" },
                  { target: "die Frist", source: "the deadline", speak: "die Frist" },
                  { target: "umsetzen", source: "to implement", speak: "umsetzen" },
                  { target: "die Effizienz", source: "the efficiency", speak: "die Effizienz" },
                  { target: "der Aufwand", source: "the effort/expense", speak: "der Aufwand" },
                ],
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "The implementation of the plan requires great effort.",
                answer: "Die Umsetzung des Plans erfordert großen Aufwand",
                bank: ["Die", "Umsetzung", "des", "Plans", "erfordert", "großen", "Aufwand", "dem"],
                speak: "Die Umsetzung des Plans erfordert großen Aufwand",
              },
              {
                type: "fill",
                prompt: "Fill in the connector",
                before: "Die Frist war knapp,",
                after: "lieferten wir pünktlich.",
                answer: "trotzdem",
                options: ["trotzdem", "weil", "damit"],
                translation: "The deadline was tight, nevertheless we delivered on time.",
                speak: "Die Frist war knapp, trotzdem lieferten wir pünktlich.",
              },
              {
                type: "select",
                prompt: "Choose the correct sentence",
                question: "This falls within my colleague's remit.",
                options: [
                  "Das fällt in die Zuständigkeit meines Kollegen.",
                  "Das fällt in die Zuständigkeit mein Kollege.",
                  "Das fällt in der Zuständigkeit meines Kollegen.",
                ],
                answer: 0,
                speak: "Das fällt in die Zuständigkeit meines Kollegen.",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Wir sollten den Aufwand und den Nutzen sorgfältig abwägen",
                translation: "We should carefully weigh effort against benefit.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Das Projekt wurde trotz knapper Frist erfolgreich abgeschlossen",
                answer: "Das Projekt wurde trotz knapper Frist erfolgreich abgeschlossen",
                bank: ["Das", "Projekt", "wurde", "trotz", "knapper", "Frist", "erfolgreich", "abgeschlossen", "wegen"],
                translation: "The project was completed successfully despite a tight deadline.",
              },
              {
                type: "fill",
                prompt: "Fill in the comparative",
                before: "Dieses Verfahren ist deutlich",
                after: "als das alte.",
                answer: "effizienter",
                options: ["effizienter", "effizient", "am effizientesten"],
                translation: "This procedure is significantly more efficient than the old one.",
                speak: "Dieses Verfahren ist deutlich effizienter als das alte.",
              },
              {
                type: "select",
                prompt: "What does “die Frist” mean?",
                question: "die Frist",
                speak: "die Frist",
                options: ["the deadline", "the meeting", "the budget"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u11-l3",
            title: "Lesson 3",
            exercises: [
              {
                type: "match",
                prompt: "Match the discussion words",
                pairs: [
                  { target: "der Einwand", source: "the objection", speak: "der Einwand" },
                  { target: "berücksichtigen", source: "to take into account", speak: "berücksichtigen" },
                  { target: "der Standpunkt", source: "the standpoint", speak: "der Standpunkt" },
                  { target: "nachvollziehbar", source: "comprehensible", speak: "nachvollziehbar" },
                  { target: "die Tragweite", source: "the scope/import", speak: "die Tragweite" },
                ],
              },
              {
                type: "fill",
                prompt: "Fill in the connector",
                before: "Wir müssen alle Aspekte",
                after: ", bevor wir entscheiden.",
                answer: "berücksichtigen",
                options: ["berücksichtigen", "berücksichtigt", "berücksichtige"],
                translation: "We must take all aspects into account before we decide.",
                speak: "Wir müssen alle Aspekte berücksichtigen, bevor wir entscheiden.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "Your objection is entirely comprehensible.",
                answer: "Ihr Einwand ist durchaus nachvollziehbar",
                bank: ["Ihr", "Einwand", "ist", "durchaus", "nachvollziehbar", "Standpunkt", "der"],
                speak: "Ihr Einwand ist durchaus nachvollziehbar",
              },
              {
                type: "select",
                prompt: "Choose the sentence with correct Genitiv",
                question: "Few grasp the scope of this decision.",
                options: [
                  "Nur wenige erfassen die Tragweite dieser Entscheidung.",
                  "Nur wenige erfassen die Tragweite diese Entscheidung.",
                  "Nur wenige erfassen die Tragweite dieser Entscheidungen den.",
                ],
                answer: 0,
                speak: "Nur wenige erfassen die Tragweite dieser Entscheidung.",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Ich kann deinen Standpunkt nachvollziehen, teile ihn aber nicht",
                translation: "I can understand your standpoint, but I do not share it.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Diese Entscheidung muss gründlich begründet werden",
                answer: "Diese Entscheidung muss gründlich begründet werden",
                bank: ["Diese", "Entscheidung", "muss", "gründlich", "begründet", "werden", "wird", "die"],
                translation: "This decision must be thoroughly justified.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "Despite all objections the decision was upheld.",
                answer: "Trotz aller Einwände wurde die Entscheidung beibehalten",
                bank: ["Trotz", "aller", "Einwände", "wurde", "die", "Entscheidung", "beibehalten", "wegen"],
                speak: "Trotz aller Einwände wurde die Entscheidung beibehalten",
              },
              {
                type: "select",
                prompt: "What does “berücksichtigen” mean?",
                question: "berücksichtigen",
                speak: "berücksichtigen",
                options: ["to take into account", "to overlook", "to refuse"],
                answer: 0,
              },
            ],
          },
        ],
      },
    ],
  },
  // =================================================================
  // SECTION de-s6 — Mastery (C2)
  // =================================================================
  {
    id: "de-s6",
    title: "Mastery",
    subtitle: "Nuance, idiom and debate (C2)",
    units: [
      // ---------------------------------------------------------------
      // UNIT 12 — Nuance & idiom
      // ---------------------------------------------------------------
      {
        id: "de-u12",
        title: "Nuance & idiom",
        subtitle: "Idioms, register and subtle distinctions",
        cefr: "C1",
        color: "#D00000",
        icon: "🎭",
        lessons: [
          {
            id: "de-u12-l1",
            title: "Lesson 1",
            exercises: [
              {
                type: "match",
                prompt: "Match the idioms to their meanings",
                pairs: [
                  { target: "die Daumen drücken", source: "to keep one's fingers crossed", speak: "die Daumen drücken" },
                  { target: "ins Gras beißen", source: "to bite the dust", speak: "ins Gras beißen" },
                  { target: "Tomaten auf den Augen haben", source: "to be oblivious", speak: "Tomaten auf den Augen haben" },
                  { target: "die Katze im Sack kaufen", source: "to buy a pig in a poke", speak: "die Katze im Sack kaufen" },
                  { target: "aus dem Häuschen sein", source: "to be over the moon", speak: "aus dem Häuschen sein" },
                ],
              },
              {
                type: "select",
                prompt: "What does this idiom mean?",
                question: "Ich drücke dir die Daumen.",
                speak: "Ich drücke dir die Daumen.",
                options: [
                  "I'm keeping my fingers crossed for you.",
                  "I'm pointing at you.",
                  "I'm angry with you.",
                ],
                answer: 0,
              },
              {
                type: "fill",
                prompt: "Complete the idiom",
                before: "Du nimmst kein Blatt vor den",
                after: ".",
                answer: "Mund",
                options: ["Mund", "Augen", "Kopf"],
                translation: "You don't mince your words.",
                speak: "Du nimmst kein Blatt vor den Mund.",
              },
              {
                type: "wordbank",
                prompt: "Translate this idiomatic sentence",
                given: "That is the straw that breaks the camel's back.",
                answer: "Das bringt das Fass zum Überlaufen",
                bank: ["Das", "bringt", "das", "Fass", "zum", "Überlaufen", "Glas", "voll"],
                speak: "Das bringt das Fass zum Überlaufen",
              },
              {
                type: "speak",
                prompt: "Say this idiom out loud",
                text: "Jetzt haben wir den Salat",
                translation: "Now we're in a fine mess.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Er hat die Flinte ins Korn geworfen",
                answer: "Er hat die Flinte ins Korn geworfen",
                bank: ["Er", "hat", "die", "Flinte", "ins", "Korn", "geworfen", "gelegt", "den"],
                translation: "He threw in the towel (gave up).",
              },
              {
                type: "select",
                prompt: "What does “aus dem Häuschen sein” mean?",
                question: "aus dem Häuschen sein",
                speak: "aus dem Häuschen sein",
                options: ["to be over the moon", "to be homeless", "to be furious"],
                answer: 0,
              },
              {
                type: "wordbank",
                prompt: "Translate this idiomatic sentence",
                given: "He always exaggerates everything wildly.",
                answer: "Er macht aus einer Mücke einen Elefanten",
                bank: ["Er", "macht", "aus", "einer", "Mücke", "einen", "Elefanten", "großen", "die"],
                speak: "Er macht aus einer Mücke einen Elefanten",
              },
            ],
          },
          {
            id: "de-u12-l2",
            title: "Lesson 2",
            exercises: [
              {
                type: "match",
                prompt: "Match the register pairs",
                pairs: [
                  { target: "speisen", source: "to dine (formal)", speak: "speisen" },
                  { target: "futtern", source: "to scoff (colloquial)", speak: "futtern" },
                  { target: "erwerben", source: "to acquire (formal)", speak: "erwerben" },
                  { target: "kriegen", source: "to get (colloquial)", speak: "kriegen" },
                  { target: "sich erkundigen", source: "to inquire (formal)", speak: "sich erkundigen" },
                ],
              },
              {
                type: "select",
                prompt: "Which is the more formal register?",
                question: "to get a document",
                options: [
                  "ein Dokument erhalten",
                  "ein Dokument kriegen",
                  "ein Dokument abstauben",
                ],
                answer: 0,
                speak: "ein Dokument erhalten",
              },
              {
                type: "fill",
                prompt: "Fill in the formal verb",
                before: "Dürfte ich mich nach dem Termin",
                after: "?",
                answer: "erkundigen",
                options: ["erkundigen", "fragen", "kriegen"],
                translation: "Might I inquire about the appointment?",
                speak: "Dürfte ich mich nach dem Termin erkundigen?",
              },
              {
                type: "wordbank",
                prompt: "Translate this formal sentence",
                given: "We would be delighted to welcome you.",
                answer: "Wir würden uns sehr freuen, Sie begrüßen zu dürfen",
                bank: ["Wir", "würden", "uns", "sehr", "freuen,", "Sie", "begrüßen", "zu", "dürfen", "können"],
                speak: "Wir würden uns sehr freuen, Sie begrüßen zu dürfen",
              },
              {
                type: "speak",
                prompt: "Say this formal phrase out loud",
                text: "Hätten Sie die Güte, mir kurz zu helfen?",
                translation: "Would you be so kind as to help me briefly?",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Es wäre überaus freundlich, wenn Sie mir Bescheid gäben",
                answer: "Es wäre überaus freundlich, wenn Sie mir Bescheid gäben",
                bank: ["Es", "wäre", "überaus", "freundlich,", "wenn", "Sie", "mir", "Bescheid", "gäben", "geben"],
                translation: "It would be extremely kind if you let me know.",
              },
              {
                type: "select",
                prompt: "Which word is colloquial, not formal?",
                question: "to get",
                speak: "kriegen",
                options: ["kriegen", "erhalten", "erwerben"],
                answer: 0,
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "May I take the liberty of making a suggestion?",
                answer: "Darf ich mir erlauben, einen Vorschlag zu machen?",
                bank: ["Darf", "ich", "mir", "erlauben,", "einen", "Vorschlag", "zu", "machen?", "die"],
                speak: "Darf ich mir erlauben, einen Vorschlag zu machen?",
              },
            ],
          },
          {
            id: "de-u12-l3",
            title: "Lesson 3",
            exercises: [
              {
                type: "match",
                prompt: "Match the subtle distinctions",
                pairs: [
                  { target: "scheinbar", source: "seemingly (but not really)", speak: "scheinbar" },
                  { target: "anscheinend", source: "apparently (probably so)", speak: "anscheinend" },
                  { target: "eigentlich", source: "actually", speak: "eigentlich" },
                  { target: "letztlich", source: "ultimately", speak: "letztlich" },
                  { target: "ohnehin", source: "anyway", speak: "ohnehin" },
                ],
              },
              {
                type: "select",
                prompt: "Choose the right nuance",
                question: "He is apparently ill (it seems likely true).",
                options: [
                  "Er ist anscheinend krank.",
                  "Er ist scheinbar krank.",
                  "Er ist eigentlich krank.",
                ],
                answer: 0,
                speak: "Er ist anscheinend krank.",
              },
              {
                type: "fill",
                prompt: "Fill in the particle",
                before: "Das war",
                after: "nur ein Missverständnis.",
                answer: "letztlich",
                options: ["letztlich", "scheinbar", "kaum"],
                translation: "Ultimately it was just a misunderstanding.",
                speak: "Das war letztlich nur ein Missverständnis.",
              },
              {
                type: "wordbank",
                prompt: "Translate this nuanced sentence",
                given: "Actually I wanted to leave earlier.",
                answer: "Eigentlich wollte ich früher gehen",
                bank: ["Eigentlich", "wollte", "ich", "früher", "gehen", "kommen", "spät"],
                speak: "Eigentlich wollte ich früher gehen",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Das spielt ohnehin keine große Rolle mehr",
                translation: "That doesn't really matter anymore anyway.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Scheinbar einfache Fragen sind oft am schwierigsten",
                answer: "Scheinbar einfache Fragen sind oft am schwierigsten",
                bank: ["Scheinbar", "einfache", "Fragen", "sind", "oft", "am", "schwierigsten", "leichtesten", "die"],
                translation: "Seemingly simple questions are often the hardest.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "The difference is subtle but crucial.",
                answer: "Der Unterschied ist subtil, aber entscheidend",
                bank: ["Der", "Unterschied", "ist", "subtil,", "aber", "entscheidend", "klein", "die"],
                speak: "Der Unterschied ist subtil, aber entscheidend",
              },
              {
                type: "select",
                prompt: "What does “ohnehin” mean?",
                question: "ohnehin",
                speak: "ohnehin",
                options: ["anyway", "rarely", "suddenly"],
                answer: 0,
              },
            ],
          },
        ],
      },
      // ---------------------------------------------------------------
      // UNIT 13 — Debate & literature
      // ---------------------------------------------------------------
      {
        id: "de-u13",
        title: "Debate & literature",
        subtitle: "Argue, persuade and read literature",
        cefr: "C1",
        color: "#370617",
        icon: "📚",
        lessons: [
          {
            id: "de-u13-l1",
            title: "Lesson 1",
            exercises: [
              {
                type: "match",
                prompt: "Match the debate phrases",
                pairs: [
                  { target: "entgegenhalten", source: "to counter (an argument)", speak: "entgegenhalten" },
                  { target: "untermauern", source: "to underpin/substantiate", speak: "untermauern" },
                  { target: "einräumen", source: "to concede", speak: "einräumen" },
                  { target: "in Frage stellen", source: "to call into question", speak: "in Frage stellen" },
                  { target: "auf den Punkt bringen", source: "to sum up succinctly", speak: "auf den Punkt bringen" },
                ],
              },
              {
                type: "select",
                prompt: "Choose the most persuasive phrasing",
                question: "I must concede that this argument has merit.",
                options: [
                  "Ich muss einräumen, dass dieses Argument berechtigt ist.",
                  "Ich muss einräumen, dass dieses Argument ist berechtigt.",
                  "Ich muss einräumen, dieses Argument dass berechtigt ist.",
                ],
                answer: 0,
                speak: "Ich muss einräumen, dass dieses Argument berechtigt ist.",
              },
              {
                type: "fill",
                prompt: "Fill in the verb",
                before: "Lassen Sie mich diesen Einwand mit Zahlen",
                after: ".",
                answer: "untermauern",
                options: ["untermauern", "untermauert", "untermauere"],
                translation: "Let me substantiate this objection with figures.",
                speak: "Lassen Sie mich diesen Einwand mit Zahlen untermauern.",
              },
              {
                type: "wordbank",
                prompt: "Translate this debate sentence",
                given: "I would like to counter that with a different perspective.",
                answer: "Dem möchte ich eine andere Perspektive entgegenhalten",
                bank: ["Dem", "möchte", "ich", "eine", "andere", "Perspektive", "entgegenhalten", "Meinung", "den"],
                speak: "Dem möchte ich eine andere Perspektive entgegenhalten",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Damit haben Sie das Problem auf den Punkt gebracht",
                translation: "With that you have summed the problem up perfectly.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Diese Behauptung lässt sich kaum aufrechterhalten",
                answer: "Diese Behauptung lässt sich kaum aufrechterhalten",
                bank: ["Diese", "Behauptung", "lässt", "sich", "kaum", "aufrechterhalten", "leicht", "die"],
                translation: "This claim can hardly be maintained.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "We should fundamentally call this assumption into question.",
                answer: "Wir sollten diese Annahme grundsätzlich in Frage stellen",
                bank: ["Wir", "sollten", "diese", "Annahme", "grundsätzlich", "in", "Frage", "stellen", "der"],
                speak: "Wir sollten diese Annahme grundsätzlich in Frage stellen",
              },
              {
                type: "select",
                prompt: "What does “einräumen” mean here?",
                question: "ein Argument einräumen",
                speak: "ein Argument einräumen",
                options: ["to concede a point", "to dismiss a point", "to invent a point"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u13-l2",
            title: "Lesson 2",
            exercises: [
              {
                type: "match",
                prompt: "Match the literary terms",
                pairs: [
                  { target: "die Handlung", source: "the plot", speak: "die Handlung" },
                  { target: "die Figur", source: "the character", speak: "die Figur" },
                  { target: "die Metapher", source: "the metaphor", speak: "die Metapher" },
                  { target: "der Erzähler", source: "the narrator", speak: "der Erzähler" },
                  { target: "die Stimmung", source: "the mood/atmosphere", speak: "die Stimmung" },
                ],
              },
              {
                type: "fill",
                prompt: "Fill in the Genitiv",
                before: "Die Sprache",
                after: "Romans ist außergewöhnlich poetisch.",
                answer: "des",
                options: ["des", "der", "dem"],
                translation: "The language of the novel is exceptionally poetic.",
                speak: "Die Sprache des Romans ist außergewöhnlich poetisch.",
              },
              {
                type: "select",
                prompt: "Choose the literary phrasing",
                question: "The narrator describes the scene with great subtlety.",
                options: [
                  "Der Erzähler schildert die Szene mit großer Feinheit.",
                  "Der Erzähler schildert die Szene mit großer Feinheit schildert.",
                  "Der Erzähler die Szene schildert mit großer Feinheit.",
                ],
                answer: 0,
                speak: "Der Erzähler schildert die Szene mit großer Feinheit.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "The metaphor lends the text a melancholy mood.",
                answer: "Die Metapher verleiht dem Text eine melancholische Stimmung",
                bank: ["Die", "Metapher", "verleiht", "dem", "Text", "eine", "melancholische", "Stimmung", "den"],
                speak: "Die Metapher verleiht dem Text eine melancholische Stimmung",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Der Autor spielt meisterhaft mit Andeutungen und Symbolen",
                translation: "The author plays masterfully with hints and symbols.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Die Hauptfigur verkörpert den Zwiespalt ihrer Zeit",
                answer: "Die Hauptfigur verkörpert den Zwiespalt ihrer Zeit",
                bank: ["Die", "Hauptfigur", "verkörpert", "den", "Zwiespalt", "ihrer", "Zeit", "seiner", "die"],
                translation: "The protagonist embodies the conflict of her time.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "Despite its brevity the poem is deeply moving.",
                answer: "Trotz seiner Kürze ist das Gedicht zutiefst bewegend",
                bank: ["Trotz", "seiner", "Kürze", "ist", "das", "Gedicht", "zutiefst", "bewegend", "wegen"],
                speak: "Trotz seiner Kürze ist das Gedicht zutiefst bewegend",
              },
              {
                type: "select",
                prompt: "What does “die Handlung” mean in literature?",
                question: "die Handlung",
                speak: "die Handlung",
                options: ["the plot", "the cover", "the author"],
                answer: 0,
              },
            ],
          },
          {
            id: "de-u13-l3",
            title: "Lesson 3",
            exercises: [
              {
                type: "match",
                prompt: "Match the rhetorical phrases",
                pairs: [
                  { target: "letzten Endes", source: "in the final analysis", speak: "letzten Endes" },
                  { target: "im Großen und Ganzen", source: "by and large", speak: "im Großen und Ganzen" },
                  { target: "vor diesem Hintergrund", source: "against this backdrop", speak: "vor diesem Hintergrund" },
                  { target: "es liegt auf der Hand", source: "it is obvious", speak: "es liegt auf der Hand" },
                  { target: "mit Verlaub", source: "with respect", speak: "mit Verlaub" },
                ],
              },
              {
                type: "fill",
                prompt: "Fill in the rhetorical connector",
                before: "Vor diesem",
                after: "erscheint die Kritik berechtigt.",
                answer: "Hintergrund",
                options: ["Hintergrund", "Vordergrund", "Anfang"],
                translation: "Against this backdrop the criticism seems justified.",
                speak: "Vor diesem Hintergrund erscheint die Kritik berechtigt.",
              },
              {
                type: "select",
                prompt: "Choose the most eloquent conclusion",
                question: "In the final analysis it remains a matter of conviction.",
                options: [
                  "Letzten Endes bleibt es eine Frage der Überzeugung.",
                  "Letzten Endes es bleibt eine Frage der Überzeugung.",
                  "Letzten Endes bleibt es eine Frage die Überzeugung.",
                ],
                answer: 0,
                speak: "Letzten Endes bleibt es eine Frage der Überzeugung.",
              },
              {
                type: "wordbank",
                prompt: "Translate this rhetorical sentence",
                given: "By and large I share this assessment.",
                answer: "Im Großen und Ganzen teile ich diese Einschätzung",
                bank: ["Im", "Großen", "und", "Ganzen", "teile", "ich", "diese", "Einschätzung", "der"],
                speak: "Im Großen und Ganzen teile ich diese Einschätzung",
              },
              {
                type: "speak",
                prompt: "Say it out loud",
                text: "Mit Verlaub, das halte ich für einen Trugschluss",
                translation: "With respect, I consider that a fallacy.",
              },
              {
                type: "listen",
                prompt: "Tap what you hear",
                speak: "Es liegt auf der Hand, dass eine Lösung dringend nötig ist",
                answer: "Es liegt auf der Hand, dass eine Lösung dringend nötig ist",
                bank: ["Es", "liegt", "auf", "der", "Hand,", "dass", "eine", "Lösung", "dringend", "nötig", "ist", "kaum"],
                translation: "It is obvious that a solution is urgently needed.",
              },
              {
                type: "wordbank",
                prompt: "Translate this sentence",
                given: "Whoever wants to convince must first listen.",
                answer: "Wer überzeugen will, muss zuerst zuhören",
                bank: ["Wer", "überzeugen", "will,", "muss", "zuerst", "zuhören", "reden", "der"],
                speak: "Wer überzeugen will, muss zuerst zuhören",
              },
              {
                type: "select",
                prompt: "What does “es liegt auf der Hand” mean?",
                question: "es liegt auf der Hand",
                speak: "es liegt auf der Hand",
                options: ["it is obvious", "it is forbidden", "it is impossible"],
                answer: 0,
              },
            ],
          },
        ],
      },
    ],
  },
];
