import type { Course } from "@/curriculum/types";

// Spanish course content. Hand-authored, beginner-friendly (A1).
// Vocabulary is introduced per unit and reused across that unit's lessons.

export const spanishCourse: Course = {
  code: "es",
  name: "Spanish",
  endonym: "Español",
  flag: "🇪🇸",
  fromLanguage: "English",
  speechLocale: "es-ES",
  sections: [
    {
      id: "es-s1",
      title: "Rookie",
      subtitle: "First words & phrases",
      units: [
        // ---------------------------------------------------------------
        // UNIT 1 — Greetings & basics
        // ---------------------------------------------------------------
        {
          id: "es-u1",
          title: "Greetings",
          subtitle: "Say hello and introduce yourself",
          cefr: "A1",
          color: "#58CC02",
          icon: "👋",
          lessons: [
            {
              id: "es-u1-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the greetings",
                  pairs: [
                    { target: "hola", source: "hello", speak: "hola" },
                    { target: "adiós", source: "goodbye", speak: "adiós" },
                    { target: "sí", source: "yes", speak: "sí" },
                    { target: "no", source: "no", speak: "no" },
                    { target: "gracias", source: "thanks", speak: "gracias" },
                  ],
                },
                {
                  type: "select",
                  prompt: "How do you say “hello”?",
                  question: "hello",
                  options: ["hola", "adiós", "gracias"],
                  answer: 0,
                  speak: "hola",
                },
                {
                  type: "select",
                  prompt: "What does “adiós” mean?",
                  question: "adiós",
                  speak: "adiós",
                  options: ["hello", "goodbye", "please"],
                  answer: 1,
                },
                {
                  type: "fill",
                  prompt: "Complete the greeting",
                  before: "Buenos",
                  after: ".",
                  answer: "días",
                  options: ["días", "noches", "hola"],
                  translation: "Good morning.",
                  speak: "Buenos días.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "Good night.",
                  answer: "Buenas noches.",
                  bank: ["Buenas", "noches.", "días.", "hola"],
                  speak: "Buenas noches.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Hola, gracias.",
                  answer: "Hola, gracias.",
                  bank: ["Hola,", "gracias.", "adiós", "por"],
                  translation: "Hello, thanks.",
                },
              ],
            },
            {
              id: "es-u1-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "yo", source: "I", speak: "yo" },
                    { target: "tú", source: "you", speak: "tú" },
                    { target: "soy", source: "am", speak: "soy" },
                    { target: "eres", source: "are (you)", speak: "eres" },
                  ],
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I am Ana.",
                  options: ["Yo soy Ana.", "Yo eres Ana.", "Tú soy Ana."],
                  answer: 0,
                  speak: "Yo soy Ana.",
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "Yo",
                  after: "Juan.",
                  answer: "soy",
                  options: ["soy", "eres", "es"],
                  translation: "I am Juan.",
                  speak: "Yo soy Juan.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I am María.",
                  answer: "Yo soy María.",
                  bank: ["Yo", "soy", "María.", "eres", "tú"],
                  speak: "Yo soy María.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct verb",
                  question: "Tú ___ Pablo.",
                  options: ["eres", "soy", "es"],
                  answer: 0,
                  speak: "Tú eres Pablo.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Yo soy Ana.",
                  answer: "Yo soy Ana.",
                  bank: ["Yo", "soy", "Ana.", "tú", "eres"],
                  translation: "I am Ana.",
                },
              ],
            },
            {
              id: "es-u1-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the phrases",
                  pairs: [
                    { target: "¿Cómo estás?", source: "How are you?", speak: "¿Cómo estás?" },
                    { target: "bien", source: "well", speak: "bien" },
                    { target: "y", source: "and", speak: "y" },
                    { target: "me llamo", source: "my name is", speak: "me llamo" },
                  ],
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "My name is Juan.",
                  answer: "Me llamo Juan.",
                  bank: ["Me", "llamo", "Juan.", "soy", "yo"],
                  speak: "Me llamo Juan.",
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "¿Cómo",
                  after: "?",
                  answer: "estás",
                  options: ["estás", "eres", "soy"],
                  translation: "How are you?",
                  speak: "¿Cómo estás?",
                },
                {
                  type: "select",
                  prompt: "Choose the best reply",
                  question: "¿Cómo estás?",
                  speak: "¿Cómo estás?",
                  options: ["Bien, gracias.", "Buenos días.", "Adiós."],
                  answer: 0,
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "Well, and you?",
                  answer: "Bien, ¿y tú?",
                  bank: ["Bien,", "¿y", "tú?", "yo", "soy"],
                  speak: "Bien, ¿y tú?",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Me llamo María.",
                  answer: "Me llamo María.",
                  bank: ["Me", "llamo", "María.", "soy", "Juan."],
                  translation: "My name is María.",
                },
              ],
            },
          ],
        },
        // ---------------------------------------------------------------
        // UNIT 2 — Food & people
        // ---------------------------------------------------------------
        {
          id: "es-u2",
          title: "Food & people",
          subtitle: "Food, drinks and family",
          cefr: "A1",
          color: "#FF9600",
          icon: "🍎",
          lessons: [
            {
              id: "es-u2-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the food words",
                  pairs: [
                    { target: "el pan", source: "the bread", speak: "el pan" },
                    { target: "la manzana", source: "the apple", speak: "la manzana" },
                    { target: "el agua", source: "the water", speak: "el agua" },
                    { target: "el café", source: "the coffee", speak: "el café" },
                    { target: "la leche", source: "the milk", speak: "la leche" },
                  ],
                },
                {
                  type: "select",
                  prompt: "Which article fits?",
                  question: "___ manzana",
                  options: ["la", "el", "los"],
                  answer: 0,
                  speak: "la manzana",
                },
                {
                  type: "select",
                  prompt: "What does “el agua” mean?",
                  question: "el agua",
                  speak: "el agua",
                  options: ["the water", "the milk", "the bread"],
                  answer: 0,
                },
                {
                  type: "fill",
                  prompt: "Fill in the article",
                  before: "Bebo",
                  after: "leche.",
                  answer: "la",
                  options: ["la", "el", "los"],
                  translation: "I drink the milk.",
                  speak: "Bebo la leche.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "The bread is good.",
                  answer: "El pan es bueno.",
                  bank: ["El", "pan", "es", "bueno.", "la", "manzana"],
                  speak: "El pan es bueno.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "El café está caliente.",
                  answer: "El café está caliente.",
                  bank: ["El", "café", "está", "caliente.", "el", "agua"],
                  translation: "The coffee is hot.",
                },
              ],
            },
            {
              id: "es-u2-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the verbs",
                  pairs: [
                    { target: "comer", source: "to eat", speak: "comer" },
                    { target: "como", source: "I eat", speak: "como" },
                    { target: "comes", source: "you eat", speak: "comes" },
                    { target: "beber", source: "to drink", speak: "beber" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "Yo",
                  after: "pan.",
                  answer: "como",
                  options: ["como", "comes", "bebo"],
                  translation: "I eat bread.",
                  speak: "Yo como pan.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct verb",
                  question: "Tú ___ una manzana.",
                  options: ["comes", "como", "bebes"],
                  answer: 0,
                  speak: "Tú comes una manzana.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I drink water.",
                  answer: "Yo bebo agua.",
                  bank: ["Yo", "bebo", "agua.", "como", "pan"],
                  speak: "Yo bebo agua.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I eat an apple.",
                  options: ["Yo como una manzana.", "Yo comes una manzana.", "Yo bebo una manzana."],
                  answer: 0,
                  speak: "Yo como una manzana.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Yo como pan.",
                  answer: "Yo como pan.",
                  bank: ["Yo", "como", "pan.", "bebo", "agua"],
                  translation: "I eat bread.",
                },
              ],
            },
            {
              id: "es-u2-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the family words",
                  pairs: [
                    { target: "la madre", source: "the mother", speak: "la madre" },
                    { target: "el padre", source: "the father", speak: "el padre" },
                    { target: "el hermano", source: "the brother", speak: "el hermano" },
                    { target: "la familia", source: "the family", speak: "la familia" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "Esta es mi",
                  after: ".",
                  answer: "madre",
                  options: ["madre", "padre", "hermano"],
                  translation: "This is my mother.",
                  speak: "Esta es mi madre.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "My family is big.",
                  answer: "Mi familia es grande.",
                  bank: ["Mi", "familia", "es", "grande.", "madre", "pequeña"],
                  speak: "Mi familia es grande.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "This is my father.",
                  options: ["Este es mi padre.", "Esta es mi padre.", "Este es mi madre."],
                  answer: 0,
                  speak: "Este es mi padre.",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I have a brother.",
                  answer: "Tengo un hermano.",
                  bank: ["Tengo", "un", "hermano.", "una", "madre"],
                  speak: "Tengo un hermano.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "Esta es mi familia.",
                  answer: "Esta es mi familia.",
                  bank: ["Esta", "es", "mi", "familia.", "madre.", "padre."],
                  translation: "This is my family.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
