import type { Course } from "@/curriculum/types";

// Mandarin Chinese course content. Hand-authored, beginner-friendly (A1–A2).
// Simplified characters with toned pinyin throughout so learners always see
// pronunciation. Vocabulary is introduced per unit and reused across lessons.

export const chineseCourse: Course = {
  code: "zh",
  name: "Chinese",
  endonym: "中文",
  flag: "🇨🇳",
  fromLanguage: "English",
  speechLocale: "zh-CN",
  sections: [
    {
      id: "zh-s1",
      title: "Rookie",
      subtitle: "First words & phrases",
      units: [
        // ---------------------------------------------------------------
        // UNIT 1 — Greetings & basics
        // ---------------------------------------------------------------
        {
          id: "zh-u1",
          title: "Greetings",
          subtitle: "Say hello and introduce yourself",
          cefr: "A1",
          color: "#58CC02",
          icon: "👋",
          lessons: [
            {
              id: "zh-u1-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the greetings",
                  pairs: [
                    { target: "你好", source: "Hello", sub: "nǐ hǎo", speak: "你好" },
                    { target: "谢谢", source: "Thanks", sub: "xièxie", speak: "谢谢" },
                    { target: "再见", source: "Goodbye", sub: "zàijiàn", speak: "再见" },
                    { target: "是", source: "Yes / to be", sub: "shì", speak: "是" },
                    { target: "不", source: "No / not", sub: "bù", speak: "不" },
                  ],
                },
                {
                  type: "select",
                  prompt: "How do you say “Hello”?",
                  question: "Hello",
                  options: ["你好", "再见", "谢谢"],
                  optionSubs: ["nǐ hǎo", "zàijiàn", "xièxie"],
                  answer: 0,
                  speak: "你好",
                },
                {
                  type: "select",
                  prompt: "What does “谢谢” mean?",
                  question: "谢谢",
                  subtext: "xièxie",
                  speak: "谢谢",
                  options: ["Hello", "Thanks", "Goodbye"],
                  optionSubs: ["nǐ hǎo", "xièxie", "zàijiàn"],
                  answer: 1,
                },
                {
                  type: "fill",
                  prompt: "Complete the phrase",
                  before: "你",
                  after: "",
                  answer: "好",
                  options: ["好", "谢", "是"],
                  translation: "Hello",
                  pinyin: "nǐ hǎo",
                  speak: "你好",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this phrase",
                  given: "Thank you",
                  answer: "谢谢 你",
                  bank: ["谢谢", "你", "再见", "好"],
                  speak: "谢谢你",
                  pinyin: "xièxie nǐ",
                  translation: "Thank you",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "你好",
                  answer: "你 好",
                  bank: ["你", "好", "谢谢", "再见"],
                  translation: "Hello",
                  pinyin: "nǐ hǎo",
                },
              ],
            },
            {
              id: "zh-u1-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "我", source: "I / me", sub: "wǒ", speak: "我" },
                    { target: "你", source: "you", sub: "nǐ", speak: "你" },
                    { target: "是", source: "to be", sub: "shì", speak: "是" },
                    { target: "学生", source: "student", sub: "xuéshēng", speak: "学生" },
                  ],
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I am a student.",
                  options: ["我是学生", "你是学生", "我是老师"],
                  optionSubs: ["wǒ shì xuéshēng", "nǐ shì xuéshēng", "wǒ shì lǎoshī"],
                  answer: 0,
                  speak: "我是学生",
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "我",
                  after: "学生",
                  answer: "是",
                  options: ["是", "你", "好"],
                  translation: "I am a student.",
                  pinyin: "wǒ shì xuéshēng",
                  speak: "我是学生",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I am a student.",
                  answer: "我 是 学生",
                  bank: ["我", "是", "学生", "你", "老师"],
                  speak: "我是学生",
                  pinyin: "wǒ shì xuéshēng",
                  translation: "I am a student.",
                },
                {
                  type: "select",
                  prompt: "What does “你” mean?",
                  question: "你",
                  subtext: "nǐ",
                  speak: "你",
                  options: ["I / me", "you", "to be"],
                  optionSubs: ["wǒ", "nǐ", "shì"],
                  answer: 1,
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "你是学生",
                  answer: "你 是 学生",
                  bank: ["你", "是", "学生", "我", "老师"],
                  translation: "You are a student.",
                  pinyin: "nǐ shì xuéshēng",
                },
              ],
            },
            {
              id: "zh-u1-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "老师", source: "teacher", sub: "lǎoshī", speak: "老师" },
                    { target: "好", source: "good", sub: "hǎo", speak: "好" },
                    { target: "吗", source: "(question)", sub: "ma", speak: "吗" },
                    { target: "很", source: "very", sub: "hěn", speak: "很" },
                  ],
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "Are you well?",
                  answer: "你 好 吗",
                  bank: ["你", "好", "吗", "我", "是"],
                  speak: "你好吗",
                  pinyin: "nǐ hǎo ma",
                  translation: "Are you well?",
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "我",
                  after: "好",
                  answer: "很",
                  options: ["很", "吗", "你"],
                  translation: "I am very well.",
                  pinyin: "wǒ hěn hǎo",
                  speak: "我很好",
                },
                {
                  type: "select",
                  prompt: "Choose the best reply",
                  question: "你好吗？",
                  subtext: "nǐ hǎo ma",
                  speak: "你好吗",
                  options: ["我很好", "再见", "谢谢你"],
                  optionSubs: ["wǒ hěn hǎo", "zàijiàn", "xièxie nǐ"],
                  answer: 0,
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I am a teacher.",
                  answer: "我 是 老师",
                  bank: ["我", "是", "老师", "学生", "你"],
                  speak: "我是老师",
                  pinyin: "wǒ shì lǎoshī",
                  translation: "I am a teacher.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "我很好",
                  answer: "我 很 好",
                  bank: ["我", "很", "好", "你", "吗"],
                  translation: "I am very well.",
                  pinyin: "wǒ hěn hǎo",
                },
              ],
            },
          ],
        },
        // ---------------------------------------------------------------
        // UNIT 2 — Numbers & family
        // ---------------------------------------------------------------
        {
          id: "zh-u2",
          title: "Numbers & family",
          subtitle: "Count and talk about family",
          cefr: "A1",
          color: "#1CB0F6",
          icon: "👨‍👩‍👧",
          lessons: [
            {
              id: "zh-u2-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the numbers",
                  pairs: [
                    { target: "一", source: "one", sub: "yī", speak: "一" },
                    { target: "二", source: "two", sub: "èr", speak: "二" },
                    { target: "三", source: "three", sub: "sān", speak: "三" },
                    { target: "四", source: "four", sub: "sì", speak: "四" },
                    { target: "五", source: "five", sub: "wǔ", speak: "五" },
                  ],
                },
                {
                  type: "select",
                  prompt: "How do you say “three”?",
                  question: "three",
                  options: ["二", "三", "五"],
                  optionSubs: ["èr", "sān", "wǔ"],
                  answer: 1,
                  speak: "三",
                },
                {
                  type: "select",
                  prompt: "What does “五” mean?",
                  question: "五",
                  subtext: "wǔ",
                  speak: "五",
                  options: ["four", "five", "two"],
                  optionSubs: ["sì", "wǔ", "èr"],
                  answer: 1,
                },
                {
                  type: "fill",
                  prompt: "Fill in the number",
                  before: "一 二",
                  after: "",
                  answer: "三",
                  options: ["三", "五", "四"],
                  translation: "one two three",
                  pinyin: "yī èr sān",
                  speak: "一二三",
                },
                {
                  type: "wordbank",
                  prompt: "Put the numbers in order",
                  given: "one two three",
                  answer: "一 二 三",
                  bank: ["一", "二", "三", "四", "五"],
                  speak: "一二三",
                  pinyin: "yī èr sān",
                  translation: "one two three",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "四 五",
                  answer: "四 五",
                  bank: ["四", "五", "三", "二"],
                  translation: "four five",
                  pinyin: "sì wǔ",
                },
              ],
            },
            {
              id: "zh-u2-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the family words",
                  pairs: [
                    { target: "妈妈", source: "mom", sub: "māma", speak: "妈妈" },
                    { target: "爸爸", source: "dad", sub: "bàba", speak: "爸爸" },
                    { target: "哥哥", source: "older brother", sub: "gēge", speak: "哥哥" },
                    { target: "妹妹", source: "younger sister", sub: "mèimei", speak: "妹妹" },
                  ],
                },
                {
                  type: "select",
                  prompt: "How do you say “mom”?",
                  question: "mom",
                  options: ["妈妈", "爸爸", "哥哥"],
                  optionSubs: ["māma", "bàba", "gēge"],
                  answer: 0,
                  speak: "妈妈",
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "这是我",
                  after: "",
                  answer: "妈妈",
                  options: ["妈妈", "爸爸", "学生"],
                  translation: "This is my mom.",
                  pinyin: "zhè shì wǒ māma",
                  speak: "这是我妈妈",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "This is my dad.",
                  answer: "这 是 我 爸爸",
                  bank: ["这", "是", "我", "爸爸", "妈妈"],
                  speak: "这是我爸爸",
                  pinyin: "zhè shì wǒ bàba",
                  translation: "This is my dad.",
                },
                {
                  type: "select",
                  prompt: "What does “妹妹” mean?",
                  question: "妹妹",
                  subtext: "mèimei",
                  speak: "妹妹",
                  options: ["older brother", "younger sister", "mom"],
                  optionSubs: ["gēge", "mèimei", "māma"],
                  answer: 1,
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "这是我妈妈",
                  answer: "这 是 我 妈妈",
                  bank: ["这", "是", "我", "妈妈", "爸爸"],
                  translation: "This is my mom.",
                  pinyin: "zhè shì wǒ māma",
                },
              ],
            },
            {
              id: "zh-u2-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "有", source: "to have", sub: "yǒu", speak: "有" },
                    { target: "个", source: "(measure word)", sub: "gè", speak: "个" },
                    { target: "家", source: "home / family", sub: "jiā", speak: "家" },
                    { target: "和", source: "and", sub: "hé", speak: "和" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "我",
                  after: "一个哥哥",
                  answer: "有",
                  options: ["有", "是", "和"],
                  translation: "I have an older brother.",
                  pinyin: "wǒ yǒu yí gè gēge",
                  speak: "我有一个哥哥",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I have a younger sister.",
                  answer: "我 有 一 个 妹妹",
                  bank: ["我", "有", "一", "个", "妹妹", "哥哥"],
                  speak: "我有一个妹妹",
                  pinyin: "wǒ yǒu yí gè mèimei",
                  translation: "I have a younger sister.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "Mom and dad",
                  options: ["妈妈和爸爸", "妈妈是爸爸", "妈妈有爸爸"],
                  optionSubs: ["māma hé bàba", "māma shì bàba", "māma yǒu bàba"],
                  answer: 0,
                  speak: "妈妈和爸爸",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "Mom and dad",
                  answer: "妈妈 和 爸爸",
                  bank: ["妈妈", "和", "爸爸", "有", "家"],
                  speak: "妈妈和爸爸",
                  pinyin: "māma hé bàba",
                  translation: "Mom and dad",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "我有一个哥哥",
                  answer: "我 有 一 个 哥哥",
                  bank: ["我", "有", "一", "个", "哥哥", "妹妹"],
                  translation: "I have an older brother.",
                  pinyin: "wǒ yǒu yí gè gēge",
                },
              ],
            },
          ],
        },
        // ---------------------------------------------------------------
        // UNIT 3 — Food & drink
        // ---------------------------------------------------------------
        {
          id: "zh-u3",
          title: "Food",
          subtitle: "Talk about food and drinks",
          cefr: "A1",
          color: "#FF9600",
          icon: "🍜",
          lessons: [
            {
              id: "zh-u3-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the food words",
                  pairs: [
                    { target: "茶", source: "tea", sub: "chá", speak: "茶" },
                    { target: "水", source: "water", sub: "shuǐ", speak: "水" },
                    { target: "米饭", source: "rice", sub: "mǐfàn", speak: "米饭" },
                    { target: "面", source: "noodles", sub: "miàn", speak: "面" },
                    { target: "苹果", source: "apple", sub: "píngguǒ", speak: "苹果" },
                  ],
                },
                {
                  type: "select",
                  prompt: "How do you say “tea”?",
                  question: "tea",
                  options: ["茶", "水", "米饭"],
                  optionSubs: ["chá", "shuǐ", "mǐfàn"],
                  answer: 0,
                  speak: "茶",
                },
                {
                  type: "select",
                  prompt: "What does “水” mean?",
                  question: "水",
                  subtext: "shuǐ",
                  speak: "水",
                  options: ["tea", "water", "rice"],
                  optionSubs: ["chá", "shuǐ", "mǐfàn"],
                  answer: 1,
                },
                {
                  type: "fill",
                  prompt: "Fill in the word",
                  before: "我喝",
                  after: "",
                  answer: "茶",
                  options: ["茶", "米饭", "苹果"],
                  translation: "I drink tea.",
                  pinyin: "wǒ hē chá",
                  speak: "我喝茶",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I drink water.",
                  answer: "我 喝 水",
                  bank: ["我", "喝", "水", "茶", "吃"],
                  speak: "我喝水",
                  pinyin: "wǒ hē shuǐ",
                  translation: "I drink water.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "我喝茶",
                  answer: "我 喝 茶",
                  bank: ["我", "喝", "茶", "水", "吃"],
                  translation: "I drink tea.",
                  pinyin: "wǒ hē chá",
                },
              ],
            },
            {
              id: "zh-u3-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the verbs",
                  pairs: [
                    { target: "吃", source: "to eat", sub: "chī", speak: "吃" },
                    { target: "喝", source: "to drink", sub: "hē", speak: "喝" },
                    { target: "喜欢", source: "to like", sub: "xǐhuān", speak: "喜欢" },
                    { target: "想", source: "to want", sub: "xiǎng", speak: "想" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "我",
                  after: "米饭",
                  answer: "吃",
                  options: ["吃", "喝", "喜欢"],
                  translation: "I eat rice.",
                  pinyin: "wǒ chī mǐfàn",
                  speak: "我吃米饭",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I like tea.",
                  options: ["我喜欢茶", "我吃茶", "我是茶"],
                  optionSubs: ["wǒ xǐhuān chá", "wǒ chī chá", "wǒ shì chá"],
                  answer: 0,
                  speak: "我喜欢茶",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I eat noodles.",
                  answer: "我 吃 面",
                  bank: ["我", "吃", "面", "喝", "水"],
                  speak: "我吃面",
                  pinyin: "wǒ chī miàn",
                  translation: "I eat noodles.",
                },
                {
                  type: "select",
                  prompt: "What does “喜欢” mean?",
                  question: "喜欢",
                  subtext: "xǐhuān",
                  speak: "喜欢",
                  options: ["to eat", "to like", "to drink"],
                  optionSubs: ["chī", "xǐhuān", "hē"],
                  answer: 1,
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "我喜欢茶",
                  answer: "我 喜欢 茶",
                  bank: ["我", "喜欢", "茶", "吃", "面"],
                  translation: "I like tea.",
                  pinyin: "wǒ xǐhuān chá",
                },
              ],
            },
            {
              id: "zh-u3-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "好吃", source: "tasty (food)", sub: "hǎochī", speak: "好吃" },
                    { target: "也", source: "also", sub: "yě", speak: "也" },
                    { target: "不", source: "not", sub: "bù", speak: "不" },
                    { target: "什么", source: "what", sub: "shénme", speak: "什么" },
                  ],
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I want to eat rice.",
                  answer: "我 想 吃 米饭",
                  bank: ["我", "想", "吃", "米饭", "喝", "茶"],
                  speak: "我想吃米饭",
                  pinyin: "wǒ xiǎng chī mǐfàn",
                  translation: "I want to eat rice.",
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "我",
                  after: "喜欢茶",
                  answer: "不",
                  options: ["不", "也", "很"],
                  translation: "I don't like tea.",
                  pinyin: "wǒ bù xǐhuān chá",
                  speak: "我不喜欢茶",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "The noodles are tasty.",
                  options: ["面很好吃", "面是好吃", "面喝好吃"],
                  optionSubs: ["miàn hěn hǎochī", "miàn shì hǎochī", "miàn hē hǎochī"],
                  answer: 0,
                  speak: "面很好吃",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I also like rice.",
                  answer: "我 也 喜欢 米饭",
                  bank: ["我", "也", "喜欢", "米饭", "不", "茶"],
                  speak: "我也喜欢米饭",
                  pinyin: "wǒ yě xǐhuān mǐfàn",
                  translation: "I also like rice.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "我想吃面",
                  answer: "我 想 吃 面",
                  bank: ["我", "想", "吃", "面", "喝", "水"],
                  translation: "I want to eat noodles.",
                  pinyin: "wǒ xiǎng chī miàn",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "zh-s2",
      title: "Explorer",
      subtitle: "Everyday situations",
      units: [
        // ---------------------------------------------------------------
        // UNIT 4 — Around town
        // ---------------------------------------------------------------
        {
          id: "zh-u4",
          title: "Town",
          subtitle: "Find your way around town",
          cefr: "A2",
          color: "#CE82FF",
          icon: "🏙️",
          lessons: [
            {
              id: "zh-u4-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the places",
                  pairs: [
                    { target: "学校", source: "school", sub: "xuéxiào", speak: "学校" },
                    { target: "商店", source: "shop", sub: "shāngdiàn", speak: "商店" },
                    { target: "饭馆", source: "restaurant", sub: "fànguǎn", speak: "饭馆" },
                    { target: "医院", source: "hospital", sub: "yīyuàn", speak: "医院" },
                    { target: "这里", source: "here", sub: "zhèlǐ", speak: "这里" },
                  ],
                },
                {
                  type: "select",
                  prompt: "How do you say “school”?",
                  question: "school",
                  options: ["学校", "商店", "医院"],
                  optionSubs: ["xuéxiào", "shāngdiàn", "yīyuàn"],
                  answer: 0,
                  speak: "学校",
                },
                {
                  type: "select",
                  prompt: "What does “饭馆” mean?",
                  question: "饭馆",
                  subtext: "fànguǎn",
                  speak: "饭馆",
                  options: ["shop", "restaurant", "school"],
                  optionSubs: ["shāngdiàn", "fànguǎn", "xuéxiào"],
                  answer: 1,
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "学校在",
                  after: "",
                  answer: "这里",
                  options: ["这里", "商店", "医院"],
                  translation: "The school is here.",
                  pinyin: "xuéxiào zài zhèlǐ",
                  speak: "学校在这里",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this question",
                  given: "Where is the shop?",
                  answer: "商店 在 哪里",
                  bank: ["商店", "在", "哪里", "学校", "这里"],
                  speak: "商店在哪里",
                  pinyin: "shāngdiàn zài nǎlǐ",
                  translation: "Where is the shop?",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "学校在这里",
                  answer: "学校 在 这里",
                  bank: ["学校", "在", "这里", "商店", "哪里"],
                  translation: "The school is here.",
                  pinyin: "xuéxiào zài zhèlǐ",
                },
              ],
            },
            {
              id: "zh-u4-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "在", source: "at / to be at", sub: "zài", speak: "在" },
                    { target: "哪里", source: "where", sub: "nǎlǐ", speak: "哪里" },
                    { target: "去", source: "to go", sub: "qù", speak: "去" },
                    { target: "远", source: "far", sub: "yuǎn", speak: "远" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "我",
                  after: "学校",
                  answer: "去",
                  options: ["去", "在", "远"],
                  translation: "I go to school.",
                  pinyin: "wǒ qù xuéxiào",
                  speak: "我去学校",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I go to the shop.",
                  answer: "我 去 商店",
                  bank: ["我", "去", "商店", "在", "学校"],
                  speak: "我去商店",
                  pinyin: "wǒ qù shāngdiàn",
                  translation: "I go to the shop.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "The hospital is far.",
                  options: ["医院很远", "医院去远", "医院在远"],
                  optionSubs: ["yīyuàn hěn yuǎn", "yīyuàn qù yuǎn", "yīyuàn zài yuǎn"],
                  answer: 0,
                  speak: "医院很远",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this question",
                  given: "Where do you go?",
                  answer: "你 去 哪里",
                  bank: ["你", "去", "哪里", "在", "我"],
                  speak: "你去哪里",
                  pinyin: "nǐ qù nǎlǐ",
                  translation: "Where do you go?",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "我去学校",
                  answer: "我 去 学校",
                  bank: ["我", "去", "学校", "商店", "在"],
                  translation: "I go to school.",
                  pinyin: "wǒ qù xuéxiào",
                },
              ],
            },
            {
              id: "zh-u4-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "买", source: "to buy", sub: "mǎi", speak: "买" },
                    { target: "钱", source: "money", sub: "qián", speak: "钱" },
                    { target: "多少", source: "how much", sub: "duōshǎo", speak: "多少" },
                    { target: "块", source: "(unit of money)", sub: "kuài", speak: "块" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "我想",
                  after: "苹果",
                  answer: "买",
                  options: ["买", "去", "钱"],
                  translation: "I want to buy apples.",
                  pinyin: "wǒ xiǎng mǎi píngguǒ",
                  speak: "我想买苹果",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this question",
                  given: "How much money?",
                  answer: "多少 钱",
                  bank: ["多少", "钱", "买", "块", "去"],
                  speak: "多少钱",
                  pinyin: "duōshǎo qián",
                  translation: "How much money?",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I buy tea.",
                  options: ["我买茶", "我去茶", "我钱茶"],
                  optionSubs: ["wǒ mǎi chá", "wǒ qù chá", "wǒ qián chá"],
                  answer: 0,
                  speak: "我买茶",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I want to buy water.",
                  answer: "我 想 买 水",
                  bank: ["我", "想", "买", "水", "茶", "钱"],
                  speak: "我想买水",
                  pinyin: "wǒ xiǎng mǎi shuǐ",
                  translation: "I want to buy water.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "多少钱",
                  answer: "多少 钱",
                  bank: ["多少", "钱", "买", "块"],
                  translation: "How much money?",
                  pinyin: "duōshǎo qián",
                },
              ],
            },
          ],
        },
        // ---------------------------------------------------------------
        // UNIT 5 — Daily life
        // ---------------------------------------------------------------
        {
          id: "zh-u5",
          title: "Daily life",
          subtitle: "Describe your daily routine",
          cefr: "A2",
          color: "#FF4B4B",
          icon: "⏰",
          lessons: [
            {
              id: "zh-u5-l1",
              title: "Lesson 1",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the verbs",
                  pairs: [
                    { target: "工作", source: "to work", sub: "gōngzuò", speak: "工作" },
                    { target: "看", source: "to look / watch", sub: "kàn", speak: "看" },
                    { target: "读", source: "to read", sub: "dú", speak: "读" },
                    { target: "睡觉", source: "to sleep", sub: "shuìjiào", speak: "睡觉" },
                    { target: "说", source: "to speak", sub: "shuō", speak: "说" },
                  ],
                },
                {
                  type: "select",
                  prompt: "What does “工作” mean?",
                  question: "工作",
                  subtext: "gōngzuò",
                  speak: "工作",
                  options: ["to work", "to read", "to sleep"],
                  optionSubs: ["gōngzuò", "dú", "shuìjiào"],
                  answer: 0,
                },
                {
                  type: "fill",
                  prompt: "Fill in the verb",
                  before: "我",
                  after: "书",
                  answer: "看",
                  options: ["看", "睡觉", "工作"],
                  translation: "I read a book.",
                  pinyin: "wǒ kàn shū",
                  speak: "我看书",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I speak Chinese.",
                  answer: "我 说 中文",
                  bank: ["我", "说", "中文", "看", "书"],
                  speak: "我说中文",
                  pinyin: "wǒ shuō zhōngwén",
                  translation: "I speak Chinese.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I work.",
                  options: ["我工作", "我睡觉", "我看书"],
                  optionSubs: ["wǒ gōngzuò", "wǒ shuìjiào", "wǒ kàn shū"],
                  answer: 0,
                  speak: "我工作",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "我看书",
                  answer: "我 看 书",
                  bank: ["我", "看", "书", "说", "中文"],
                  translation: "I read a book.",
                  pinyin: "wǒ kàn shū",
                },
              ],
            },
            {
              id: "zh-u5-l2",
              title: "Lesson 2",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the time words",
                  pairs: [
                    { target: "今天", source: "today", sub: "jīntiān", speak: "今天" },
                    { target: "明天", source: "tomorrow", sub: "míngtiān", speak: "明天" },
                    { target: "现在", source: "now", sub: "xiànzài", speak: "现在" },
                    { target: "天", source: "day", sub: "tiān", speak: "天" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the time word",
                  before: "我",
                  after: "工作",
                  answer: "今天",
                  options: ["今天", "明天", "现在"],
                  translation: "I work today.",
                  pinyin: "wǒ jīntiān gōngzuò",
                  speak: "我今天工作",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I read now.",
                  answer: "我 现在 看 书",
                  bank: ["我", "现在", "看", "书", "今天", "工作"],
                  speak: "我现在看书",
                  pinyin: "wǒ xiànzài kàn shū",
                  translation: "I read now.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I work tomorrow.",
                  options: ["我明天工作", "我现在工作", "我今天看书"],
                  optionSubs: ["wǒ míngtiān gōngzuò", "wǒ xiànzài gōngzuò", "wǒ jīntiān kàn shū"],
                  answer: 0,
                  speak: "我明天工作",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I sleep now.",
                  answer: "我 现在 睡觉",
                  bank: ["我", "现在", "睡觉", "今天", "看"],
                  speak: "我现在睡觉",
                  pinyin: "wǒ xiànzài shuìjiào",
                  translation: "I sleep now.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "我今天工作",
                  answer: "我 今天 工作",
                  bank: ["我", "今天", "工作", "明天", "现在"],
                  translation: "I work today.",
                  pinyin: "wǒ jīntiān gōngzuò",
                },
              ],
            },
            {
              id: "zh-u5-l3",
              title: "Lesson 3",
              exercises: [
                {
                  type: "match",
                  prompt: "Match the words",
                  pairs: [
                    { target: "书", source: "book", sub: "shū", speak: "书" },
                    { target: "很", source: "very", sub: "hěn", speak: "很" },
                    { target: "累", source: "tired", sub: "lèi", speak: "累" },
                    { target: "高兴", source: "happy", sub: "gāoxìng", speak: "高兴" },
                  ],
                },
                {
                  type: "fill",
                  prompt: "Fill in the blank",
                  before: "我今天很",
                  after: "",
                  answer: "累",
                  options: ["累", "高兴", "书"],
                  translation: "I am very tired today.",
                  pinyin: "wǒ jīntiān hěn lèi",
                  speak: "我今天很累",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I am very happy.",
                  answer: "我 很 高兴",
                  bank: ["我", "很", "高兴", "累", "书"],
                  speak: "我很高兴",
                  pinyin: "wǒ hěn gāoxìng",
                  translation: "I am very happy.",
                },
                {
                  type: "select",
                  prompt: "Choose the correct sentence",
                  question: "I like to read books.",
                  options: ["我喜欢看书", "我累看书", "我高兴看书"],
                  optionSubs: ["wǒ xǐhuān kàn shū", "wǒ lèi kàn shū", "wǒ gāoxìng kàn shū"],
                  answer: 0,
                  speak: "我喜欢看书",
                },
                {
                  type: "wordbank",
                  prompt: "Translate this sentence",
                  given: "I am tired today.",
                  answer: "我 今天 很 累",
                  bank: ["我", "今天", "很", "累", "高兴", "书"],
                  speak: "我今天很累",
                  pinyin: "wǒ jīntiān hěn lèi",
                  translation: "I am tired today.",
                },
                {
                  type: "listen",
                  prompt: "Tap what you hear",
                  speak: "我很高兴",
                  answer: "我 很 高兴",
                  bank: ["我", "很", "高兴", "累", "今天"],
                  translation: "I am very happy.",
                  pinyin: "wǒ hěn gāoxìng",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
