import type { CourseBlueprint } from "@/curriculum/generate";

export const germanBlueprint: CourseBlueprint = {
  code: "de",
  name: "German",
  endonym: "Deutsch",
  flag: "🇩🇪",
  fromLanguage: "English",
  speechLocale: "de-DE",
  sections: [
    {
      id: "de-s1",
      title: "Rookie",
      subtitle: "First words and everyday basics",
      units: [
        {
          id: "de-u1",
          title: "Greetings",
          subtitle: "Say hello and introduce yourself",
          cefr: "A1",
          color: "#58CC02",
          icon: "👋",
          vocab: [
            { target: "hallo", en: "hello" },
            { target: "tschüss", en: "bye" },
            { target: "ja", en: "yes" },
            { target: "nein", en: "no" },
            { target: "danke", en: "thank you" },
            { target: "bitte", en: "please" },
            { target: "guten Morgen", en: "good morning" },
            { target: "guten Tag", en: "good day" },
            { target: "gute Nacht", en: "good night" },
            { target: "willkommen", en: "welcome" },
            { target: "ich", en: "I" },
            { target: "du", en: "you" },
            { target: "heißen", en: "to be called" },
            { target: "sein", en: "to be" },
            { target: "der Name", en: "the name" },
            { target: "gut", en: "good" },
            { target: "wie", en: "how" },
            { target: "geht", en: "goes" },
            { target: "der Freund", en: "the friend" },
            { target: "die Frau", en: "the woman" },
            { target: "der Mann", en: "the man" },
            { target: "entschuldigung", en: "excuse me" },
            { target: "und", en: "and" },
            { target: "sehr", en: "very" },
          ],
          sentences: [
            { target: "Hallo wie geht es dir", en: "Hello, how are you" },
            { target: "Ich heiße Anna", en: "My name is Anna" },
            { target: "Guten Morgen", en: "Good morning" },
            { target: "Danke sehr gut", en: "Thank you, very good" },
            { target: "Wie heißt du", en: "What is your name" },
            { target: "Ich bin gut", en: "I am good" },
            { target: "Gute Nacht", en: "Good night" },
            { target: "Du bist mein Freund", en: "You are my friend" },
            { target: "Bitte und danke", en: "Please and thank you" },
            { target: "Willkommen und guten Tag", en: "Welcome and good day" },
            { target: "Ja danke", en: "Yes, thank you" },
            { target: "Nein danke", en: "No, thank you" },
            { target: "Die Frau heißt Eva", en: "The woman is called Eva" },
            { target: "Der Mann ist sehr gut", en: "The man is very good" },
            { target: "Tschüss und gute Nacht", en: "Bye and good night" },
            { target: "Wie ist dein Name", en: "What is your name" },
          ],
        },
        {
          id: "de-u2",
          title: "People & family",
          subtitle: "Talk about family and friends",
          cefr: "A1",
          color: "#1CB0F6",
          icon: "👨‍👩‍👧",
          vocab: [
            { target: "die Familie", en: "the family" },
            { target: "die Mutter", en: "the mother" },
            { target: "der Vater", en: "the father" },
            { target: "die Eltern", en: "the parents" },
            { target: "der Bruder", en: "the brother" },
            { target: "die Schwester", en: "the sister" },
            { target: "das Kind", en: "the child" },
            { target: "der Sohn", en: "the son" },
            { target: "die Tochter", en: "the daughter" },
            { target: "die Großmutter", en: "the grandmother" },
            { target: "der Großvater", en: "the grandfather" },
            { target: "der Junge", en: "the boy" },
            { target: "das Mädchen", en: "the girl" },
            { target: "haben", en: "to have" },
            { target: "lieben", en: "to love" },
            { target: "klein", en: "small" },
            { target: "groß", en: "big" },
            { target: "alt", en: "old" },
            { target: "jung", en: "young" },
            { target: "mein", en: "my" },
            { target: "dein", en: "your" },
            { target: "wir", en: "we" },
            { target: "auch", en: "also" },
            { target: "zwei", en: "two" },
          ],
          sentences: [
            { target: "Ich habe einen Bruder", en: "I have a brother" },
            { target: "Meine Mutter ist sehr jung", en: "My mother is very young" },
            { target: "Der Vater liebt das Kind", en: "The father loves the child" },
            { target: "Wir haben zwei Kinder", en: "We have two children" },
            { target: "Mein Bruder ist groß", en: "My brother is big" },
            { target: "Die Schwester ist klein", en: "The sister is small" },
            { target: "Meine Eltern sind alt", en: "My parents are old" },
            { target: "Der Junge liebt die Familie", en: "The boy loves the family" },
            { target: "Das Mädchen ist meine Tochter", en: "The girl is my daughter" },
            { target: "Dein Sohn ist sehr jung", en: "Your son is very young" },
            { target: "Wir lieben die Großmutter", en: "We love the grandmother" },
            { target: "Der Großvater ist alt", en: "The grandfather is old" },
            { target: "Ich liebe meine Familie", en: "I love my family" },
            { target: "Du hast eine Schwester", en: "You have a sister" },
            { target: "Mein Vater ist auch groß", en: "My father is also big" },
            { target: "Die Eltern lieben die Kinder", en: "The parents love the children" },
          ],
        },
        {
          id: "de-u3",
          title: "Food & drink",
          subtitle: "Order and describe meals",
          cefr: "A1",
          color: "#FF9600",
          icon: "🍎",
          vocab: [
            { target: "das Wasser", en: "the water" },
            { target: "das Brot", en: "the bread" },
            { target: "der Apfel", en: "the apple" },
            { target: "die Milch", en: "the milk" },
            { target: "der Kaffee", en: "the coffee" },
            { target: "der Tee", en: "the tea" },
            { target: "das Ei", en: "the egg" },
            { target: "der Käse", en: "the cheese" },
            { target: "das Fleisch", en: "the meat" },
            { target: "der Fisch", en: "the fish" },
            { target: "die Suppe", en: "the soup" },
            { target: "der Reis", en: "the rice" },
            { target: "der Zucker", en: "the sugar" },
            { target: "das Salz", en: "the salt" },
            { target: "das Obst", en: "the fruit" },
            { target: "das Gemüse", en: "the vegetables" },
            { target: "essen", en: "to eat" },
            { target: "trinken", en: "to drink" },
            { target: "möchten", en: "would like" },
            { target: "der Hunger", en: "the hunger" },
            { target: "lecker", en: "tasty" },
            { target: "kalt", en: "cold" },
            { target: "warm", en: "warm" },
            { target: "das Frühstück", en: "the breakfast" },
          ],
          sentences: [
            { target: "Ich trinke Wasser", en: "I drink water" },
            { target: "Wir essen Brot", en: "We eat bread" },
            { target: "Der Kaffee ist warm", en: "The coffee is warm" },
            { target: "Ich möchte einen Apfel", en: "I would like an apple" },
            { target: "Das Frühstück ist lecker", en: "The breakfast is tasty" },
            { target: "Die Milch ist kalt", en: "The milk is cold" },
            { target: "Du isst Fisch und Reis", en: "You eat fish and rice" },
            { target: "Ich möchte Tee trinken", en: "I would like to drink tea" },
            { target: "Wir essen Obst und Gemüse", en: "We eat fruit and vegetables" },
            { target: "Der Käse ist sehr lecker", en: "The cheese is very tasty" },
            { target: "Ich habe Hunger", en: "I am hungry" },
            { target: "Das Fleisch ist warm", en: "The meat is warm" },
            { target: "Die Suppe ist kalt", en: "The soup is cold" },
            { target: "Ich möchte Brot und Käse", en: "I would like bread and cheese" },
            { target: "Du trinkst Milch", en: "You drink milk" },
            { target: "Das Ei ist lecker", en: "The egg is tasty" },
          ],
        },
        {
          id: "de-u4",
          title: "Numbers & time",
          subtitle: "Count and tell the time",
          cefr: "A1",
          color: "#CE82FF",
          icon: "🕐",
          vocab: [
            { target: "eins", en: "one" },
            { target: "zwei", en: "two" },
            { target: "drei", en: "three" },
            { target: "vier", en: "four" },
            { target: "fünf", en: "five" },
            { target: "sechs", en: "six" },
            { target: "sieben", en: "seven" },
            { target: "acht", en: "eight" },
            { target: "neun", en: "nine" },
            { target: "zehn", en: "ten" },
            { target: "die Uhr", en: "the clock" },
            { target: "die Stunde", en: "the hour" },
            { target: "die Minute", en: "the minute" },
            { target: "der Tag", en: "the day" },
            { target: "die Woche", en: "the week" },
            { target: "der Monat", en: "the month" },
            { target: "das Jahr", en: "the year" },
            { target: "heute", en: "today" },
            { target: "morgen", en: "tomorrow" },
            { target: "jetzt", en: "now" },
            { target: "spät", en: "late" },
            { target: "früh", en: "early" },
            { target: "wie viel", en: "how much" },
            { target: "die Zeit", en: "the time" },
          ],
          sentences: [
            { target: "Es ist drei Uhr", en: "It is three o'clock" },
            { target: "Ich habe zwei Stunden", en: "I have two hours" },
            { target: "Wie viel Uhr ist es", en: "What time is it" },
            { target: "Heute ist ein Tag", en: "Today is a day" },
            { target: "Es ist sehr spät", en: "It is very late" },
            { target: "Wir haben eine Woche", en: "We have a week" },
            { target: "Morgen ist ein Tag", en: "Tomorrow is a day" },
            { target: "Ich habe keine Zeit", en: "I have no time" },
            { target: "Es ist jetzt früh", en: "It is early now" },
            { target: "Der Monat hat vier Wochen", en: "The month has four weeks" },
            { target: "Das Jahr hat zwölf Monate", en: "The year has twelve months" },
            { target: "Eine Stunde hat sechzig Minuten", en: "An hour has sixty minutes" },
            { target: "Ich komme heute", en: "I come today" },
            { target: "Es ist zehn Uhr", en: "It is ten o'clock" },
            { target: "Wir haben acht Stunden", en: "We have eight hours" },
            { target: "Die Zeit ist jetzt", en: "The time is now" },
          ],
        },
      ],
    },
    {
      id: "de-s2",
      title: "Explorer",
      subtitle: "Get around and handle daily life",
      units: [
        {
          id: "de-u5",
          title: "Around town",
          subtitle: "Find your way in the city",
          cefr: "A2",
          color: "#FF4B4B",
          icon: "🏙️",
          vocab: [
            { target: "die Stadt", en: "the city" },
            { target: "die Straße", en: "the street" },
            { target: "der Bahnhof", en: "the train station" },
            { target: "der Markt", en: "the market" },
            { target: "die Bank", en: "the bank" },
            { target: "das Geschäft", en: "the shop" },
            { target: "das Restaurant", en: "the restaurant" },
            { target: "das Hotel", en: "the hotel" },
            { target: "die Kirche", en: "the church" },
            { target: "der Park", en: "the park" },
            { target: "das Auto", en: "the car" },
            { target: "der Bus", en: "the bus" },
            { target: "der Zug", en: "the train" },
            { target: "links", en: "left" },
            { target: "rechts", en: "right" },
            { target: "geradeaus", en: "straight ahead" },
            { target: "hier", en: "here" },
            { target: "dort", en: "there" },
            { target: "wo", en: "where" },
            { target: "gehen", en: "to go" },
            { target: "fahren", en: "to drive" },
            { target: "finden", en: "to find" },
            { target: "nah", en: "near" },
            { target: "weit", en: "far" },
          ],
          sentences: [
            { target: "Wo ist der Bahnhof", en: "Where is the train station" },
            { target: "Ich gehe in die Stadt", en: "I go into the city" },
            { target: "Das Hotel ist hier links", en: "The hotel is here on the left" },
            { target: "Wir fahren mit dem Bus", en: "We go by bus" },
            { target: "Der Park ist sehr weit", en: "The park is very far" },
            { target: "Gehen Sie geradeaus", en: "Go straight ahead" },
            { target: "Das Restaurant ist dort rechts", en: "The restaurant is there on the right" },
            { target: "Ich finde die Straße nicht", en: "I cannot find the street" },
            { target: "Der Markt ist nah", en: "The market is near" },
            { target: "Wo ist die Bank", en: "Where is the bank" },
            { target: "Wir fahren mit dem Zug", en: "We travel by train" },
            { target: "Das Auto ist dort", en: "The car is there" },
            { target: "Die Kirche ist sehr alt", en: "The church is very old" },
            { target: "Ich gehe zum Markt", en: "I go to the market" },
            { target: "Das Geschäft ist hier", en: "The shop is here" },
            { target: "Wo finde ich ein Hotel", en: "Where do I find a hotel" },
          ],
        },
        {
          id: "de-u6",
          title: "Daily routine",
          subtitle: "Describe your everyday day",
          cefr: "A2",
          color: "#2B70C9",
          icon: "⏰",
          vocab: [
            { target: "aufstehen", en: "to get up" },
            { target: "schlafen", en: "to sleep" },
            { target: "arbeiten", en: "to work" },
            { target: "kochen", en: "to cook" },
            { target: "putzen", en: "to clean" },
            { target: "duschen", en: "to shower" },
            { target: "anziehen", en: "to get dressed" },
            { target: "frühstücken", en: "to have breakfast" },
            { target: "lernen", en: "to learn" },
            { target: "lesen", en: "to read" },
            { target: "schreiben", en: "to write" },
            { target: "spielen", en: "to play" },
            { target: "der Morgen", en: "the morning" },
            { target: "der Abend", en: "the evening" },
            { target: "die Nacht", en: "the night" },
            { target: "das Haus", en: "the house" },
            { target: "die Arbeit", en: "the work" },
            { target: "die Schule", en: "the school" },
            { target: "immer", en: "always" },
            { target: "oft", en: "often" },
            { target: "manchmal", en: "sometimes" },
            { target: "nie", en: "never" },
            { target: "müde", en: "tired" },
            { target: "dann", en: "then" },
          ],
          sentences: [
            { target: "Ich stehe früh auf", en: "I get up early" },
            { target: "Am Morgen dusche ich", en: "In the morning I shower" },
            { target: "Wir arbeiten oft", en: "We work often" },
            { target: "Ich koche am Abend", en: "I cook in the evening" },
            { target: "Du gehst zur Schule", en: "You go to school" },
            { target: "Ich bin sehr müde", en: "I am very tired" },
            { target: "Sie lernt immer", en: "She always studies" },
            { target: "Ich lese am Abend", en: "I read in the evening" },
            { target: "Manchmal spiele ich", en: "Sometimes I play" },
            { target: "Wir putzen das Haus", en: "We clean the house" },
            { target: "Ich frühstücke und arbeite dann", en: "I have breakfast and then work" },
            { target: "Du schläfst nie früh", en: "You never sleep early" },
            { target: "Ich ziehe mich an", en: "I get dressed" },
            { target: "Am Abend bin ich müde", en: "In the evening I am tired" },
            { target: "Wir gehen zur Arbeit", en: "We go to work" },
            { target: "Ich schreibe oft", en: "I write often" },
          ],
        },
        {
          id: "de-u7",
          title: "Shopping",
          subtitle: "Buy things and ask prices",
          cefr: "A2",
          color: "#A560E8",
          icon: "🛍️",
          vocab: [
            { target: "kaufen", en: "to buy" },
            { target: "bezahlen", en: "to pay" },
            { target: "kosten", en: "to cost" },
            { target: "der Preis", en: "the price" },
            { target: "das Geld", en: "the money" },
            { target: "der Euro", en: "the euro" },
            { target: "teuer", en: "expensive" },
            { target: "billig", en: "cheap" },
            { target: "die Kleidung", en: "the clothing" },
            { target: "das Hemd", en: "the shirt" },
            { target: "die Hose", en: "the trousers" },
            { target: "die Schuhe", en: "the shoes" },
            { target: "die Jacke", en: "the jacket" },
            { target: "die Größe", en: "the size" },
            { target: "die Farbe", en: "the color" },
            { target: "rot", en: "red" },
            { target: "blau", en: "blue" },
            { target: "schwarz", en: "black" },
            { target: "weiß", en: "white" },
            { target: "neu", en: "new" },
            { target: "brauchen", en: "to need" },
            { target: "zeigen", en: "to show" },
            { target: "der Laden", en: "the store" },
            { target: "viel", en: "much" },
          ],
          sentences: [
            { target: "Was kostet das Hemd", en: "What does the shirt cost" },
            { target: "Ich kaufe eine Jacke", en: "I buy a jacket" },
            { target: "Die Schuhe sind sehr teuer", en: "The shoes are very expensive" },
            { target: "Ich brauche eine neue Hose", en: "I need new trousers" },
            { target: "Das Hemd ist rot", en: "The shirt is red" },
            { target: "Wie viel kostet die Jacke", en: "How much does the jacket cost" },
            { target: "Ich bezahle mit Geld", en: "I pay with money" },
            { target: "Der Preis ist billig", en: "The price is cheap" },
            { target: "Welche Größe brauchst du", en: "Which size do you need" },
            { target: "Zeigen Sie mir die Schuhe", en: "Show me the shoes" },
            { target: "Die Jacke ist blau", en: "The jacket is blue" },
            { target: "Das Hemd kostet zehn Euro", en: "The shirt costs ten euros" },
            { target: "Ich kaufe neue Kleidung", en: "I buy new clothing" },
            { target: "Die Farbe ist schwarz", en: "The color is black" },
            { target: "Der Laden ist hier", en: "The store is here" },
            { target: "Das kostet zu viel", en: "That costs too much" },
          ],
        },
      ],
    },
    {
      id: "de-s3",
      title: "Independent",
      subtitle: "Handle work, study and travel",
      units: [
        {
          id: "de-u8",
          title: "Work & study",
          subtitle: "Talk about jobs and learning",
          cefr: "B1",
          color: "#00CD9C",
          icon: "💼",
          vocab: [
            { target: "der Beruf", en: "the profession" },
            { target: "der Chef", en: "the boss" },
            { target: "der Kollege", en: "the colleague" },
            { target: "das Büro", en: "the office" },
            { target: "die Firma", en: "the company" },
            { target: "das Gehalt", en: "the salary" },
            { target: "die Besprechung", en: "the meeting" },
            { target: "der Termin", en: "the appointment" },
            { target: "die Aufgabe", en: "the task" },
            { target: "das Projekt", en: "the project" },
            { target: "die Universität", en: "the university" },
            { target: "der Student", en: "the student" },
            { target: "die Prüfung", en: "the exam" },
            { target: "das Fach", en: "the subject" },
            { target: "studieren", en: "to study" },
            { target: "verdienen", en: "to earn" },
            { target: "verstehen", en: "to understand" },
            { target: "erklären", en: "to explain" },
            { target: "anfangen", en: "to begin" },
            { target: "beenden", en: "to finish" },
            { target: "schwierig", en: "difficult" },
            { target: "wichtig", en: "important" },
            { target: "erfolgreich", en: "successful" },
            { target: "weil", en: "because" },
          ],
          sentences: [
            { target: "Ich arbeite in einem Büro", en: "I work in an office" },
            { target: "Mein Chef erklärt das Projekt", en: "My boss explains the project" },
            { target: "Die Prüfung war sehr schwierig", en: "The exam was very difficult" },
            { target: "Ich studiere an der Universität", en: "I study at the university" },
            { target: "Wir haben heute eine Besprechung", en: "We have a meeting today" },
            { target: "Der Kollege versteht die Aufgabe", en: "The colleague understands the task" },
            { target: "Ich verdiene ein gutes Gehalt", en: "I earn a good salary" },
            { target: "Das Projekt ist sehr wichtig", en: "The project is very important" },
            { target: "Ich lerne, weil die Prüfung wichtig ist", en: "I study because the exam is important" },
            { target: "Wir fangen das Projekt an", en: "We begin the project" },
            { target: "Der Student ist sehr erfolgreich", en: "The student is very successful" },
            { target: "Ich habe morgen einen Termin", en: "I have an appointment tomorrow" },
            { target: "Die Firma ist sehr groß", en: "The company is very big" },
            { target: "Ich beende die Aufgabe heute", en: "I finish the task today" },
            { target: "Mein Beruf ist schwierig", en: "My profession is difficult" },
            { target: "Das Fach ist wichtig", en: "The subject is important" },
          ],
        },
        {
          id: "de-u9",
          title: "Travel",
          subtitle: "Plan trips and explain plans",
          cefr: "B1",
          color: "#FF86D0",
          icon: "✈️",
          vocab: [
            { target: "die Reise", en: "the trip" },
            { target: "der Urlaub", en: "the vacation" },
            { target: "der Flug", en: "the flight" },
            { target: "das Flugzeug", en: "the airplane" },
            { target: "der Koffer", en: "the suitcase" },
            { target: "das Gepäck", en: "the luggage" },
            { target: "der Pass", en: "the passport" },
            { target: "die Fahrkarte", en: "the ticket" },
            { target: "das Ziel", en: "the destination" },
            { target: "die Grenze", en: "the border" },
            { target: "das Land", en: "the country" },
            { target: "das Meer", en: "the sea" },
            { target: "der Berg", en: "the mountain" },
            { target: "die Karte", en: "the map" },
            { target: "buchen", en: "to book" },
            { target: "reisen", en: "to travel" },
            { target: "ankommen", en: "to arrive" },
            { target: "abfahren", en: "to depart" },
            { target: "packen", en: "to pack" },
            { target: "besuchen", en: "to visit" },
            { target: "während", en: "during" },
            { target: "nächst", en: "next" },
            { target: "zusammen", en: "together" },
            { target: "ohne", en: "without" },
          ],
          sentences: [
            { target: "Ich buche einen Flug", en: "I book a flight" },
            { target: "Wir reisen nächste Woche", en: "We travel next week" },
            { target: "Der Zug fährt um drei ab", en: "The train departs at three" },
            { target: "Ich packe meinen Koffer", en: "I pack my suitcase" },
            { target: "Wir besuchen ein neues Land", en: "We visit a new country" },
            { target: "Das Flugzeug kommt spät an", en: "The airplane arrives late" },
            { target: "Ich reise ohne Gepäck", en: "I travel without luggage" },
            { target: "Während des Urlaubs lese ich viel", en: "During the vacation I read a lot" },
            { target: "Das Meer ist sehr schön", en: "The sea is very beautiful" },
            { target: "Wir fahren zusammen in den Urlaub", en: "We go on vacation together" },
            { target: "Ich brauche meinen Pass", en: "I need my passport" },
            { target: "Die Fahrkarte ist sehr teuer", en: "The ticket is very expensive" },
            { target: "Wir besuchen die Berge", en: "We visit the mountains" },
            { target: "Das Ziel ist sehr weit", en: "The destination is very far" },
            { target: "Ich reise gern ans Meer", en: "I like to travel to the sea" },
            { target: "Wir kommen morgen an", en: "We arrive tomorrow" },
          ],
        },
      ],
    },
    {
      id: "de-s4",
      title: "Upper Intermediate",
      subtitle: "Express opinions on complex topics",
      units: [
        {
          id: "de-u10",
          title: "Opinions & media",
          subtitle: "Share views on news and media",
          cefr: "B2",
          color: "#FFC800",
          icon: "📰",
          vocab: [
            { target: "die Meinung", en: "the opinion" },
            { target: "die Nachricht", en: "the news" },
            { target: "die Zeitung", en: "the newspaper" },
            { target: "der Artikel", en: "the article" },
            { target: "das Fernsehen", en: "the television" },
            { target: "die Sendung", en: "the program" },
            { target: "das Internet", en: "the internet" },
            { target: "die Werbung", en: "the advertising" },
            { target: "die Quelle", en: "the source" },
            { target: "die Tatsache", en: "the fact" },
            { target: "der Einfluss", en: "the influence" },
            { target: "die Gesellschaft", en: "the society" },
            { target: "behaupten", en: "to claim" },
            { target: "bezweifeln", en: "to doubt" },
            { target: "zustimmen", en: "to agree" },
            { target: "ablehnen", en: "to reject" },
            { target: "berichten", en: "to report" },
            { target: "überzeugen", en: "to convince" },
            { target: "glaubwürdig", en: "credible" },
            { target: "wahrscheinlich", en: "probably" },
            { target: "deshalb", en: "therefore" },
            { target: "obwohl", en: "although" },
            { target: "trotzdem", en: "nevertheless" },
            { target: "meiner Meinung nach", en: "in my opinion" },
          ],
          sentences: [
            { target: "Meiner Meinung nach ist die Quelle glaubwürdig", en: "In my opinion the source is credible" },
            { target: "Die Zeitung berichtet über die Gesellschaft", en: "The newspaper reports on society" },
            { target: "Ich bezweifle diese Nachricht", en: "I doubt this news" },
            { target: "Obwohl der Artikel lang ist lese ich ihn", en: "Although the article is long, I read it" },
            { target: "Die Werbung hat großen Einfluss", en: "Advertising has a great influence" },
            { target: "Ich stimme deiner Meinung zu", en: "I agree with your opinion" },
            { target: "Er behauptet eine Tatsache", en: "He claims a fact" },
            { target: "Das Internet überzeugt viele Menschen", en: "The internet convinces many people" },
            { target: "Deshalb lehne ich die Werbung ab", en: "Therefore I reject the advertising" },
            { target: "Die Sendung ist wahrscheinlich glaubwürdig", en: "The program is probably credible" },
            { target: "Ich sehe oft das Fernsehen", en: "I often watch television" },
            { target: "Trotzdem bezweifle ich die Quelle", en: "Nevertheless I doubt the source" },
            { target: "Die Nachricht hat großen Einfluss", en: "The news has a great influence" },
            { target: "Der Artikel berichtet über das Internet", en: "The article reports on the internet" },
            { target: "Ich glaube diese Tatsache nicht", en: "I do not believe this fact" },
            { target: "Seine Meinung überzeugt mich nicht", en: "His opinion does not convince me" },
          ],
        },
        {
          id: "de-u11",
          title: "Health & society",
          subtitle: "Discuss wellbeing and community",
          cefr: "B2",
          color: "#E5533C",
          icon: "🩺",
          vocab: [
            { target: "die Gesundheit", en: "the health" },
            { target: "die Krankheit", en: "the illness" },
            { target: "der Arzt", en: "the doctor" },
            { target: "das Krankenhaus", en: "the hospital" },
            { target: "die Behandlung", en: "the treatment" },
            { target: "das Medikament", en: "the medicine" },
            { target: "die Ernährung", en: "the nutrition" },
            { target: "die Bewegung", en: "the exercise" },
            { target: "der Stress", en: "the stress" },
            { target: "die Umwelt", en: "the environment" },
            { target: "die Regierung", en: "the government" },
            { target: "die Bevölkerung", en: "the population" },
            { target: "das Problem", en: "the problem" },
            { target: "die Lösung", en: "the solution" },
            { target: "sich fühlen", en: "to feel" },
            { target: "sich erholen", en: "to recover" },
            { target: "vermeiden", en: "to avoid" },
            { target: "verbessern", en: "to improve" },
            { target: "unterstützen", en: "to support" },
            { target: "gesund", en: "healthy" },
            { target: "krank", en: "sick" },
            { target: "notwendig", en: "necessary" },
            { target: "gefährlich", en: "dangerous" },
            { target: "deswegen", en: "for that reason" },
          ],
          sentences: [
            { target: "Eine gute Ernährung ist sehr wichtig", en: "Good nutrition is very important" },
            { target: "Der Arzt empfiehlt mehr Bewegung", en: "The doctor recommends more exercise" },
            { target: "Stress ist gefährlich für die Gesundheit", en: "Stress is dangerous for health" },
            { target: "Die Regierung sucht eine Lösung", en: "The government is looking for a solution" },
            { target: "Ich fühle mich heute krank", en: "I feel sick today" },
            { target: "Wir müssen die Umwelt verbessern", en: "We must improve the environment" },
            { target: "Das Medikament hilft gegen die Krankheit", en: "The medicine helps against the illness" },
            { target: "Bewegung ist notwendig für die Gesundheit", en: "Exercise is necessary for health" },
            { target: "Deswegen vermeide ich Stress", en: "For that reason I avoid stress" },
            { target: "Die Bevölkerung unterstützt die Lösung", en: "The population supports the solution" },
            { target: "Im Krankenhaus erhole ich mich", en: "In the hospital I recover" },
            { target: "Das Problem ist sehr gefährlich", en: "The problem is very dangerous" },
            { target: "Eine gesunde Ernährung vermeidet Krankheiten", en: "A healthy diet avoids illnesses" },
            { target: "Die Behandlung war erfolgreich", en: "The treatment was successful" },
            { target: "Wir unterstützen die Regierung nicht", en: "We do not support the government" },
            { target: "Sport verbessert die Gesundheit", en: "Sport improves health" },
          ],
        },
      ],
    },
    {
      id: "de-s5",
      title: "Advanced",
      subtitle: "Engage with abstract and academic topics",
      units: [
        {
          id: "de-u12",
          title: "Abstract ideas",
          subtitle: "Reason about concepts and values",
          cefr: "C1",
          color: "#7C4DFF",
          icon: "💭",
          vocab: [
            { target: "der Gedanke", en: "the thought" },
            { target: "der Begriff", en: "the concept" },
            { target: "die Bedeutung", en: "the meaning" },
            { target: "die Wahrheit", en: "the truth" },
            { target: "die Freiheit", en: "the freedom" },
            { target: "die Gerechtigkeit", en: "the justice" },
            { target: "die Wirklichkeit", en: "the reality" },
            { target: "das Bewusstsein", en: "the consciousness" },
            { target: "der Zweifel", en: "the doubt" },
            { target: "die Vernunft", en: "the reason" },
            { target: "die Erfahrung", en: "the experience" },
            { target: "der Zusammenhang", en: "the connection" },
            { target: "die Voraussetzung", en: "the precondition" },
            { target: "die Folge", en: "the consequence" },
            { target: "wahrnehmen", en: "to perceive" },
            { target: "begreifen", en: "to comprehend" },
            { target: "voraussetzen", en: "to presuppose" },
            { target: "verallgemeinern", en: "to generalize" },
            { target: "widersprechen", en: "to contradict" },
            { target: "abstrakt", en: "abstract" },
            { target: "grundsätzlich", en: "fundamentally" },
            { target: "dennoch", en: "yet" },
            { target: "einerseits", en: "on the one hand" },
            { target: "andererseits", en: "on the other hand" },
          ],
          sentences: [
            { target: "Der Begriff der Freiheit ist abstrakt", en: "The concept of freedom is abstract" },
            { target: "Einerseits zweifle ich andererseits begreife ich es", en: "On the one hand I doubt, on the other I comprehend it" },
            { target: "Die Wahrheit widerspricht der Wirklichkeit oft", en: "The truth often contradicts reality" },
            { target: "Vernunft setzt Erfahrung voraus", en: "Reason presupposes experience" },
            { target: "Jeder Gedanke hat eine Bedeutung", en: "Every thought has a meaning" },
            { target: "Wir nehmen die Wirklichkeit verschieden wahr", en: "We perceive reality differently" },
            { target: "Grundsätzlich verstehe ich den Zusammenhang", en: "Fundamentally I understand the connection" },
            { target: "Die Folge ist grundsätzlich klar", en: "The consequence is fundamentally clear" },
            { target: "Dennoch bleibt der Zweifel bestehen", en: "Yet the doubt remains" },
            { target: "Gerechtigkeit ist eine Voraussetzung für Freiheit", en: "Justice is a precondition for freedom" },
            { target: "Das Bewusstsein begreift die Wahrheit nicht", en: "Consciousness does not comprehend the truth" },
            { target: "Man darf nicht zu schnell verallgemeinern", en: "One must not generalize too quickly" },
            { target: "Der Zusammenhang ist sehr abstrakt", en: "The connection is very abstract" },
            { target: "Erfahrung verändert unsere Wahrnehmung", en: "Experience changes our perception" },
            { target: "Diese Voraussetzung widerspricht der Vernunft", en: "This precondition contradicts reason" },
            { target: "Die Bedeutung des Begriffs ist unklar", en: "The meaning of the concept is unclear" },
          ],
        },
        {
          id: "de-u13",
          title: "Academia",
          subtitle: "Navigate research and scholarship",
          cefr: "C1",
          color: "#3F51B5",
          icon: "🎓",
          vocab: [
            { target: "die Forschung", en: "the research" },
            { target: "die Wissenschaft", en: "the science" },
            { target: "die Theorie", en: "the theory" },
            { target: "die These", en: "the thesis" },
            { target: "die Studie", en: "the study" },
            { target: "das Ergebnis", en: "the result" },
            { target: "der Beweis", en: "the proof" },
            { target: "die Methode", en: "the method" },
            { target: "die Analyse", en: "the analysis" },
            { target: "die Daten", en: "the data" },
            { target: "die Quelle", en: "the source" },
            { target: "der Autor", en: "the author" },
            { target: "die Veröffentlichung", en: "the publication" },
            { target: "der Beitrag", en: "the contribution" },
            { target: "die Erkenntnis", en: "the insight" },
            { target: "untersuchen", en: "to investigate" },
            { target: "analysieren", en: "to analyze" },
            { target: "belegen", en: "to substantiate" },
            { target: "schlussfolgern", en: "to conclude" },
            { target: "zitieren", en: "to cite" },
            { target: "umfassend", en: "comprehensive" },
            { target: "empirisch", en: "empirical" },
            { target: "folglich", en: "consequently" },
            { target: "hinsichtlich", en: "with regard to" },
          ],
          sentences: [
            { target: "Die Studie untersucht ein wichtiges Problem", en: "The study investigates an important problem" },
            { target: "Die Daten belegen unsere These", en: "The data substantiate our thesis" },
            { target: "Der Autor zitiert mehrere Quellen", en: "The author cites several sources" },
            { target: "Folglich ist die Theorie glaubwürdig", en: "Consequently the theory is credible" },
            { target: "Die Analyse liefert ein klares Ergebnis", en: "The analysis yields a clear result" },
            { target: "Wir analysieren die empirischen Daten", en: "We analyze the empirical data" },
            { target: "Die Forschung braucht eine gute Methode", en: "Research needs a good method" },
            { target: "Hinsichtlich der Ergebnisse bin ich skeptisch", en: "With regard to the results I am skeptical" },
            { target: "Die Erkenntnis ist sehr umfassend", en: "The insight is very comprehensive" },
            { target: "Der Beweis stützt die These", en: "The proof supports the thesis" },
            { target: "Folglich schlussfolgern wir ein Ergebnis", en: "Consequently we conclude a result" },
            { target: "Die Veröffentlichung ist ein wichtiger Beitrag", en: "The publication is an important contribution" },
            { target: "Die Methode ist nicht umfassend genug", en: "The method is not comprehensive enough" },
            { target: "Wir untersuchen die Quelle genau", en: "We investigate the source closely" },
            { target: "Die Wissenschaft braucht empirische Beweise", en: "Science needs empirical proof" },
            { target: "Diese Theorie widerspricht der Studie", en: "This theory contradicts the study" },
          ],
        },
      ],
    },
    {
      id: "de-s6",
      title: "Mastery",
      subtitle: "Command nuance, idiom and rhetoric",
      units: [
        {
          id: "de-u14",
          title: "Idioms & nuance",
          subtitle: "Use idioms and subtle shades of meaning",
          cefr: "C2",
          color: "#009688",
          icon: "🎭",
          vocab: [
            { target: "die Redewendung", en: "the idiom" },
            { target: "der Ausdruck", en: "the expression" },
            { target: "der Nachdruck", en: "the emphasis" },
            { target: "die Anspielung", en: "the allusion" },
            { target: "der Beigeschmack", en: "the connotation" },
            { target: "die Ironie", en: "the irony" },
            { target: "das Sprichwort", en: "the proverb" },
            { target: "der Tonfall", en: "the tone" },
            { target: "die Zwischentöne", en: "the nuances" },
            { target: "die Übertreibung", en: "the exaggeration" },
            { target: "andeuten", en: "to imply" },
            { target: "betonen", en: "to emphasize" },
            { target: "verharmlosen", en: "to play down" },
            { target: "auffassen", en: "to interpret" },
            { target: "umschreiben", en: "to paraphrase" },
            { target: "Daumen drücken", en: "to keep fingers crossed" },
            { target: "ins Wasser fallen", en: "to fall through" },
            { target: "auf dem Schlauch stehen", en: "to be stumped" },
            { target: "die Katze im Sack", en: "a pig in a poke" },
            { target: "treffend", en: "apt" },
            { target: "geläufig", en: "common" },
            { target: "doppeldeutig", en: "ambiguous" },
            { target: "augenscheinlich", en: "apparently" },
            { target: "sozusagen", en: "so to speak" },
          ],
          sentences: [
            { target: "Diese Redewendung ist sehr geläufig", en: "This idiom is very common" },
            { target: "Er betont jedes Wort mit Nachdruck", en: "He emphasizes every word with emphasis" },
            { target: "Ihr Tonfall hatte einen ironischen Beigeschmack", en: "Her tone had an ironic connotation" },
            { target: "Ich drücke dir die Daumen", en: "I keep my fingers crossed for you" },
            { target: "Der Plan ist leider ins Wasser gefallen", en: "Unfortunately the plan fell through" },
            { target: "Augenscheinlich deutet er etwas an", en: "Apparently he is implying something" },
            { target: "Diese Aussage ist sehr doppeldeutig", en: "This statement is very ambiguous" },
            { target: "Das ist sozusagen ein treffender Ausdruck", en: "That is, so to speak, an apt expression" },
            { target: "Ich stehe völlig auf dem Schlauch", en: "I am completely stumped" },
            { target: "Man sollte das Problem nicht verharmlosen", en: "One should not play down the problem" },
            { target: "Seine Ironie war kaum zu überhören", en: "His irony was hard to miss" },
            { target: "Das Sprichwort trifft den Kern", en: "The proverb hits the core" },
            { target: "Ich fasse seine Worte anders auf", en: "I interpret his words differently" },
            { target: "Ihre Übertreibung war kaum zu glauben", en: "Her exaggeration was hard to believe" },
            { target: "Kaufe nie die Katze im Sack", en: "Never buy a pig in a poke" },
            { target: "Lass mich das treffend umschreiben", en: "Let me paraphrase that aptly" },
          ],
        },
        {
          id: "de-u15",
          title: "Debate & literature",
          subtitle: "Argue rhetorically and read literature",
          cefr: "C2",
          color: "#5D4037",
          icon: "📚",
          vocab: [
            { target: "die Debatte", en: "the debate" },
            { target: "das Argument", en: "the argument" },
            { target: "der Einwand", en: "the objection" },
            { target: "die Widerlegung", en: "the rebuttal" },
            { target: "die Rhetorik", en: "the rhetoric" },
            { target: "die Überzeugungskraft", en: "the persuasiveness" },
            { target: "der Standpunkt", en: "the standpoint" },
            { target: "die Schlussfolgerung", en: "the conclusion" },
            { target: "die Literatur", en: "the literature" },
            { target: "der Roman", en: "the novel" },
            { target: "die Erzählung", en: "the narrative" },
            { target: "die Metapher", en: "the metaphor" },
            { target: "der Stil", en: "the style" },
            { target: "die Figur", en: "the character" },
            { target: "das Werk", en: "the work" },
            { target: "darlegen", en: "to set out" },
            { target: "entkräften", en: "to refute" },
            { target: "abwägen", en: "to weigh up" },
            { target: "verdeutlichen", en: "to clarify" },
            { target: "interpretieren", en: "to interpret" },
            { target: "stichhaltig", en: "valid" },
            { target: "voreingenommen", en: "biased" },
            { target: "demzufolge", en: "accordingly" },
            { target: "letztendlich", en: "ultimately" },
          ],
          sentences: [
            { target: "Er legt sein Argument klar dar", en: "He sets out his argument clearly" },
            { target: "Ihr Einwand ist durchaus stichhaltig", en: "Her objection is quite valid" },
            { target: "Die Widerlegung entkräftet seinen Standpunkt", en: "The rebuttal refutes his standpoint" },
            { target: "Wir müssen beide Argumente sorgfältig abwägen", en: "We must carefully weigh both arguments" },
            { target: "Seine Rhetorik hat große Überzeugungskraft", en: "His rhetoric has great persuasiveness" },
            { target: "Der Roman verwendet eine kühne Metapher", en: "The novel uses a bold metaphor" },
            { target: "Ich interpretiere die Figur ganz anders", en: "I interpret the character quite differently" },
            { target: "Demzufolge ist seine Schlussfolgerung falsch", en: "Accordingly his conclusion is wrong" },
            { target: "Der Autor ist eindeutig voreingenommen", en: "The author is clearly biased" },
            { target: "Letztendlich überzeugt mich die Debatte nicht", en: "Ultimately the debate does not convince me" },
            { target: "Der Stil dieses Werkes ist einzigartig", en: "The style of this work is unique" },
            { target: "Die Erzählung verdeutlicht ein wichtiges Thema", en: "The narrative clarifies an important theme" },
            { target: "Sein Standpunkt ist letztendlich stichhaltig", en: "His standpoint is ultimately valid" },
            { target: "Wir entkräften jeden Einwand", en: "We refute every objection" },
            { target: "Die Metapher verdeutlicht den Konflikt", en: "The metaphor clarifies the conflict" },
            { target: "Diese Literatur ist schwer zu interpretieren", en: "This literature is hard to interpret" },
          ],
        },
      ],
    },
  ],
};
