import type { SectionBlueprint } from "@/curriculum/generate";

export const germanThemeSections: SectionBlueprint[] = [
  {
    id: "de-sT1",
    title: "Themes",
    subtitle: "Broaden your vocabulary",
    units: [
      {
        id: "de-ut1",
        title: "Nature & weather",
        subtitle: "Describe the outdoors and the sky",
        cefr: "A2",
        color: "#34A853",
        icon: "🌦️",
        vocab: [
          { target: "die Natur", en: "the nature" },
          { target: "der Baum", en: "the tree" },
          { target: "der Wald", en: "the forest" },
          { target: "die Blume", en: "the flower" },
          { target: "das Gras", en: "the grass" },
          { target: "der Fluss", en: "the river" },
          { target: "der See", en: "the lake" },
          { target: "der Himmel", en: "the sky" },
          { target: "die Sonne", en: "the sun" },
          { target: "der Mond", en: "the moon" },
          { target: "der Stern", en: "the star" },
          { target: "die Wolke", en: "the cloud" },
          { target: "der Regen", en: "the rain" },
          { target: "der Schnee", en: "the snow" },
          { target: "der Wind", en: "the wind" },
          { target: "das Wetter", en: "the weather" },
          { target: "der Sturm", en: "the storm" },
          { target: "der Nebel", en: "the fog" },
          { target: "das Tier", en: "the animal" },
          { target: "der Vogel", en: "the bird" },
          { target: "scheinen", en: "to shine" },
          { target: "regnen", en: "to rain" },
          { target: "windig", en: "windy" },
          { target: "sonnig", en: "sunny" },
        ],
        sentences: [
          { target: "Die Sonne scheint heute", en: "The sun is shining today" },
          { target: "Es regnet im Wald", en: "It is raining in the forest" },
          { target: "Der Himmel ist sehr blau", en: "The sky is very blue" },
          { target: "Der Baum ist groß und alt", en: "The tree is big and old" },
          { target: "Heute ist das Wetter sonnig", en: "Today the weather is sunny" },
          { target: "Der Wind ist sehr kalt", en: "The wind is very cold" },
          { target: "Viele Sterne sind am Himmel", en: "Many stars are in the sky" },
          { target: "Der Fluss ist sehr breit", en: "The river is very wide" },
          { target: "Im Winter fällt der Schnee", en: "In winter the snow falls" },
          { target: "Der Vogel singt im Baum", en: "The bird sings in the tree" },
          { target: "Die Blume ist rot und schön", en: "The flower is red and beautiful" },
          { target: "Eine Wolke verdeckt die Sonne", en: "A cloud covers the sun" },
          { target: "Der Mond scheint in der Nacht", en: "The moon shines at night" },
          { target: "Es ist heute sehr windig", en: "It is very windy today" },
        ],
      },
      {
        id: "de-ut2",
        title: "Emotions & feelings",
        subtitle: "Say how you and others feel",
        cefr: "A2",
        color: "#EA4F8A",
        icon: "😊",
        vocab: [
          { target: "das Gefühl", en: "the feeling" },
          { target: "die Freude", en: "the joy" },
          { target: "die Angst", en: "the fear" },
          { target: "die Liebe", en: "the love" },
          { target: "die Wut", en: "the anger" },
          { target: "die Hoffnung", en: "the hope" },
          { target: "die Überraschung", en: "the surprise" },
          { target: "glücklich", en: "happy" },
          { target: "traurig", en: "sad" },
          { target: "wütend", en: "angry" },
          { target: "ängstlich", en: "anxious" },
          { target: "ruhig", en: "calm" },
          { target: "nervös", en: "nervous" },
          { target: "stolz", en: "proud" },
          { target: "müde", en: "tired" },
          { target: "froh", en: "glad" },
          { target: "fühlen", en: "to feel" },
          { target: "weinen", en: "to cry" },
          { target: "lachen", en: "to laugh" },
          { target: "lächeln", en: "to smile" },
          { target: "hoffen", en: "to hope" },
          { target: "fürchten", en: "to fear" },
          { target: "weil", en: "because" },
          { target: "sehr", en: "very" },
        ],
        sentences: [
          { target: "Ich bin heute sehr glücklich", en: "I am very happy today" },
          { target: "Sie weint, weil sie traurig ist", en: "She cries because she is sad" },
          { target: "Ich fühle eine große Freude", en: "I feel a great joy" },
          { target: "Er ist sehr wütend", en: "He is very angry" },
          { target: "Wir lachen und lächeln zusammen", en: "We laugh and smile together" },
          { target: "Ich habe Angst vor dem Sturm", en: "I am afraid of the storm" },
          { target: "Sie ist stolz auf ihr Kind", en: "She is proud of her child" },
          { target: "Ich bleibe ruhig und froh", en: "I stay calm and glad" },
          { target: "Er ist nervös vor der Prüfung", en: "He is nervous before the exam" },
          { target: "Wir hoffen auf gutes Wetter", en: "We hope for good weather" },
          { target: "Das Gefühl der Liebe ist schön", en: "The feeling of love is beautiful" },
          { target: "Ich bin müde, aber glücklich", en: "I am tired but happy" },
          { target: "Sie fürchtet die Dunkelheit nicht", en: "She does not fear the darkness" },
          { target: "Die Überraschung macht ihn froh", en: "The surprise makes him glad" },
        ],
      },
      {
        id: "de-ut3",
        title: "House & everyday objects",
        subtitle: "Name rooms and things at home",
        cefr: "A2",
        color: "#F4A300",
        icon: "🏠",
        vocab: [
          { target: "das Haus", en: "the house" },
          { target: "die Wohnung", en: "the apartment" },
          { target: "das Zimmer", en: "the room" },
          { target: "die Küche", en: "the kitchen" },
          { target: "das Bad", en: "the bathroom" },
          { target: "das Schlafzimmer", en: "the bedroom" },
          { target: "die Tür", en: "the door" },
          { target: "das Fenster", en: "the window" },
          { target: "der Tisch", en: "the table" },
          { target: "der Stuhl", en: "the chair" },
          { target: "das Bett", en: "the bed" },
          { target: "das Sofa", en: "the sofa" },
          { target: "der Schrank", en: "the cupboard" },
          { target: "die Lampe", en: "the lamp" },
          { target: "der Teppich", en: "the carpet" },
          { target: "der Spiegel", en: "the mirror" },
          { target: "die Uhr", en: "the clock" },
          { target: "der Schlüssel", en: "the key" },
          { target: "das Buch", en: "the book" },
          { target: "der Garten", en: "the garden" },
          { target: "öffnen", en: "to open" },
          { target: "schließen", en: "to close" },
          { target: "sauber", en: "clean" },
          { target: "gemütlich", en: "cozy" },
        ],
        sentences: [
          { target: "Die Küche ist sehr sauber", en: "The kitchen is very clean" },
          { target: "Ich öffne das Fenster", en: "I open the window" },
          { target: "Der Tisch steht im Zimmer", en: "The table is in the room" },
          { target: "Das Bett ist sehr gemütlich", en: "The bed is very cozy" },
          { target: "Bitte schließe die Tür", en: "Please close the door" },
          { target: "Die Lampe steht auf dem Tisch", en: "The lamp is on the table" },
          { target: "Wo ist mein Schlüssel", en: "Where is my key" },
          { target: "Das Buch liegt auf dem Sofa", en: "The book is on the sofa" },
          { target: "Die Wohnung hat drei Zimmer", en: "The apartment has three rooms" },
          { target: "Der Garten ist sehr schön", en: "The garden is very beautiful" },
          { target: "Im Bad gibt es einen Spiegel", en: "In the bathroom there is a mirror" },
          { target: "Der Stuhl steht am Fenster", en: "The chair is by the window" },
          { target: "Mein Schlafzimmer ist sehr gemütlich", en: "My bedroom is very cozy" },
          { target: "Die Uhr hängt an der Wand", en: "The clock hangs on the wall" },
        ],
      },
    ],
  },
  {
    id: "de-sT2",
    title: "Real life",
    subtitle: "Talk about the wider world",
    units: [
      {
        id: "de-ut4",
        title: "Work & money",
        subtitle: "Discuss jobs, pay and spending",
        cefr: "B1",
        color: "#0F9D8C",
        icon: "💰",
        vocab: [
          { target: "die Arbeit", en: "the work" },
          { target: "der Job", en: "the job" },
          { target: "der Beruf", en: "the profession" },
          { target: "der Kollege", en: "the colleague" },
          { target: "der Chef", en: "the boss" },
          { target: "das Büro", en: "the office" },
          { target: "das Geld", en: "the money" },
          { target: "das Gehalt", en: "the salary" },
          { target: "die Steuer", en: "the tax" },
          { target: "das Konto", en: "the account" },
          { target: "die Rechnung", en: "the bill" },
          { target: "der Vertrag", en: "the contract" },
          { target: "die Stunde", en: "the hour" },
          { target: "verdienen", en: "to earn" },
          { target: "bezahlen", en: "to pay" },
          { target: "sparen", en: "to save" },
          { target: "ausgeben", en: "to spend" },
          { target: "arbeiten", en: "to work" },
          { target: "kosten", en: "to cost" },
          { target: "teuer", en: "expensive" },
          { target: "billig", en: "cheap" },
          { target: "genug", en: "enough" },
          { target: "fleißig", en: "hardworking" },
          { target: "monatlich", en: "monthly" },
        ],
        sentences: [
          { target: "Ich verdiene ein gutes Gehalt", en: "I earn a good salary" },
          { target: "Mein Chef arbeitet im Büro", en: "My boss works in the office" },
          { target: "Wir müssen die Rechnung bezahlen", en: "We have to pay the bill" },
          { target: "Sie spart jeden Monat Geld", en: "She saves money every month" },
          { target: "Der Vertrag ist sehr wichtig", en: "The contract is very important" },
          { target: "Ich gebe zu viel Geld aus", en: "I spend too much money" },
          { target: "Mein Kollege ist sehr fleißig", en: "My colleague is very hardworking" },
          { target: "Das Auto ist zu teuer", en: "The car is too expensive" },
          { target: "Ich habe nicht genug Geld", en: "I do not have enough money" },
          { target: "Die Steuer ist sehr hoch", en: "The tax is very high" },
          { target: "Er arbeitet acht Stunden monatlich", en: "He works eight hours monthly" },
          { target: "Ich bezahle die Rechnung mit dem Konto", en: "I pay the bill with the account" },
          { target: "Dieser Job ist sehr gut", en: "This job is very good" },
          { target: "Wie viel kostet die Arbeit", en: "How much does the work cost" },
        ],
      },
      {
        id: "de-ut5",
        title: "Health & body",
        subtitle: "Talk about your body and feeling unwell",
        cefr: "B1",
        color: "#D94343",
        icon: "🩺",
        vocab: [
          { target: "der Körper", en: "the body" },
          { target: "der Kopf", en: "the head" },
          { target: "das Auge", en: "the eye" },
          { target: "die Nase", en: "the nose" },
          { target: "der Mund", en: "the mouth" },
          { target: "die Hand", en: "the hand" },
          { target: "der Arm", en: "the arm" },
          { target: "das Bein", en: "the leg" },
          { target: "der Fuß", en: "the foot" },
          { target: "der Rücken", en: "the back" },
          { target: "das Herz", en: "the heart" },
          { target: "die Gesundheit", en: "the health" },
          { target: "die Krankheit", en: "the illness" },
          { target: "der Arzt", en: "the doctor" },
          { target: "die Schmerzen", en: "the pain" },
          { target: "das Fieber", en: "the fever" },
          { target: "das Medikament", en: "the medicine" },
          { target: "wehtun", en: "to hurt" },
          { target: "sich fühlen", en: "to feel" },
          { target: "schlafen", en: "to sleep" },
          { target: "gesund", en: "healthy" },
          { target: "krank", en: "sick" },
          { target: "stark", en: "strong" },
          { target: "schwach", en: "weak" },
        ],
        sentences: [
          { target: "Mein Kopf tut sehr weh", en: "My head hurts a lot" },
          { target: "Ich fühle mich heute krank", en: "I feel sick today" },
          { target: "Der Arzt hilft mir gern", en: "The doctor gladly helps me" },
          { target: "Sie hat Fieber und Schmerzen", en: "She has a fever and pain" },
          { target: "Mein Rücken ist sehr schwach", en: "My back is very weak" },
          { target: "Ich nehme ein Medikament", en: "I take a medicine" },
          { target: "Sein Herz ist gesund und stark", en: "His heart is healthy and strong" },
          { target: "Meine Hand tut weh", en: "My hand hurts" },
          { target: "Ich muss heute viel schlafen", en: "I have to sleep a lot today" },
          { target: "Der Arzt fragt nach meiner Gesundheit", en: "The doctor asks about my health" },
          { target: "Mein Bein ist sehr stark", en: "My leg is very strong" },
          { target: "Die Krankheit ist nicht gefährlich", en: "The illness is not dangerous" },
          { target: "Ich fühle mich wieder gesund", en: "I feel healthy again" },
          { target: "Sein Fuß tut nach dem Sport weh", en: "His foot hurts after the sport" },
        ],
      },
      {
        id: "de-ut6",
        title: "Travel & directions",
        subtitle: "Find your way and plan a journey",
        cefr: "B1",
        color: "#2D7DD2",
        icon: "🧭",
        vocab: [
          { target: "die Reise", en: "the trip" },
          { target: "der Weg", en: "the way" },
          { target: "die Richtung", en: "the direction" },
          { target: "die Karte", en: "the map" },
          { target: "der Bahnhof", en: "the train station" },
          { target: "der Flughafen", en: "the airport" },
          { target: "der Zug", en: "the train" },
          { target: "das Flugzeug", en: "the airplane" },
          { target: "die Fahrkarte", en: "the ticket" },
          { target: "der Koffer", en: "the suitcase" },
          { target: "das Hotel", en: "the hotel" },
          { target: "die Ecke", en: "the corner" },
          { target: "die Kreuzung", en: "the intersection" },
          { target: "links", en: "left" },
          { target: "rechts", en: "right" },
          { target: "geradeaus", en: "straight ahead" },
          { target: "nah", en: "near" },
          { target: "weit", en: "far" },
          { target: "fahren", en: "to drive" },
          { target: "fliegen", en: "to fly" },
          { target: "ankommen", en: "to arrive" },
          { target: "abbiegen", en: "to turn" },
          { target: "suchen", en: "to look for" },
          { target: "verloren", en: "lost" },
        ],
        sentences: [
          { target: "Wo ist der Bahnhof bitte", en: "Where is the train station please" },
          { target: "Biegen Sie hier links ab", en: "Turn left here" },
          { target: "Das Hotel ist nicht weit", en: "The hotel is not far" },
          { target: "Ich suche den richtigen Weg", en: "I am looking for the right way" },
          { target: "Wir fahren mit dem Zug", en: "We travel by train" },
          { target: "Gehen Sie immer geradeaus", en: "Always go straight ahead" },
          { target: "Der Flughafen ist sehr nah", en: "The airport is very near" },
          { target: "Ich habe meine Fahrkarte verloren", en: "I have lost my ticket" },
          { target: "Das Flugzeug kommt spät an", en: "The airplane arrives late" },
          { target: "An der Kreuzung biegen wir rechts ab", en: "At the intersection we turn right" },
          { target: "Ich packe meinen Koffer für die Reise", en: "I pack my suitcase for the trip" },
          { target: "Welche Richtung ist das Hotel", en: "Which direction is the hotel" },
          { target: "Wir fliegen morgen in den Urlaub", en: "We fly on vacation tomorrow" },
          { target: "Die Karte zeigt den kurzen Weg", en: "The map shows the short way" },
        ],
      },
    ],
  },
];
