import type { CourseBlueprint } from "@/curriculum/generate";

export const spanishBlueprint: CourseBlueprint = {
  code: "es",
  name: "Spanish",
  endonym: "Español",
  flag: "🇪🇸",
  fromLanguage: "English",
  speechLocale: "es-ES",
  sections: [
    {
      id: "es-s1",
      title: "Rookie",
      subtitle: "First steps in Spanish",
      units: [
        {
          id: "es-u1",
          title: "Greetings",
          subtitle: "Say hello and goodbye",
          cefr: "A1",
          color: "#E94F37",
          icon: "👋",
          vocab: [
            { target: "hola", en: "hello" },
            { target: "adiós", en: "goodbye" },
            { target: "sí", en: "yes" },
            { target: "no", en: "no" },
            { target: "gracias", en: "thank you" },
            { target: "por favor", en: "please" },
            { target: "buenos días", en: "good morning" },
            { target: "buenas noches", en: "good night" },
            { target: "bien", en: "well" },
            { target: "mal", en: "bad" },
            { target: "yo", en: "I" },
            { target: "tú", en: "you" },
            { target: "soy", en: "I am" },
            { target: "eres", en: "you are" },
            { target: "estoy", en: "I am (state)" },
            { target: "estás", en: "you are (state)" },
            { target: "cómo", en: "how" },
            { target: "qué", en: "what" },
            { target: "me llamo", en: "my name is" },
            { target: "encantado", en: "nice to meet you" },
            { target: "señor", en: "mister" },
            { target: "señora", en: "madam" },
            { target: "hasta luego", en: "see you later" },
            { target: "perdón", en: "sorry" },
          ],
          sentences: [
            { target: "Hola cómo estás", en: "Hello, how are you" },
            { target: "Estoy bien gracias", en: "I am well, thank you" },
            { target: "Yo me llamo Ana", en: "My name is Ana" },
            { target: "¿Cómo estás tú", en: "How are you" },
            { target: "Buenos días señora", en: "Good morning, madam" },
            { target: "Adiós hasta luego", en: "Goodbye, see you later" },
            { target: "Sí por favor", en: "Yes, please" },
            { target: "No gracias", en: "No, thank you" },
            { target: "Yo estoy mal hoy", en: "I am bad today" },
            { target: "Encantado señor", en: "Nice to meet you, sir" },
            { target: "Buenas noches mamá", en: "Good night, mom" },
            { target: "¿Qué tal estás", en: "How are you doing" },
            { target: "Yo soy Ana", en: "I am Ana" },
            { target: "Tú eres bueno", en: "You are good" },
            { target: "Perdón señora", en: "Sorry, madam" },
            { target: "Gracias por favor", en: "Thanks, please" },
          ],
        },
        {
          id: "es-u2",
          title: "People & family",
          subtitle: "Family and friends",
          cefr: "A1",
          color: "#F4A259",
          icon: "👨‍👩‍👧",
          vocab: [
            { target: "la familia", en: "the family" },
            { target: "la madre", en: "the mother" },
            { target: "el padre", en: "the father" },
            { target: "la mamá", en: "the mom" },
            { target: "el papá", en: "the dad" },
            { target: "el hermano", en: "the brother" },
            { target: "la hermana", en: "the sister" },
            { target: "el hijo", en: "the son" },
            { target: "la hija", en: "the daughter" },
            { target: "el abuelo", en: "the grandfather" },
            { target: "la abuela", en: "the grandmother" },
            { target: "el amigo", en: "the friend (m)" },
            { target: "la amiga", en: "the friend (f)" },
            { target: "el hombre", en: "the man" },
            { target: "la mujer", en: "the woman" },
            { target: "el niño", en: "the boy" },
            { target: "la niña", en: "the girl" },
            { target: "el bebé", en: "the baby" },
            { target: "grande", en: "big" },
            { target: "pequeño", en: "small" },
            { target: "tengo", en: "I have" },
            { target: "tiene", en: "he/she has" },
            { target: "mi", en: "my" },
            { target: "es", en: "is" },
          ],
          sentences: [
            { target: "Mi madre es grande", en: "My mother is big" },
            { target: "Tengo un hermano pequeño", en: "I have a small brother" },
            { target: "Mi padre es alto", en: "My father is tall" },
            { target: "La niña es mi hija", en: "The girl is my daughter" },
            { target: "Mi abuela tiene un perro", en: "My grandmother has a dog" },
            { target: "El hombre es mi amigo", en: "The man is my friend" },
            { target: "Tengo una hermana grande", en: "I have a big sister" },
            { target: "Mi familia es pequeña", en: "My family is small" },
            { target: "El bebé es pequeño", en: "The baby is small" },
            { target: "Mi amiga tiene una hija", en: "My friend has a daughter" },
            { target: "El abuelo es mi padre", en: "The grandfather is my father" },
            { target: "La mujer es mi madre", en: "The woman is my mother" },
            { target: "Mi hijo es un niño", en: "My son is a boy" },
            { target: "Tengo mi familia aquí", en: "I have my family here" },
            { target: "Mi hermano tiene un amigo", en: "My brother has a friend" },
            { target: "La mamá es grande", en: "The mom is big" },
          ],
        },
        {
          id: "es-u3",
          title: "Food & drink",
          subtitle: "Eat and drink",
          cefr: "A1",
          color: "#2A9D8F",
          icon: "🍎",
          vocab: [
            { target: "el agua", en: "the water" },
            { target: "el pan", en: "the bread" },
            { target: "la leche", en: "the milk" },
            { target: "el café", en: "the coffee" },
            { target: "el té", en: "the tea" },
            { target: "la manzana", en: "the apple" },
            { target: "el huevo", en: "the egg" },
            { target: "el queso", en: "the cheese" },
            { target: "la carne", en: "the meat" },
            { target: "el pescado", en: "the fish" },
            { target: "el arroz", en: "the rice" },
            { target: "la fruta", en: "the fruit" },
            { target: "el vino", en: "the wine" },
            { target: "la sopa", en: "the soup" },
            { target: "el azúcar", en: "the sugar" },
            { target: "la sal", en: "the salt" },
            { target: "como", en: "I eat" },
            { target: "bebo", en: "I drink" },
            { target: "come", en: "he/she eats" },
            { target: "bebe", en: "he/she drinks" },
            { target: "quiero", en: "I want" },
            { target: "rico", en: "tasty" },
            { target: "mucho", en: "a lot" },
            { target: "un poco", en: "a little" },
          ],
          sentences: [
            { target: "Yo bebo agua", en: "I drink water" },
            { target: "Como pan con queso", en: "I eat bread with cheese" },
            { target: "Quiero un café por favor", en: "I want a coffee, please" },
            { target: "El pescado es rico", en: "The fish is tasty" },
            { target: "Bebo leche por la mañana", en: "I drink milk in the morning" },
            { target: "Quiero un poco de sal", en: "I want a little salt" },
            { target: "Mi madre come fruta", en: "My mother eats fruit" },
            { target: "El niño bebe leche", en: "The boy drinks milk" },
            { target: "Como arroz con carne", en: "I eat rice with meat" },
            { target: "Quiero mucho pan", en: "I want a lot of bread" },
            { target: "La sopa es muy rica", en: "The soup is very tasty" },
            { target: "Bebo té con azúcar", en: "I drink tea with sugar" },
            { target: "Quiero una manzana", en: "I want an apple" },
            { target: "Como un huevo", en: "I eat an egg" },
            { target: "El vino es rico", en: "The wine is tasty" },
            { target: "Ella bebe un poco", en: "She drinks a little" },
          ],
        },
      ],
    },
    {
      id: "es-s2",
      title: "Explorer",
      subtitle: "Get around and describe your day",
      units: [
        {
          id: "es-u4",
          title: "Around town",
          subtitle: "Places in the city",
          cefr: "A2",
          color: "#4361EE",
          icon: "🏙️",
          vocab: [
            { target: "la ciudad", en: "the city" },
            { target: "la calle", en: "the street" },
            { target: "la casa", en: "the house" },
            { target: "la tienda", en: "the shop" },
            { target: "el mercado", en: "the market" },
            { target: "el banco", en: "the bank" },
            { target: "la plaza", en: "the square" },
            { target: "el parque", en: "the park" },
            { target: "el hotel", en: "the hotel" },
            { target: "el museo", en: "the museum" },
            { target: "la escuela", en: "the school" },
            { target: "el restaurante", en: "the restaurant" },
            { target: "la estación", en: "the station" },
            { target: "el coche", en: "the car" },
            { target: "el autobús", en: "the bus" },
            { target: "voy", en: "I go" },
            { target: "va", en: "he/she goes" },
            { target: "está", en: "is (located)" },
            { target: "aquí", en: "here" },
            { target: "allí", en: "there" },
            { target: "cerca", en: "near" },
            { target: "lejos", en: "far" },
            { target: "dónde", en: "where" },
            { target: "a", en: "to" },
          ],
          sentences: [
            { target: "Voy a la tienda", en: "I go to the shop" },
            { target: "El banco está cerca", en: "The bank is near" },
            { target: "¿Dónde está el museo", en: "Where is the museum" },
            { target: "La casa está allí", en: "The house is there" },
            { target: "Voy al parque hoy", en: "I go to the park today" },
            { target: "El hotel está lejos", en: "The hotel is far" },
            { target: "Ella va al mercado", en: "She goes to the market" },
            { target: "El restaurante está aquí", en: "The restaurant is here" },
            { target: "Voy a la escuela", en: "I go to school" },
            { target: "La plaza está cerca", en: "The square is near" },
            { target: "¿Dónde está la calle", en: "Where is the street" },
            { target: "Voy en autobús", en: "I go by bus" },
            { target: "La estación está lejos", en: "The station is far" },
            { target: "Mi casa está aquí", en: "My house is here" },
            { target: "Voy a la ciudad", en: "I go to the city" },
            { target: "El parque está allí", en: "The park is there" },
          ],
        },
        {
          id: "es-u5",
          title: "Daily routine",
          subtitle: "Talk about your day",
          cefr: "A2",
          color: "#7209B7",
          icon: "⏰",
          vocab: [
            { target: "el día", en: "the day" },
            { target: "la mañana", en: "the morning" },
            { target: "la tarde", en: "the afternoon" },
            { target: "la noche", en: "the night" },
            { target: "el trabajo", en: "the work" },
            { target: "la hora", en: "the hour" },
            { target: "me levanto", en: "I get up" },
            { target: "me ducho", en: "I shower" },
            { target: "desayuno", en: "I have breakfast" },
            { target: "trabajo", en: "I work" },
            { target: "estudio", en: "I study" },
            { target: "duermo", en: "I sleep" },
            { target: "leo", en: "I read" },
            { target: "escribo", en: "I write" },
            { target: "hablo", en: "I speak" },
            { target: "camino", en: "I walk" },
            { target: "siempre", en: "always" },
            { target: "nunca", en: "never" },
            { target: "ahora", en: "now" },
            { target: "temprano", en: "early" },
            { target: "tarde", en: "late" },
            { target: "todos los días", en: "every day" },
            { target: "después", en: "after" },
            { target: "antes", en: "before" },
          ],
          sentences: [
            { target: "Me levanto temprano", en: "I get up early" },
            { target: "Desayuno por la mañana", en: "I have breakfast in the morning" },
            { target: "Trabajo todos los días", en: "I work every day" },
            { target: "Estudio por la tarde", en: "I study in the afternoon" },
            { target: "Siempre me ducho temprano", en: "I always shower early" },
            { target: "Nunca duermo tarde", en: "I never sleep late" },
            { target: "Leo un poco por la noche", en: "I read a little at night" },
            { target: "Camino al trabajo ahora", en: "I walk to work now" },
            { target: "Hablo español todos los días", en: "I speak Spanish every day" },
            { target: "Escribo después del trabajo", en: "I write after work" },
            { target: "Me levanto antes de las ocho", en: "I get up before eight" },
            { target: "Duermo por la noche", en: "I sleep at night" },
            { target: "Trabajo por la mañana", en: "I work in the morning" },
            { target: "Estudio español ahora", en: "I study Spanish now" },
            { target: "Siempre desayuno temprano", en: "I always have breakfast early" },
            { target: "Camino mucho por la tarde", en: "I walk a lot in the afternoon" },
          ],
        },
      ],
    },
  ],
};
