import type { SectionBlueprint } from "@/curriculum/generate";

export const spanishExtraSections: SectionBlueprint[] = [
  {
    id: "es-s3",
    title: "Independent",
    subtitle: "Handle work, study and travel",
    units: [
      {
        id: "es-u6",
        title: "Work & study",
        subtitle: "Talk about your career and studies",
        cefr: "B1",
        color: "#3A86FF",
        icon: "💼",
        vocab: [
          { target: "el trabajo", en: "the job" },
          { target: "la empresa", en: "the company" },
          { target: "la oficina", en: "the office" },
          { target: "el jefe", en: "the boss" },
          { target: "el compañero", en: "the colleague" },
          { target: "la reunión", en: "the meeting" },
          { target: "el sueldo", en: "the salary" },
          { target: "el horario", en: "the schedule" },
          { target: "el proyecto", en: "the project" },
          { target: "la carrera", en: "the degree" },
          { target: "la universidad", en: "the university" },
          { target: "el examen", en: "the exam" },
          { target: "el título", en: "the diploma" },
          { target: "la entrevista", en: "the interview" },
          { target: "la experiencia", en: "the experience" },
          { target: "estudié", en: "I studied" },
          { target: "trabajaba", en: "I used to work" },
          { target: "aprendí", en: "I learned" },
          { target: "conseguí", en: "I got" },
          { target: "para", en: "in order to" },
          { target: "porque", en: "because" },
          { target: "cuando", en: "when" },
          { target: "todavía", en: "still" },
          { target: "ocupado", en: "busy" },
        ],
        sentences: [
          { target: "Estudié una carrera en la universidad", en: "I studied a degree at university" },
          { target: "Trabajaba en una empresa grande", en: "I used to work at a big company" },
          { target: "Aprendí mucho en ese proyecto", en: "I learned a lot on that project" },
          { target: "Conseguí el trabajo porque tengo experiencia", en: "I got the job because I have experience" },
          { target: "Estudio para conseguir un título", en: "I study in order to get a diploma" },
          { target: "Mi jefe está muy ocupado hoy", en: "My boss is very busy today" },
          { target: "Tengo una reunión por la tarde", en: "I have a meeting in the afternoon" },
          { target: "El horario de la oficina es flexible", en: "The office schedule is flexible" },
          { target: "Aprobé el examen cuando estudié mucho", en: "I passed the exam when I studied a lot" },
          { target: "Mi compañero todavía trabaja aquí", en: "My colleague still works here" },
          { target: "Tuve una entrevista para ese proyecto", en: "I had an interview for that project" },
          { target: "El sueldo no es muy alto", en: "The salary is not very high" },
          { target: "Trabajaba mucho cuando era joven", en: "I used to work a lot when I was young" },
          { target: "Estudié para el examen toda la noche", en: "I studied for the exam all night" },
          { target: "Conseguí experiencia en esa empresa", en: "I got experience at that company" },
        ],
      },
      {
        id: "es-u7",
        title: "Travel & plans",
        subtitle: "Make plans and tell trip stories",
        cefr: "B1",
        color: "#06A77D",
        icon: "✈️",
        vocab: [
          { target: "el viaje", en: "the trip" },
          { target: "el vuelo", en: "the flight" },
          { target: "el aeropuerto", en: "the airport" },
          { target: "la maleta", en: "the suitcase" },
          { target: "el billete", en: "the ticket" },
          { target: "el pasaporte", en: "the passport" },
          { target: "la reserva", en: "the reservation" },
          { target: "la playa", en: "the beach" },
          { target: "la montaña", en: "the mountain" },
          { target: "el extranjero", en: "abroad" },
          { target: "el destino", en: "the destination" },
          { target: "las vacaciones", en: "the holidays" },
          { target: "viajé", en: "I traveled" },
          { target: "visité", en: "I visited" },
          { target: "llegué", en: "I arrived" },
          { target: "perdí", en: "I lost" },
          { target: "voy a", en: "I am going to" },
          { target: "quería", en: "I wanted" },
          { target: "por", en: "through" },
          { target: "el año pasado", en: "last year" },
          { target: "luego", en: "then" },
          { target: "barato", en: "cheap" },
          { target: "caro", en: "expensive" },
          { target: "juntos", en: "together" },
        ],
        sentences: [
          { target: "El año pasado viajé al extranjero", en: "Last year I traveled abroad" },
          { target: "Visité la playa en mis vacaciones", en: "I visited the beach on my holidays" },
          { target: "Voy a viajar a la montaña", en: "I am going to travel to the mountain" },
          { target: "Perdí mi maleta en el aeropuerto", en: "I lost my suitcase at the airport" },
          { target: "Quería un billete más barato", en: "I wanted a cheaper ticket" },
          { target: "Llegué al hotel por la noche", en: "I arrived at the hotel at night" },
          { target: "Hice la reserva por internet", en: "I made the reservation online" },
          { target: "Mi vuelo fue muy caro", en: "My flight was very expensive" },
          { target: "Viajamos juntos el año pasado", en: "We traveled together last year" },
          { target: "Necesito mi pasaporte para el viaje", en: "I need my passport for the trip" },
          { target: "Voy a visitar un nuevo destino", en: "I am going to visit a new destination" },
          { target: "Llegué temprano al aeropuerto", en: "I arrived early at the airport" },
          { target: "Quería ir a la playa contigo", en: "I wanted to go to the beach with you" },
          { target: "Luego viajé por toda la ciudad", en: "Then I traveled through the whole city" },
          { target: "Las vacaciones fueron muy baratas", en: "The holidays were very cheap" },
        ],
      },
    ],
  },
  {
    id: "es-s4",
    title: "Upper Intermediate",
    subtitle: "Share opinions and discuss society",
    units: [
      {
        id: "es-u8",
        title: "Opinions & media",
        subtitle: "React to news and express wishes",
        cefr: "B2",
        color: "#FB5607",
        icon: "📰",
        vocab: [
          { target: "la noticia", en: "the news item" },
          { target: "el periódico", en: "the newspaper" },
          { target: "la prensa", en: "the press" },
          { target: "el medio", en: "the medium" },
          { target: "la opinión", en: "the opinion" },
          { target: "la verdad", en: "the truth" },
          { target: "la mentira", en: "the lie" },
          { target: "el anuncio", en: "the advertisement" },
          { target: "la entrevista", en: "the interview" },
          { target: "el público", en: "the audience" },
          { target: "el debate", en: "the debate" },
          { target: "creo que", en: "I think that" },
          { target: "me parece", en: "it seems to me" },
          { target: "estoy de acuerdo", en: "I agree" },
          { target: "dudo que", en: "I doubt that" },
          { target: "espero que", en: "I hope that" },
          { target: "ojalá", en: "I wish" },
          { target: "sea", en: "is (subjunctive)" },
          { target: "tenga", en: "has (subjunctive)" },
          { target: "diga", en: "says (subjunctive)" },
          { target: "se dice", en: "it is said" },
          { target: "según", en: "according to" },
          { target: "aunque", en: "although" },
          { target: "verdadero", en: "true" },
        ],
        sentences: [
          { target: "Creo que la noticia es verdadera", en: "I think the news item is true" },
          { target: "Espero que la prensa diga la verdad", en: "I hope the press tells the truth" },
          { target: "Dudo que el anuncio sea honesto", en: "I doubt the advertisement is honest" },
          { target: "Me parece que el debate fue interesante", en: "It seems to me the debate was interesting" },
          { target: "Ojalá el público tenga más información", en: "I wish the audience had more information" },
          { target: "Estoy de acuerdo con tu opinión", en: "I agree with your opinion" },
          { target: "Según el periódico la verdad es otra", en: "According to the newspaper the truth is different" },
          { target: "Aunque sea difícil hay que leer la prensa", en: "Although it is hard one must read the press" },
          { target: "Se dice que el medio tiene poder", en: "It is said that the media has power" },
          { target: "Espero que la entrevista sea sincera", en: "I hope the interview is sincere" },
          { target: "No creo que eso sea una mentira", en: "I do not think that is a lie" },
          { target: "Me parece que el anuncio dice mentiras", en: "It seems to me the ad tells lies" },
          { target: "Dudo que el público crea esa noticia", en: "I doubt the audience believes that news item" },
          { target: "Ojalá la prensa tenga más libertad", en: "I wish the press had more freedom" },
          { target: "Aunque dudo de la noticia espero que sea verdad", en: "Although I doubt the news I hope it is true" },
        ],
      },
      {
        id: "es-u9",
        title: "Health & society",
        subtitle: "Discuss wellbeing and the community",
        cefr: "B2",
        color: "#8338EC",
        icon: "🩺",
        vocab: [
          { target: "la salud", en: "the health" },
          { target: "la enfermedad", en: "the illness" },
          { target: "el médico", en: "the doctor" },
          { target: "el hospital", en: "the hospital" },
          { target: "el tratamiento", en: "the treatment" },
          { target: "la sociedad", en: "the society" },
          { target: "el gobierno", en: "the government" },
          { target: "la ley", en: "the law" },
          { target: "el derecho", en: "the right" },
          { target: "la pobreza", en: "the poverty" },
          { target: "el medio ambiente", en: "the environment" },
          { target: "la población", en: "the population" },
          { target: "el problema", en: "the problem" },
          { target: "la solución", en: "the solution" },
          { target: "se necesita", en: "it is needed" },
          { target: "se debe", en: "one must" },
          { target: "es importante que", en: "it is important that" },
          { target: "haya", en: "there is (subjunctive)" },
          { target: "cuide", en: "takes care (subjunctive)" },
          { target: "mejore", en: "improves (subjunctive)" },
          { target: "para que", en: "so that" },
          { target: "sano", en: "healthy" },
          { target: "grave", en: "serious" },
          { target: "juntos", en: "together" },
        ],
        sentences: [
          { target: "Es importante que la población esté sana", en: "It is important that the population is healthy" },
          { target: "Se necesita una solución para la pobreza", en: "A solution for poverty is needed" },
          { target: "El gobierno debe proteger el medio ambiente", en: "The government must protect the environment" },
          { target: "Espero que el médico mejore su salud", en: "I hope the doctor improves his health" },
          { target: "Se debe cuidar el medio ambiente", en: "One must take care of the environment" },
          { target: "La enfermedad es muy grave", en: "The illness is very serious" },
          { target: "Es importante que haya derechos para todos", en: "It is important that there are rights for everyone" },
          { target: "La sociedad necesita una ley justa", en: "Society needs a fair law" },
          { target: "Trabajamos juntos para que mejore la salud", en: "We work together so that health improves" },
          { target: "El hospital ofrece un buen tratamiento", en: "The hospital offers a good treatment" },
          { target: "Es importante que el gobierno cuide a la población", en: "It is important that the government takes care of the population" },
          { target: "La pobreza es un problema grave", en: "Poverty is a serious problem" },
          { target: "Se necesita más salud para la sociedad", en: "More health is needed for society" },
          { target: "Espero que la ley mejore pronto", en: "I hope the law improves soon" },
          { target: "Hay que cuidar la salud para vivir sano", en: "One must care for health to live healthy" },
        ],
      },
    ],
  },
  {
    id: "es-s5",
    title: "Advanced",
    subtitle: "Reason about abstract ideas",
    units: [
      {
        id: "es-u10",
        title: "Abstract ideas",
        subtitle: "Argue with nuance and connectors",
        cefr: "C1",
        color: "#264653",
        icon: "🧠",
        vocab: [
          { target: "la idea", en: "the idea" },
          { target: "el conocimiento", en: "the knowledge" },
          { target: "la libertad", en: "the freedom" },
          { target: "la justicia", en: "the justice" },
          { target: "el poder", en: "the power" },
          { target: "la conciencia", en: "the conscience" },
          { target: "el sentido", en: "the meaning" },
          { target: "la duda", en: "the doubt" },
          { target: "la razón", en: "the reason" },
          { target: "el propósito", en: "the purpose" },
          { target: "la consecuencia", en: "the consequence" },
          { target: "el matiz", en: "the nuance" },
          { target: "la perspectiva", en: "the perspective" },
          { target: "la realidad", en: "the reality" },
          { target: "el valor", en: "the value" },
          { target: "sin embargo", en: "however" },
          { target: "por lo tanto", en: "therefore" },
          { target: "aunque", en: "even though" },
          { target: "a pesar de", en: "in spite of" },
          { target: "en cuanto a", en: "regarding" },
          { target: "supone", en: "implies" },
          { target: "implica", en: "involves" },
          { target: "profundo", en: "profound" },
          { target: "complejo", en: "complex" },
        ],
        sentences: [
          { target: "La libertad implica una gran responsabilidad", en: "Freedom involves a great responsibility" },
          { target: "Sin embargo la realidad es más compleja", en: "However reality is more complex" },
          { target: "El conocimiento supone una perspectiva profunda", en: "Knowledge implies a profound perspective" },
          { target: "Por lo tanto debemos cuestionar el poder", en: "Therefore we must question power" },
          { target: "Aunque tengo dudas defiendo esta idea", en: "Even though I have doubts I defend this idea" },
          { target: "A pesar de la duda hay un propósito claro", en: "In spite of doubt there is a clear purpose" },
          { target: "En cuanto a la justicia cada matiz importa", en: "Regarding justice every nuance matters" },
          { target: "La razón sin conciencia carece de valor", en: "Reason without conscience lacks value" },
          { target: "El poder sin justicia pierde su sentido", en: "Power without justice loses its meaning" },
          { target: "Toda idea profunda implica una consecuencia", en: "Every profound idea involves a consequence" },
          { target: "Sin embargo el matiz cambia toda la perspectiva", en: "However the nuance changes the whole perspective" },
          { target: "La libertad y la justicia son valores complejos", en: "Freedom and justice are complex values" },
          { target: "Por lo tanto el conocimiento da sentido a la realidad", en: "Therefore knowledge gives meaning to reality" },
          { target: "A pesar de su poder carece de conciencia", en: "In spite of his power he lacks conscience" },
          { target: "En cuanto a la realidad cada perspectiva tiene su razón", en: "Regarding reality every perspective has its reason" },
        ],
      },
    ],
  },
];
