import type { SectionBlueprint } from "@/curriculum/generate";

export const spanishThemeSections: SectionBlueprint[] = [
  {
    id: "es-sT1",
    title: "Themes",
    subtitle: "Broaden your vocabulary",
    units: [
      {
        id: "es-ut1",
        title: "Nature & weather",
        subtitle: "The world outside",
        cefr: "A2",
        color: "#43AA8B",
        icon: "🌳",
        vocab: [
          { target: "el árbol", en: "the tree" },
          { target: "la flor", en: "the flower" },
          { target: "la hoja", en: "the leaf" },
          { target: "la planta", en: "the plant" },
          { target: "el río", en: "the river" },
          { target: "el mar", en: "the sea" },
          { target: "la montaña", en: "the mountain" },
          { target: "el bosque", en: "the forest" },
          { target: "la playa", en: "the beach" },
          { target: "el cielo", en: "the sky" },
          { target: "el sol", en: "the sun" },
          { target: "la luna", en: "the moon" },
          { target: "la nube", en: "the cloud" },
          { target: "la lluvia", en: "the rain" },
          { target: "el viento", en: "the wind" },
          { target: "la nieve", en: "the snow" },
          { target: "el clima", en: "the weather" },
          { target: "el calor", en: "the heat" },
          { target: "el frío", en: "the cold" },
          { target: "el animal", en: "the animal" },
          { target: "el pájaro", en: "the bird" },
          { target: "hace", en: "it is (weather)" },
          { target: "llueve", en: "it rains" },
          { target: "caliente", en: "hot" },
        ],
        sentences: [
          { target: "Hoy hace mucho calor", en: "It is very hot today" },
          { target: "El árbol es muy grande", en: "The tree is very big" },
          { target: "Me gusta la playa", en: "I like the beach" },
          { target: "El sol está en el cielo", en: "The sun is in the sky" },
          { target: "Hoy llueve mucho", en: "It rains a lot today" },
          { target: "La montaña tiene mucha nieve", en: "The mountain has a lot of snow" },
          { target: "El río está cerca del bosque", en: "The river is near the forest" },
          { target: "Hay una flor en la planta", en: "There is a flower on the plant" },
          { target: "El viento es muy frío", en: "The wind is very cold" },
          { target: "La luna está en el cielo", en: "The moon is in the sky" },
          { target: "Hace frío en la montaña", en: "It is cold in the mountain" },
          { target: "El pájaro está en el árbol", en: "The bird is in the tree" },
          { target: "El agua del mar está caliente", en: "The sea water is hot" },
          { target: "Hay muchas nubes hoy", en: "There are many clouds today" },
        ],
      },
      {
        id: "es-ut2",
        title: "Emotions & feelings",
        subtitle: "How you feel",
        cefr: "A2",
        color: "#F49D37",
        icon: "😊",
        vocab: [
          { target: "feliz", en: "happy" },
          { target: "triste", en: "sad" },
          { target: "contento", en: "glad" },
          { target: "enfadado", en: "angry" },
          { target: "cansado", en: "tired" },
          { target: "nervioso", en: "nervous" },
          { target: "tranquilo", en: "calm" },
          { target: "asustado", en: "scared" },
          { target: "aburrido", en: "bored" },
          { target: "sorprendido", en: "surprised" },
          { target: "preocupado", en: "worried" },
          { target: "enamorado", en: "in love" },
          { target: "el miedo", en: "the fear" },
          { target: "la alegría", en: "the joy" },
          { target: "el amor", en: "the love" },
          { target: "la sonrisa", en: "the smile" },
          { target: "el sentimiento", en: "the feeling" },
          { target: "me siento", en: "I feel" },
          { target: "se siente", en: "he/she feels" },
          { target: "estoy", en: "I am (state)" },
          { target: "porque", en: "because" },
          { target: "cuando", en: "when" },
          { target: "muy", en: "very" },
          { target: "un poco", en: "a little" },
        ],
        sentences: [
          { target: "Hoy me siento muy feliz", en: "Today I feel very happy" },
          { target: "Estoy triste porque estoy solo", en: "I am sad because I am alone" },
          { target: "Ella se siente cansada", en: "She feels tired" },
          { target: "Estoy un poco nervioso", en: "I am a little nervous" },
          { target: "Me siento tranquilo ahora", en: "I feel calm now" },
          { target: "Él está muy contento hoy", en: "He is very glad today" },
          { target: "Estoy preocupado por mi madre", en: "I am worried about my mother" },
          { target: "Tengo mucho miedo", en: "I am very afraid" },
          { target: "Me siento feliz cuando canto", en: "I feel happy when I sing" },
          { target: "Ella está enamorada de él", en: "She is in love with him" },
          { target: "Estoy aburrido en casa", en: "I am bored at home" },
          { target: "Tu sonrisa me da alegría", en: "Your smile gives me joy" },
          { target: "Estoy enfadado porque es tarde", en: "I am angry because it is late" },
          { target: "Me siento sorprendido hoy", en: "I feel surprised today" },
        ],
      },
      {
        id: "es-ut3",
        title: "House & everyday objects",
        subtitle: "Around the home",
        cefr: "A2",
        color: "#577590",
        icon: "🏠",
        vocab: [
          { target: "la casa", en: "the house" },
          { target: "la habitación", en: "the room" },
          { target: "la cocina", en: "the kitchen" },
          { target: "el baño", en: "the bathroom" },
          { target: "el salón", en: "the living room" },
          { target: "la puerta", en: "the door" },
          { target: "la ventana", en: "the window" },
          { target: "la mesa", en: "the table" },
          { target: "la silla", en: "the chair" },
          { target: "la cama", en: "the bed" },
          { target: "el sofá", en: "the sofa" },
          { target: "el armario", en: "the wardrobe" },
          { target: "la lámpara", en: "the lamp" },
          { target: "el espejo", en: "the mirror" },
          { target: "el reloj", en: "the clock" },
          { target: "el plato", en: "the plate" },
          { target: "el vaso", en: "the glass" },
          { target: "la llave", en: "the key" },
          { target: "el libro", en: "the book" },
          { target: "el teléfono", en: "the telephone" },
          { target: "hay", en: "there is" },
          { target: "en", en: "in" },
          { target: "sobre", en: "on" },
          { target: "limpio", en: "clean" },
        ],
        sentences: [
          { target: "El libro está sobre la mesa", en: "The book is on the table" },
          { target: "Hay una cama en la habitación", en: "There is a bed in the room" },
          { target: "La cocina está muy limpia", en: "The kitchen is very clean" },
          { target: "La llave está en la puerta", en: "The key is in the door" },
          { target: "Hay una silla en el salón", en: "There is a chair in the living room" },
          { target: "El espejo está sobre el armario", en: "The mirror is on the wardrobe" },
          { target: "Mi teléfono está en la cama", en: "My telephone is on the bed" },
          { target: "Hay un vaso sobre la mesa", en: "There is a glass on the table" },
          { target: "La ventana de la cocina es grande", en: "The kitchen window is big" },
          { target: "El reloj está en la habitación", en: "The clock is in the room" },
          { target: "Hay una lámpara sobre la mesa", en: "There is a lamp on the table" },
          { target: "El baño está muy limpio", en: "The bathroom is very clean" },
          { target: "El sofá está en el salón", en: "The sofa is in the living room" },
          { target: "Hay platos en la cocina", en: "There are plates in the kitchen" },
        ],
      },
    ],
  },
  {
    id: "es-sT2",
    title: "Real life",
    subtitle: "Talk about the wider world",
    units: [
      {
        id: "es-ut4",
        title: "Work & money",
        subtitle: "Jobs and earning",
        cefr: "B1",
        color: "#1B998B",
        icon: "💼",
        vocab: [
          { target: "el trabajo", en: "the work" },
          { target: "la empresa", en: "the company" },
          { target: "la oficina", en: "the office" },
          { target: "el jefe", en: "the boss" },
          { target: "el empleado", en: "the employee" },
          { target: "la reunión", en: "the meeting" },
          { target: "el sueldo", en: "the salary" },
          { target: "el dinero", en: "the money" },
          { target: "el banco", en: "the bank" },
          { target: "el precio", en: "the price" },
          { target: "la cuenta", en: "the account" },
          { target: "el contrato", en: "the contract" },
          { target: "el proyecto", en: "the project" },
          { target: "el cliente", en: "the client" },
          { target: "la tarea", en: "the task" },
          { target: "ganar", en: "to earn" },
          { target: "pagar", en: "to pay" },
          { target: "gastar", en: "to spend" },
          { target: "ahorrar", en: "to save" },
          { target: "trabajar", en: "to work" },
          { target: "ocupado", en: "busy" },
          { target: "caro", en: "expensive" },
          { target: "barato", en: "cheap" },
          { target: "necesito", en: "I need" },
        ],
        sentences: [
          { target: "Trabajo en una empresa grande", en: "I work in a big company" },
          { target: "Mi jefe está muy ocupado hoy", en: "My boss is very busy today" },
          { target: "Necesito ahorrar más dinero", en: "I need to save more money" },
          { target: "El sueldo no es muy alto", en: "The salary is not very high" },
          { target: "Tengo una reunión en la oficina", en: "I have a meeting at the office" },
          { target: "El cliente quiere pagar ahora", en: "The client wants to pay now" },
          { target: "Este proyecto es muy caro", en: "This project is very expensive" },
          { target: "Quiero ganar más dinero", en: "I want to earn more money" },
          { target: "El empleado trabaja todos los días", en: "The employee works every day" },
          { target: "Necesito firmar el contrato", en: "I need to sign the contract" },
          { target: "El precio es muy barato", en: "The price is very cheap" },
          { target: "Tengo mucho dinero en el banco", en: "I have a lot of money in the bank" },
          { target: "No quiero gastar mucho dinero", en: "I do not want to spend a lot of money" },
          { target: "Tengo una tarea para el cliente", en: "I have a task for the client" },
        ],
      },
      {
        id: "es-ut5",
        title: "Health & body",
        subtitle: "Body and well-being",
        cefr: "B1",
        color: "#E63946",
        icon: "🩺",
        vocab: [
          { target: "el cuerpo", en: "the body" },
          { target: "la cabeza", en: "the head" },
          { target: "el ojo", en: "the eye" },
          { target: "la boca", en: "the mouth" },
          { target: "la mano", en: "the hand" },
          { target: "el brazo", en: "the arm" },
          { target: "la pierna", en: "the leg" },
          { target: "el pie", en: "the foot" },
          { target: "el corazón", en: "the heart" },
          { target: "el estómago", en: "the stomach" },
          { target: "la espalda", en: "the back" },
          { target: "la salud", en: "the health" },
          { target: "el médico", en: "the doctor" },
          { target: "el hospital", en: "the hospital" },
          { target: "la medicina", en: "the medicine" },
          { target: "el dolor", en: "the pain" },
          { target: "la fiebre", en: "the fever" },
          { target: "enfermo", en: "sick" },
          { target: "sano", en: "healthy" },
          { target: "me duele", en: "it hurts me" },
          { target: "necesito", en: "I need" },
          { target: "descansar", en: "to rest" },
          { target: "el dentista", en: "the dentist" },
          { target: "la cita", en: "the appointment" },
        ],
        sentences: [
          { target: "Me duele mucho la cabeza", en: "My head hurts a lot" },
          { target: "Necesito ir al médico hoy", en: "I need to go to the doctor today" },
          { target: "Estoy enfermo y tengo fiebre", en: "I am sick and I have a fever" },
          { target: "El médico está en el hospital", en: "The doctor is at the hospital" },
          { target: "Me duele el estómago", en: "My stomach hurts" },
          { target: "Necesito descansar un poco", en: "I need to rest a little" },
          { target: "Tengo una cita con el dentista", en: "I have an appointment with the dentist" },
          { target: "Mi salud es muy buena", en: "My health is very good" },
          { target: "Me duele la espalda hoy", en: "My back hurts today" },
          { target: "Necesito tomar la medicina", en: "I need to take the medicine" },
          { target: "Tengo un dolor en el brazo", en: "I have a pain in the arm" },
          { target: "Estoy sano porque como bien", en: "I am healthy because I eat well" },
          { target: "Me duele el pie cuando camino", en: "My foot hurts when I walk" },
          { target: "El corazón es parte del cuerpo", en: "The heart is part of the body" },
        ],
      },
      {
        id: "es-ut6",
        title: "Travel & directions",
        subtitle: "Finding your way",
        cefr: "B1",
        color: "#2D6A4F",
        icon: "🧭",
        vocab: [
          { target: "el viaje", en: "the trip" },
          { target: "el avión", en: "the plane" },
          { target: "el tren", en: "the train" },
          { target: "el billete", en: "the ticket" },
          { target: "la maleta", en: "the suitcase" },
          { target: "el pasaporte", en: "the passport" },
          { target: "el aeropuerto", en: "the airport" },
          { target: "el mapa", en: "the map" },
          { target: "el camino", en: "the way" },
          { target: "la izquierda", en: "the left" },
          { target: "la derecha", en: "the right" },
          { target: "recto", en: "straight" },
          { target: "la esquina", en: "the corner" },
          { target: "el cruce", en: "the crossing" },
          { target: "la dirección", en: "the direction" },
          { target: "lejos", en: "far" },
          { target: "cerca", en: "near" },
          { target: "perdido", en: "lost" },
          { target: "viajar", en: "to travel" },
          { target: "llegar", en: "to arrive" },
          { target: "girar", en: "to turn" },
          { target: "seguir", en: "to follow" },
          { target: "dónde", en: "where" },
          { target: "cómo", en: "how" },
        ],
        sentences: [
          { target: "Quiero viajar en tren", en: "I want to travel by train" },
          { target: "El avión llega muy tarde", en: "The plane arrives very late" },
          { target: "Necesito mi pasaporte y el billete", en: "I need my passport and the ticket" },
          { target: "Gira a la derecha en la esquina", en: "Turn right at the corner" },
          { target: "Sigue recto hasta el cruce", en: "Go straight to the crossing" },
          { target: "Estoy perdido y necesito un mapa", en: "I am lost and I need a map" },
          { target: "El aeropuerto está muy lejos", en: "The airport is very far" },
          { target: "¿Cómo llego al aeropuerto", en: "How do I get to the airport" },
          { target: "El tren llega a la estación", en: "The train arrives at the station" },
          { target: "Gira a la izquierda aquí", en: "Turn left here" },
          { target: "¿Dónde está mi maleta", en: "Where is my suitcase" },
          { target: "El hotel está muy cerca", en: "The hotel is very near" },
          { target: "Me gusta viajar en avión", en: "I like to travel by plane" },
          { target: "Sigue el camino a la derecha", en: "Follow the way to the right" },
        ],
      },
    ],
  },
];
