import type { CourseBlueprint } from "@/curriculum/generate";

export const frenchBlueprint: CourseBlueprint = {
  code: "fr",
  name: "French",
  endonym: "Français",
  flag: "🇫🇷",
  fromLanguage: "English",
  speechLocale: "fr-FR",
  sections: [
    {
      id: "fr-s1",
      title: "Rookie",
      subtitle: "First words and everyday basics",
      units: [
        {
          id: "fr-u1",
          title: "Greetings & basics",
          subtitle: "Say hello and introduce yourself",
          cefr: "A1",
          color: "#58CC02",
          icon: "👋",
          vocab: [
            { target: "bonjour", en: "hello" },
            { target: "salut", en: "hi" },
            { target: "oui", en: "yes" },
            { target: "non", en: "no" },
            { target: "merci", en: "thanks" },
            { target: "au revoir", en: "goodbye" },
            { target: "bonne nuit", en: "good night" },
            { target: "bonsoir", en: "good evening" },
            { target: "bienvenue", en: "welcome" },
            { target: "pardon", en: "excuse me" },
            { target: "je", en: "I" },
            { target: "tu", en: "you" },
            { target: "il", en: "he" },
            { target: "elle", en: "she" },
            { target: "être", en: "to be" },
            { target: "nom", en: "name" },
            { target: "ami", en: "friend" },
            { target: "et", en: "and" },
            { target: "très", en: "very" },
            { target: "bien", en: "well" },
            { target: "aussi", en: "also" },
            { target: "madame", en: "madam" },
            { target: "monsieur", en: "sir" },
            { target: "bon", en: "good" },
          ],
          sentences: [
            { target: "bonjour comment ça va", en: "hello, how are you" },
            { target: "je m'appelle Anna", en: "my name is Anna" },
            { target: "comment tu t'appelles", en: "what is your name" },
            { target: "bonjour madame", en: "hello, madam" },
            { target: "merci beaucoup", en: "thank you very much" },
            { target: "oui merci", en: "yes, thanks" },
            { target: "non merci", en: "no, thanks" },
            { target: "au revoir et bonne nuit", en: "goodbye and good night" },
            { target: "tu es mon ami", en: "you are my friend" },
            { target: "elle est très gentille", en: "she is very kind" },
            { target: "il s'appelle Marc", en: "his name is Marc" },
            { target: "bonsoir monsieur", en: "good evening, sir" },
          ],
        },
        {
          id: "fr-u2",
          title: "Food & drink",
          subtitle: "Order and describe meals",
          cefr: "A1",
          color: "#FF9600",
          icon: "🍎",
          vocab: [
            { target: "eau", en: "water" },
            { target: "pain", en: "bread" },
            { target: "pomme", en: "apple" },
            { target: "lait", en: "milk" },
            { target: "café", en: "coffee" },
            { target: "thé", en: "tea" },
            { target: "œuf", en: "egg" },
            { target: "fromage", en: "cheese" },
            { target: "viande", en: "meat" },
            { target: "poisson", en: "fish" },
            { target: "riz", en: "rice" },
            { target: "sucre", en: "sugar" },
            { target: "sel", en: "salt" },
            { target: "fruit", en: "fruit" },
            { target: "légume", en: "vegetable" },
            { target: "manger", en: "to eat" },
            { target: "boire", en: "to drink" },
            { target: "vouloir", en: "to want" },
            { target: "vin", en: "wine" },
            { target: "froid", en: "cold" },
            { target: "chaud", en: "hot" },
            { target: "petit déjeuner", en: "breakfast" },
          ],
          sentences: [
            { target: "je bois de l'eau", en: "I drink water" },
            { target: "nous mangeons du pain", en: "we eat bread" },
            { target: "le café est chaud", en: "the coffee is hot" },
            { target: "je veux une pomme", en: "I want an apple" },
            { target: "le lait est froid", en: "the milk is cold" },
            { target: "tu manges du poisson", en: "you eat fish" },
            { target: "je veux boire du thé", en: "I want to drink tea" },
            { target: "le fromage est très bon", en: "the cheese is very good" },
            { target: "j'ai faim", en: "I am hungry" },
            { target: "la viande est chaude", en: "the meat is hot" },
            { target: "je veux du pain et du fromage", en: "I want bread and cheese" },
            { target: "le vin est bon", en: "the wine is good" },
          ],
        },
      ],
    },
  ],
};
