import type { SectionBlueprint } from "@/curriculum/generate";

// Additional French units (hand-authored A1–A2, verified). Merged onto the base
// course in src/curriculum/index.ts.
export const frenchExtraSections: SectionBlueprint[] = [
  {
    id: "fr-s2",
    title: "Explorer",
    subtitle: "People, numbers and daily life",
    units: [
      {
        id: "fr-u3",
        title: "Family & people",
        subtitle: "Talk about family and friends",
        cefr: "A1",
        color: "#1CB0F6",
        icon: "👨‍👩‍👧",
        vocab: [
          { target: "famille", en: "family" },
          { target: "mère", en: "mother" },
          { target: "père", en: "father" },
          { target: "parents", en: "parents" },
          { target: "frère", en: "brother" },
          { target: "sœur", en: "sister" },
          { target: "fils", en: "son" },
          { target: "fille", en: "daughter" },
          { target: "enfant", en: "child" },
          { target: "grand-mère", en: "grandmother" },
          { target: "grand-père", en: "grandfather" },
          { target: "mari", en: "husband" },
          { target: "bébé", en: "baby" },
          { target: "oncle", en: "uncle" },
          { target: "tante", en: "aunt" },
          { target: "avoir", en: "to have" },
          { target: "aimer", en: "to love" },
          { target: "petit", en: "small" },
          { target: "grand", en: "big" },
          { target: "vieux", en: "old" },
          { target: "jeune", en: "young" },
          { target: "mon", en: "my" },
        ],
        sentences: [
          { target: "j'ai un frère", en: "I have a brother" },
          { target: "ma mère est jeune", en: "my mother is young" },
          { target: "mon père aime l'enfant", en: "my father loves the child" },
          { target: "nous avons deux enfants", en: "we have two children" },
          { target: "ma sœur est petite", en: "my sister is small" },
          { target: "mon frère est grand", en: "my brother is big" },
          { target: "j'aime ma famille", en: "I love my family" },
          { target: "mon mari est vieux", en: "my husband is old" },
          { target: "la grand-mère est vieille", en: "the grandmother is old" },
          { target: "nous aimons le bébé", en: "we love the baby" },
          { target: "mon oncle est jeune", en: "my uncle is young" },
          { target: "ma tante aime les enfants", en: "my aunt loves the children" },
        ],
      },
      {
        id: "fr-u4",
        title: "Numbers & time",
        subtitle: "Count and tell the time",
        cefr: "A2",
        color: "#CE82FF",
        icon: "🕐",
        vocab: [
          { target: "un", en: "one" },
          { target: "deux", en: "two" },
          { target: "trois", en: "three" },
          { target: "quatre", en: "four" },
          { target: "cinq", en: "five" },
          { target: "six", en: "six" },
          { target: "sept", en: "seven" },
          { target: "huit", en: "eight" },
          { target: "neuf", en: "nine" },
          { target: "dix", en: "ten" },
          { target: "heure", en: "hour" },
          { target: "minute", en: "minute" },
          { target: "jour", en: "day" },
          { target: "semaine", en: "week" },
          { target: "mois", en: "month" },
          { target: "année", en: "year" },
          { target: "aujourd'hui", en: "today" },
          { target: "demain", en: "tomorrow" },
          { target: "maintenant", en: "now" },
          { target: "tard", en: "late" },
          { target: "tôt", en: "early" },
          { target: "matin", en: "morning" },
        ],
        sentences: [
          { target: "il est trois heures", en: "it is three o'clock" },
          { target: "quelle heure est-il", en: "what time is it" },
          { target: "aujourd'hui est un bon jour", en: "today is a good day" },
          { target: "il est très tard", en: "it is very late" },
          { target: "demain est un nouveau jour", en: "tomorrow is a new day" },
          { target: "je n'ai pas le temps", en: "I don't have time" },
          { target: "il est tôt maintenant", en: "it is early now" },
          { target: "une semaine a sept jours", en: "a week has seven days" },
          { target: "l'année a douze mois", en: "the year has twelve months" },
          { target: "j'ai deux heures", en: "I have two hours" },
          { target: "nous avons cinq jours", en: "we have five days" },
          { target: "le matin je travaille", en: "in the morning I work" },
        ],
      },
    ],
  },
];
