import type { SectionBlueprint } from "@/curriculum/generate";

// Themed French units (hand-authored A2–B1, verified). Merged onto the base
// course in src/curriculum/index.ts to give the course real depth.
export const frenchThemeSections: SectionBlueprint[] = [
  {
    id: "fr-s3",
    title: "Globetrotter",
    subtitle: "Get around, shop, travel and chat",
    units: [
      {
        id: "fr-u5",
        title: "Around town",
        subtitle: "Find your way in the city",
        cefr: "A2",
        color: "#FF4B4B",
        icon: "🏙️",
        vocab: [
          { target: "ville", en: "city" },
          { target: "rue", en: "street" },
          { target: "gare", en: "train station" },
          { target: "marché", en: "market" },
          { target: "banque", en: "bank" },
          { target: "magasin", en: "shop" },
          { target: "restaurant", en: "restaurant" },
          { target: "hôtel", en: "hotel" },
          { target: "église", en: "church" },
          { target: "parc", en: "park" },
          { target: "voiture", en: "car" },
          { target: "bus", en: "bus" },
          { target: "train", en: "train" },
          { target: "gauche", en: "left" },
          { target: "droite", en: "right" },
          { target: "ici", en: "here" },
          { target: "là", en: "there" },
          { target: "où", en: "where" },
          { target: "aller", en: "to go" },
          { target: "trouver", en: "to find" },
          { target: "près", en: "near" },
          { target: "loin", en: "far" },
        ],
        sentences: [
          { target: "où est la gare", en: "where is the train station" },
          { target: "je vais en ville", en: "I go into town" },
          { target: "l'hôtel est à gauche", en: "the hotel is on the left" },
          { target: "nous allons en bus", en: "we go by bus" },
          { target: "le parc est très loin", en: "the park is very far" },
          { target: "le restaurant est là", en: "the restaurant is there" },
          { target: "je ne trouve pas la rue", en: "I can't find the street" },
          { target: "le marché est près", en: "the market is near" },
          { target: "où est la banque", en: "where is the bank" },
          { target: "la voiture est ici", en: "the car is here" },
          { target: "l'église est très vieille", en: "the church is very old" },
          { target: "je vais au marché", en: "I go to the market" },
        ],
      },
      {
        id: "fr-u6",
        title: "Daily life",
        subtitle: "Describe your everyday routine",
        cefr: "A2",
        color: "#2B70C9",
        icon: "⏰",
        vocab: [
          { target: "se réveiller", en: "to wake up" },
          { target: "dormir", en: "to sleep" },
          { target: "travailler", en: "to work" },
          { target: "cuisiner", en: "to cook" },
          { target: "nettoyer", en: "to clean" },
          { target: "lire", en: "to read" },
          { target: "écrire", en: "to write" },
          { target: "jouer", en: "to play" },
          { target: "étudier", en: "to study" },
          { target: "maison", en: "house" },
          { target: "école", en: "school" },
          { target: "travail", en: "work" },
          { target: "toujours", en: "always" },
          { target: "souvent", en: "often" },
          { target: "parfois", en: "sometimes" },
          { target: "jamais", en: "never" },
          { target: "fatigué", en: "tired" },
          { target: "soir", en: "evening" },
          { target: "nuit", en: "night" },
          { target: "matin", en: "morning" },
        ],
        sentences: [
          { target: "je me réveille tôt", en: "I wake up early" },
          { target: "nous travaillons souvent", en: "we work often" },
          { target: "je cuisine le soir", en: "I cook in the evening" },
          { target: "tu vas à l'école", en: "you go to school" },
          { target: "je suis très fatigué", en: "I am very tired" },
          { target: "elle étudie toujours", en: "she always studies" },
          { target: "je lis le soir", en: "I read in the evening" },
          { target: "parfois je joue", en: "sometimes I play" },
          { target: "nous nettoyons la maison", en: "we clean the house" },
          { target: "tu ne dors jamais tôt", en: "you never sleep early" },
          { target: "le matin je travaille", en: "in the morning I work" },
          { target: "j'écris souvent", en: "I write often" },
        ],
      },
      {
        id: "fr-u7",
        title: "Shopping & money",
        subtitle: "Buy things and talk prices",
        cefr: "A2",
        color: "#FF9600",
        icon: "🛍️",
        vocab: [
          { target: "argent", en: "money" },
          { target: "prix", en: "price" },
          { target: "cher", en: "expensive" },
          { target: "acheter", en: "to buy" },
          { target: "vendre", en: "to sell" },
          { target: "payer", en: "to pay" },
          { target: "magasin", en: "shop" },
          { target: "vêtements", en: "clothes" },
          { target: "chaussures", en: "shoes" },
          { target: "sac", en: "bag" },
          { target: "carte", en: "card" },
          { target: "espèces", en: "cash" },
          { target: "combien", en: "how much" },
          { target: "nouveau", en: "new" },
          { target: "besoin", en: "need" },
          { target: "ouvert", en: "open" },
          { target: "fermé", en: "closed" },
          { target: "vouloir", en: "to want" },
          { target: "beaucoup", en: "a lot" },
          { target: "petit", en: "small" },
        ],
        sentences: [
          { target: "combien ça coûte", en: "how much does it cost" },
          { target: "c'est trop cher", en: "it's too expensive" },
          { target: "je veux acheter un sac", en: "I want to buy a bag" },
          { target: "je paie par carte", en: "I pay by card" },
          { target: "le magasin est fermé", en: "the shop is closed" },
          { target: "ces chaussures sont chères", en: "these shoes are expensive" },
          { target: "j'ai besoin de vêtements", en: "I need clothes" },
          { target: "avez-vous des espèces", en: "do you have cash" },
          { target: "le prix est bon", en: "the price is good" },
          { target: "je voudrais payer", en: "I would like to pay" },
          { target: "le magasin est ouvert", en: "the shop is open" },
          { target: "j'ai besoin de chaussures", en: "I need shoes" },
        ],
      },
      {
        id: "fr-u8",
        title: "Travel & transport",
        subtitle: "Trips, tickets and holidays",
        cefr: "B1",
        color: "#1CB0F6",
        icon: "✈️",
        vocab: [
          { target: "voyage", en: "trip" },
          { target: "avion", en: "plane" },
          { target: "aéroport", en: "airport" },
          { target: "billet", en: "ticket" },
          { target: "valise", en: "suitcase" },
          { target: "passeport", en: "passport" },
          { target: "vacances", en: "holidays" },
          { target: "mer", en: "sea" },
          { target: "plage", en: "beach" },
          { target: "montagne", en: "mountain" },
          { target: "pays", en: "country" },
          { target: "partir", en: "to leave" },
          { target: "arriver", en: "to arrive" },
          { target: "voyager", en: "to travel" },
          { target: "réserver", en: "to book" },
          { target: "chambre", en: "room" },
          { target: "clé", en: "key" },
          { target: "carte", en: "map" },
          { target: "demain", en: "tomorrow" },
          { target: "beau", en: "beautiful" },
        ],
        sentences: [
          { target: "je voyage en avion", en: "I travel by plane" },
          { target: "où est l'aéroport", en: "where is the airport" },
          { target: "j'ai mon billet", en: "I have my ticket" },
          { target: "nous partons demain", en: "we leave tomorrow" },
          { target: "je vais à la plage", en: "I go to the beach" },
          { target: "la chambre est réservée", en: "the room is booked" },
          { target: "j'aime les vacances", en: "I love holidays" },
          { target: "la mer est très belle", en: "the sea is very beautiful" },
          { target: "où est mon passeport", en: "where is my passport" },
          { target: "nous arrivons à la gare", en: "we arrive at the station" },
          { target: "la montagne est loin", en: "the mountain is far" },
          { target: "je voyage chaque année", en: "I travel every year" },
        ],
      },
      {
        id: "fr-u9",
        title: "Weather & nature",
        subtitle: "Talk about the weather and the world",
        cefr: "A2",
        color: "#58CC02",
        icon: "🌦️",
        vocab: [
          { target: "temps", en: "weather" },
          { target: "soleil", en: "sun" },
          { target: "pluie", en: "rain" },
          { target: "neige", en: "snow" },
          { target: "vent", en: "wind" },
          { target: "nuage", en: "cloud" },
          { target: "chaud", en: "hot" },
          { target: "froid", en: "cold" },
          { target: "ciel", en: "sky" },
          { target: "arbre", en: "tree" },
          { target: "fleur", en: "flower" },
          { target: "feu", en: "fire" },
          { target: "animal", en: "animal" },
          { target: "chien", en: "dog" },
          { target: "chat", en: "cat" },
          { target: "oiseau", en: "bird" },
          { target: "bleu", en: "blue" },
          { target: "beau", en: "nice" },
          { target: "hiver", en: "winter" },
          { target: "été", en: "summer" },
        ],
        sentences: [
          { target: "il fait beau aujourd'hui", en: "the weather is nice today" },
          { target: "il pleut beaucoup", en: "it rains a lot" },
          { target: "le soleil est chaud", en: "the sun is hot" },
          { target: "il fait froid en hiver", en: "it is cold in winter" },
          { target: "le ciel est bleu", en: "the sky is blue" },
          { target: "j'aime les animaux", en: "I love animals" },
          { target: "le chien est petit", en: "the dog is small" },
          { target: "il neige aujourd'hui", en: "it is snowing today" },
          { target: "la fleur est belle", en: "the flower is beautiful" },
          { target: "le chat dort", en: "the cat sleeps" },
          { target: "l'arbre est très grand", en: "the tree is very big" },
          { target: "j'aime l'été", en: "I love summer" },
        ],
      },
    ],
  },
];
