import type { CourseBlueprint } from "@/curriculum/generate";

export const icelandicBlueprint: CourseBlueprint = {
  code: "is",
  name: "Icelandic",
  endonym: "Íslenska",
  flag: "🇮🇸",
  fromLanguage: "English",
  speechLocale: "is-IS",
  sections: [
    {
      id: "is-s1",
      title: "Rookie",
      subtitle: "First words and everyday basics",
      units: [
        {
          id: "is-u1",
          title: "Greetings & basics",
          subtitle: "Say hello and introduce yourself",
          cefr: "A1",
          color: "#58CC02",
          icon: "👋",
          vocab: [
            { target: "halló", en: "hello" },
            { target: "já", en: "yes" },
            { target: "nei", en: "no" },
            { target: "takk", en: "thanks" },
            { target: "bless", en: "bye" },
            { target: "ég", en: "I" },
            { target: "þú", en: "you" },
            { target: "góðan dag", en: "good day" },
            { target: "góða nótt", en: "good night" },
            { target: "gott kvöld", en: "good evening" },
            { target: "velkominn", en: "welcome" },
            { target: "fyrirgefðu", en: "excuse me" },
            { target: "góður", en: "good" },
            { target: "hvað", en: "what" },
            { target: "hvernig", en: "how" },
            { target: "heita", en: "to be called" },
            { target: "vera", en: "to be" },
            { target: "nafn", en: "name" },
            { target: "og", en: "and" },
            { target: "mjög", en: "very" },
            { target: "líka", en: "also" },
            { target: "vinur", en: "friend" },
            { target: "kona", en: "woman" },
            { target: "maður", en: "man" },
          ],
          sentences: [
            { target: "halló hvernig hefurðu það", en: "hello, how are you" },
            { target: "ég heiti Anna", en: "my name is Anna" },
            { target: "hvað heitir þú", en: "what is your name" },
            { target: "góðan dag", en: "good day" },
            { target: "takk fyrir", en: "thank you" },
            { target: "já takk", en: "yes please" },
            { target: "nei takk", en: "no thanks" },
            { target: "góða nótt", en: "good night" },
            { target: "þú ert vinur minn", en: "you are my friend" },
            { target: "ég er góður", en: "I am good" },
            { target: "konan heitir Eva", en: "the woman is called Eva" },
            { target: "maðurinn er mjög góður", en: "the man is very good" },
            { target: "bless og góða nótt", en: "bye and good night" },
            { target: "velkominn vinur", en: "welcome, friend" },
          ],
        },
        {
          id: "is-u2",
          title: "People & family",
          subtitle: "Talk about family and friends",
          cefr: "A1",
          color: "#1CB0F6",
          icon: "👨‍👩‍👧",
          vocab: [
            { target: "fjölskylda", en: "family" },
            { target: "mamma", en: "mom" },
            { target: "pabbi", en: "dad" },
            { target: "móðir", en: "mother" },
            { target: "faðir", en: "father" },
            { target: "foreldrar", en: "parents" },
            { target: "bróðir", en: "brother" },
            { target: "systir", en: "sister" },
            { target: "barn", en: "child" },
            { target: "sonur", en: "son" },
            { target: "dóttir", en: "daughter" },
            { target: "amma", en: "grandmother" },
            { target: "afi", en: "grandfather" },
            { target: "strákur", en: "boy" },
            { target: "stelpa", en: "girl" },
            { target: "eiga", en: "to have" },
            { target: "elska", en: "to love" },
            { target: "lítill", en: "small" },
            { target: "stór", en: "big" },
            { target: "gamall", en: "old" },
            { target: "ungur", en: "young" },
            { target: "minn", en: "my" },
            { target: "við", en: "we" },
            { target: "tveir", en: "two" },
          ],
          sentences: [
            { target: "ég á bróður", en: "I have a brother" },
            { target: "mamma er mjög ung", en: "mom is very young" },
            { target: "pabbi elskar barnið", en: "dad loves the child" },
            { target: "við eigum tvö börn", en: "we have two children" },
            { target: "bróðir minn er stór", en: "my brother is big" },
            { target: "systir mín er lítil", en: "my sister is small" },
            { target: "foreldrar mínir eru gamlir", en: "my parents are old" },
            { target: "strákurinn elskar fjölskylduna", en: "the boy loves the family" },
            { target: "stelpan er dóttir mín", en: "the girl is my daughter" },
            { target: "sonur þinn er mjög ungur", en: "your son is very young" },
            { target: "við elskum ömmu", en: "we love grandmother" },
            { target: "afi er gamall", en: "grandfather is old" },
            { target: "ég elska fjölskyldu mína", en: "I love my family" },
            { target: "pabbi er líka stór", en: "dad is also big" },
          ],
        },
        {
          id: "is-u3",
          title: "Food & drink",
          subtitle: "Order and describe meals",
          cefr: "A1",
          color: "#FF9600",
          icon: "🍎",
          vocab: [
            { target: "vatn", en: "water" },
            { target: "brauð", en: "bread" },
            { target: "epli", en: "apple" },
            { target: "mjólk", en: "milk" },
            { target: "kaffi", en: "coffee" },
            { target: "te", en: "tea" },
            { target: "egg", en: "egg" },
            { target: "ostur", en: "cheese" },
            { target: "kjöt", en: "meat" },
            { target: "fiskur", en: "fish" },
            { target: "súpa", en: "soup" },
            { target: "hrísgrjón", en: "rice" },
            { target: "sykur", en: "sugar" },
            { target: "salt", en: "salt" },
            { target: "ávöxtur", en: "fruit" },
            { target: "grænmeti", en: "vegetables" },
            { target: "borða", en: "to eat" },
            { target: "drekka", en: "to drink" },
            { target: "vilja", en: "to want" },
            { target: "svangur", en: "hungry" },
            { target: "góður", en: "tasty" },
            { target: "kaldur", en: "cold" },
            { target: "heitur", en: "hot" },
            { target: "morgunmatur", en: "breakfast" },
          ],
          sentences: [
            { target: "ég drekk vatn", en: "I drink water" },
            { target: "við borðum brauð", en: "we eat bread" },
            { target: "kaffið er heitt", en: "the coffee is hot" },
            { target: "ég vil epli", en: "I want an apple" },
            { target: "morgunmaturinn er góður", en: "the breakfast is tasty" },
            { target: "mjólkin er köld", en: "the milk is cold" },
            { target: "þú borðar fisk", en: "you eat fish" },
            { target: "ég vil drekka te", en: "I want to drink tea" },
            { target: "við borðum ávöxt og grænmeti", en: "we eat fruit and vegetables" },
            { target: "osturinn er mjög góður", en: "the cheese is very tasty" },
            { target: "ég er svangur", en: "I am hungry" },
            { target: "kjötið er heitt", en: "the meat is hot" },
            { target: "súpan er köld", en: "the soup is cold" },
            { target: "ég vil brauð og ost", en: "I want bread and cheese" },
          ],
        },
      ],
    },
    {
      id: "is-s2",
      title: "Explorer",
      subtitle: "Get around and handle daily life",
      units: [
        {
          id: "is-u4",
          title: "Around town",
          subtitle: "Find your way in the city",
          cefr: "A2",
          color: "#FF4B4B",
          icon: "🏙️",
          vocab: [
            { target: "borg", en: "city" },
            { target: "gata", en: "street" },
            { target: "lestarstöð", en: "train station" },
            { target: "markaður", en: "market" },
            { target: "banki", en: "bank" },
            { target: "búð", en: "shop" },
            { target: "veitingastaður", en: "restaurant" },
            { target: "hótel", en: "hotel" },
            { target: "kirkja", en: "church" },
            { target: "garður", en: "park" },
            { target: "bíll", en: "car" },
            { target: "strætó", en: "bus" },
            { target: "lest", en: "train" },
            { target: "vinstri", en: "left" },
            { target: "hægri", en: "right" },
            { target: "beint áfram", en: "straight ahead" },
            { target: "hér", en: "here" },
            { target: "þar", en: "there" },
            { target: "hvar", en: "where" },
            { target: "fara", en: "to go" },
            { target: "keyra", en: "to drive" },
            { target: "finna", en: "to find" },
            { target: "nálægt", en: "near" },
            { target: "langt", en: "far" },
          ],
          sentences: [
            { target: "hvar er lestarstöðin", en: "where is the train station" },
            { target: "ég fer í borgina", en: "I go into the city" },
            { target: "hótelið er hér vinstra megin", en: "the hotel is here on the left" },
            { target: "við förum með strætó", en: "we go by bus" },
            { target: "garðurinn er mjög langt", en: "the park is very far" },
            { target: "farðu beint áfram", en: "go straight ahead" },
            { target: "veitingastaðurinn er þar", en: "the restaurant is there" },
            { target: "ég finn ekki götuna", en: "I cannot find the street" },
            { target: "markaðurinn er nálægt", en: "the market is near" },
            { target: "hvar er bankinn", en: "where is the bank" },
            { target: "við förum með lest", en: "we travel by train" },
            { target: "bíllinn er þar", en: "the car is there" },
            { target: "kirkjan er mjög gömul", en: "the church is very old" },
            { target: "ég fer á markaðinn", en: "I go to the market" },
          ],
        },
        {
          id: "is-u5",
          title: "Numbers & time",
          subtitle: "Count and tell the time",
          cefr: "A2",
          color: "#CE82FF",
          icon: "🕐",
          vocab: [
            { target: "einn", en: "one" },
            { target: "tveir", en: "two" },
            { target: "þrír", en: "three" },
            { target: "fjórir", en: "four" },
            { target: "fimm", en: "five" },
            { target: "sex", en: "six" },
            { target: "sjö", en: "seven" },
            { target: "átta", en: "eight" },
            { target: "níu", en: "nine" },
            { target: "tíu", en: "ten" },
            { target: "klukka", en: "clock" },
            { target: "klukkustund", en: "hour" },
            { target: "mínúta", en: "minute" },
            { target: "dagur", en: "day" },
            { target: "vika", en: "week" },
            { target: "mánuður", en: "month" },
            { target: "ár", en: "year" },
            { target: "í dag", en: "today" },
            { target: "á morgun", en: "tomorrow" },
            { target: "núna", en: "now" },
            { target: "seint", en: "late" },
            { target: "snemma", en: "early" },
            { target: "tími", en: "time" },
            { target: "hversu", en: "how (much)" },
          ],
          sentences: [
            { target: "klukkan er þrjú", en: "it is three o'clock" },
            { target: "ég á tvær klukkustundir", en: "I have two hours" },
            { target: "hvað er klukkan", en: "what time is it" },
            { target: "í dag er góður dagur", en: "today is a good day" },
            { target: "það er mjög seint", en: "it is very late" },
            { target: "við eigum eina viku", en: "we have one week" },
            { target: "á morgun er nýr dagur", en: "tomorrow is a new day" },
            { target: "ég á engan tíma", en: "I have no time" },
            { target: "það er snemma núna", en: "it is early now" },
            { target: "mánuðurinn á fjórar vikur", en: "the month has four weeks" },
            { target: "árið á tólf mánuði", en: "the year has twelve months" },
            { target: "klukkan er tíu", en: "it is ten o'clock" },
            { target: "ég kem í dag", en: "I come today" },
            { target: "tíminn er núna", en: "the time is now" },
          ],
        },
        {
          id: "is-u6",
          title: "Daily life",
          subtitle: "Describe your everyday day",
          cefr: "A2",
          color: "#2B70C9",
          icon: "⏰",
          vocab: [
            { target: "vakna", en: "to wake up" },
            { target: "sofa", en: "to sleep" },
            { target: "vinna", en: "to work" },
            { target: "elda", en: "to cook" },
            { target: "þrífa", en: "to clean" },
            { target: "fara í sturtu", en: "to shower" },
            { target: "klæða sig", en: "to get dressed" },
            { target: "læra", en: "to study" },
            { target: "lesa", en: "to read" },
            { target: "skrifa", en: "to write" },
            { target: "spila", en: "to play" },
            { target: "morgunn", en: "morning" },
            { target: "kvöld", en: "evening" },
            { target: "nótt", en: "night" },
            { target: "hús", en: "house" },
            { target: "vinna", en: "work" },
            { target: "skóli", en: "school" },
            { target: "alltaf", en: "always" },
            { target: "oft", en: "often" },
            { target: "stundum", en: "sometimes" },
            { target: "aldrei", en: "never" },
            { target: "þreyttur", en: "tired" },
            { target: "svo", en: "then" },
            { target: "heima", en: "at home" },
          ],
          sentences: [
            { target: "ég vakna snemma", en: "I wake up early" },
            { target: "á morgnana fer ég í sturtu", en: "in the morning I shower" },
            { target: "við vinnum oft", en: "we work often" },
            { target: "ég elda á kvöldin", en: "I cook in the evenings" },
            { target: "þú ferð í skólann", en: "you go to school" },
            { target: "ég er mjög þreyttur", en: "I am very tired" },
            { target: "hún lærir alltaf", en: "she always studies" },
            { target: "ég les á kvöldin", en: "I read in the evenings" },
            { target: "stundum spila ég", en: "sometimes I play" },
            { target: "við þrífum húsið", en: "we clean the house" },
            { target: "þú sefur aldrei snemma", en: "you never sleep early" },
            { target: "á kvöldin er ég þreyttur", en: "in the evenings I am tired" },
            { target: "við förum heim", en: "we go home" },
            { target: "ég skrifa oft", en: "I write often" },
          ],
        },
      ],
    },
  ],
};
