import type { CourseBlueprint } from "@/curriculum/generate";

export const italianBlueprint: CourseBlueprint = {
  code: "it",
  name: "Italian",
  endonym: "Italiano",
  flag: "🇮🇹",
  fromLanguage: "English",
  speechLocale: "it-IT",
  sections: [
    {
      id: "it-s1",
      title: "Rookie",
      subtitle: "First words and everyday basics",
      units: [
        {
          id: "it-u1",
          title: "Greetings & basics",
          subtitle: "Say hello and introduce yourself",
          cefr: "A1",
          color: "#58CC02",
          icon: "👋",
          vocab: [
            { target: "ciao", en: "hi" },
            { target: "buongiorno", en: "good morning" },
            { target: "sì", en: "yes" },
            { target: "no", en: "no" },
            { target: "grazie", en: "thanks" },
            { target: "prego", en: "you're welcome" },
            { target: "arrivederci", en: "goodbye" },
            { target: "buonanotte", en: "good night" },
            { target: "buonasera", en: "good evening" },
            { target: "io", en: "I" },
            { target: "tu", en: "you" },
            { target: "lui", en: "he" },
            { target: "lei", en: "she" },
            { target: "essere", en: "to be" },
            { target: "nome", en: "name" },
            { target: "amico", en: "friend" },
            { target: "e", en: "and" },
            { target: "molto", en: "very" },
            { target: "bene", en: "well" },
            { target: "anche", en: "also" },
            { target: "signora", en: "madam" },
            { target: "signore", en: "sir" },
            { target: "scusa", en: "excuse me" },
            { target: "buono", en: "good" },
          ],
          sentences: [
            { target: "ciao come stai", en: "hi, how are you" },
            { target: "mi chiamo Anna", en: "my name is Anna" },
            { target: "come ti chiami", en: "what is your name" },
            { target: "buongiorno signora", en: "good morning, madam" },
            { target: "grazie mille", en: "thanks a lot" },
            { target: "sì grazie", en: "yes, thanks" },
            { target: "no grazie", en: "no, thanks" },
            { target: "arrivederci e buonanotte", en: "goodbye and good night" },
            { target: "tu sei il mio amico", en: "you are my friend" },
            { target: "lei è molto gentile", en: "she is very kind" },
            { target: "lui si chiama Marco", en: "his name is Marco" },
            { target: "buonasera signore", en: "good evening, sir" },
          ],
        },
        {
          id: "it-u2",
          title: "Food & drink",
          subtitle: "Order and describe meals",
          cefr: "A1",
          color: "#FF9600",
          icon: "🍎",
          vocab: [
            { target: "acqua", en: "water" },
            { target: "pane", en: "bread" },
            { target: "mela", en: "apple" },
            { target: "latte", en: "milk" },
            { target: "caffè", en: "coffee" },
            { target: "tè", en: "tea" },
            { target: "uovo", en: "egg" },
            { target: "formaggio", en: "cheese" },
            { target: "carne", en: "meat" },
            { target: "pesce", en: "fish" },
            { target: "riso", en: "rice" },
            { target: "zucchero", en: "sugar" },
            { target: "sale", en: "salt" },
            { target: "frutta", en: "fruit" },
            { target: "verdura", en: "vegetable" },
            { target: "mangiare", en: "to eat" },
            { target: "bere", en: "to drink" },
            { target: "volere", en: "to want" },
            { target: "vino", en: "wine" },
            { target: "freddo", en: "cold" },
            { target: "caldo", en: "hot" },
            { target: "colazione", en: "breakfast" },
          ],
          sentences: [
            { target: "bevo acqua", en: "I drink water" },
            { target: "mangiamo il pane", en: "we eat bread" },
            { target: "il caffè è caldo", en: "the coffee is hot" },
            { target: "voglio una mela", en: "I want an apple" },
            { target: "il latte è freddo", en: "the milk is cold" },
            { target: "tu mangi il pesce", en: "you eat fish" },
            { target: "voglio bere il tè", en: "I want to drink tea" },
            { target: "il formaggio è molto buono", en: "the cheese is very good" },
            { target: "ho fame", en: "I am hungry" },
            { target: "la carne è calda", en: "the meat is hot" },
            { target: "voglio pane e formaggio", en: "I want bread and cheese" },
            { target: "il vino è buono", en: "the wine is good" },
          ],
        },
      ],
    },
  ],
};
