import type { SectionBlueprint } from "@/curriculum/generate";

// Additional Italian units (hand-authored A1–A2, verified). Merged onto the base
// course in src/curriculum/index.ts.
export const italianExtraSections: SectionBlueprint[] = [
  {
    id: "it-s2",
    title: "Explorer",
    subtitle: "People, numbers and daily life",
    units: [
      {
        id: "it-u3",
        title: "Family & people",
        subtitle: "Talk about family and friends",
        cefr: "A1",
        color: "#1CB0F6",
        icon: "👨‍👩‍👧",
        vocab: [
          { target: "famiglia", en: "family" },
          { target: "madre", en: "mother" },
          { target: "padre", en: "father" },
          { target: "genitori", en: "parents" },
          { target: "fratello", en: "brother" },
          { target: "sorella", en: "sister" },
          { target: "figlio", en: "son" },
          { target: "figlia", en: "daughter" },
          { target: "bambino", en: "child" },
          { target: "nonna", en: "grandmother" },
          { target: "nonno", en: "grandfather" },
          { target: "marito", en: "husband" },
          { target: "moglie", en: "wife" },
          { target: "neonato", en: "baby" },
          { target: "zio", en: "uncle" },
          { target: "zia", en: "aunt" },
          { target: "avere", en: "to have" },
          { target: "amare", en: "to love" },
          { target: "piccolo", en: "small" },
          { target: "grande", en: "big" },
          { target: "vecchio", en: "old" },
          { target: "giovane", en: "young" },
          { target: "mio", en: "my" },
        ],
        sentences: [
          { target: "ho un fratello", en: "I have a brother" },
          { target: "mia madre è giovane", en: "my mother is young" },
          { target: "mio padre ama il bambino", en: "my father loves the child" },
          { target: "abbiamo due bambini", en: "we have two children" },
          { target: "mia sorella è piccola", en: "my sister is small" },
          { target: "mio fratello è grande", en: "my brother is big" },
          { target: "amo la mia famiglia", en: "I love my family" },
          { target: "mio marito è vecchio", en: "my husband is old" },
          { target: "la nonna è vecchia", en: "the grandmother is old" },
          { target: "amiamo il neonato", en: "we love the baby" },
          { target: "mio zio è giovane", en: "my uncle is young" },
          { target: "mia zia ama i bambini", en: "my aunt loves the children" },
        ],
      },
      {
        id: "it-u4",
        title: "Numbers & time",
        subtitle: "Count and tell the time",
        cefr: "A2",
        color: "#CE82FF",
        icon: "🕐",
        vocab: [
          { target: "uno", en: "one" },
          { target: "due", en: "two" },
          { target: "tre", en: "three" },
          { target: "quattro", en: "four" },
          { target: "cinque", en: "five" },
          { target: "sei", en: "six" },
          { target: "sette", en: "seven" },
          { target: "otto", en: "eight" },
          { target: "nove", en: "nine" },
          { target: "dieci", en: "ten" },
          { target: "ora", en: "hour" },
          { target: "minuto", en: "minute" },
          { target: "giorno", en: "day" },
          { target: "settimana", en: "week" },
          { target: "mese", en: "month" },
          { target: "anno", en: "year" },
          { target: "oggi", en: "today" },
          { target: "domani", en: "tomorrow" },
          { target: "adesso", en: "now" },
          { target: "tardi", en: "late" },
          { target: "presto", en: "early" },
          { target: "mattina", en: "morning" },
        ],
        sentences: [
          { target: "sono le tre", en: "it is three o'clock" },
          { target: "che ora è", en: "what time is it" },
          { target: "oggi è un buon giorno", en: "today is a good day" },
          { target: "è molto tardi", en: "it is very late" },
          { target: "domani è un nuovo giorno", en: "tomorrow is a new day" },
          { target: "non ho tempo", en: "I don't have time" },
          { target: "è presto adesso", en: "it is early now" },
          { target: "una settimana ha sette giorni", en: "a week has seven days" },
          { target: "l'anno ha dodici mesi", en: "the year has twelve months" },
          { target: "ho due ore", en: "I have two hours" },
          { target: "abbiamo cinque giorni", en: "we have five days" },
          { target: "la mattina lavoro", en: "in the morning I work" },
        ],
      },
    ],
  },
];
