import type { SectionBlueprint } from "@/curriculum/generate";

// Themed Italian units (hand-authored A2–B1, verified). Merged onto the base
// course in src/curriculum/index.ts to give the course real depth.
export const italianThemeSections: SectionBlueprint[] = [
  {
    id: "it-s3",
    title: "Globetrotter",
    subtitle: "Get around, shop, travel and chat",
    units: [
      {
        id: "it-u5",
        title: "Around town",
        subtitle: "Find your way in the city",
        cefr: "A2",
        color: "#FF4B4B",
        icon: "🏙️",
        vocab: [
          { target: "città", en: "city" },
          { target: "strada", en: "street" },
          { target: "stazione", en: "station" },
          { target: "mercato", en: "market" },
          { target: "banca", en: "bank" },
          { target: "negozio", en: "shop" },
          { target: "ristorante", en: "restaurant" },
          { target: "albergo", en: "hotel" },
          { target: "chiesa", en: "church" },
          { target: "parco", en: "park" },
          { target: "macchina", en: "car" },
          { target: "autobus", en: "bus" },
          { target: "treno", en: "train" },
          { target: "sinistra", en: "left" },
          { target: "destra", en: "right" },
          { target: "qui", en: "here" },
          { target: "lì", en: "there" },
          { target: "dove", en: "where" },
          { target: "andare", en: "to go" },
          { target: "trovare", en: "to find" },
          { target: "vicino", en: "near" },
          { target: "lontano", en: "far" },
        ],
        sentences: [
          { target: "dov'è la stazione", en: "where is the station" },
          { target: "vado in città", en: "I go into town" },
          { target: "l'albergo è a sinistra", en: "the hotel is on the left" },
          { target: "andiamo in autobus", en: "we go by bus" },
          { target: "il parco è molto lontano", en: "the park is very far" },
          { target: "il ristorante è lì", en: "the restaurant is there" },
          { target: "non trovo la strada", en: "I can't find the street" },
          { target: "il mercato è vicino", en: "the market is near" },
          { target: "dov'è la banca", en: "where is the bank" },
          { target: "la macchina è qui", en: "the car is here" },
          { target: "la chiesa è molto vecchia", en: "the church is very old" },
          { target: "vado al mercato", en: "I go to the market" },
        ],
      },
      {
        id: "it-u6",
        title: "Daily life",
        subtitle: "Describe your everyday routine",
        cefr: "A2",
        color: "#2B70C9",
        icon: "⏰",
        vocab: [
          { target: "svegliarsi", en: "to wake up" },
          { target: "dormire", en: "to sleep" },
          { target: "lavorare", en: "to work" },
          { target: "cucinare", en: "to cook" },
          { target: "pulire", en: "to clean" },
          { target: "leggere", en: "to read" },
          { target: "scrivere", en: "to write" },
          { target: "giocare", en: "to play" },
          { target: "studiare", en: "to study" },
          { target: "casa", en: "house" },
          { target: "scuola", en: "school" },
          { target: "lavoro", en: "work" },
          { target: "sempre", en: "always" },
          { target: "spesso", en: "often" },
          { target: "a volte", en: "sometimes" },
          { target: "mai", en: "never" },
          { target: "stanco", en: "tired" },
          { target: "sera", en: "evening" },
          { target: "notte", en: "night" },
          { target: "mattina", en: "morning" },
        ],
        sentences: [
          { target: "mi sveglio presto", en: "I wake up early" },
          { target: "lavoriamo spesso", en: "we work often" },
          { target: "cucino la sera", en: "I cook in the evening" },
          { target: "tu vai a scuola", en: "you go to school" },
          { target: "sono molto stanco", en: "I am very tired" },
          { target: "lei studia sempre", en: "she always studies" },
          { target: "leggo la sera", en: "I read in the evening" },
          { target: "a volte gioco", en: "sometimes I play" },
          { target: "puliamo la casa", en: "we clean the house" },
          { target: "non dormi mai presto", en: "you never sleep early" },
          { target: "la mattina lavoro", en: "in the morning I work" },
          { target: "scrivo spesso", en: "I write often" },
        ],
      },
      {
        id: "it-u7",
        title: "Shopping & money",
        subtitle: "Buy things and talk prices",
        cefr: "A2",
        color: "#FF9600",
        icon: "🛍️",
        vocab: [
          { target: "soldi", en: "money" },
          { target: "prezzo", en: "price" },
          { target: "caro", en: "expensive" },
          { target: "comprare", en: "to buy" },
          { target: "vendere", en: "to sell" },
          { target: "pagare", en: "to pay" },
          { target: "negozio", en: "shop" },
          { target: "vestiti", en: "clothes" },
          { target: "scarpe", en: "shoes" },
          { target: "borsa", en: "bag" },
          { target: "carta", en: "card" },
          { target: "contanti", en: "cash" },
          { target: "quanto", en: "how much" },
          { target: "nuovo", en: "new" },
          { target: "bisogno", en: "need" },
          { target: "aperto", en: "open" },
          { target: "chiuso", en: "closed" },
          { target: "volere", en: "to want" },
          { target: "molto", en: "a lot" },
          { target: "piccolo", en: "small" },
        ],
        sentences: [
          { target: "quanto costa", en: "how much does it cost" },
          { target: "è troppo caro", en: "it's too expensive" },
          { target: "voglio comprare una borsa", en: "I want to buy a bag" },
          { target: "pago con la carta", en: "I pay by card" },
          { target: "il negozio è chiuso", en: "the shop is closed" },
          { target: "queste scarpe sono care", en: "these shoes are expensive" },
          { target: "ho bisogno di vestiti", en: "I need clothes" },
          { target: "avete contanti", en: "do you have cash" },
          { target: "il prezzo è buono", en: "the price is good" },
          { target: "vorrei pagare", en: "I would like to pay" },
          { target: "il negozio è aperto", en: "the shop is open" },
          { target: "ho bisogno di scarpe", en: "I need shoes" },
        ],
      },
      {
        id: "it-u8",
        title: "Travel & transport",
        subtitle: "Trips, tickets and holidays",
        cefr: "B1",
        color: "#1CB0F6",
        icon: "✈️",
        vocab: [
          { target: "viaggio", en: "trip" },
          { target: "aereo", en: "plane" },
          { target: "aeroporto", en: "airport" },
          { target: "biglietto", en: "ticket" },
          { target: "valigia", en: "suitcase" },
          { target: "passaporto", en: "passport" },
          { target: "vacanza", en: "holiday" },
          { target: "mare", en: "sea" },
          { target: "spiaggia", en: "beach" },
          { target: "montagna", en: "mountain" },
          { target: "paese", en: "country" },
          { target: "partire", en: "to leave" },
          { target: "arrivare", en: "to arrive" },
          { target: "viaggiare", en: "to travel" },
          { target: "prenotare", en: "to book" },
          { target: "camera", en: "room" },
          { target: "chiave", en: "key" },
          { target: "mappa", en: "map" },
          { target: "domani", en: "tomorrow" },
          { target: "bello", en: "beautiful" },
        ],
        sentences: [
          { target: "viaggio in aereo", en: "I travel by plane" },
          { target: "dov'è l'aeroporto", en: "where is the airport" },
          { target: "ho il mio biglietto", en: "I have my ticket" },
          { target: "partiamo domani", en: "we leave tomorrow" },
          { target: "vado in spiaggia", en: "I go to the beach" },
          { target: "la camera è prenotata", en: "the room is booked" },
          { target: "amo le vacanze", en: "I love holidays" },
          { target: "il mare è molto bello", en: "the sea is very beautiful" },
          { target: "dov'è il mio passaporto", en: "where is my passport" },
          { target: "arriviamo alla stazione", en: "we arrive at the station" },
          { target: "la montagna è lontana", en: "the mountain is far" },
          { target: "viaggio ogni anno", en: "I travel every year" },
        ],
      },
      {
        id: "it-u9",
        title: "Weather & nature",
        subtitle: "Talk about the weather and the world",
        cefr: "A2",
        color: "#58CC02",
        icon: "🌦️",
        vocab: [
          { target: "tempo", en: "weather" },
          { target: "sole", en: "sun" },
          { target: "pioggia", en: "rain" },
          { target: "neve", en: "snow" },
          { target: "vento", en: "wind" },
          { target: "nuvola", en: "cloud" },
          { target: "caldo", en: "hot" },
          { target: "freddo", en: "cold" },
          { target: "cielo", en: "sky" },
          { target: "albero", en: "tree" },
          { target: "fiore", en: "flower" },
          { target: "fuoco", en: "fire" },
          { target: "animale", en: "animal" },
          { target: "cane", en: "dog" },
          { target: "gatto", en: "cat" },
          { target: "uccello", en: "bird" },
          { target: "blu", en: "blue" },
          { target: "bello", en: "nice" },
          { target: "inverno", en: "winter" },
          { target: "estate", en: "summer" },
        ],
        sentences: [
          { target: "oggi fa bello", en: "the weather is nice today" },
          { target: "piove molto", en: "it rains a lot" },
          { target: "il sole è caldo", en: "the sun is hot" },
          { target: "fa freddo in inverno", en: "it is cold in winter" },
          { target: "il cielo è blu", en: "the sky is blue" },
          { target: "amo gli animali", en: "I love animals" },
          { target: "il cane è piccolo", en: "the dog is small" },
          { target: "oggi nevica", en: "it is snowing today" },
          { target: "il fiore è bello", en: "the flower is beautiful" },
          { target: "il gatto dorme", en: "the cat sleeps" },
          { target: "l'albero è molto grande", en: "the tree is very big" },
          { target: "amo l'estate", en: "I love summer" },
        ],
      },
    ],
  },
];
