import type { CourseBlueprint } from "@/curriculum/generate";

// A for-fun novelty course in Elvish (Sindarin, as devised by J.R.R. Tolkien).
// Constructed-language vocabulary is reconstructed/debated, so this is a small
// curated set of widely-cited words and iconic phrases — learn it for delight,
// not for a trip to Rivendell. No neural voice (uses the system voice).
export const sindarinBlueprint: CourseBlueprint = {
  code: "sjn",
  name: "Elvish",
  endonym: "Edhellen (Sindarin)",
  flag: "🧝",
  fromLanguage: "English",
  sections: [
    {
      id: "sjn-s1",
      title: "Apprentice of the Eldar",
      subtitle: "Words and greetings of the Elves",
      units: [
        {
          id: "sjn-u1",
          title: "Greetings of the Eldar",
          subtitle: "Hail a friend in Sindarin",
          cefr: "A1",
          color: "#7C4DFF",
          icon: "🧝",
          vocab: [
            { target: "mellon", en: "friend" },
            { target: "edhel", en: "elf" },
            { target: "adan", en: "man (human)" },
            { target: "aran", en: "king" },
            { target: "im", en: "I" },
            { target: "le", en: "you" },
            { target: "maer", en: "good" },
            { target: "suilad", en: "greeting" },
            { target: "novaer", en: "farewell" },
            { target: "naneth", en: "mother" },
            { target: "adar", en: "father" },
            { target: "gûr", en: "heart" },
            { target: "estel", en: "hope" },
            { target: "mîl", en: "love" },
            { target: "nín", en: "my" },
          ],
          sentences: [
            { target: "mae govannen", en: "well met (hello)" },
            { target: "hannon le", en: "thank you" },
            { target: "mellon nín", en: "my friend" },
            { target: "im edhel", en: "I am an elf" },
            { target: "le aran", en: "you are a king" },
            { target: "novaer mellon", en: "farewell, friend" },
            { target: "estel nín", en: "my hope" },
            { target: "gûr nín", en: "my heart" },
          ],
        },
        {
          id: "sjn-u2",
          title: "Earth & sky",
          subtitle: "Star, sun, moon and more",
          cefr: "A1",
          color: "#5B8DEF",
          icon: "✨",
          vocab: [
            { target: "gîl", en: "star" },
            { target: "anor", en: "sun" },
            { target: "ithil", en: "moon" },
            { target: "galad", en: "light" },
            { target: "aur", en: "day" },
            { target: "dû", en: "night" },
            { target: "amrûn", en: "east / sunrise" },
            { target: "celon", en: "river" },
            { target: "orod", en: "mountain" },
            { target: "taur", en: "forest" },
            { target: "alph", en: "swan" },
            { target: "lasse", en: "leaf" },
            { target: "ëar", en: "sea" },
            { target: "rîw", en: "winter" },
            { target: "ethuil", en: "spring" },
          ],
          sentences: [
            { target: "elin gîl", en: "the stars (a star sky)" },
            { target: "galad nín", en: "my light" },
            { target: "anor a ithil", en: "sun and moon" },
            { target: "aur a dû", en: "day and night" },
            { target: "i orod", en: "the mountain" },
            { target: "i taur", en: "the forest" },
            { target: "i ëar", en: "the sea" },
            { target: "galad a estel", en: "light and hope" },
          ],
        },
      ],
    },
  ],
};
