import type { CourseBlueprint } from "@/curriculum/generate";

// Thai course blueprint. Hand-authored vocab + sentence banks per unit; the
// generator expands these into many spaced-repetition lessons. Thai script uses
// correct vowels and tone marks. Romanization lives in the `pinyin` field and
// uses a readable phonetic style with tone hints (à low, á high, â falling,
// ǎ rising, a mid; long vowels doubled). Gendered politeness is kept consistent
// within each example (male speaker: ผม / ครับ; female speaker: ฉัน / ค่ะ).

export const thaiBlueprint: CourseBlueprint = {
  code: "th",
  name: "Thai",
  endonym: "ไทย",
  flag: "🇹🇭",
  fromLanguage: "English",
  speechLocale: "th-TH",
  sections: [
    {
      id: "th-s1",
      title: "Rookie",
      subtitle: "First words and everyday basics",
      units: [
        {
          id: "th-u1",
          title: "Greetings & politeness",
          subtitle: "Say hello and be polite",
          cefr: "A1",
          color: "#E2483D",
          icon: "👋",
          vocab: [
            { target: "สวัสดี", en: "hello; goodbye", pinyin: "sà-wàt-dii" },
            { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
            { target: "ค่ะ", en: "(polite, female)", pinyin: "kâ" },
            { target: "ขอบคุณ", en: "thank you", pinyin: "kɔ̀ɔp-kun" },
            { target: "ใช่", en: "yes; correct", pinyin: "châi" },
            { target: "ไม่", en: "no; not", pinyin: "mâi" },
            { target: "ผม", en: "I (male)", pinyin: "pǒm" },
            { target: "ฉัน", en: "I (female)", pinyin: "chǎn" },
            { target: "คุณ", en: "you", pinyin: "kun" },
            { target: "ขอโทษ", en: "sorry; excuse me", pinyin: "kɔ̌ɔ-tôot" },
            { target: "ไม่เป็นไร", en: "it's okay", pinyin: "mâi-pen-rai" },
            { target: "สบายดี", en: "fine; well", pinyin: "sà-baai-dii" },
            { target: "ชื่อ", en: "name; to be named", pinyin: "chʉ̂ʉ" },
            { target: "อะไร", en: "what", pinyin: "à-rai" },
            { target: "เป็น", en: "to be", pinyin: "pen" },
            { target: "ดี", en: "good", pinyin: "dii" },
            { target: "มาก", en: "very; a lot", pinyin: "mâak" },
            { target: "และ", en: "and", pinyin: "lɛ́" },
            { target: "เขา", en: "he; she", pinyin: "kǎo" },
            { target: "ยินดี", en: "glad; pleased", pinyin: "yin-dii" },
            { target: "ลาก่อน", en: "goodbye", pinyin: "laa-kɔ̀ɔn" },
            { target: "พบ", en: "to meet", pinyin: "póp" },
            { target: "ที่", en: "that; which", pinyin: "tîi" },
            { target: "ไหม", en: "(question word)", pinyin: "mǎi" },
          ],
          sentences: [
            { target: "สวัสดี ครับ", en: "Hello.", pinyin: "sà-wàt-dii kráp" },
            { target: "สวัสดี ค่ะ", en: "Hello.", pinyin: "sà-wàt-dii kâ" },
            { target: "ขอบคุณ ครับ", en: "Thank you.", pinyin: "kɔ̀ɔp-kun kráp" },
            { target: "ขอบคุณ มาก ค่ะ", en: "Thank you very much.", pinyin: "kɔ̀ɔp-kun mâak kâ" },
            { target: "ขอโทษ ครับ", en: "Sorry.", pinyin: "kɔ̌ɔ-tôot kráp" },
            { target: "ไม่เป็นไร ค่ะ", en: "It's okay.", pinyin: "mâi-pen-rai kâ" },
            { target: "ผม สบายดี", en: "I am fine.", pinyin: "pǒm sà-baai-dii" },
            { target: "คุณ สบายดี ไหม", en: "Are you well?", pinyin: "kun sà-baai-dii mǎi" },
            { target: "คุณ ชื่อ อะไร", en: "What is your name?", pinyin: "kun chʉ̂ʉ à-rai" },
            { target: "ผม ชื่อ คุณ", en: "My name is You.", pinyin: "pǒm chʉ̂ʉ kun" },
            { target: "เขา เป็น คน ดี", en: "He is a good person.", pinyin: "kǎo pen kon dii" },
            { target: "ยินดี ที่ พบ คุณ", en: "Nice to meet you.", pinyin: "yin-dii tîi póp kun" },
            { target: "ลาก่อน ครับ", en: "Goodbye.", pinyin: "laa-kɔ̀ɔn kráp" },
            { target: "ใช่ ค่ะ", en: "Yes.", pinyin: "châi kâ" },
            { target: "ไม่ ใช่ ครับ", en: "No.", pinyin: "mâi châi kráp" },
          ],
        },
        {
          id: "th-u2",
          title: "Numbers",
          subtitle: "Count and ask how many",
          cefr: "A1",
          color: "#F4A23B",
          icon: "🔢",
          vocab: [
            { target: "หนึ่ง", en: "one", pinyin: "nʉ̀ng" },
            { target: "สอง", en: "two", pinyin: "sɔ̌ɔng" },
            { target: "สาม", en: "three", pinyin: "sǎam" },
            { target: "สี่", en: "four", pinyin: "sìi" },
            { target: "ห้า", en: "five", pinyin: "hâa" },
            { target: "หก", en: "six", pinyin: "hòk" },
            { target: "เจ็ด", en: "seven", pinyin: "jèt" },
            { target: "แปด", en: "eight", pinyin: "pɛ̀ɛt" },
            { target: "เก้า", en: "nine", pinyin: "kâo" },
            { target: "สิบ", en: "ten", pinyin: "sìp" },
            { target: "ศูนย์", en: "zero", pinyin: "sǔun" },
            { target: "ร้อย", en: "hundred", pinyin: "rɔ́ɔi" },
            { target: "ยี่สิบ", en: "twenty", pinyin: "yîi-sìp" },
            { target: "เท่าไหร่", en: "how much; how many", pinyin: "tâo-rài" },
            { target: "กี่", en: "how many", pinyin: "kìi" },
            { target: "ปี", en: "year; years old", pinyin: "pii" },
            { target: "อายุ", en: "age", pinyin: "aa-yú" },
            { target: "มี", en: "to have", pinyin: "mii" },
            { target: "คน", en: "person; (classifier)", pinyin: "kon" },
            { target: "อัน", en: "thing; (classifier)", pinyin: "an" },
            { target: "นี้", en: "this", pinyin: "níi" },
            { target: "ผม", en: "I (male)", pinyin: "pǒm" },
            { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
            { target: "ค่ะ", en: "(polite, female)", pinyin: "kâ" },
          ],
          sentences: [
            { target: "หนึ่ง สอง สาม", en: "One, two, three.", pinyin: "nʉ̀ng sɔ̌ɔng sǎam" },
            { target: "ผม มี สอง อัน", en: "I have two.", pinyin: "pǒm mii sɔ̌ɔng an" },
            { target: "มี กี่ คน", en: "How many people?", pinyin: "mii kìi kon" },
            { target: "มี สาม คน", en: "There are three people.", pinyin: "mii sǎam kon" },
            { target: "อัน นี้ เท่าไหร่", en: "How much is this one?", pinyin: "an níi tâo-rài" },
            { target: "ห้า ร้อย", en: "Five hundred.", pinyin: "hâa rɔ́ɔi" },
            { target: "คุณ อายุ เท่าไหร่", en: "How old are you?", pinyin: "kun aa-yú tâo-rài" },
            { target: "ผม อายุ สิบ ปี", en: "I am ten years old.", pinyin: "pǒm aa-yú sìp pii" },
            { target: "เจ็ด และ แปด", en: "Seven and eight.", pinyin: "jèt lɛ́ pɛ̀ɛt" },
            { target: "หนึ่ง ร้อย", en: "One hundred.", pinyin: "nʉ̀ng rɔ́ɔi" },
            { target: "ผม มี กี่ อัน", en: "How many do I have?", pinyin: "pǒm mii kìi an" },
            { target: "เก้า สิบ", en: "Ninety.", pinyin: "kâo sìp" },
            { target: "ยี่สิบ ปี", en: "Twenty years.", pinyin: "yîi-sìp pii" },
            { target: "มี สี่ อัน ครับ", en: "There are four.", pinyin: "mii sìi an kráp" },
          ],
        },
        {
          id: "th-u3",
          title: "Family & people",
          subtitle: "Talk about your family",
          cefr: "A1",
          color: "#3FB27F",
          icon: "👨‍👩‍👧",
          vocab: [
            { target: "แม่", en: "mom", pinyin: "mɛ̂ɛ" },
            { target: "พ่อ", en: "dad", pinyin: "pɔ̂ɔ" },
            { target: "พี่", en: "older sibling", pinyin: "pîi" },
            { target: "น้อง", en: "younger sibling", pinyin: "nɔ́ɔng" },
            { target: "ลูก", en: "child", pinyin: "lûuk" },
            { target: "ครอบครัว", en: "family", pinyin: "krɔ̂ɔp-krua" },
            { target: "เพื่อน", en: "friend", pinyin: "pʉ̂an" },
            { target: "ครู", en: "teacher", pinyin: "kruu" },
            { target: "นักเรียน", en: "student", pinyin: "nák-rian" },
            { target: "ผู้ชาย", en: "man", pinyin: "pûu-chaai" },
            { target: "ผู้หญิง", en: "woman", pinyin: "pûu-yǐng" },
            { target: "บ้าน", en: "house; home", pinyin: "bâan" },
            { target: "รัก", en: "to love", pinyin: "rák" },
            { target: "ของ", en: "of; belonging to", pinyin: "kɔ̌ɔng" },
            { target: "เรา", en: "we; us", pinyin: "rao" },
            { target: "ใคร", en: "who", pinyin: "krai" },
            { target: "ใหญ่", en: "big", pinyin: "yài" },
            { target: "เล็ก", en: "small", pinyin: "lék" },
            { target: "นี่", en: "this (one)", pinyin: "nîi" },
            { target: "นั่น", en: "that (one)", pinyin: "nân" },
            { target: "เป็น", en: "to be", pinyin: "pen" },
            { target: "ผม", en: "I (male)", pinyin: "pǒm" },
            { target: "เขา", en: "he; she", pinyin: "kǎo" },
            { target: "คน", en: "person; (classifier)", pinyin: "kon" },
          ],
          sentences: [
            { target: "นี่ เป็น แม่", en: "This is mom.", pinyin: "nîi pen mɛ̂ɛ" },
            { target: "นั่น เป็น ใคร", en: "Who is that?", pinyin: "nân pen krai" },
            { target: "เขา เป็น พ่อ ผม", en: "He is my dad.", pinyin: "kǎo pen pɔ̂ɔ pǒm" },
            { target: "ผม รัก ครอบครัว", en: "I love my family.", pinyin: "pǒm rák krɔ̂ɔp-krua" },
            { target: "ผม มี พี่", en: "I have an older sibling.", pinyin: "pǒm mii pîi" },
            { target: "เขา เป็น ครู", en: "She is a teacher.", pinyin: "kǎo pen kruu" },
            { target: "เรา เป็น นักเรียน", en: "We are students.", pinyin: "rao pen nák-rian" },
            { target: "เขา เป็น เพื่อน ผม", en: "He is my friend.", pinyin: "kǎo pen pʉ̂an pǒm" },
            { target: "น้อง เล็ก มาก", en: "The younger sibling is very small.", pinyin: "nɔ́ɔng lék mâak" },
            { target: "บ้าน ของ เรา ใหญ่", en: "Our house is big.", pinyin: "bâan kɔ̌ɔng rao yài" },
            { target: "ลูก ของ คุณ", en: "Your child.", pinyin: "lûuk kɔ̌ɔng kun" },
            { target: "พี่ ของ ผม ใหญ่", en: "My older sibling is big.", pinyin: "pîi kɔ̌ɔng pǒm yài" },
            { target: "เขา รัก ลูก", en: "She loves her child.", pinyin: "kǎo rák lûuk" },
            { target: "ผม รัก แม่", en: "I love mom.", pinyin: "pǒm rák mɛ̂ɛ" },
          ],
        },
        {
          id: "th-u4",
          title: "Food & drink",
          subtitle: "Order food and drinks",
          cefr: "A1",
          color: "#C45BD0",
          icon: "🍜",
          vocab: [
            { target: "น้ำ", en: "water", pinyin: "náam" },
            { target: "ชา", en: "tea", pinyin: "chaa" },
            { target: "กาแฟ", en: "coffee", pinyin: "kaa-fɛɛ" },
            { target: "ข้าว", en: "rice; meal", pinyin: "kâao" },
            { target: "ก๋วยเตี๋ยว", en: "noodles", pinyin: "kǔai-tǐao" },
            { target: "ผัก", en: "vegetable", pinyin: "pàk" },
            { target: "เนื้อ", en: "meat", pinyin: "nʉ́a" },
            { target: "ไก่", en: "chicken", pinyin: "kài" },
            { target: "ไข่", en: "egg", pinyin: "kài" },
            { target: "ผลไม้", en: "fruit", pinyin: "pǒn-lá-máai" },
            { target: "นม", en: "milk", pinyin: "nom" },
            { target: "กิน", en: "to eat", pinyin: "kin" },
            { target: "ดื่ม", en: "to drink", pinyin: "dʉ̀ʉm" },
            { target: "ชอบ", en: "to like", pinyin: "chɔ̂ɔp" },
            { target: "อยาก", en: "to want to", pinyin: "yàak" },
            { target: "เอา", en: "to take; want", pinyin: "ao" },
            { target: "อร่อย", en: "delicious", pinyin: "à-rɔ̀i" },
            { target: "เผ็ด", en: "spicy", pinyin: "pèt" },
            { target: "แก้ว", en: "glass (classifier)", pinyin: "kɛ̂ɛo" },
            { target: "หิว", en: "hungry", pinyin: "hǐu" },
            { target: "ผม", en: "I (male)", pinyin: "pǒm" },
            { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
            { target: "มาก", en: "very; a lot", pinyin: "mâak" },
            { target: "ไหม", en: "(question word)", pinyin: "mǎi" },
          ],
          sentences: [
            { target: "ผม ชอบ ดื่ม ชา", en: "I like to drink tea.", pinyin: "pǒm chɔ̂ɔp dʉ̀ʉm chaa" },
            { target: "ผม อยาก ดื่ม น้ำ", en: "I want to drink water.", pinyin: "pǒm yàak dʉ̀ʉm náam" },
            { target: "เอา กาแฟ หนึ่ง แก้ว", en: "One coffee, please.", pinyin: "ao kaa-fɛɛ nʉ̀ng kɛ̂ɛo" },
            { target: "คุณ ชอบ กิน เนื้อ ไหม", en: "Do you like to eat meat?", pinyin: "kun chɔ̂ɔp kin nʉ́a mǎi" },
            { target: "ข้าว อร่อย มาก", en: "The rice is very delicious.", pinyin: "kâao à-rɔ̀i mâak" },
            { target: "ชา อร่อย", en: "The tea is delicious.", pinyin: "chaa à-rɔ̀i" },
            { target: "ผม อยาก กิน ก๋วยเตี๋ยว", en: "I want to eat noodles.", pinyin: "pǒm yàak kin kǔai-tǐao" },
            { target: "ผม ชอบ ผลไม้", en: "I like fruit.", pinyin: "pǒm chɔ̂ɔp pǒn-lá-máai" },
            { target: "ผม เอา ผัก", en: "I'll have vegetables.", pinyin: "pǒm ao pàk" },
            { target: "เขา ดื่ม นม", en: "He drinks milk.", pinyin: "kǎo dʉ̀ʉm nom" },
            { target: "ก๋วยเตี๋ยว เผ็ด มาก", en: "The noodles are very spicy.", pinyin: "kǔai-tǐao pèt mâak" },
            { target: "คุณ อยาก ดื่ม กาแฟ ไหม", en: "Do you want to drink coffee?", pinyin: "kun yàak dʉ̀ʉm kaa-fɛɛ mǎi" },
            { target: "ไข่ อร่อย", en: "The egg is delicious.", pinyin: "kài à-rɔ̀i" },
            { target: "ผม หิว มาก ครับ", en: "I am very hungry.", pinyin: "pǒm hǐu mâak kráp" },
          ],
        },
      ],
    },
    {
      id: "th-s2",
      title: "Explorer",
      subtitle: "Get around and handle daily life",
      units: [
        {
          id: "th-u5",
          title: "Around town",
          subtitle: "Places and directions",
          cefr: "A2",
          color: "#3B82C4",
          icon: "🏙️",
          vocab: [
            { target: "อยู่", en: "to be at; to stay", pinyin: "yùu" },
            { target: "ที่ไหน", en: "where", pinyin: "tîi-nǎi" },
            { target: "ที่นี่", en: "here", pinyin: "tîi-nîi" },
            { target: "ที่นั่น", en: "there", pinyin: "tîi-nân" },
            { target: "โรงเรียน", en: "school", pinyin: "rooŋ-rian" },
            { target: "โรงพยาบาล", en: "hospital", pinyin: "rooŋ-pá-yaa-baan" },
            { target: "ร้าน", en: "shop; store", pinyin: "ráan" },
            { target: "ร้านอาหาร", en: "restaurant", pinyin: "ráan-aa-hǎan" },
            { target: "ธนาคาร", en: "bank", pinyin: "tá-naa-kaan" },
            { target: "สถานี", en: "station", pinyin: "sà-thǎa-nii" },
            { target: "ตลาด", en: "market", pinyin: "tà-làat" },
            { target: "ไป", en: "to go", pinyin: "pai" },
            { target: "มา", en: "to come", pinyin: "maa" },
            { target: "เลี้ยว", en: "to turn", pinyin: "líao" },
            { target: "ซ้าย", en: "left", pinyin: "sáai" },
            { target: "ขวา", en: "right", pinyin: "kwǎa" },
            { target: "ตรง", en: "straight", pinyin: "troŋ" },
            { target: "ไกล", en: "far", pinyin: "klai" },
            { target: "ใกล้", en: "near", pinyin: "klâi" },
            { target: "ยังไง", en: "how", pinyin: "yaŋ-ŋai" },
            { target: "ขอถาม", en: "may I ask", pinyin: "kɔ̌ɔ-tǎam" },
            { target: "ผม", en: "I (male)", pinyin: "pǒm" },
            { target: "อยาก", en: "to want to", pinyin: "yàak" },
            { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
          ],
          sentences: [
            { target: "คุณ อยู่ ที่ไหน", en: "Where are you?", pinyin: "kun yùu tîi-nǎi" },
            { target: "ผม อยู่ โรงเรียน", en: "I am at school.", pinyin: "pǒm yùu rooŋ-rian" },
            { target: "ร้าน อยู่ ที่ไหน", en: "Where is the shop?", pinyin: "ráan yùu tîi-nǎi" },
            { target: "ขอถาม ธนาคาร อยู่ ที่ไหน", en: "Excuse me, where is the bank?", pinyin: "kɔ̌ɔ-tǎam tá-naa-kaan yùu tîi-nǎi" },
            { target: "ผม อยาก ไป โรงพยาบาล", en: "I want to go to the hospital.", pinyin: "pǒm yàak pai rooŋ-pá-yaa-baan" },
            { target: "สถานี อยู่ ไกล", en: "The station is far.", pinyin: "sà-thǎa-nii yùu klai" },
            { target: "โรงเรียน อยู่ ใกล้", en: "The school is near.", pinyin: "rooŋ-rian yùu klâi" },
            { target: "เลี้ยว ซ้าย", en: "Turn left.", pinyin: "líao sáai" },
            { target: "เลี้ยว ขวา", en: "Turn right.", pinyin: "líao kwǎa" },
            { target: "ไป สถานี ยังไง", en: "How do I get to the station?", pinyin: "pai sà-thǎa-nii yaŋ-ŋai" },
            { target: "ผม มา ที่นี่", en: "I come here.", pinyin: "pǒm maa tîi-nîi" },
            { target: "เขา อยู่ ที่นั่น", en: "He is there.", pinyin: "kǎo yùu tîi-nân" },
            { target: "ร้านอาหาร อยู่ ตรง นี้", en: "The restaurant is right here.", pinyin: "ráan-aa-hǎan yùu troŋ níi" },
            { target: "ผม อยาก ไป ตลาด", en: "I want to go to the market.", pinyin: "pǒm yàak pai tà-làat" },
          ],
        },
        {
          id: "th-u6",
          title: "Daily life",
          subtitle: "Time, days and routines",
          cefr: "A2",
          color: "#7C6FE0",
          icon: "⏰",
          vocab: [
            { target: "วันนี้", en: "today", pinyin: "wan-níi" },
            { target: "พรุ่งนี้", en: "tomorrow", pinyin: "prûng-níi" },
            { target: "เมื่อวาน", en: "yesterday", pinyin: "mʉ̂a-waan" },
            { target: "ตอนนี้", en: "now", pinyin: "tɔɔn-níi" },
            { target: "เช้า", en: "morning", pinyin: "cháao" },
            { target: "เย็น", en: "evening", pinyin: "yen" },
            { target: "โมง", en: "o'clock", pinyin: "mooŋ" },
            { target: "เวลา", en: "time", pinyin: "wee-laa" },
            { target: "วัน", en: "day", pinyin: "wan" },
            { target: "อาทิตย์", en: "week", pinyin: "aa-tít" },
            { target: "เดือน", en: "month", pinyin: "dʉan" },
            { target: "ตื่น", en: "to wake up", pinyin: "tʉ̀ʉn" },
            { target: "นอน", en: "to sleep", pinyin: "nɔɔn" },
            { target: "ทำงาน", en: "to work", pinyin: "tam-ŋaan" },
            { target: "ทำ", en: "to do; make", pinyin: "tam" },
            { target: "ดู", en: "to watch; look", pinyin: "duu" },
            { target: "กลับบ้าน", en: "to go home", pinyin: "klàp-bâan" },
            { target: "ทุกวัน", en: "every day", pinyin: "túk-wan" },
            { target: "เมื่อไหร่", en: "when", pinyin: "mʉ̂a-rài" },
            { target: "แล้ว", en: "already", pinyin: "lɛ́ɛo" },
            { target: "จะ", en: "will (future)", pinyin: "jà" },
            { target: "ผม", en: "I (male)", pinyin: "pǒm" },
            { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
            { target: "กี่", en: "how many", pinyin: "kìi" },
          ],
          sentences: [
            { target: "ตอนนี้ กี่ โมง", en: "What time is it now?", pinyin: "tɔɔn-níi kìi mooŋ" },
            { target: "ตอนนี้ สาม โมง", en: "It's three o'clock.", pinyin: "tɔɔn-níi sǎam mooŋ" },
            { target: "วันนี้ วัน อะไร", en: "What day is it today?", pinyin: "wan-níi wan à-rai" },
            { target: "ผม ทำงาน ทุกวัน", en: "I work every day.", pinyin: "pǒm tam-ŋaan túk-wan" },
            { target: "ผม อยาก นอน", en: "I want to sleep.", pinyin: "pǒm yàak nɔɔn" },
            { target: "คุณ ทำงาน เมื่อไหร่", en: "When do you work?", pinyin: "kun tam-ŋaan mʉ̂a-rài" },
            { target: "ผม จะ ทำงาน พรุ่งนี้", en: "I will work tomorrow.", pinyin: "pǒm jà tam-ŋaan prûng-níi" },
            { target: "เขา กลับบ้าน แล้ว", en: "He went home already.", pinyin: "kǎo klàp-bâan lɛ́ɛo" },
            { target: "ผม ตื่น เช้า", en: "I wake up in the morning.", pinyin: "pǒm tʉ̀ʉn cháao" },
            { target: "ผม ตื่น ตอนนี้", en: "I am waking up now.", pinyin: "pǒm tʉ̀ʉn tɔɔn-níi" },
            { target: "คุณ ทำ อะไร", en: "What are you doing?", pinyin: "kun tam à-rai" },
            { target: "เมื่อวาน ผม กลับบ้าน", en: "Yesterday I went home.", pinyin: "mʉ̂a-waan pǒm klàp-bâan" },
            { target: "ผม ดู เวลา", en: "I look at the time.", pinyin: "pǒm duu wee-laa" },
            { target: "ผม จะ นอน แล้ว", en: "I am going to sleep now.", pinyin: "pǒm jà nɔɔn lɛ́ɛo" },
          ],
        },
        {
          id: "th-u7",
          title: "Shopping & money",
          subtitle: "Buy things and ask prices",
          cefr: "A2",
          color: "#D98324",
          icon: "🛍️",
          vocab: [
            { target: "ซื้อ", en: "to buy", pinyin: "sʉ́ʉ" },
            { target: "ขาย", en: "to sell", pinyin: "kǎai" },
            { target: "เงิน", en: "money", pinyin: "ŋən" },
            { target: "บาท", en: "baht", pinyin: "bàat" },
            { target: "ราคา", en: "price", pinyin: "raa-kaa" },
            { target: "แพง", en: "expensive", pinyin: "pɛɛŋ" },
            { target: "ถูก", en: "cheap", pinyin: "tùuk" },
            { target: "ของ", en: "thing; stuff", pinyin: "kɔ̌ɔng" },
            { target: "เสื้อ", en: "shirt", pinyin: "sʉ̂a" },
            { target: "รองเท้า", en: "shoes", pinyin: "rɔɔŋ-táao" },
            { target: "หนังสือ", en: "book", pinyin: "nǎng-sʉ̌ʉ" },
            { target: "สี", en: "color", pinyin: "sǐi" },
            { target: "แดง", en: "red", pinyin: "dɛɛŋ" },
            { target: "ขาว", en: "white", pinyin: "kǎao" },
            { target: "ดำ", en: "black", pinyin: "dam" },
            { target: "ตัว", en: "(classifier, clothes)", pinyin: "tua" },
            { target: "นั้น", en: "that", pinyin: "nán" },
            { target: "ลด", en: "to reduce; discount", pinyin: "lót" },
            { target: "ได้", en: "can; able to", pinyin: "dâai" },
            { target: "สวย", en: "beautiful", pinyin: "sǔai" },
            { target: "ใหม่", en: "new", pinyin: "mài" },
            { target: "เท่าไหร่", en: "how much", pinyin: "tâo-rài" },
            { target: "ผม", en: "I (male)", pinyin: "pǒm" },
            { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
          ],
          sentences: [
            { target: "อัน นี้ เท่าไหร่", en: "How much is this?", pinyin: "an níi tâo-rài" },
            { target: "แพง มาก", en: "Very expensive.", pinyin: "pɛɛŋ mâak" },
            { target: "ถูก มาก", en: "Very cheap.", pinyin: "tùuk mâak" },
            { target: "ผม อยาก ซื้อ เสื้อ", en: "I want to buy a shirt.", pinyin: "pǒm yàak sʉ́ʉ sʉ̂a" },
            { target: "ผม อยาก ซื้อ รองเท้า", en: "I want to buy shoes.", pinyin: "pǒm yàak sʉ́ʉ rɔɔŋ-táao" },
            { target: "เสื้อ ตัว นี้ สวย", en: "This shirt is beautiful.", pinyin: "sʉ̂a tua níi sǔai" },
            { target: "ผม ชอบ สี แดง", en: "I like the color red.", pinyin: "pǒm chɔ̂ɔp sǐi dɛɛŋ" },
            { target: "ลด ได้ ไหม", en: "Can you discount it?", pinyin: "lót dâai mǎi" },
            { target: "เสื้อ ตัว นั้น แพง", en: "That shirt is expensive.", pinyin: "sʉ̂a tua nán pɛɛŋ" },
            { target: "นี่ รองเท้า ใหม่", en: "These are new shoes.", pinyin: "nîi rɔɔŋ-táao mài" },
            { target: "ผม ซื้อ อัน นี้", en: "I'll buy this one.", pinyin: "pǒm sʉ́ʉ an níi" },
            { target: "หนังสือ ราคา เท่าไหร่", en: "How much is the book?", pinyin: "nǎng-sʉ̌ʉ raa-kaa tâo-rài" },
            { target: "ของ นี้ สวย มาก", en: "This thing is very beautiful.", pinyin: "kɔ̌ɔng níi sǔai mâak" },
            { target: "ห้า ร้อย บาท ครับ", en: "Five hundred baht.", pinyin: "hâa rɔ́ɔi bàat kráp" },
          ],
        },
      ],
    },
    {
      id: "th-s3",
      title: "Independent",
      subtitle: "Handle work, study and travel",
      units: [
        {
          id: "th-u8",
          title: "Work & study",
          subtitle: "Jobs, school and learning",
          cefr: "B1",
          color: "#2BA39A",
          icon: "💼",
          vocab: [
            { target: "บริษัท", en: "company", pinyin: "bɔɔ-rí-sàt" },
            { target: "เพื่อนร่วมงาน", en: "colleague", pinyin: "pʉ̂an-rûam-ŋaan" },
            { target: "ประชุม", en: "meeting", pinyin: "prà-chum" },
            { target: "คอมพิวเตอร์", en: "computer", pinyin: "kɔm-piu-tə̂ə" },
            { target: "โทรศัพท์", en: "phone", pinyin: "too-rá-sàp" },
            { target: "เรียน", en: "to study", pinyin: "rian" },
            { target: "สอบ", en: "exam", pinyin: "sɔ̀ɔp" },
            { target: "คำถาม", en: "question", pinyin: "kam-tǎam" },
            { target: "ภาษา", en: "language", pinyin: "paa-sǎa" },
            { target: "ไทย", en: "Thai", pinyin: "tai" },
            { target: "อังกฤษ", en: "English", pinyin: "aŋ-krìt" },
            { target: "พูด", en: "to speak", pinyin: "pûut" },
            { target: "เขียน", en: "to write", pinyin: "kǐan" },
            { target: "อ่าน", en: "to read", pinyin: "àan" },
            { target: "เข้าใจ", en: "to understand", pinyin: "kâo-jai" },
            { target: "รู้", en: "to know", pinyin: "rúu" },
            { target: "คิด", en: "to think", pinyin: "kít" },
            { target: "ยุ่ง", en: "busy", pinyin: "yûŋ" },
            { target: "เหนื่อย", en: "tired", pinyin: "nʉ̀ai" },
            { target: "ยาก", en: "difficult", pinyin: "yâak" },
            { target: "ง่าย", en: "easy", pinyin: "ŋâai" },
            { target: "เพราะ", en: "because", pinyin: "prɔ́" },
            { target: "งาน", en: "work; job", pinyin: "ŋaan" },
            { target: "ทำงาน", en: "to work", pinyin: "tam-ŋaan" },
            { target: "ที่", en: "at; that", pinyin: "tîi" },
            { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          ],
          sentences: [
            { target: "ผม ทำงาน ที่ บริษัท", en: "I work at a company.", pinyin: "pǒm tam-ŋaan tîi bɔɔ-rí-sàt" },
            { target: "ผม เรียน ภาษา ไทย", en: "I study Thai.", pinyin: "pǒm rian paa-sǎa tai" },
            { target: "ภาษา ไทย ยาก", en: "Thai is difficult.", pinyin: "paa-sǎa tai yâak" },
            { target: "ภาษา อังกฤษ ง่าย", en: "English is easy.", pinyin: "paa-sǎa aŋ-krìt ŋâai" },
            { target: "คุณ พูด ภาษา อังกฤษ ได้ ไหม", en: "Can you speak English?", pinyin: "kun pûut paa-sǎa aŋ-krìt dâai mǎi" },
            { target: "ผม ไม่ เข้าใจ", en: "I don't understand.", pinyin: "pǒm mâi kâo-jai" },
            { target: "วันนี้ ผม ยุ่ง มาก", en: "I am very busy today.", pinyin: "wan-níi pǒm yûŋ mâak" },
            { target: "ผม มี คำถาม", en: "I have a question.", pinyin: "pǒm mii kam-tǎam" },
            { target: "พรุ่งนี้ ผม มี สอบ", en: "I have an exam tomorrow.", pinyin: "prûng-níi pǒm mii sɔ̀ɔp" },
            { target: "ผม เหนื่อย เพราะ งาน", en: "I'm tired because of work.", pinyin: "pǒm nʉ̀ai prɔ́ ŋaan" },
            { target: "ผม เขียน ภาษา ไทย ได้", en: "I can write Thai.", pinyin: "pǒm kǐan paa-sǎa tai dâai" },
            { target: "เพื่อนร่วมงาน ผม ยุ่ง มาก", en: "My colleague is very busy.", pinyin: "pʉ̂an-rûam-ŋaan pǒm yûŋ mâak" },
            { target: "ผม รู้ คำถาม นี้", en: "I know this question.", pinyin: "pǒm rúu kam-tǎam níi" },
            { target: "ผม อ่าน ได้", en: "I can read.", pinyin: "pǒm àan dâai" },
          ],
        },
        {
          id: "th-u9",
          title: "Travel",
          subtitle: "Trips, transport and plans",
          cefr: "B1",
          color: "#C2477E",
          icon: "✈️",
          vocab: [
            { target: "เที่ยว", en: "to travel; go out", pinyin: "tîao" },
            { target: "เครื่องบิน", en: "airplane", pinyin: "krʉ̂aŋ-bin" },
            { target: "รถไฟ", en: "train", pinyin: "rót-fai" },
            { target: "รถ", en: "car", pinyin: "rót" },
            { target: "แท็กซี่", en: "taxi", pinyin: "tɛ́k-sîi" },
            { target: "สนามบิน", en: "airport", pinyin: "sà-nǎam-bin" },
            { target: "โรงแรม", en: "hotel", pinyin: "rooŋ-rɛɛm" },
            { target: "พาสปอร์ต", en: "passport", pinyin: "pháat-spɔ̀ɔt" },
            { target: "ตั๋ว", en: "ticket", pinyin: "tǔa" },
            { target: "เมือง", en: "city", pinyin: "mʉaŋ" },
            { target: "ประเทศ", en: "country", pinyin: "prà-têet" },
            { target: "แผนที่", en: "map", pinyin: "pɛ̌ɛn-tîi" },
            { target: "นั่ง", en: "to sit; ride", pinyin: "nâng" },
            { target: "ขับ", en: "to drive", pinyin: "kàp" },
            { target: "ถึง", en: "to arrive", pinyin: "tʉ̌ng" },
            { target: "ออก", en: "to leave; depart", pinyin: "ɔ̀ɔk" },
            { target: "กระเป๋า", en: "bag; luggage", pinyin: "krà-pǎo" },
            { target: "วันหยุด", en: "holiday; vacation", pinyin: "wan-yùt" },
            { target: "ด้วยกัน", en: "together", pinyin: "dûai-kan" },
            { target: "ต้อง", en: "must; need to", pinyin: "tɔ̂ŋ" },
            { target: "ควร", en: "should", pinyin: "kuan" },
            { target: "หวัง", en: "to hope", pinyin: "wǎng" },
            { target: "ผม", en: "I (male)", pinyin: "pǒm" },
            { target: "อยาก", en: "to want to", pinyin: "yàak" },
          ],
          sentences: [
            { target: "ผม ชอบ เที่ยว", en: "I like to travel.", pinyin: "pǒm chɔ̂ɔp tîao" },
            { target: "ผม อยาก ไป ประเทศ ไทย", en: "I want to go to Thailand.", pinyin: "pǒm yàak pai prà-têet tai" },
            { target: "ผม นั่ง เครื่องบิน", en: "I take the plane.", pinyin: "pǒm nâng krʉ̂aŋ-bin" },
            { target: "ผม อยาก นั่ง รถไฟ", en: "I want to take the train.", pinyin: "pǒm yàak nâng rót-fai" },
            { target: "ผม ต้อง มี พาสปอร์ต", en: "I need a passport.", pinyin: "pǒm tɔ̂ŋ mii pháat-spɔ̀ɔt" },
            { target: "ตั๋ว ราคา เท่าไหร่", en: "How much is the ticket?", pinyin: "tǔa raa-kaa tâo-rài" },
            { target: "สนามบิน อยู่ ไกล", en: "The airport is far.", pinyin: "sà-nǎam-bin yùu klai" },
            { target: "เรา ไป ด้วยกัน", en: "Let's go together.", pinyin: "rao pai dûai-kan" },
            { target: "ผม จะ ออก พรุ่งนี้", en: "I leave tomorrow.", pinyin: "pǒm jà ɔ̀ɔk prûng-níi" },
            { target: "ผม นั่ง แท็กซี่ ไป โรงแรม", en: "I take a taxi to the hotel.", pinyin: "pǒm nâng tɛ́k-sîi pai rooŋ-rɛɛm" },
            { target: "คุณ ควร นั่ง รถไฟ", en: "You should take the train.", pinyin: "kun kuan nâng rót-fai" },
            { target: "ผม หวัง จะ ไป เที่ยว", en: "I hope to go traveling.", pinyin: "pǒm wǎng jà pai tîao" },
            { target: "ผม ถึง สนามบิน แล้ว", en: "I have arrived at the airport.", pinyin: "pǒm tʉ̌ng sà-nǎam-bin lɛ́ɛo" },
            { target: "เมือง นี้ ใหญ่ มาก", en: "This city is very big.", pinyin: "mʉaŋ níi yài mâak" },
          ],
        },
      ],
    },
  ],
};
