import type { SectionBlueprint } from "@/curriculum/generate";

// Additional theme-based Thai sections. Hand-authored vocab + sentence banks per
// unit; the generator expands these into many spaced-repetition lessons. Thai
// script uses correct vowels and tone marks. Romanization lives in the `pinyin`
// field and follows the same readable phonetic style as th.ts (à low, á high,
// â falling, ǎ rising, a mid; long vowels doubled). Politeness is kept
// consistent within each example (male speaker: ผม / ครับ).

export const thaiThemeSections: SectionBlueprint[] = [
  {
    id: "th-sT1",
    title: "Themes",
    subtitle: "Broaden your vocabulary",
    units: [
      {
        id: "th-ut1",
        title: "Nature & weather",
        subtitle: "Talk about the world outside",
        cefr: "A2",
        color: "#4CAF82",
        icon: "🌦️",
        vocab: [
          { target: "อากาศ", en: "weather; air", pinyin: "aa-kàat" },
          { target: "ฝน", en: "rain", pinyin: "fǒn" },
          { target: "แดด", en: "sunshine", pinyin: "dɛ̀ɛt" },
          { target: "ลม", en: "wind", pinyin: "lom" },
          { target: "เมฆ", en: "cloud", pinyin: "mêek" },
          { target: "ฟ้า", en: "sky", pinyin: "fáa" },
          { target: "ร้อน", en: "hot", pinyin: "rɔ́ɔn" },
          { target: "หนาว", en: "cold", pinyin: "nǎao" },
          { target: "ต้นไม้", en: "tree", pinyin: "tôn-máai" },
          { target: "ดอกไม้", en: "flower", pinyin: "dɔ̀ɔk-máai" },
          { target: "ภูเขา", en: "mountain", pinyin: "puu-kǎo" },
          { target: "ทะเล", en: "sea", pinyin: "tá-lee" },
          { target: "แม่น้ำ", en: "river", pinyin: "mɛ̂ɛ-náam" },
          { target: "ป่า", en: "forest", pinyin: "pàa" },
          { target: "นก", en: "bird", pinyin: "nók" },
          { target: "หมา", en: "dog", pinyin: "mǎa" },
          { target: "แมว", en: "cat", pinyin: "mɛɛo" },
          { target: "ดวงอาทิตย์", en: "sun", pinyin: "duaŋ-aa-tít" },
          { target: "สวย", en: "beautiful", pinyin: "sǔai" },
          { target: "ตก", en: "to fall", pinyin: "tòk" },
          { target: "แรง", en: "strong", pinyin: "rɛɛŋ" },
          { target: "ชอบ", en: "to like", pinyin: "chɔ̂ɔp" },
          { target: "อยู่", en: "to be at", pinyin: "yùu" },
          { target: "บน", en: "on; above", pinyin: "bon" },
          { target: "มี", en: "to have; there is", pinyin: "mii" },
          { target: "ใหญ่", en: "big", pinyin: "yài" },
          { target: "วันนี้", en: "today", pinyin: "wan-níi" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
        ],
        sentences: [
          { target: "วันนี้ อากาศ ร้อน", en: "The weather is hot today.", pinyin: "wan-níi aa-kàat rɔ́ɔn" },
          { target: "วันนี้ ฝน ตก", en: "It is raining today.", pinyin: "wan-níi fǒn tòk" },
          { target: "ฟ้า สวย มาก", en: "The sky is very beautiful.", pinyin: "fáa sǔai mâak" },
          { target: "ผม ชอบ ทะเล", en: "I like the sea.", pinyin: "pǒm chɔ̂ɔp tá-lee" },
          { target: "ภูเขา สวย มาก", en: "The mountain is very beautiful.", pinyin: "puu-kǎo sǔai mâak" },
          { target: "วันนี้ หนาว มาก", en: "It is very cold today.", pinyin: "wan-níi nǎao mâak" },
          { target: "ลม แรง มาก", en: "The wind is very strong.", pinyin: "lom rɛɛŋ mâak" },
          { target: "ผม ชอบ ดอกไม้", en: "I like flowers.", pinyin: "pǒm chɔ̂ɔp dɔ̀ɔk-máai" },
          { target: "นก อยู่ บน ต้นไม้", en: "The bird is on the tree.", pinyin: "nók yùu bon tôn-máai" },
          { target: "วันนี้ มี แดด", en: "It is sunny today.", pinyin: "wan-níi mii dɛ̀ɛt" },
          { target: "ป่า ใหญ่ มาก", en: "The forest is very big.", pinyin: "pàa yài mâak" },
          { target: "ผม ชอบ หมา", en: "I like dogs.", pinyin: "pǒm chɔ̂ɔp mǎa" },
          { target: "แม่น้ำ สวย มาก ครับ", en: "The river is very beautiful.", pinyin: "mɛ̂ɛ-náam sǔai mâak kráp" },
          { target: "วันนี้ ฟ้า มี เมฆ", en: "The sky is cloudy today.", pinyin: "wan-níi fáa mii mêek" },
        ],
      },
      {
        id: "th-ut2",
        title: "Emotions & feelings",
        subtitle: "Say how you feel",
        cefr: "A2",
        color: "#E86FA0",
        icon: "😊",
        vocab: [
          { target: "ความรู้สึก", en: "feeling", pinyin: "kwaam-rúu-sʉ̀k" },
          { target: "ดีใจ", en: "happy; glad", pinyin: "dii-jai" },
          { target: "เสียใจ", en: "sad", pinyin: "sǐa-jai" },
          { target: "โกรธ", en: "angry", pinyin: "kròot" },
          { target: "กลัว", en: "afraid", pinyin: "klua" },
          { target: "เบื่อ", en: "bored", pinyin: "bʉ̀a" },
          { target: "ตื่นเต้น", en: "excited", pinyin: "tʉ̀ʉn-tên" },
          { target: "เหงา", en: "lonely", pinyin: "ŋǎo" },
          { target: "สนุก", en: "fun", pinyin: "sà-nùk" },
          { target: "มีความสุข", en: "happy", pinyin: "mii-kwaam-sùk" },
          { target: "กังวล", en: "worried", pinyin: "kaŋ-won" },
          { target: "ประหลาดใจ", en: "surprised", pinyin: "prà-làat-jai" },
          { target: "ภูมิใจ", en: "proud", pinyin: "puum-jai" },
          { target: "ยิ้ม", en: "to smile", pinyin: "yím" },
          { target: "หัวเราะ", en: "to laugh", pinyin: "hǔa-rɔ́" },
          { target: "ร้องไห้", en: "to cry", pinyin: "rɔ́ɔŋ-hâi" },
          { target: "รู้สึก", en: "to feel", pinyin: "rúu-sʉ̀k" },
          { target: "เป็นห่วง", en: "to be concerned", pinyin: "pen-hùaŋ" },
          { target: "สบายใจ", en: "at ease; relieved", pinyin: "sà-baai-jai" },
          { target: "เขา", en: "he; she", pinyin: "kǎo" },
          { target: "คุณ", en: "you", pinyin: "kun" },
          { target: "ตอนนี้", en: "now", pinyin: "tɔɔn-níi" },
          { target: "วันนี้", en: "today", pinyin: "wan-níi" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ทำไม", en: "why", pinyin: "tam-mai" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
        ],
        sentences: [
          { target: "วันนี้ ผม ดีใจ", en: "I am happy today.", pinyin: "wan-níi pǒm dii-jai" },
          { target: "ผม รู้สึก เหงา", en: "I feel lonely.", pinyin: "pǒm rúu-sʉ̀k ŋǎo" },
          { target: "ผม มีความสุข มาก", en: "I am very happy.", pinyin: "pǒm mii-kwaam-sùk mâak" },
          { target: "ทำไม คุณ เสียใจ", en: "Why are you sad?", pinyin: "tam-mai kun sǐa-jai" },
          { target: "เขา โกรธ มาก", en: "He is very angry.", pinyin: "kǎo kròot mâak" },
          { target: "ผม กลัว มาก", en: "I am very afraid.", pinyin: "pǒm klua mâak" },
          { target: "วันนี้ สนุก มาก", en: "Today was very fun.", pinyin: "wan-níi sà-nùk mâak" },
          { target: "ผม ตื่นเต้น มาก", en: "I am very excited.", pinyin: "pǒm tʉ̀ʉn-tên mâak" },
          { target: "เขา ยิ้ม", en: "She smiles.", pinyin: "kǎo yím" },
          { target: "ผม เป็นห่วง คุณ", en: "I am concerned about you.", pinyin: "pǒm pen-hùaŋ kun" },
          { target: "ผม เบื่อ มาก", en: "I am very bored.", pinyin: "pǒm bʉ̀a mâak" },
          { target: "เขา ร้องไห้", en: "She is crying.", pinyin: "kǎo rɔ́ɔŋ-hâi" },
          { target: "ผม ภูมิใจ มาก ครับ", en: "I am very proud.", pinyin: "pǒm puum-jai mâak kráp" },
          { target: "ตอนนี้ ผม สบายใจ", en: "Now I feel at ease.", pinyin: "tɔɔn-níi pǒm sà-baai-jai" },
        ],
      },
      {
        id: "th-ut3",
        title: "House & everyday objects",
        subtitle: "Name things around the home",
        cefr: "A2",
        color: "#5B8DEF",
        icon: "🏠",
        vocab: [
          { target: "ห้อง", en: "room", pinyin: "hɔ̂ŋ" },
          { target: "ห้องนอน", en: "bedroom", pinyin: "hɔ̂ŋ-nɔɔn" },
          { target: "ห้องน้ำ", en: "bathroom", pinyin: "hɔ̂ŋ-náam" },
          { target: "ห้องครัว", en: "kitchen", pinyin: "hɔ̂ŋ-krua" },
          { target: "ประตู", en: "door", pinyin: "prà-tuu" },
          { target: "หน้าต่าง", en: "window", pinyin: "nâa-tàaŋ" },
          { target: "โต๊ะ", en: "table", pinyin: "tó" },
          { target: "เก้าอี้", en: "chair", pinyin: "kâo-îi" },
          { target: "เตียง", en: "bed", pinyin: "tiaŋ" },
          { target: "ตู้", en: "cupboard", pinyin: "tûu" },
          { target: "ไฟ", en: "light", pinyin: "fai" },
          { target: "ทีวี", en: "TV", pinyin: "tii-wii" },
          { target: "ช้อน", en: "spoon", pinyin: "chɔ́ɔn" },
          { target: "จาน", en: "plate", pinyin: "jaan" },
          { target: "ถ้วย", en: "cup; bowl", pinyin: "tûai" },
          { target: "มีด", en: "knife", pinyin: "mîit" },
          { target: "กุญแจ", en: "key", pinyin: "kun-jɛɛ" },
          { target: "นาฬิกา", en: "clock", pinyin: "naa-lí-kaa" },
          { target: "เปิด", en: "to open; turn on", pinyin: "pə̀ət" },
          { target: "ปิด", en: "to close; turn off", pinyin: "pìt" },
          { target: "บน", en: "on; above", pinyin: "bon" },
          { target: "ใน", en: "in; inside", pinyin: "nai" },
          { target: "ช่วย", en: "please; to help", pinyin: "chûai" },
          { target: "อยู่", en: "to be at", pinyin: "yùu" },
          { target: "ดู", en: "to watch", pinyin: "duu" },
          { target: "นอน", en: "to sleep", pinyin: "nɔɔn" },
          { target: "ใหญ่", en: "big", pinyin: "yài" },
          { target: "ที่ไหน", en: "where", pinyin: "tîi-nǎi" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
        ],
        sentences: [
          { target: "ผม อยู่ ใน ห้อง", en: "I am in the room.", pinyin: "pǒm yùu nai hɔ̂ŋ" },
          { target: "กุญแจ อยู่ บน โต๊ะ", en: "The key is on the table.", pinyin: "kun-jɛɛ yùu bon tó" },
          { target: "ช่วย เปิด ประตู", en: "Please open the door.", pinyin: "chûai pə̀ət prà-tuu" },
          { target: "ช่วย ปิด ไฟ", en: "Please turn off the light.", pinyin: "chûai pìt fai" },
          { target: "ห้องน้ำ อยู่ ที่ไหน", en: "Where is the bathroom?", pinyin: "hɔ̂ŋ-náam yùu tîi-nǎi" },
          { target: "เก้าอี้ อยู่ ใน ห้องครัว", en: "The chair is in the kitchen.", pinyin: "kâo-îi yùu nai hɔ̂ŋ-krua" },
          { target: "ผม ดู ทีวี", en: "I watch TV.", pinyin: "pǒm duu tii-wii" },
          { target: "จาน อยู่ บน โต๊ะ", en: "The plate is on the table.", pinyin: "jaan yùu bon tó" },
          { target: "ผม นอน บน เตียง", en: "I sleep on the bed.", pinyin: "pǒm nɔɔn bon tiaŋ" },
          { target: "ช่วย เปิด หน้าต่าง", en: "Please open the window.", pinyin: "chûai pə̀ət nâa-tàaŋ" },
          { target: "นาฬิกา อยู่ ใน ห้องนอน", en: "The clock is in the bedroom.", pinyin: "naa-lí-kaa yùu nai hɔ̂ŋ-nɔɔn" },
          { target: "ช้อน อยู่ ใน ตู้", en: "The spoon is in the cupboard.", pinyin: "chɔ́ɔn yùu nai tûu" },
          { target: "ห้องครัว ใหญ่ มาก ครับ", en: "The kitchen is very big.", pinyin: "hɔ̂ŋ-krua yài mâak kráp" },
          { target: "ช่วย ปิด ประตู", en: "Please close the door.", pinyin: "chûai pìt prà-tuu" },
        ],
      },
    ],
  },
  {
    id: "th-sT2",
    title: "Real life",
    subtitle: "Talk about the wider world",
    units: [
      {
        id: "th-ut4",
        title: "Work & money",
        subtitle: "Jobs, pay and the workplace",
        cefr: "B1",
        color: "#2E9E8F",
        icon: "💰",
        vocab: [
          { target: "อาชีพ", en: "occupation", pinyin: "aa-chîip" },
          { target: "เงินเดือน", en: "salary", pinyin: "ŋən-dʉan" },
          { target: "เจ้านาย", en: "boss", pinyin: "jâo-naai" },
          { target: "ลูกค้า", en: "customer", pinyin: "lûuk-káa" },
          { target: "สัญญา", en: "contract", pinyin: "sǎn-yaa" },
          { target: "โครงการ", en: "project", pinyin: "kroŋ-kaan" },
          { target: "หน้าที่", en: "duty; responsibility", pinyin: "nâa-tîi" },
          { target: "ออฟฟิศ", en: "office", pinyin: "ɔ́f-fít" },
          { target: "ภาษี", en: "tax", pinyin: "paa-sǐi" },
          { target: "ธุรกิจ", en: "business", pinyin: "tú-rá-kìt" },
          { target: "ลงทุน", en: "to invest", pinyin: "loŋ-tun" },
          { target: "กำไร", en: "profit", pinyin: "kam-rai" },
          { target: "จ่าย", en: "to pay", pinyin: "jàai" },
          { target: "ประหยัด", en: "to save; be thrifty", pinyin: "prà-yàt" },
          { target: "สมัคร", en: "to apply", pinyin: "sà-màk" },
          { target: "ประสบการณ์", en: "experience", pinyin: "prà-sòp-kaan" },
          { target: "ตำแหน่ง", en: "position", pinyin: "tam-nɛ̀ŋ" },
          { target: "ลาออก", en: "to resign", pinyin: "laa-ɔ̀ɔk" },
          { target: "ขยัน", en: "diligent", pinyin: "kà-yǎn" },
          { target: "สำคัญ", en: "important", pinyin: "sǎm-kan" },
          { target: "เงิน", en: "money", pinyin: "ŋən" },
          { target: "งาน", en: "work; job", pinyin: "ŋaan" },
          { target: "ทำงาน", en: "to work", pinyin: "tam-ŋaan" },
          { target: "ใจดี", en: "kind", pinyin: "jai-dii" },
          { target: "น้อย", en: "few; little", pinyin: "nɔ́ɔi" },
          { target: "อยาก", en: "to want to", pinyin: "yàak" },
          { target: "มี", en: "to have", pinyin: "mii" },
          { target: "เขา", en: "he; she", pinyin: "kǎo" },
          { target: "แล้ว", en: "already", pinyin: "lɛ́ɛo" },
          { target: "ที่", en: "at; that", pinyin: "tîi" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ต้อง", en: "must; need to", pinyin: "tɔ̂ŋ" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
        ],
        sentences: [
          { target: "ผม ต้อง ทำงาน", en: "I have to work.", pinyin: "pǒm tɔ̂ŋ tam-ŋaan" },
          { target: "เงินเดือน ผม น้อย", en: "My salary is low.", pinyin: "ŋən-dʉan pǒm nɔ́ɔi" },
          { target: "ผม อยาก ประหยัด เงิน", en: "I want to save money.", pinyin: "pǒm yàak prà-yàt ŋən" },
          { target: "เจ้านาย ผม ใจดี", en: "My boss is kind.", pinyin: "jâo-naai pǒm jai-dii" },
          { target: "ลูกค้า สำคัญ มาก", en: "The customer is very important.", pinyin: "lûuk-káa sǎm-kan mâak" },
          { target: "ผม ต้อง จ่าย ภาษี", en: "I have to pay tax.", pinyin: "pǒm tɔ̂ŋ jàai paa-sǐi" },
          { target: "ผม อยาก สมัคร งาน", en: "I want to apply for a job.", pinyin: "pǒm yàak sà-màk ŋaan" },
          { target: "เขา ขยัน มาก", en: "He is very diligent.", pinyin: "kǎo kà-yǎn mâak" },
          { target: "โครงการ นี้ สำคัญ", en: "This project is important.", pinyin: "kroŋ-kaan níi sǎm-kan" },
          { target: "ผม มี ประสบการณ์", en: "I have experience.", pinyin: "pǒm mii prà-sòp-kaan" },
          { target: "เขา ลาออก แล้ว", en: "He has resigned.", pinyin: "kǎo laa-ɔ̀ɔk lɛ́ɛo" },
          { target: "ผม ทำงาน ที่ ออฟฟิศ", en: "I work at the office.", pinyin: "pǒm tam-ŋaan tîi ɔ́f-fít" },
          { target: "ธุรกิจ มี กำไร", en: "The business is profitable.", pinyin: "tú-rá-kìt mii kam-rai" },
          { target: "ผม ต้อง จ่าย เงิน ครับ", en: "I have to pay.", pinyin: "pǒm tɔ̂ŋ jàai ŋən kráp" },
        ],
      },
      {
        id: "th-ut5",
        title: "Health & body",
        subtitle: "The body, illness and care",
        cefr: "B1",
        color: "#E0584B",
        icon: "🩺",
        vocab: [
          { target: "ร่างกาย", en: "body", pinyin: "râaŋ-kaai" },
          { target: "หัว", en: "head", pinyin: "hǔa" },
          { target: "ตา", en: "eye", pinyin: "taa" },
          { target: "ปาก", en: "mouth", pinyin: "pàak" },
          { target: "มือ", en: "hand", pinyin: "mʉʉ" },
          { target: "เท้า", en: "foot", pinyin: "táao" },
          { target: "ท้อง", en: "stomach", pinyin: "tɔ́ɔŋ" },
          { target: "หมอ", en: "doctor", pinyin: "mɔ̌ɔ" },
          { target: "ยา", en: "medicine", pinyin: "yaa" },
          { target: "ป่วย", en: "to be sick", pinyin: "pùai" },
          { target: "ปวด", en: "to ache", pinyin: "pùat" },
          { target: "ไข้", en: "fever", pinyin: "kâi" },
          { target: "ไอ", en: "to cough", pinyin: "ai" },
          { target: "เจ็บ", en: "to hurt", pinyin: "jèp" },
          { target: "แข็งแรง", en: "strong; healthy", pinyin: "kɛ̌ŋ-rɛɛŋ" },
          { target: "พัก", en: "to rest", pinyin: "pák" },
          { target: "ออกกำลังกาย", en: "to exercise", pinyin: "ɔ̀ɔk-kam-laŋ-kaai" },
          { target: "สุขภาพ", en: "health", pinyin: "sùk-kà-pâap" },
          { target: "หายใจ", en: "to breathe", pinyin: "hǎai-jai" },
          { target: "หาย", en: "to recover", pinyin: "hǎai" },
          { target: "กิน", en: "to eat; take", pinyin: "kin" },
          { target: "หา", en: "to seek; see", pinyin: "hǎa" },
          { target: "ไป", en: "to go", pinyin: "pai" },
          { target: "อยาก", en: "to want to", pinyin: "yàak" },
          { target: "มี", en: "to have", pinyin: "mii" },
          { target: "ทุกวัน", en: "every day", pinyin: "túk-wan" },
          { target: "เขา", en: "he; she", pinyin: "kǎo" },
          { target: "สำคัญ", en: "important", pinyin: "sǎm-kan" },
          { target: "แล้ว", en: "already", pinyin: "lɛ́ɛo" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ต้อง", en: "must; need to", pinyin: "tɔ̂ŋ" },
          { target: "วันนี้", en: "today", pinyin: "wan-níi" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
        ],
        sentences: [
          { target: "วันนี้ ผม ป่วย", en: "I am sick today.", pinyin: "wan-níi pǒm pùai" },
          { target: "ผม ปวด หัว", en: "I have a headache.", pinyin: "pǒm pùat hǔa" },
          { target: "ผม ปวด ท้อง", en: "I have a stomachache.", pinyin: "pǒm pùat tɔ́ɔŋ" },
          { target: "ผม ต้อง กิน ยา", en: "I need to take medicine.", pinyin: "pǒm tɔ̂ŋ kin yaa" },
          { target: "ผม อยาก ไป หา หมอ", en: "I want to see a doctor.", pinyin: "pǒm yàak pai hǎa mɔ̌ɔ" },
          { target: "ผม มี ไข้", en: "I have a fever.", pinyin: "pǒm mii kâi" },
          { target: "ผม ต้อง พัก", en: "I need to rest.", pinyin: "pǒm tɔ̂ŋ pák" },
          { target: "ผม ออกกำลังกาย ทุกวัน", en: "I exercise every day.", pinyin: "pǒm ɔ̀ɔk-kam-laŋ-kaai túk-wan" },
          { target: "เขา แข็งแรง มาก", en: "He is very healthy.", pinyin: "kǎo kɛ̌ŋ-rɛɛŋ mâak" },
          { target: "ตา ผม เจ็บ", en: "My eye hurts.", pinyin: "taa pǒm jèp" },
          { target: "สุขภาพ สำคัญ มาก", en: "Health is very important.", pinyin: "sùk-kà-pâap sǎm-kan mâak" },
          { target: "ผม หาย แล้ว", en: "I have recovered.", pinyin: "pǒm hǎai lɛ́ɛo" },
          { target: "เท้า ผม เจ็บ มาก", en: "My foot hurts a lot.", pinyin: "táao pǒm jèp mâak" },
          { target: "ผม ต้อง พัก ครับ", en: "I need to rest.", pinyin: "pǒm tɔ̂ŋ pák kráp" },
        ],
      },
      {
        id: "th-ut6",
        title: "Travel & directions",
        subtitle: "Find your way and get around",
        cefr: "B1",
        color: "#7A5CD0",
        icon: "🧭",
        vocab: [
          { target: "ทาง", en: "way; route", pinyin: "taaŋ" },
          { target: "ถนน", en: "road; street", pinyin: "tà-nǒn" },
          { target: "ทางแยก", en: "intersection", pinyin: "taaŋ-yɛ̂ɛk" },
          { target: "สะพาน", en: "bridge", pinyin: "sà-paan" },
          { target: "มุม", en: "corner", pinyin: "mum" },
          { target: "ป้าย", en: "sign", pinyin: "pâai" },
          { target: "เหนือ", en: "north", pinyin: "nʉ̌a" },
          { target: "ใต้", en: "south; under", pinyin: "tâai" },
          { target: "ตะวันออก", en: "east", pinyin: "tà-wan-ɔ̀ɔk" },
          { target: "ตะวันตก", en: "west", pinyin: "tà-wan-tòk" },
          { target: "ระยะทาง", en: "distance", pinyin: "rá-yá-taaŋ" },
          { target: "กิโล", en: "kilometer", pinyin: "kì-loo" },
          { target: "เดิน", en: "to walk", pinyin: "dəən" },
          { target: "ข้าม", en: "to cross", pinyin: "kâam" },
          { target: "ผ่าน", en: "to pass", pinyin: "pàan" },
          { target: "หลง", en: "to be lost", pinyin: "lǒŋ" },
          { target: "หา", en: "to look for", pinyin: "hǎa" },
          { target: "จอด", en: "to park", pinyin: "jɔ̀ɔt" },
          { target: "ที่จอดรถ", en: "parking lot", pinyin: "tîi-jɔ̀ɔt-rót" },
          { target: "รถเมล์", en: "bus", pinyin: "rót-mee" },
          { target: "รถ", en: "car", pinyin: "rót" },
          { target: "เลี้ยว", en: "to turn", pinyin: "líao" },
          { target: "ตรง", en: "straight", pinyin: "troŋ" },
          { target: "นั่ง", en: "to sit; ride", pinyin: "nâng" },
          { target: "สถานี", en: "station", pinyin: "sà-thǎa-nii" },
          { target: "ไป", en: "to go", pinyin: "pai" },
          { target: "ห้า", en: "five", pinyin: "hâa" },
          { target: "ที่", en: "at; that", pinyin: "tîi" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "อยาก", en: "to want to", pinyin: "yàak" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
          { target: "ที่ไหน", en: "where", pinyin: "tîi-nǎi" },
        ],
        sentences: [
          { target: "ผม หลง ทาง", en: "I am lost.", pinyin: "pǒm lǒŋ taaŋ" },
          { target: "ที่จอดรถ อยู่ ที่ไหน", en: "Where is the parking lot?", pinyin: "tîi-jɔ̀ɔt-rót yùu tîi-nǎi" },
          { target: "ผม อยาก หา ถนน นี้", en: "I want to find this road.", pinyin: "pǒm yàak hǎa tà-nǒn níi" },
          { target: "เดิน ตรง ไป", en: "Walk straight ahead.", pinyin: "dəən troŋ pai" },
          { target: "ข้าม สะพาน", en: "Cross the bridge.", pinyin: "kâam sà-paan" },
          { target: "เลี้ยว ที่ มุม", en: "Turn at the corner.", pinyin: "líao tîi mum" },
          { target: "ผม นั่ง รถเมล์", en: "I take the bus.", pinyin: "pǒm nâng rót-mee" },
          { target: "ระยะทาง ไกล มาก", en: "The distance is very far.", pinyin: "rá-yá-taaŋ klai mâak" },
          { target: "ผม อยาก จอด รถ", en: "I want to park the car.", pinyin: "pǒm yàak jɔ̀ɔt rót" },
          { target: "ป้าย อยู่ ที่ มุม", en: "The sign is at the corner.", pinyin: "pâai yùu tîi mum" },
          { target: "ผ่าน ทางแยก นี้", en: "Pass this intersection.", pinyin: "pàan taaŋ-yɛ̂ɛk níi" },
          { target: "สถานี อยู่ ทาง เหนือ", en: "The station is to the north.", pinyin: "sà-thǎa-nii yùu taaŋ nʉ̌a" },
          { target: "ผม เดิน ห้า กิโล", en: "I walk five kilometers.", pinyin: "pǒm dəən hâa kì-loo" },
          { target: "ผม หลง ทาง ครับ", en: "I am lost.", pinyin: "pǒm lǒŋ taaŋ kráp" },
        ],
      },
    ],
  },
];
