import type { SectionBlueprint } from "@/curriculum/generate";

// Additional theme-based Thai sections. Hand-authored vocab + sentence banks per
// unit; the generator expands these into many spaced-repetition lessons. Thai
// script uses correct vowels and tone marks. Romanization lives in the `pinyin`
// field and follows the same readable phonetic style as th.ts (à low, á high,
// â falling, ǎ rising, a mid; long vowels doubled). Politeness is kept
// consistent within each example (male speaker: ผม / ครับ). Every sentence uses
// only this unit's vocab plus common function words that are themselves listed
// in the unit's vocab bank.

export const thaiThemeSections: SectionBlueprint[] = [
  {
    id: "th-sT1",
    title: "Themes",
    subtitle: "Broaden your vocabulary",
    units: [
      {
        id: "th-ut1",
        title: "Nature & weather",
        subtitle: "Talk about the world outside",
        cefr: "A2",
        color: "#4CAF82",
        icon: "🌦️",
        vocab: [
          { target: "อากาศ", en: "weather; air", pinyin: "aa-kàat" },
          { target: "ฝน", en: "rain", pinyin: "fǒn" },
          { target: "แดด", en: "sunshine", pinyin: "dɛ̀ɛt" },
          { target: "ลม", en: "wind", pinyin: "lom" },
          { target: "ฟ้า", en: "sky", pinyin: "fáa" },
          { target: "ร้อน", en: "hot", pinyin: "rɔ́ɔn" },
          { target: "หนาว", en: "cold", pinyin: "nǎao" },
          { target: "ต้นไม้", en: "tree", pinyin: "tôn-máai" },
          { target: "ดอกไม้", en: "flower", pinyin: "dɔ̀ɔk-máai" },
          { target: "ภูเขา", en: "mountain", pinyin: "puu-kǎo" },
          { target: "ทะเล", en: "sea", pinyin: "tá-lee" },
          { target: "แม่น้ำ", en: "river", pinyin: "mɛ̂ɛ-náam" },
          { target: "ป่า", en: "forest", pinyin: "pàa" },
          { target: "ตก", en: "to fall", pinyin: "tòk" },
          { target: "สวย", en: "beautiful", pinyin: "sǔai" },
          { target: "ใหญ่", en: "big", pinyin: "yài" },
          { target: "ชอบ", en: "to like", pinyin: "chɔ̂ɔp" },
          { target: "อยู่", en: "to be at", pinyin: "yùu" },
          { target: "บน", en: "on; above", pinyin: "bon" },
          { target: "มี", en: "to have; there is", pinyin: "mii" },
          { target: "วันนี้", en: "today", pinyin: "wan-níi" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
        ],
        sentences: [
          { target: "วันนี้ อากาศ ร้อน", en: "The weather is hot today.", pinyin: "wan-níi aa-kàat rɔ́ɔn" },
          { target: "วันนี้ ฝน ตก", en: "It is raining today.", pinyin: "wan-níi fǒn tòk" },
          { target: "ฟ้า สวย มาก", en: "The sky is very beautiful.", pinyin: "fáa sǔai mâak" },
          { target: "ผม ชอบ ทะเล", en: "I like the sea.", pinyin: "pǒm chɔ̂ɔp tá-lee" },
          { target: "ภูเขา สวย มาก", en: "The mountain is very beautiful.", pinyin: "puu-kǎo sǔai mâak" },
          { target: "วันนี้ หนาว มาก", en: "It is very cold today.", pinyin: "wan-níi nǎao mâak" },
          { target: "วันนี้ มี ลม", en: "It is windy today.", pinyin: "wan-níi mii lom" },
          { target: "ผม ชอบ ดอกไม้", en: "I like flowers.", pinyin: "pǒm chɔ̂ɔp dɔ̀ɔk-máai" },
          { target: "ดอกไม้ อยู่ บน ภูเขา", en: "The flowers are on the mountain.", pinyin: "dɔ̀ɔk-máai yùu bon puu-kǎo" },
          { target: "วันนี้ มี แดด", en: "It is sunny today.", pinyin: "wan-níi mii dɛ̀ɛt" },
          { target: "ป่า ใหญ่ มาก", en: "The forest is very big.", pinyin: "pàa yài mâak" },
          { target: "ผม ชอบ ต้นไม้", en: "I like trees.", pinyin: "pǒm chɔ̂ɔp tôn-máai" },
          { target: "แม่น้ำ สวย มาก ครับ", en: "The river is very beautiful.", pinyin: "mɛ̂ɛ-náam sǔai mâak kráp" },
          { target: "ผม ชอบ ฟ้า", en: "I like the sky.", pinyin: "pǒm chɔ̂ɔp fáa" },
        ],
      },
      {
        id: "th-ut2",
        title: "Emotions & feelings",
        subtitle: "Say how you feel",
        cefr: "A2",
        color: "#E86FA0",
        icon: "😊",
        vocab: [
          { target: "ดีใจ", en: "happy; glad", pinyin: "dii-jai" },
          { target: "เสียใจ", en: "sad", pinyin: "sǐa-jai" },
          { target: "โกรธ", en: "angry", pinyin: "kròot" },
          { target: "กลัว", en: "afraid", pinyin: "klua" },
          { target: "เบื่อ", en: "bored", pinyin: "bʉ̀a" },
          { target: "ตื่นเต้น", en: "excited", pinyin: "tʉ̀ʉn-tên" },
          { target: "เหงา", en: "lonely", pinyin: "ŋǎo" },
          { target: "สนุก", en: "fun", pinyin: "sà-nùk" },
          { target: "มีความสุข", en: "happy", pinyin: "mii-kwaam-sùk" },
          { target: "ภูมิใจ", en: "proud", pinyin: "puum-jai" },
          { target: "ยิ้ม", en: "to smile", pinyin: "yím" },
          { target: "ร้องไห้", en: "to cry", pinyin: "rɔ́ɔŋ-hâi" },
          { target: "รู้สึก", en: "to feel", pinyin: "rúu-sʉ̀k" },
          { target: "เป็นห่วง", en: "to be concerned", pinyin: "pen-hùaŋ" },
          { target: "สบายใจ", en: "at ease; relieved", pinyin: "sà-baai-jai" },
          { target: "เขา", en: "he; she", pinyin: "kǎo" },
          { target: "คุณ", en: "you", pinyin: "kun" },
          { target: "ตอนนี้", en: "now", pinyin: "tɔɔn-níi" },
          { target: "วันนี้", en: "today", pinyin: "wan-níi" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ทำไม", en: "why", pinyin: "tam-mai" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
        ],
        sentences: [
          { target: "วันนี้ ผม ดีใจ", en: "I am happy today.", pinyin: "wan-níi pǒm dii-jai" },
          { target: "ผม รู้สึก เหงา", en: "I feel lonely.", pinyin: "pǒm rúu-sʉ̀k ŋǎo" },
          { target: "ผม มีความสุข มาก", en: "I am very happy.", pinyin: "pǒm mii-kwaam-sùk mâak" },
          { target: "ทำไม คุณ เสียใจ", en: "Why are you sad?", pinyin: "tam-mai kun sǐa-jai" },
          { target: "เขา โกรธ มาก", en: "He is very angry.", pinyin: "kǎo kròot mâak" },
          { target: "ผม กลัว มาก", en: "I am very afraid.", pinyin: "pǒm klua mâak" },
          { target: "วันนี้ สนุก มาก", en: "Today was very fun.", pinyin: "wan-níi sà-nùk mâak" },
          { target: "ผม ตื่นเต้น มาก", en: "I am very excited.", pinyin: "pǒm tʉ̀ʉn-tên mâak" },
          { target: "เขา ยิ้ม", en: "She smiles.", pinyin: "kǎo yím" },
          { target: "ผม เป็นห่วง คุณ", en: "I am concerned about you.", pinyin: "pǒm pen-hùaŋ kun" },
          { target: "ผม เบื่อ มาก", en: "I am very bored.", pinyin: "pǒm bʉ̀a mâak" },
          { target: "เขา ร้องไห้", en: "She is crying.", pinyin: "kǎo rɔ́ɔŋ-hâi" },
          { target: "ผม ภูมิใจ มาก ครับ", en: "I am very proud.", pinyin: "pǒm puum-jai mâak kráp" },
          { target: "ตอนนี้ ผม สบายใจ", en: "Now I feel at ease.", pinyin: "tɔɔn-níi pǒm sà-baai-jai" },
        ],
      },
      {
        id: "th-ut3",
        title: "House & everyday objects",
        subtitle: "Name things around the home",
        cefr: "A2",
        color: "#5B8DEF",
        icon: "🏠",
        vocab: [
          { target: "ห้อง", en: "room", pinyin: "hɔ̂ŋ" },
          { target: "ห้องนอน", en: "bedroom", pinyin: "hɔ̂ŋ-nɔɔn" },
          { target: "ห้องน้ำ", en: "bathroom", pinyin: "hɔ̂ŋ-náam" },
          { target: "ห้องครัว", en: "kitchen", pinyin: "hɔ̂ŋ-krua" },
          { target: "ประตู", en: "door", pinyin: "prà-tuu" },
          { target: "หน้าต่าง", en: "window", pinyin: "nâa-tàaŋ" },
          { target: "โต๊ะ", en: "table", pinyin: "tó" },
          { target: "เตียง", en: "bed", pinyin: "tiaŋ" },
          { target: "ตู้", en: "cupboard", pinyin: "tûu" },
          { target: "ไฟ", en: "light", pinyin: "fai" },
          { target: "กุญแจ", en: "key", pinyin: "kun-jɛɛ" },
          { target: "นาฬิกา", en: "clock", pinyin: "naa-lí-kaa" },
          { target: "เปิด", en: "to open; turn on", pinyin: "pə̀ət" },
          { target: "ปิด", en: "to close; turn off", pinyin: "pìt" },
          { target: "ช่วย", en: "please; to help", pinyin: "chûai" },
          { target: "อยู่", en: "to be at", pinyin: "yùu" },
          { target: "นอน", en: "to sleep", pinyin: "nɔɔn" },
          { target: "บน", en: "on; above", pinyin: "bon" },
          { target: "ใน", en: "in; inside", pinyin: "nai" },
          { target: "ใหญ่", en: "big", pinyin: "yài" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ที่ไหน", en: "where", pinyin: "tîi-nǎi" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
        ],
        sentences: [
          { target: "ผม อยู่ ใน ห้อง", en: "I am in the room.", pinyin: "pǒm yùu nai hɔ̂ŋ" },
          { target: "กุญแจ อยู่ บน โต๊ะ", en: "The key is on the table.", pinyin: "kun-jɛɛ yùu bon tó" },
          { target: "ช่วย เปิด ประตู", en: "Please open the door.", pinyin: "chûai pə̀ət prà-tuu" },
          { target: "ช่วย ปิด ไฟ", en: "Please turn off the light.", pinyin: "chûai pìt fai" },
          { target: "ห้องน้ำ อยู่ ที่ไหน", en: "Where is the bathroom?", pinyin: "hɔ̂ŋ-náam yùu tîi-nǎi" },
          { target: "เตียง อยู่ ใน ห้องนอน", en: "The bed is in the bedroom.", pinyin: "tiaŋ yùu nai hɔ̂ŋ-nɔɔn" },
          { target: "ตู้ ใหญ่ มาก", en: "The cupboard is very big.", pinyin: "tûu yài mâak" },
          { target: "ไฟ อยู่ ใน ห้อง", en: "The light is in the room.", pinyin: "fai yùu nai hɔ̂ŋ" },
          { target: "ผม นอน บน เตียง", en: "I sleep on the bed.", pinyin: "pǒm nɔɔn bon tiaŋ" },
          { target: "ช่วย เปิด หน้าต่าง", en: "Please open the window.", pinyin: "chûai pə̀ət nâa-tàaŋ" },
          { target: "นาฬิกา อยู่ บน โต๊ะ", en: "The clock is on the table.", pinyin: "naa-lí-kaa yùu bon tó" },
          { target: "กุญแจ อยู่ ใน ตู้", en: "The key is in the cupboard.", pinyin: "kun-jɛɛ yùu nai tûu" },
          { target: "ห้องครัว ใหญ่ มาก ครับ", en: "The kitchen is very big.", pinyin: "hɔ̂ŋ-krua yài mâak kráp" },
          { target: "ช่วย ปิด ประตู", en: "Please close the door.", pinyin: "chûai pìt prà-tuu" },
        ],
      },
    ],
  },
  {
    id: "th-sT2",
    title: "Real life",
    subtitle: "Talk about the wider world",
    units: [
      {
        id: "th-ut4",
        title: "Work & money",
        subtitle: "Jobs, pay and the workplace",
        cefr: "B1",
        color: "#2E9E8F",
        icon: "💰",
        vocab: [
          { target: "เงินเดือน", en: "salary", pinyin: "ŋən-dʉan" },
          { target: "เจ้านาย", en: "boss", pinyin: "jâo-naai" },
          { target: "โครงการ", en: "project", pinyin: "kroŋ-kaan" },
          { target: "ออฟฟิศ", en: "office", pinyin: "ɔ́f-fít" },
          { target: "ภาษี", en: "tax", pinyin: "paa-sǐi" },
          { target: "ธุรกิจ", en: "business", pinyin: "tú-rá-kìt" },
          { target: "จ่าย", en: "to pay", pinyin: "jàai" },
          { target: "ประหยัด", en: "to save; be thrifty", pinyin: "prà-yàt" },
          { target: "ขยัน", en: "diligent", pinyin: "kà-yǎn" },
          { target: "สำคัญ", en: "important", pinyin: "sǎm-kan" },
          { target: "เงิน", en: "money", pinyin: "ŋən" },
          { target: "งาน", en: "work; job", pinyin: "ŋaan" },
          { target: "ทำงาน", en: "to work", pinyin: "tam-ŋaan" },
          { target: "น้อย", en: "few; little", pinyin: "nɔ́ɔi" },
          { target: "อยาก", en: "to want to", pinyin: "yàak" },
          { target: "มี", en: "to have", pinyin: "mii" },
          { target: "เขา", en: "he; she", pinyin: "kǎo" },
          { target: "แล้ว", en: "already", pinyin: "lɛ́ɛo" },
          { target: "ที่", en: "at; that", pinyin: "tîi" },
          { target: "นี้", en: "this", pinyin: "níi" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ต้อง", en: "must; need to", pinyin: "tɔ̂ŋ" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
        ],
        sentences: [
          { target: "ผม ต้อง ทำงาน", en: "I have to work.", pinyin: "pǒm tɔ̂ŋ tam-ŋaan" },
          { target: "เงินเดือน ผม น้อย", en: "My salary is low.", pinyin: "ŋən-dʉan pǒm nɔ́ɔi" },
          { target: "ผม อยาก ประหยัด เงิน", en: "I want to save money.", pinyin: "pǒm yàak prà-yàt ŋən" },
          { target: "เจ้านาย ผม ขยัน", en: "My boss is diligent.", pinyin: "jâo-naai pǒm kà-yǎn" },
          { target: "งาน นี้ สำคัญ มาก", en: "This job is very important.", pinyin: "ŋaan níi sǎm-kan mâak" },
          { target: "ผม ต้อง จ่าย ภาษี", en: "I have to pay tax.", pinyin: "pǒm tɔ̂ŋ jàai paa-sǐi" },
          { target: "ผม อยาก มี งาน", en: "I want to have a job.", pinyin: "pǒm yàak mii ŋaan" },
          { target: "เขา ขยัน มาก", en: "He is very diligent.", pinyin: "kǎo kà-yǎn mâak" },
          { target: "โครงการ นี้ สำคัญ", en: "This project is important.", pinyin: "kroŋ-kaan níi sǎm-kan" },
          { target: "ผม มี โครงการ", en: "I have a project.", pinyin: "pǒm mii kroŋ-kaan" },
          { target: "เขา จ่าย แล้ว", en: "He has paid already.", pinyin: "kǎo jàai lɛ́ɛo" },
          { target: "ผม ทำงาน ที่ ออฟฟิศ", en: "I work at the office.", pinyin: "pǒm tam-ŋaan tîi ɔ́f-fít" },
          { target: "ธุรกิจ สำคัญ มาก", en: "Business is very important.", pinyin: "tú-rá-kìt sǎm-kan mâak" },
          { target: "ผม ต้อง จ่าย เงิน ครับ", en: "I have to pay.", pinyin: "pǒm tɔ̂ŋ jàai ŋən kráp" },
        ],
      },
      {
        id: "th-ut5",
        title: "Health & body",
        subtitle: "The body, illness and care",
        cefr: "B1",
        color: "#E0584B",
        icon: "🩺",
        vocab: [
          { target: "หัว", en: "head", pinyin: "hǔa" },
          { target: "ท้อง", en: "stomach", pinyin: "tɔ́ɔŋ" },
          { target: "หมอ", en: "doctor", pinyin: "mɔ̌ɔ" },
          { target: "ยา", en: "medicine", pinyin: "yaa" },
          { target: "ป่วย", en: "to be sick", pinyin: "pùai" },
          { target: "ปวด", en: "to ache", pinyin: "pùat" },
          { target: "ไข้", en: "fever", pinyin: "kâi" },
          { target: "เจ็บ", en: "to hurt", pinyin: "jèp" },
          { target: "แข็งแรง", en: "strong; healthy", pinyin: "kɛ̌ŋ-rɛɛŋ" },
          { target: "พัก", en: "to rest", pinyin: "pák" },
          { target: "สุขภาพ", en: "health", pinyin: "sùk-kà-pâap" },
          { target: "กิน", en: "to eat; take", pinyin: "kin" },
          { target: "หา", en: "to seek; see", pinyin: "hǎa" },
          { target: "อยาก", en: "to want to", pinyin: "yàak" },
          { target: "มี", en: "to have", pinyin: "mii" },
          { target: "ทุกวัน", en: "every day", pinyin: "túk-wan" },
          { target: "เขา", en: "he; she", pinyin: "kǎo" },
          { target: "สำคัญ", en: "important", pinyin: "sǎm-kan" },
          { target: "แล้ว", en: "already", pinyin: "lɛ́ɛo" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ต้อง", en: "must; need to", pinyin: "tɔ̂ŋ" },
          { target: "วันนี้", en: "today", pinyin: "wan-níi" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
        ],
        sentences: [
          { target: "วันนี้ ผม ป่วย", en: "I am sick today.", pinyin: "wan-níi pǒm pùai" },
          { target: "ผม ปวด หัว", en: "I have a headache.", pinyin: "pǒm pùat hǔa" },
          { target: "ผม ปวด ท้อง", en: "I have a stomachache.", pinyin: "pǒm pùat tɔ́ɔŋ" },
          { target: "ผม ต้อง กิน ยา", en: "I need to take medicine.", pinyin: "pǒm tɔ̂ŋ kin yaa" },
          { target: "ผม อยาก หา หมอ", en: "I want to see a doctor.", pinyin: "pǒm yàak hǎa mɔ̌ɔ" },
          { target: "ผม มี ไข้", en: "I have a fever.", pinyin: "pǒm mii kâi" },
          { target: "ผม ต้อง พัก", en: "I need to rest.", pinyin: "pǒm tɔ̂ŋ pák" },
          { target: "ผม กิน ยา ทุกวัน", en: "I take medicine every day.", pinyin: "pǒm kin yaa túk-wan" },
          { target: "เขา แข็งแรง มาก", en: "He is very healthy.", pinyin: "kǎo kɛ̌ŋ-rɛɛŋ mâak" },
          { target: "ท้อง ผม เจ็บ", en: "My stomach hurts.", pinyin: "tɔ́ɔŋ pǒm jèp" },
          { target: "สุขภาพ สำคัญ มาก", en: "Health is very important.", pinyin: "sùk-kà-pâap sǎm-kan mâak" },
          { target: "ผม พัก แล้ว", en: "I have rested.", pinyin: "pǒm pák lɛ́ɛo" },
          { target: "หัว ผม เจ็บ มาก", en: "My head hurts a lot.", pinyin: "hǔa pǒm jèp mâak" },
          { target: "ผม ต้อง พัก ครับ", en: "I need to rest.", pinyin: "pǒm tɔ̂ŋ pák kráp" },
        ],
      },
      {
        id: "th-ut6",
        title: "Travel & directions",
        subtitle: "Find your way and get around",
        cefr: "B1",
        color: "#7A5CD0",
        icon: "🧭",
        vocab: [
          { target: "ทาง", en: "way; route", pinyin: "taaŋ" },
          { target: "ถนน", en: "road; street", pinyin: "tà-nǒn" },
          { target: "ทางแยก", en: "intersection", pinyin: "taaŋ-yɛ̂ɛk" },
          { target: "สะพาน", en: "bridge", pinyin: "sà-paan" },
          { target: "มุม", en: "corner", pinyin: "mum" },
          { target: "ป้าย", en: "sign", pinyin: "pâai" },
          { target: "เหนือ", en: "north", pinyin: "nʉ̌a" },
          { target: "ระยะทาง", en: "distance", pinyin: "rá-yá-taaŋ" },
          { target: "กิโล", en: "kilometer", pinyin: "kì-loo" },
          { target: "เดิน", en: "to walk", pinyin: "dəən" },
          { target: "ข้าม", en: "to cross", pinyin: "kâam" },
          { target: "ผ่าน", en: "to pass", pinyin: "pàan" },
          { target: "หลง", en: "to be lost", pinyin: "lǒŋ" },
          { target: "หา", en: "to look for", pinyin: "hǎa" },
          { target: "จอด", en: "to park", pinyin: "jɔ̀ɔt" },
          { target: "ที่จอดรถ", en: "parking lot", pinyin: "tîi-jɔ̀ɔt-rót" },
          { target: "รถเมล์", en: "bus", pinyin: "rót-mee" },
          { target: "รถ", en: "car", pinyin: "rót" },
          { target: "เลี้ยว", en: "to turn", pinyin: "líao" },
          { target: "ตรง", en: "straight", pinyin: "troŋ" },
          { target: "นั่ง", en: "to sit; ride", pinyin: "nâng" },
          { target: "สถานี", en: "station", pinyin: "sà-thǎa-nii" },
          { target: "ไป", en: "to go", pinyin: "pai" },
          { target: "ไกล", en: "far", pinyin: "klai" },
          { target: "ห้า", en: "five", pinyin: "hâa" },
          { target: "อยู่", en: "to be at", pinyin: "yùu" },
          { target: "ที่", en: "at; that", pinyin: "tîi" },
          { target: "นี้", en: "this", pinyin: "níi" },
          { target: "มาก", en: "very; a lot", pinyin: "mâak" },
          { target: "ผม", en: "I (male)", pinyin: "pǒm" },
          { target: "อยาก", en: "to want to", pinyin: "yàak" },
          { target: "ครับ", en: "(polite, male)", pinyin: "kráp" },
          { target: "ที่ไหน", en: "where", pinyin: "tîi-nǎi" },
        ],
        sentences: [
          { target: "ผม หลง ทาง", en: "I am lost.", pinyin: "pǒm lǒŋ taaŋ" },
          { target: "ที่จอดรถ อยู่ ที่ไหน", en: "Where is the parking lot?", pinyin: "tîi-jɔ̀ɔt-rót yùu tîi-nǎi" },
          { target: "ผม อยาก หา ถนน นี้", en: "I want to find this road.", pinyin: "pǒm yàak hǎa tà-nǒn níi" },
          { target: "ผม เดิน ไป", en: "I walk there.", pinyin: "pǒm dəən pai" },
          { target: "ผม ข้าม ถนน", en: "I cross the road.", pinyin: "pǒm kâam tà-nǒn" },
          { target: "เลี้ยว ที่ มุม", en: "Turn at the corner.", pinyin: "líao tîi mum" },
          { target: "ผม นั่ง รถ", en: "I ride in the car.", pinyin: "pǒm nâng rót" },
          { target: "ทาง ไกล มาก", en: "The way is very far.", pinyin: "taaŋ klai mâak" },
          { target: "ผม อยาก จอด รถ", en: "I want to park the car.", pinyin: "pǒm yàak jɔ̀ɔt rót" },
          { target: "ป้าย อยู่ ที่ มุม", en: "The sign is at the corner.", pinyin: "pâai yùu tîi mum" },
          { target: "ผม ผ่าน ถนน นี้", en: "I pass this road.", pinyin: "pǒm pàan tà-nǒn níi" },
          { target: "ป้าย อยู่ ทาง นี้", en: "The sign is this way.", pinyin: "pâai yùu taaŋ níi" },
          { target: "ผม จอด รถ ที่ นี้", en: "I park the car here.", pinyin: "pǒm jɔ̀ɔt rót tîi níi" },
          { target: "ผม หลง ทาง ครับ", en: "I am lost.", pinyin: "pǒm lǒŋ taaŋ kráp" },
        ],
      },
    ],
  },
];
