import type { CourseBlueprint } from "@/curriculum/generate";

// Mandarin Chinese course blueprint. Hand-authored vocab + sentence banks per
// unit; the generator expands these into many spaced-repetition lessons.
// Characters are Simplified. Pinyin uses tone marks and is verified per item.

export const chineseBlueprint: CourseBlueprint = {
  code: "zh",
  name: "Chinese",
  endonym: "中文",
  flag: "🇨🇳",
  fromLanguage: "English",
  speechLocale: "zh-CN",
  sections: [
    {
      id: "zh-s1",
      title: "Rookie",
      subtitle: "First words and everyday basics",
      units: [
        {
          id: "zh-u1",
          title: "Greetings",
          subtitle: "Say hello and be polite",
          cefr: "A1",
          color: "#E2483D",
          icon: "👋",
          teach: [
            {
              title: "Characters & pinyin",
              body:
                "Chinese is written with characters (汉字), where each character is one syllable and usually one unit of meaning. You don't read them phonetically — you learn them.\n\nTo help, every character here shows pinyin: its sound written in our alphabet. Read the pinyin to say it; recognize the character with repetition. 你好 = nǐ hǎo = \"hello\".",
              examples: [
                { target: "你", en: "you", pinyin: "nǐ" },
                { target: "好", en: "good", pinyin: "hǎo" },
                { target: "你好", en: "hello", pinyin: "nǐ hǎo" },
              ],
            },
            {
              title: "The four tones",
              body:
                "Mandarin is tonal: the pitch of a syllable changes its meaning. Pinyin marks four tones (plus a neutral one) with accents over the vowel:\n\n• mā (ā) — high & flat\n• má (á) — rising, like a question\n• mǎ (ǎ) — dip down then up\n• mà (à) — sharp falling\n\nSame \"ma\", four meanings (mother, hemp, horse, scold). Copy the audio closely.",
              examples: [
                { target: "妈", en: "mother", pinyin: "mā" },
                { target: "马", en: "horse", pinyin: "mǎ" },
              ],
            },
          ],
          vocab: [
            { target: "你", en: "you", pinyin: "nǐ" },
            { target: "好", en: "good", pinyin: "hǎo" },
            { target: "你好", en: "hello", pinyin: "nǐ hǎo" },
            { target: "我", en: "I; me", pinyin: "wǒ" },
            { target: "是", en: "to be", pinyin: "shì" },
            { target: "不", en: "not", pinyin: "bù" },
            { target: "谢谢", en: "thank you", pinyin: "xièxie" },
            { target: "再见", en: "goodbye", pinyin: "zàijiàn" },
            { target: "是的", en: "yes", pinyin: "shì de" },
            { target: "对不起", en: "sorry", pinyin: "duìbuqǐ" },
            { target: "没关系", en: "it's okay", pinyin: "méi guānxi" },
            { target: "请", en: "please", pinyin: "qǐng" },
            { target: "早上好", en: "good morning", pinyin: "zǎoshang hǎo" },
            { target: "晚安", en: "good night", pinyin: "wǎn'ān" },
            { target: "他", en: "he; him", pinyin: "tā" },
            { target: "她", en: "she; her", pinyin: "tā" },
            { target: "叫", en: "to be called", pinyin: "jiào" },
            { target: "名字", en: "name", pinyin: "míngzi" },
            { target: "什么", en: "what", pinyin: "shénme" },
            { target: "很", en: "very", pinyin: "hěn" },
            { target: "高兴", en: "happy; glad", pinyin: "gāoxìng" },
            { target: "认识", en: "to know (someone)", pinyin: "rènshi" },
          ],
          sentences: [
            { target: "你 好", en: "Hello.", pinyin: "nǐ hǎo" },
            { target: "谢谢 你", en: "Thank you.", pinyin: "xièxie nǐ" },
            { target: "我 很 好", en: "I am very well.", pinyin: "wǒ hěn hǎo" },
            { target: "对不起", en: "I'm sorry.", pinyin: "duìbuqǐ" },
            { target: "没关系", en: "It's okay.", pinyin: "méi guānxi" },
            { target: "他 是 我", en: "He is me.", pinyin: "tā shì wǒ" },
            { target: "我 叫 她", en: "I call her.", pinyin: "wǒ jiào tā" },
            { target: "你 叫 什么 名字", en: "What is your name?", pinyin: "nǐ jiào shénme míngzi" },
            { target: "早上好", en: "Good morning.", pinyin: "zǎoshang hǎo" },
            { target: "晚安", en: "Good night.", pinyin: "wǎn'ān" },
            { target: "再见", en: "Goodbye.", pinyin: "zàijiàn" },
            { target: "请", en: "Please.", pinyin: "qǐng" },
            { target: "我 很 高兴", en: "I am very glad.", pinyin: "wǒ hěn gāoxìng" },
            { target: "认识 你 很 高兴", en: "Nice to meet you.", pinyin: "rènshi nǐ hěn gāoxìng" },
          ],
        },
        {
          id: "zh-u2",
          title: "Numbers",
          subtitle: "Count from one to a hundred",
          cefr: "A1",
          color: "#F4A23B",
          icon: "🔢",
          vocab: [
            { target: "一", en: "one", pinyin: "yī" },
            { target: "二", en: "two", pinyin: "èr" },
            { target: "三", en: "three", pinyin: "sān" },
            { target: "四", en: "four", pinyin: "sì" },
            { target: "五", en: "five", pinyin: "wǔ" },
            { target: "六", en: "six", pinyin: "liù" },
            { target: "七", en: "seven", pinyin: "qī" },
            { target: "八", en: "eight", pinyin: "bā" },
            { target: "九", en: "nine", pinyin: "jiǔ" },
            { target: "十", en: "ten", pinyin: "shí" },
            { target: "零", en: "zero", pinyin: "líng" },
            { target: "百", en: "hundred", pinyin: "bǎi" },
            { target: "两", en: "two (of)", pinyin: "liǎng" },
            { target: "个", en: "(measure word)", pinyin: "gè" },
            { target: "几", en: "how many", pinyin: "jǐ" },
            { target: "多少", en: "how many; how much", pinyin: "duōshao" },
            { target: "岁", en: "years old", pinyin: "suì" },
            { target: "号", en: "number; day of month", pinyin: "hào" },
            { target: "块", en: "yuan (kuai)", pinyin: "kuài" },
            { target: "有", en: "to have", pinyin: "yǒu" },
            { target: "和", en: "and", pinyin: "hé" },
            { target: "的", en: "(possessive)", pinyin: "de" },
          ],
          sentences: [
            { target: "一 二 三", en: "One, two, three.", pinyin: "yī èr sān" },
            { target: "我 有 三 个", en: "I have three.", pinyin: "wǒ yǒu sān gè" },
            { target: "几 个", en: "How many?", pinyin: "jǐ gè" },
            { target: "我 有 两 个", en: "I have two.", pinyin: "wǒ yǒu liǎng gè" },
            { target: "多少 块", en: "How many yuan?", pinyin: "duōshao kuài" },
            { target: "五 块", en: "Five yuan.", pinyin: "wǔ kuài" },
            { target: "你 几 岁", en: "How old are you?", pinyin: "nǐ jǐ suì" },
            { target: "我 十 岁", en: "I am ten years old.", pinyin: "wǒ shí suì" },
            { target: "八 号", en: "The eighth.", pinyin: "bā hào" },
            { target: "一百", en: "One hundred.", pinyin: "yì bǎi" },
            { target: "六 和 七", en: "Six and seven.", pinyin: "liù hé qī" },
            { target: "我 的 四 个", en: "My four.", pinyin: "wǒ de sì gè" },
            { target: "你 有 多少", en: "How many do you have?", pinyin: "nǐ yǒu duōshao" },
            { target: "九 块", en: "Nine yuan.", pinyin: "jiǔ kuài" },
          ],
        },
        {
          id: "zh-u3",
          title: "Family & people",
          subtitle: "Talk about your family",
          cefr: "A1",
          color: "#3FB27F",
          icon: "👨‍👩‍👧",
          vocab: [
            { target: "妈妈", en: "mom", pinyin: "māma" },
            { target: "爸爸", en: "dad", pinyin: "bàba" },
            { target: "哥哥", en: "older brother", pinyin: "gēge" },
            { target: "姐姐", en: "older sister", pinyin: "jiějie" },
            { target: "弟弟", en: "younger brother", pinyin: "dìdi" },
            { target: "妹妹", en: "younger sister", pinyin: "mèimei" },
            { target: "家", en: "home; family", pinyin: "jiā" },
            { target: "人", en: "person", pinyin: "rén" },
            { target: "孩子", en: "child", pinyin: "háizi" },
            { target: "朋友", en: "friend", pinyin: "péngyou" },
            { target: "老师", en: "teacher", pinyin: "lǎoshī" },
            { target: "学生", en: "student", pinyin: "xuésheng" },
            { target: "男", en: "male", pinyin: "nán" },
            { target: "女", en: "female", pinyin: "nǚ" },
            { target: "爱", en: "to love", pinyin: "ài" },
            { target: "们", en: "(plural)", pinyin: "men" },
            { target: "我们", en: "we; us", pinyin: "wǒmen" },
            { target: "这", en: "this", pinyin: "zhè" },
            { target: "那", en: "that", pinyin: "nà" },
            { target: "谁", en: "who", pinyin: "shéi" },
            { target: "大", en: "big", pinyin: "dà" },
            { target: "小", en: "small", pinyin: "xiǎo" },
          ],
          sentences: [
            { target: "这 是 我 妈妈", en: "This is my mom.", pinyin: "zhè shì wǒ māma" },
            { target: "那 是 谁", en: "Who is that?", pinyin: "nà shì shéi" },
            { target: "他 是 我 爸爸", en: "He is my dad.", pinyin: "tā shì wǒ bàba" },
            { target: "我 爱 我 家", en: "I love my family.", pinyin: "wǒ ài wǒ jiā" },
            { target: "我 有 一 个 哥哥", en: "I have an older brother.", pinyin: "wǒ yǒu yí gè gēge" },
            { target: "她 是 老师", en: "She is a teacher.", pinyin: "tā shì lǎoshī" },
            { target: "我们 是 学生", en: "We are students.", pinyin: "wǒmen shì xuésheng" },
            { target: "他 是 我 朋友", en: "He is my friend.", pinyin: "tā shì wǒ péngyou" },
            { target: "这 个 孩子 很 小", en: "This child is small.", pinyin: "zhège háizi hěn xiǎo" },
            { target: "我 妹妹 很 小", en: "My younger sister is small.", pinyin: "wǒ mèimei hěn xiǎo" },
            { target: "你 家 有 几 个 人", en: "How many people in your family?", pinyin: "nǐ jiā yǒu jǐ gè rén" },
            { target: "我 姐姐 很 大", en: "My older sister is big.", pinyin: "wǒ jiějie hěn dà" },
            { target: "他们 是 我 朋友", en: "They are my friends.", pinyin: "tāmen shì wǒ péngyou" },
            { target: "我 爱 妈妈", en: "I love mom.", pinyin: "wǒ ài māma" },
          ],
        },
        {
          id: "zh-u4",
          title: "Food & drink",
          subtitle: "Order food and drinks",
          cefr: "A1",
          color: "#C45BD0",
          icon: "🍜",
          vocab: [
            { target: "水", en: "water", pinyin: "shuǐ" },
            { target: "茶", en: "tea", pinyin: "chá" },
            { target: "咖啡", en: "coffee", pinyin: "kāfēi" },
            { target: "饭", en: "rice; meal", pinyin: "fàn" },
            { target: "米饭", en: "cooked rice", pinyin: "mǐfàn" },
            { target: "菜", en: "dish; vegetable", pinyin: "cài" },
            { target: "肉", en: "meat", pinyin: "ròu" },
            { target: "鸡蛋", en: "egg", pinyin: "jīdàn" },
            { target: "面条", en: "noodles", pinyin: "miàntiáo" },
            { target: "水果", en: "fruit", pinyin: "shuǐguǒ" },
            { target: "苹果", en: "apple", pinyin: "píngguǒ" },
            { target: "牛奶", en: "milk", pinyin: "niúnǎi" },
            { target: "吃", en: "to eat", pinyin: "chī" },
            { target: "喝", en: "to drink", pinyin: "hē" },
            { target: "喜欢", en: "to like", pinyin: "xǐhuan" },
            { target: "想", en: "to want", pinyin: "xiǎng" },
            { target: "要", en: "to want; need", pinyin: "yào" },
            { target: "好吃", en: "delicious", pinyin: "hǎochī" },
            { target: "好喝", en: "tasty (drink)", pinyin: "hǎohē" },
            { target: "杯", en: "cup (measure)", pinyin: "bēi" },
            { target: "吗", en: "(question)", pinyin: "ma" },
            { target: "也", en: "also", pinyin: "yě" },
          ],
          sentences: [
            { target: "我 喜欢 喝 茶", en: "I like to drink tea.", pinyin: "wǒ xǐhuan hē chá" },
            { target: "我 想 喝 水", en: "I want to drink water.", pinyin: "wǒ xiǎng hē shuǐ" },
            { target: "我 要 一 杯 咖啡", en: "I want a cup of coffee.", pinyin: "wǒ yào yì bēi kāfēi" },
            { target: "你 喜欢 吃 肉 吗", en: "Do you like to eat meat?", pinyin: "nǐ xǐhuan chī ròu ma" },
            { target: "米饭 很 好吃", en: "The rice is delicious.", pinyin: "mǐfàn hěn hǎochī" },
            { target: "茶 很 好喝", en: "The tea is tasty.", pinyin: "chá hěn hǎohē" },
            { target: "我 想 吃 面条", en: "I want to eat noodles.", pinyin: "wǒ xiǎng chī miàntiáo" },
            { target: "我 也 喜欢 苹果", en: "I also like apples.", pinyin: "wǒ yě xǐhuan píngguǒ" },
            { target: "我 要 吃 菜", en: "I want to eat vegetables.", pinyin: "wǒ yào chī cài" },
            { target: "他 喝 牛奶", en: "He drinks milk.", pinyin: "tā hē niúnǎi" },
            { target: "我 喜欢 吃 水果", en: "I like to eat fruit.", pinyin: "wǒ xǐhuan chī shuǐguǒ" },
            { target: "你 要 喝 咖啡 吗", en: "Do you want to drink coffee?", pinyin: "nǐ yào hē kāfēi ma" },
            { target: "鸡蛋 很 好吃", en: "The egg is delicious.", pinyin: "jīdàn hěn hǎochī" },
            { target: "我 想 吃 饭", en: "I want to eat.", pinyin: "wǒ xiǎng chī fàn" },
          ],
        },
      ],
    },
    {
      id: "zh-s2",
      title: "Explorer",
      subtitle: "Get around and handle daily life",
      units: [
        {
          id: "zh-u5",
          title: "Around town",
          subtitle: "Places and directions",
          cefr: "A2",
          color: "#3B82C4",
          icon: "🏙️",
          vocab: [
            { target: "在", en: "to be at; in", pinyin: "zài" },
            { target: "这里", en: "here", pinyin: "zhèlǐ" },
            { target: "那里", en: "there", pinyin: "nàlǐ" },
            { target: "哪里", en: "where", pinyin: "nǎlǐ" },
            { target: "学校", en: "school", pinyin: "xuéxiào" },
            { target: "医院", en: "hospital", pinyin: "yīyuàn" },
            { target: "商店", en: "shop; store", pinyin: "shāngdiàn" },
            { target: "饭馆", en: "restaurant", pinyin: "fànguǎn" },
            { target: "银行", en: "bank", pinyin: "yínháng" },
            { target: "车站", en: "station", pinyin: "chēzhàn" },
            { target: "路", en: "road", pinyin: "lù" },
            { target: "去", en: "to go", pinyin: "qù" },
            { target: "来", en: "to come", pinyin: "lái" },
            { target: "走", en: "to walk; leave", pinyin: "zǒu" },
            { target: "左", en: "left", pinyin: "zuǒ" },
            { target: "右", en: "right", pinyin: "yòu" },
            { target: "前面", en: "in front", pinyin: "qiánmiàn" },
            { target: "后面", en: "behind", pinyin: "hòumiàn" },
            { target: "远", en: "far", pinyin: "yuǎn" },
            { target: "近", en: "near", pinyin: "jìn" },
            { target: "怎么", en: "how", pinyin: "zěnme" },
            { target: "请问", en: "excuse me", pinyin: "qǐngwèn" },
          ],
          sentences: [
            { target: "你 在 哪里", en: "Where are you?", pinyin: "nǐ zài nǎlǐ" },
            { target: "我 在 学校", en: "I am at school.", pinyin: "wǒ zài xuéxiào" },
            { target: "商店 在 哪里", en: "Where is the shop?", pinyin: "shāngdiàn zài nǎlǐ" },
            { target: "请问 银行 在 哪里", en: "Excuse me, where is the bank?", pinyin: "qǐngwèn yínháng zài nǎlǐ" },
            { target: "我 要 去 医院", en: "I want to go to the hospital.", pinyin: "wǒ yào qù yīyuàn" },
            { target: "车站 很 远", en: "The station is far.", pinyin: "chēzhàn hěn yuǎn" },
            { target: "学校 很 近", en: "The school is near.", pinyin: "xuéxiào hěn jìn" },
            { target: "车站 在 后面", en: "The station is behind.", pinyin: "chēzhàn zài hòumiàn" },
            { target: "饭馆 在 前面", en: "The restaurant is in front.", pinyin: "fànguǎn zài qiánmiàn" },
            { target: "怎么 去 车站", en: "How to get to the station?", pinyin: "zěnme qù chēzhàn" },
            { target: "我 来 这里", en: "I come here.", pinyin: "wǒ lái zhèlǐ" },
            { target: "他 在 那里", en: "He is there.", pinyin: "tā zài nàlǐ" },
            { target: "银行 在 前面", en: "The bank is in front.", pinyin: "yínháng zài qiánmiàn" },
            { target: "我 想 去 商店", en: "I want to go to the shop.", pinyin: "wǒ xiǎng qù shāngdiàn" },
          ],
        },
        {
          id: "zh-u6",
          title: "Daily life",
          subtitle: "Time, days and routines",
          cefr: "A2",
          color: "#7C6FE0",
          icon: "⏰",
          vocab: [
            { target: "今天", en: "today", pinyin: "jīntiān" },
            { target: "明天", en: "tomorrow", pinyin: "míngtiān" },
            { target: "昨天", en: "yesterday", pinyin: "zuótiān" },
            { target: "现在", en: "now", pinyin: "xiànzài" },
            { target: "点", en: "o'clock", pinyin: "diǎn" },
            { target: "分", en: "minute", pinyin: "fēn" },
            { target: "时候", en: "time; moment", pinyin: "shíhou" },
            { target: "星期", en: "week", pinyin: "xīngqī" },
            { target: "年", en: "year", pinyin: "nián" },
            { target: "月", en: "month", pinyin: "yuè" },
            { target: "天", en: "day", pinyin: "tiān" },
            { target: "起床", en: "to get up", pinyin: "qǐchuáng" },
            { target: "睡觉", en: "to sleep", pinyin: "shuìjiào" },
            { target: "工作", en: "to work; job", pinyin: "gōngzuò" },
            { target: "上班", en: "to go to work", pinyin: "shàngbān" },
            { target: "看", en: "to look; watch", pinyin: "kàn" },
            { target: "做", en: "to do; make", pinyin: "zuò" },
            { target: "回家", en: "to go home", pinyin: "huí jiā" },
            { target: "每天", en: "every day", pinyin: "měitiān" },
            { target: "什么时候", en: "when", pinyin: "shénme shíhou" },
            { target: "了", en: "(completed)", pinyin: "le" },
            { target: "都", en: "all; both", pinyin: "dōu" },
          ],
          sentences: [
            { target: "现在 几 点", en: "What time is it now?", pinyin: "xiànzài jǐ diǎn" },
            { target: "现在 三 点", en: "It's three o'clock.", pinyin: "xiànzài sān diǎn" },
            { target: "今天 星期 几", en: "What day is it today?", pinyin: "jīntiān xīngqī jǐ" },
            { target: "我 每天 工作", en: "I work every day.", pinyin: "wǒ měitiān gōngzuò" },
            { target: "我 想 睡觉", en: "I want to sleep.", pinyin: "wǒ xiǎng shuìjiào" },
            { target: "你 什么时候 上班", en: "When do you go to work?", pinyin: "nǐ shénme shíhou shàngbān" },
            { target: "我 明天 上班", en: "I work tomorrow.", pinyin: "wǒ míngtiān shàngbān" },
            { target: "他 回家 了", en: "He went home.", pinyin: "tā huí jiā le" },
            { target: "我 七 点 起床", en: "I get up at seven.", pinyin: "wǒ qī diǎn qǐchuáng" },
            { target: "我 现在 起床", en: "I am getting up now.", pinyin: "wǒ xiànzài qǐchuáng" },
            { target: "今天 我 都 工作", en: "Today I work all day.", pinyin: "jīntiān wǒ dōu gōngzuò" },
            { target: "你 做 什么", en: "What are you doing?", pinyin: "nǐ zuò shénme" },
            { target: "昨天 我 回家", en: "Yesterday I went home.", pinyin: "zuótiān wǒ huí jiā" },
            { target: "我 现在 上班", en: "I am going to work now.", pinyin: "wǒ xiànzài shàngbān" },
          ],
        },
        {
          id: "zh-u7",
          title: "Shopping & money",
          subtitle: "Buy things and ask prices",
          cefr: "A2",
          color: "#D98324",
          icon: "🛍️",
          vocab: [
            { target: "买", en: "to buy", pinyin: "mǎi" },
            { target: "卖", en: "to sell", pinyin: "mài" },
            { target: "钱", en: "money", pinyin: "qián" },
            { target: "多少钱", en: "how much", pinyin: "duōshao qián" },
            { target: "贵", en: "expensive", pinyin: "guì" },
            { target: "便宜", en: "cheap", pinyin: "piányi" },
            { target: "东西", en: "thing", pinyin: "dōngxi" },
            { target: "衣服", en: "clothes", pinyin: "yīfu" },
            { target: "鞋", en: "shoes", pinyin: "xié" },
            { target: "书", en: "book", pinyin: "shū" },
            { target: "颜色", en: "color", pinyin: "yánsè" },
            { target: "红", en: "red", pinyin: "hóng" },
            { target: "白", en: "white", pinyin: "bái" },
            { target: "黑", en: "black", pinyin: "hēi" },
            { target: "件", en: "(measure, clothing)", pinyin: "jiàn" },
            { target: "这个", en: "this one", pinyin: "zhège" },
            { target: "那个", en: "that one", pinyin: "nàge" },
            { target: "太", en: "too (much)", pinyin: "tài" },
            { target: "给", en: "to give", pinyin: "gěi" },
            { target: "可以", en: "can; may", pinyin: "kěyǐ" },
            { target: "新", en: "new", pinyin: "xīn" },
            { target: "好看", en: "good-looking", pinyin: "hǎokàn" },
          ],
          sentences: [
            { target: "这个 多少钱", en: "How much is this?", pinyin: "zhège duōshao qián" },
            { target: "太 贵 了", en: "Too expensive.", pinyin: "tài guì le" },
            { target: "很 便宜", en: "Very cheap.", pinyin: "hěn piányi" },
            { target: "我 要 买 衣服", en: "I want to buy clothes.", pinyin: "wǒ yào mǎi yīfu" },
            { target: "我 想 买 鞋", en: "I want to buy shoes.", pinyin: "wǒ xiǎng mǎi xié" },
            { target: "这 件 衣服 很 好看", en: "This shirt is nice.", pinyin: "zhè jiàn yīfu hěn hǎokàn" },
            { target: "我 喜欢 红 颜色", en: "I like the color red.", pinyin: "wǒ xǐhuan hóng yánsè" },
            { target: "可以 便宜 吗", en: "Can it be cheaper?", pinyin: "kěyǐ piányi ma" },
            { target: "给 你 钱", en: "Here is the money.", pinyin: "gěi nǐ qián" },
            { target: "那个 太 贵", en: "That one is too expensive.", pinyin: "nàge tài guì" },
            { target: "这 是 新 鞋", en: "These are new shoes.", pinyin: "zhè shì xīn xié" },
            { target: "我 买 这个", en: "I'll buy this one.", pinyin: "wǒ mǎi zhège" },
            { target: "书 多少钱", en: "How much is the book?", pinyin: "shū duōshao qián" },
            { target: "这个 东西 很 好看", en: "This thing is nice.", pinyin: "zhège dōngxi hěn hǎokàn" },
          ],
        },
      ],
    },
    {
      id: "zh-s3",
      title: "Independent",
      subtitle: "Handle work, study and travel",
      units: [
        {
          id: "zh-u8",
          title: "Work & study",
          subtitle: "Jobs, school and learning",
          cefr: "B1",
          color: "#2BA39A",
          icon: "💼",
          vocab: [
            { target: "公司", en: "company", pinyin: "gōngsī" },
            { target: "办公室", en: "office", pinyin: "bàngōngshì" },
            { target: "同事", en: "colleague", pinyin: "tóngshì" },
            { target: "会议", en: "meeting", pinyin: "huìyì" },
            { target: "电脑", en: "computer", pinyin: "diànnǎo" },
            { target: "手机", en: "cell phone", pinyin: "shǒujī" },
            { target: "学习", en: "to study", pinyin: "xuéxí" },
            { target: "上课", en: "to attend class", pinyin: "shàngkè" },
            { target: "考试", en: "exam", pinyin: "kǎoshì" },
            { target: "问题", en: "question; problem", pinyin: "wèntí" },
            { target: "汉语", en: "Chinese (language)", pinyin: "Hànyǔ" },
            { target: "英语", en: "English", pinyin: "Yīngyǔ" },
            { target: "说", en: "to speak", pinyin: "shuō" },
            { target: "写", en: "to write", pinyin: "xiě" },
            { target: "读", en: "to read", pinyin: "dú" },
            { target: "懂", en: "to understand", pinyin: "dǒng" },
            { target: "知道", en: "to know", pinyin: "zhīdào" },
            { target: "觉得", en: "to think; feel", pinyin: "juéde" },
            { target: "忙", en: "busy", pinyin: "máng" },
            { target: "累", en: "tired", pinyin: "lèi" },
            { target: "难", en: "difficult", pinyin: "nán" },
            { target: "容易", en: "easy", pinyin: "róngyì" },
            { target: "能", en: "can; be able to", pinyin: "néng" },
            { target: "因为", en: "because", pinyin: "yīnwèi" },
          ],
          sentences: [
            { target: "我 在 公司 工作", en: "I work at a company.", pinyin: "wǒ zài gōngsī gōngzuò" },
            { target: "我 学习 汉语", en: "I study Chinese.", pinyin: "wǒ xuéxí Hànyǔ" },
            { target: "汉语 很 难", en: "Chinese is difficult.", pinyin: "Hànyǔ hěn nán" },
            { target: "我 觉得 很 容易", en: "I think it's easy.", pinyin: "wǒ juéde hěn róngyì" },
            { target: "你 能 说 英语 吗", en: "Can you speak English?", pinyin: "nǐ néng shuō Yīngyǔ ma" },
            { target: "我 不 懂", en: "I don't understand.", pinyin: "wǒ bù dǒng" },
            { target: "我 今天 很 忙", en: "I am very busy today.", pinyin: "wǒ jīntiān hěn máng" },
            { target: "我 有 一 个 问题", en: "I have a question.", pinyin: "wǒ yǒu yí gè wèntí" },
            { target: "我 明天 有 考试", en: "I have an exam tomorrow.", pinyin: "wǒ míngtiān yǒu kǎoshì" },
            { target: "我 累 因为 工作", en: "I'm tired because of work.", pinyin: "wǒ lèi yīnwèi gōngzuò" },
            { target: "我 能 写 汉语", en: "I can write Chinese.", pinyin: "wǒ néng xiě Hànyǔ" },
            { target: "我 同事 很 忙", en: "My colleague is very busy.", pinyin: "wǒ tóngshì hěn máng" },
            { target: "我 知道 这个 问题", en: "I know this problem.", pinyin: "wǒ zhīdào zhège wèntí" },
            { target: "我 现在 上课", en: "I'm in class now.", pinyin: "wǒ xiànzài shàngkè" },
          ],
        },
        {
          id: "zh-u9",
          title: "Travel",
          subtitle: "Trips, transport and plans",
          cefr: "B1",
          color: "#C2477E",
          icon: "✈️",
          vocab: [
            { target: "旅游", en: "to travel", pinyin: "lǚyóu" },
            { target: "飞机", en: "airplane", pinyin: "fēijī" },
            { target: "火车", en: "train", pinyin: "huǒchē" },
            { target: "汽车", en: "car", pinyin: "qìchē" },
            { target: "出租车", en: "taxi", pinyin: "chūzūchē" },
            { target: "机场", en: "airport", pinyin: "jīchǎng" },
            { target: "宾馆", en: "hotel", pinyin: "bīnguǎn" },
            { target: "护照", en: "passport", pinyin: "hùzhào" },
            { target: "票", en: "ticket", pinyin: "piào" },
            { target: "城市", en: "city", pinyin: "chéngshì" },
            { target: "国家", en: "country", pinyin: "guójiā" },
            { target: "中国", en: "China", pinyin: "Zhōngguó" },
            { target: "美国", en: "America", pinyin: "Měiguó" },
            { target: "地图", en: "map", pinyin: "dìtú" },
            { target: "坐", en: "to sit; take (transport)", pinyin: "zuò" },
            { target: "开车", en: "to drive", pinyin: "kāichē" },
            { target: "到", en: "to arrive", pinyin: "dào" },
            { target: "出发", en: "to set off", pinyin: "chūfā" },
            { target: "行李", en: "luggage", pinyin: "xíngli" },
            { target: "假期", en: "vacation", pinyin: "jiàqī" },
            { target: "一起", en: "together", pinyin: "yìqǐ" },
            { target: "需要", en: "to need", pinyin: "xūyào" },
            { target: "应该", en: "should", pinyin: "yīnggāi" },
            { target: "希望", en: "to hope", pinyin: "xīwàng" },
          ],
          sentences: [
            { target: "我 喜欢 旅游", en: "I like to travel.", pinyin: "wǒ xǐhuan lǚyóu" },
            { target: "我 要 去 中国", en: "I want to go to China.", pinyin: "wǒ yào qù Zhōngguó" },
            { target: "我 坐 飞机", en: "I take the plane.", pinyin: "wǒ zuò fēijī" },
            { target: "我 想 坐 火车", en: "I want to take the train.", pinyin: "wǒ xiǎng zuò huǒchē" },
            { target: "我 需要 护照", en: "I need a passport.", pinyin: "wǒ xūyào hùzhào" },
            { target: "票 多少钱", en: "How much is the ticket?", pinyin: "piào duōshao qián" },
            { target: "机场 很 远", en: "The airport is far.", pinyin: "jīchǎng hěn yuǎn" },
            { target: "我们 一起 去", en: "Let's go together.", pinyin: "wǒmen yìqǐ qù" },
            { target: "我 明天 出发", en: "I set off tomorrow.", pinyin: "wǒ míngtiān chūfā" },
            { target: "我 坐 出租车 去 宾馆", en: "I take a taxi to the hotel.", pinyin: "wǒ zuò chūzūchē qù bīnguǎn" },
            { target: "你 应该 坐 火车", en: "You should take the train.", pinyin: "nǐ yīnggāi zuò huǒchē" },
            { target: "我 希望 去 美国", en: "I hope to go to America.", pinyin: "wǒ xīwàng qù Měiguó" },
            { target: "我 到 机场 了", en: "I have arrived at the airport.", pinyin: "wǒ dào jīchǎng le" },
            { target: "这个 城市 很 大", en: "This city is big.", pinyin: "zhège chéngshì hěn dà" },
          ],
        },
      ],
    },
  ],
};
