import type { SectionBlueprint } from "@/curriculum/generate";

// Theme-based Mandarin Chinese blueprint sections. Hand-authored vocab +
// sentence banks per unit; the generator expands these into many
// spaced-repetition lessons. Characters are Simplified. Pinyin uses tone
// marks and is verified per item. Sentences use only this unit's vocab plus
// common function words (是 很 我 你 的 了 在 吗 etc.).

export const chineseThemeSections: SectionBlueprint[] = [
  {
    id: "zh-sT1",
    title: "Themes",
    subtitle: "Broaden your vocabulary",
    units: [
      {
        id: "zh-ut1",
        title: "Nature & weather",
        subtitle: "The sky, seasons and outdoors",
        cefr: "A2",
        color: "#4FA3D1",
        icon: "🌤️",
        vocab: [
          { target: "天气", en: "weather", pinyin: "tiānqì" },
          { target: "太阳", en: "sun", pinyin: "tàiyáng" },
          { target: "月亮", en: "moon", pinyin: "yuèliang" },
          { target: "天空", en: "sky", pinyin: "tiānkōng" },
          { target: "云", en: "cloud", pinyin: "yún" },
          { target: "雨", en: "rain", pinyin: "yǔ" },
          { target: "雪", en: "snow", pinyin: "xuě" },
          { target: "风", en: "wind", pinyin: "fēng" },
          { target: "下雨", en: "to rain", pinyin: "xià yǔ" },
          { target: "下雪", en: "to snow", pinyin: "xià xuě" },
          { target: "刮风", en: "to be windy", pinyin: "guā fēng" },
          { target: "热", en: "hot", pinyin: "rè" },
          { target: "冷", en: "cold", pinyin: "lěng" },
          { target: "暖和", en: "warm", pinyin: "nuǎnhuo" },
          { target: "凉快", en: "cool", pinyin: "liángkuai" },
          { target: "春天", en: "spring", pinyin: "chūntiān" },
          { target: "夏天", en: "summer", pinyin: "xiàtiān" },
          { target: "秋天", en: "autumn", pinyin: "qiūtiān" },
          { target: "冬天", en: "winter", pinyin: "dōngtiān" },
          { target: "树", en: "tree", pinyin: "shù" },
          { target: "花", en: "flower", pinyin: "huā" },
          { target: "山", en: "mountain", pinyin: "shān" },
          { target: "海", en: "sea", pinyin: "hǎi" },
          { target: "晴天", en: "sunny day", pinyin: "qíngtiān" },
        ],
        sentences: [
          { target: "今天 天气 很 好", en: "The weather is nice today.", pinyin: "jīntiān tiānqì hěn hǎo" },
          { target: "今天 下雨", en: "It is raining today.", pinyin: "jīntiān xià yǔ" },
          { target: "明天 下雪", en: "It will snow tomorrow.", pinyin: "míngtiān xià xuě" },
          { target: "夏天 很 热", en: "Summer is very hot.", pinyin: "xiàtiān hěn rè" },
          { target: "冬天 很 冷", en: "Winter is very cold.", pinyin: "dōngtiān hěn lěng" },
          { target: "春天 很 暖和", en: "Spring is warm.", pinyin: "chūntiān hěn nuǎnhuo" },
          { target: "今天 刮风", en: "It is windy today.", pinyin: "jīntiān guā fēng" },
          { target: "天空 有 云", en: "There are clouds in the sky.", pinyin: "tiānkōng yǒu yún" },
          { target: "太阳 很 大", en: "The sun is big.", pinyin: "tàiyáng hěn dà" },
          { target: "我 喜欢 秋天", en: "I like autumn.", pinyin: "wǒ xǐhuan qiūtiān" },
          { target: "山 上 有 雪", en: "There is snow on the mountain.", pinyin: "shān shàng yǒu xuě" },
          { target: "这 朵 花 很 好看", en: "This flower is pretty.", pinyin: "zhè duǒ huā hěn hǎokàn" },
          { target: "今天 是 晴天", en: "Today is a sunny day.", pinyin: "jīntiān shì qíngtiān" },
          { target: "海 很 大", en: "The sea is big.", pinyin: "hǎi hěn dà" },
        ],
      },
      {
        id: "zh-ut2",
        title: "Emotions & feelings",
        subtitle: "Say how you feel",
        cefr: "A2",
        color: "#E0739B",
        icon: "😊",
        vocab: [
          { target: "开心", en: "happy", pinyin: "kāixīn" },
          { target: "高兴", en: "glad", pinyin: "gāoxìng" },
          { target: "快乐", en: "joyful", pinyin: "kuàilè" },
          { target: "难过", en: "sad", pinyin: "nánguò" },
          { target: "伤心", en: "heartbroken", pinyin: "shāngxīn" },
          { target: "生气", en: "angry", pinyin: "shēngqì" },
          { target: "害怕", en: "afraid", pinyin: "hàipà" },
          { target: "紧张", en: "nervous", pinyin: "jǐnzhāng" },
          { target: "担心", en: "worried", pinyin: "dānxīn" },
          { target: "累", en: "tired", pinyin: "lèi" },
          { target: "饿", en: "hungry", pinyin: "è" },
          { target: "渴", en: "thirsty", pinyin: "kě" },
          { target: "舒服", en: "comfortable; well", pinyin: "shūfu" },
          { target: "无聊", en: "bored", pinyin: "wúliáo" },
          { target: "感觉", en: "to feel; feeling", pinyin: "gǎnjué" },
          { target: "心情", en: "mood", pinyin: "xīnqíng" },
          { target: "哭", en: "to cry", pinyin: "kū" },
          { target: "笑", en: "to laugh; smile", pinyin: "xiào" },
          { target: "喜欢", en: "to like", pinyin: "xǐhuan" },
          { target: "讨厌", en: "to dislike; hate", pinyin: "tǎoyàn" },
          { target: "希望", en: "to hope", pinyin: "xīwàng" },
          { target: "满意", en: "satisfied", pinyin: "mǎnyì" },
          { target: "激动", en: "excited", pinyin: "jīdòng" },
          { target: "孤单", en: "lonely", pinyin: "gūdān" },
        ],
        sentences: [
          { target: "我 很 开心", en: "I am very happy.", pinyin: "wǒ hěn kāixīn" },
          { target: "他 很 难过", en: "He is very sad.", pinyin: "tā hěn nánguò" },
          { target: "你 为什么 生气", en: "Why are you angry?", pinyin: "nǐ wèishénme shēngqì" },
          { target: "我 有点 紧张", en: "I am a little nervous.", pinyin: "wǒ yǒudiǎn jǐnzhāng" },
          { target: "我 很 累", en: "I am very tired.", pinyin: "wǒ hěn lèi" },
          { target: "我 饿 了", en: "I am hungry.", pinyin: "wǒ è le" },
          { target: "我 很 渴", en: "I am very thirsty.", pinyin: "wǒ hěn kě" },
          { target: "她 在 哭", en: "She is crying.", pinyin: "tā zài kū" },
          { target: "我 今天 心情 很 好", en: "I am in a good mood today.", pinyin: "wǒ jīntiān xīnqíng hěn hǎo" },
          { target: "我 不 害怕", en: "I am not afraid.", pinyin: "wǒ bù hàipà" },
          { target: "我 很 担心 你", en: "I am very worried about you.", pinyin: "wǒ hěn dānxīn nǐ" },
          { target: "我 讨厌 下雨", en: "I hate the rain.", pinyin: "wǒ tǎoyàn xià yǔ" },
          { target: "我 觉得 很 无聊", en: "I feel very bored.", pinyin: "wǒ juéde hěn wúliáo" },
          { target: "我 很 满意", en: "I am very satisfied.", pinyin: "wǒ hěn mǎnyì" },
        ],
      },
      {
        id: "zh-ut3",
        title: "House & everyday objects",
        subtitle: "Rooms and things at home",
        cefr: "A2",
        color: "#7FB069",
        icon: "🏠",
        vocab: [
          { target: "房子", en: "house", pinyin: "fángzi" },
          { target: "房间", en: "room", pinyin: "fángjiān" },
          { target: "门", en: "door", pinyin: "mén" },
          { target: "窗户", en: "window", pinyin: "chuānghu" },
          { target: "厨房", en: "kitchen", pinyin: "chúfáng" },
          { target: "卧室", en: "bedroom", pinyin: "wòshì" },
          { target: "客厅", en: "living room", pinyin: "kètīng" },
          { target: "厕所", en: "toilet", pinyin: "cèsuǒ" },
          { target: "桌子", en: "table", pinyin: "zhuōzi" },
          { target: "椅子", en: "chair", pinyin: "yǐzi" },
          { target: "床", en: "bed", pinyin: "chuáng" },
          { target: "沙发", en: "sofa", pinyin: "shāfā" },
          { target: "灯", en: "lamp; light", pinyin: "dēng" },
          { target: "电视", en: "television", pinyin: "diànshì" },
          { target: "冰箱", en: "refrigerator", pinyin: "bīngxiāng" },
          { target: "空调", en: "air conditioner", pinyin: "kōngtiáo" },
          { target: "钥匙", en: "key", pinyin: "yàoshi" },
          { target: "杯子", en: "cup", pinyin: "bēizi" },
          { target: "碗", en: "bowl", pinyin: "wǎn" },
          { target: "毛巾", en: "towel", pinyin: "máojīn" },
          { target: "镜子", en: "mirror", pinyin: "jìngzi" },
          { target: "干净", en: "clean", pinyin: "gānjìng" },
          { target: "脏", en: "dirty", pinyin: "zāng" },
          { target: "打开", en: "to open; turn on", pinyin: "dǎkāi" },
        ],
        sentences: [
          { target: "这 是 我 的 房间", en: "This is my room.", pinyin: "zhè shì wǒ de fángjiān" },
          { target: "房间 很 干净", en: "The room is clean.", pinyin: "fángjiān hěn gānjìng" },
          { target: "请 打开 门", en: "Please open the door.", pinyin: "qǐng dǎkāi mén" },
          { target: "桌子 上 有 杯子", en: "There is a cup on the table.", pinyin: "zhuōzi shàng yǒu bēizi" },
          { target: "我 在 厨房", en: "I am in the kitchen.", pinyin: "wǒ zài chúfáng" },
          { target: "客厅 有 沙发", en: "There is a sofa in the living room.", pinyin: "kètīng yǒu shāfā" },
          { target: "请 打开 电视", en: "Please turn on the TV.", pinyin: "qǐng dǎkāi diànshì" },
          { target: "我 的 钥匙 在 哪里", en: "Where is my key?", pinyin: "wǒ de yàoshi zài nǎlǐ" },
          { target: "床 在 卧室", en: "The bed is in the bedroom.", pinyin: "chuáng zài wòshì" },
          { target: "请 打开 窗户", en: "Please open the window.", pinyin: "qǐng dǎkāi chuānghu" },
          { target: "这个 杯子 很 脏", en: "This cup is dirty.", pinyin: "zhège bēizi hěn zāng" },
          { target: "冰箱 在 厨房", en: "The fridge is in the kitchen.", pinyin: "bīngxiāng zài chúfáng" },
          { target: "请 打开 灯", en: "Please turn on the light.", pinyin: "qǐng dǎkāi dēng" },
          { target: "房子 很 大", en: "The house is big.", pinyin: "fángzi hěn dà" },
        ],
      },
    ],
  },
  {
    id: "zh-sT2",
    title: "Real life",
    subtitle: "Talk about the wider world",
    units: [
      {
        id: "zh-ut4",
        title: "Work & money",
        subtitle: "Jobs, pay and the office",
        cefr: "B1",
        color: "#3F8E8C",
        icon: "💰",
        vocab: [
          { target: "工作", en: "work; job", pinyin: "gōngzuò" },
          { target: "公司", en: "company", pinyin: "gōngsī" },
          { target: "老板", en: "boss", pinyin: "lǎobǎn" },
          { target: "同事", en: "colleague", pinyin: "tóngshì" },
          { target: "工资", en: "salary", pinyin: "gōngzī" },
          { target: "钱", en: "money", pinyin: "qián" },
          { target: "银行", en: "bank", pinyin: "yínháng" },
          { target: "工厂", en: "factory", pinyin: "gōngchǎng" },
          { target: "经理", en: "manager", pinyin: "jīnglǐ" },
          { target: "工人", en: "worker", pinyin: "gōngrén" },
          { target: "医生", en: "doctor", pinyin: "yīshēng" },
          { target: "护士", en: "nurse", pinyin: "hùshi" },
          { target: "司机", en: "driver", pinyin: "sījī" },
          { target: "面试", en: "interview", pinyin: "miànshì" },
          { target: "赚钱", en: "to earn money", pinyin: "zhuàn qián" },
          { target: "付钱", en: "to pay", pinyin: "fù qián" },
          { target: "花钱", en: "to spend money", pinyin: "huā qián" },
          { target: "存钱", en: "to save money", pinyin: "cún qián" },
          { target: "加班", en: "to work overtime", pinyin: "jiābān" },
          { target: "开会", en: "to have a meeting", pinyin: "kāihuì" },
          { target: "忙", en: "busy", pinyin: "máng" },
          { target: "努力", en: "to work hard", pinyin: "nǔlì" },
          { target: "便宜", en: "cheap", pinyin: "piányi" },
          { target: "贵", en: "expensive", pinyin: "guì" },
        ],
        sentences: [
          { target: "我 在 公司 工作", en: "I work at a company.", pinyin: "wǒ zài gōngsī gōngzuò" },
          { target: "我 的 老板 很 忙", en: "My boss is very busy.", pinyin: "wǒ de lǎobǎn hěn máng" },
          { target: "我 今天 加班", en: "I am working overtime today.", pinyin: "wǒ jīntiān jiābān" },
          { target: "我们 现在 开会", en: "We are having a meeting now.", pinyin: "wǒmen xiànzài kāihuì" },
          { target: "我 想 赚钱", en: "I want to earn money.", pinyin: "wǒ xiǎng zhuàn qián" },
          { target: "我 去 银行 存钱", en: "I go to the bank to save money.", pinyin: "wǒ qù yínháng cún qián" },
          { target: "他 是 医生", en: "He is a doctor.", pinyin: "tā shì yīshēng" },
          { target: "我 的 同事 很 努力", en: "My colleague works hard.", pinyin: "wǒ de tóngshì hěn nǔlì" },
          { target: "工资 太 少", en: "The salary is too little.", pinyin: "gōngzī tài shǎo" },
          { target: "这个 太 贵", en: "This is too expensive.", pinyin: "zhège tài guì" },
          { target: "我 没有 钱", en: "I have no money.", pinyin: "wǒ méiyǒu qián" },
          { target: "我 明天 有 面试", en: "I have an interview tomorrow.", pinyin: "wǒ míngtiān yǒu miànshì" },
          { target: "请 付钱", en: "Please pay.", pinyin: "qǐng fù qián" },
          { target: "我 不 想 花钱", en: "I don't want to spend money.", pinyin: "wǒ bù xiǎng huā qián" },
        ],
      },
      {
        id: "zh-ut5",
        title: "Health & body",
        subtitle: "The body and feeling unwell",
        cefr: "B1",
        color: "#D96459",
        icon: "🩺",
        vocab: [
          { target: "身体", en: "body", pinyin: "shēntǐ" },
          { target: "头", en: "head", pinyin: "tóu" },
          { target: "眼睛", en: "eye", pinyin: "yǎnjing" },
          { target: "鼻子", en: "nose", pinyin: "bízi" },
          { target: "嘴", en: "mouth", pinyin: "zuǐ" },
          { target: "耳朵", en: "ear", pinyin: "ěrduo" },
          { target: "手", en: "hand", pinyin: "shǒu" },
          { target: "脚", en: "foot", pinyin: "jiǎo" },
          { target: "肚子", en: "belly; stomach", pinyin: "dùzi" },
          { target: "牙", en: "tooth", pinyin: "yá" },
          { target: "生病", en: "to get sick", pinyin: "shēngbìng" },
          { target: "感冒", en: "to catch a cold", pinyin: "gǎnmào" },
          { target: "发烧", en: "to have a fever", pinyin: "fāshāo" },
          { target: "咳嗽", en: "to cough", pinyin: "késou" },
          { target: "疼", en: "to hurt; painful", pinyin: "téng" },
          { target: "药", en: "medicine", pinyin: "yào" },
          { target: "医院", en: "hospital", pinyin: "yīyuàn" },
          { target: "医生", en: "doctor", pinyin: "yīshēng" },
          { target: "看病", en: "to see a doctor", pinyin: "kàn bìng" },
          { target: "休息", en: "to rest", pinyin: "xiūxi" },
          { target: "锻炼", en: "to exercise", pinyin: "duànliàn" },
          { target: "健康", en: "healthy; health", pinyin: "jiànkāng" },
          { target: "舒服", en: "comfortable; well", pinyin: "shūfu" },
          { target: "吃药", en: "to take medicine", pinyin: "chī yào" },
        ],
        sentences: [
          { target: "我 生病 了", en: "I am sick.", pinyin: "wǒ shēngbìng le" },
          { target: "我 的 头 很 疼", en: "My head hurts.", pinyin: "wǒ de tóu hěn téng" },
          { target: "我 感冒 了", en: "I caught a cold.", pinyin: "wǒ gǎnmào le" },
          { target: "他 发烧 了", en: "He has a fever.", pinyin: "tā fāshāo le" },
          { target: "你 应该 休息", en: "You should rest.", pinyin: "nǐ yīnggāi xiūxi" },
          { target: "我 要 去 医院", en: "I want to go to the hospital.", pinyin: "wǒ yào qù yīyuàn" },
          { target: "请 吃药", en: "Please take medicine.", pinyin: "qǐng chī yào" },
          { target: "我 的 肚子 疼", en: "My stomach hurts.", pinyin: "wǒ de dùzi téng" },
          { target: "我 每天 锻炼", en: "I exercise every day.", pinyin: "wǒ měitiān duànliàn" },
          { target: "他 的 身体 很 健康", en: "He is very healthy.", pinyin: "tā de shēntǐ hěn jiànkāng" },
          { target: "我 不 舒服", en: "I don't feel well.", pinyin: "wǒ bù shūfu" },
          { target: "我 想 去 看病", en: "I want to see a doctor.", pinyin: "wǒ xiǎng qù kàn bìng" },
          { target: "我 的 牙 很 疼", en: "My tooth hurts a lot.", pinyin: "wǒ de yá hěn téng" },
          { target: "我 在 咳嗽", en: "I am coughing.", pinyin: "wǒ zài késou" },
        ],
      },
      {
        id: "zh-ut6",
        title: "Travel & directions",
        subtitle: "Get around and find your way",
        cefr: "B1",
        color: "#5B6FB0",
        icon: "🧭",
        vocab: [
          { target: "地方", en: "place", pinyin: "dìfang" },
          { target: "地铁", en: "subway", pinyin: "dìtiě" },
          { target: "公交车", en: "bus", pinyin: "gōngjiāochē" },
          { target: "机场", en: "airport", pinyin: "jīchǎng" },
          { target: "车站", en: "station", pinyin: "chēzhàn" },
          { target: "地图", en: "map", pinyin: "dìtú" },
          { target: "方向", en: "direction", pinyin: "fāngxiàng" },
          { target: "东", en: "east", pinyin: "dōng" },
          { target: "南", en: "south", pinyin: "nán" },
          { target: "西", en: "west", pinyin: "xī" },
          { target: "北", en: "north", pinyin: "běi" },
          { target: "左边", en: "left side", pinyin: "zuǒbian" },
          { target: "右边", en: "right side", pinyin: "yòubian" },
          { target: "旁边", en: "beside", pinyin: "pángbiān" },
          { target: "对面", en: "opposite", pinyin: "duìmiàn" },
          { target: "中间", en: "middle", pinyin: "zhōngjiān" },
          { target: "路口", en: "intersection", pinyin: "lùkǒu" },
          { target: "拐", en: "to turn", pinyin: "guǎi" },
          { target: "一直", en: "straight; continuously", pinyin: "yìzhí" },
          { target: "迷路", en: "to get lost", pinyin: "mílù" },
          { target: "出口", en: "exit", pinyin: "chūkǒu" },
          { target: "入口", en: "entrance", pinyin: "rùkǒu" },
          { target: "附近", en: "nearby", pinyin: "fùjìn" },
          { target: "到达", en: "to arrive", pinyin: "dàodá" },
        ],
        sentences: [
          { target: "车站 在 哪里", en: "Where is the station?", pinyin: "chēzhàn zài nǎlǐ" },
          { target: "请 一直 走", en: "Please go straight.", pinyin: "qǐng yìzhí zǒu" },
          { target: "在 路口 往 左 拐", en: "Turn left at the intersection.", pinyin: "zài lùkǒu wǎng zuǒ guǎi" },
          { target: "我 坐 地铁 去", en: "I go by subway.", pinyin: "wǒ zuò dìtiě qù" },
          { target: "银行 在 左边", en: "The bank is on the left.", pinyin: "yínháng zài zuǒbian" },
          { target: "医院 在 右边", en: "The hospital is on the right.", pinyin: "yīyuàn zài yòubian" },
          { target: "我 迷路 了", en: "I am lost.", pinyin: "wǒ mílù le" },
          { target: "附近 有 车站 吗", en: "Is there a station nearby?", pinyin: "fùjìn yǒu chēzhàn ma" },
          { target: "出口 在 前面", en: "The exit is ahead.", pinyin: "chūkǒu zài qiánmiàn" },
          { target: "我 坐 公交车 去 机场", en: "I take the bus to the airport.", pinyin: "wǒ zuò gōngjiāochē qù jīchǎng" },
          { target: "商店 在 对面", en: "The shop is opposite.", pinyin: "shāngdiàn zài duìmiàn" },
          { target: "学校 在 旁边", en: "The school is beside.", pinyin: "xuéxiào zài pángbiān" },
          { target: "我们 到达 了", en: "We have arrived.", pinyin: "wǒmen dàodá le" },
          { target: "你 有 地图 吗", en: "Do you have a map?", pinyin: "nǐ yǒu dìtú ma" },
        ],
      },
    ],
  },
];
